
(function(){
'use strict';const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),uniq=a=>[...new Set(a.filter(Boolean))];let result=null;
function parse(t){const s=t.toLowerCase(),p={genre:'Modern Cinematic Pop',genreKey:'pop',bpm:122,key:'D minor',scale:'Natural Minor',meter:'4/4',vocals:'Female Lead Vocal',instruments:['Piano','Cinematic Strings','Acoustic Drums'],production:'Dynamic Mix, Controlled Contrast, Huge Cinematic Finale',structure:['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Bridge','Final Chorus','Outro'],emotion:'Determined → Triumphant'};
const rules=[[/viking|nordic|wikinger/,['Nordic Cinematic EDM','folk',124,'D minor',['Tagelharpa','Taiko','Cinematic Strings','Deep Synth Bass']]],[/anime|j-pop|opening/,['Anime Rock / J-Pop','anime',150,'E minor',['Electric Guitar','Cinematic Strings','Synthesizer','Acoustic Drums']]],[/metalcore|deathcore/,['Cinematic Metalcore','metal',150,'D minor',['Distorted Guitars','Acoustic Drums','Deep Bass','Cinematic Strings']]],[/electro swing|swing/,['Electro Swing','jazz',126,'F minor',['Upright Bass','Brass Section','Piano','Electronic Drums']]],[/rap|hip.?hop|trap/,['Cinematic Rap','rap',94,'C minor',['Deep Bass','Piano','Electronic Drums','Atmospheric Synth']]],[/techno|edm|electronic/,['Modern Festival EDM','edm',132,'F minor',['Synthesizer','Electronic Drums','Deep Bass','Cinematic Impacts']]],[/ballad|ballade/,['Emotional Cinematic Ballad','ballad',82,'A minor',['Piano','Cello','Cinematic Strings']]],[/cinematic|trailer|ost|soundtrack/,['Epic Cinematic Hybrid','cinematic',110,'D minor',['Cinematic Strings','French Horn','Taiko','Hybrid Synth']]]];const h=rules.find(x=>x[0].test(s));if(h){p.genre=h[1][0];p.genreKey=h[1][1];p.bpm=h[1][2];p.key=h[1][3];p.instruments=h[1][4]}
if(/male|männlich/.test(s))p.vocals='Male Lead Vocal';if(/duet|duett/.test(s))p.vocals='Male/Female Duet';if(/choir|chor/.test(s))p.vocals+=', Layered Choir';if(/narrator|erzähler/.test(s))p.vocals+=', Deep Narrator';if(/dark|dunkel|shadow/.test(s)){p.emotion='Dark Mystery → Determination → Triumph';p.production='Dark Cinematic Production, Strong Dynamic Contrast, Massive Finale'}if(/funny|lustig|comedy/.test(s)){p.emotion='Playful → Chaotic → Celebratory';p.production='Bright Dynamic Mix, Strong Groove, Comedic Accents'}
return p}
function learning(){if(!$('mdUseLearning').checked)return{entries:0,bonus:0};let d=[];try{d=JSON.parse(localStorage.getItem('nsw-learning-feedback-v2')||'[]')}catch(e){}const good=d.filter(x=>Number(x.rating)>=4).length;return{entries:d.length,bonus:Math.min(8,Math.round(good/3))}}
function direct(){const brief=$('mdBrief').value.trim();if(!brief){$('mdStatus').textContent='Add a creative brief first.';return}const p=parse(brief),snap=window.NSWConnections?.snapshot(),learn=learning(),conflicts=[];if(/soft|gentle|ruhig/i.test(brief)&&/constant high energy|massive drop/i.test(brief))conflicts.push('Soft or gentle direction competes with constant high energy.');if(/instrumental/i.test(brief)&&/vocal|voice|stimme|choir/i.test(brief))conflicts.push('Instrumental and vocal requirements should be assigned to separate sections.');if((brief.match(/,/g)||[]).length>18)conflicts.push('The brief contains many simultaneous requirements; lower-priority details may need to be removed.');
const decisions=[
{key:'genre',title:'Genre Direction',value:p.genre,reason:'Chosen from the strongest genre and story signals in the brief.',view:'genreEvolutionView'},
{key:'tempo',title:'Tempo & Groove',value:`${p.bpm} BPM · ${p.meter}`,reason:'Balances the requested energy with clear section development.',view:'theoryView'},
{key:'theory',title:'Harmony',value:`${p.key} · ${p.scale}`,reason:'Supports the detected emotional arc without overcomplicating Suno.',view:'theoryView'},
{key:'vocal',title:'Vocal Direction',value:p.vocals,reason:'Matches the requested character, genre and narrative role.',view:'vocalDirectorView'},
{key:'instrument',title:'Instrument Palette',value:p.instruments.join(', '),reason:'Uses a focused core palette with clear complementary roles.',view:'instrumentEvolutionView'},
{key:'structure',title:'Song Structure',value:p.structure.join(' → '),reason:'Creates a recognizable build and a defined final peak.',view:'blueprintView'},
{key:'emotion',title:'Emotion Flow',value:p.emotion,reason:'Provides narrative movement instead of one static mood.',view:'lyricsView'},
{key:'production',title:'Production Direction',value:p.production,reason:'Translates the emotional and energy arc into mix behavior.',view:'productionView'}];
const style=uniq([p.genre,`${p.bpm} BPM`,p.vocals,...p.instruments,p.emotion,p.production,'Clear Voice Separation','Section-Specific Arrangement']).join(', ');
const score=clamp(76+learn.bonus+(snap?.modules.genre.ready?3:0)+(snap?.modules.blueprint.ready?3:0)-conflicts.length*8-Math.max(0,decisions.length-10)*2);
const reasons=decisions.map(x=>`${x.title}: ${x.reason}`);result={createdAt:Date.now(),brief,mode:$('mdMode').value,duration:$('mdDuration').value,language:$('mdLanguage').value,decisions,style,score,conflicts,reasons,learning:learn};window.NSW_AI_MUSIC_DIRECTOR_LAST=JSON.parse(JSON.stringify(result));render()}
function render(){const r=result;$('mdResults').classList.remove('hidden');$('mdScore').textContent=r.score;$('mdGrade').textContent=r.score>=90?'A+':r.score>=82?'A':r.score>=74?'B+':r.score>=65?'B':'C';$('mdScoreBar').style.width=r.score+'%';$('mdSummary').textContent=`${r.decisions[0].value} with ${r.decisions[3].value}. The direction uses ${r.decisions[4].value} and builds toward a defined final peak.`;$('mdBadge').textContent=`${r.decisions.length} decisions · score ${r.score}`;$('mdMetrics').innerHTML=[['Duration',r.duration],['BPM',r.decisions[1].value],['Learning entries',r.learning.entries],['Conflicts',r.conflicts.length],['Modules ready',window.NSWConnections?.readyCount()||0],['Director mode',r.mode]].map(x=>`<div class="md-metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');
$('mdDecisionGrid').innerHTML=r.decisions.map((d,i)=>`<article class="md-decision"><h3>${i+1}. ${d.title}</h3><strong>${d.value}</strong><p>${d.reason}</p><button data-md-open="${d.view}">Open Module</button></article>`).join('');document.querySelectorAll('[data-md-open]').forEach(b=>b.onclick=()=>window.NSWConnections?.navigate(b.dataset.mdOpen));
$('mdChain').innerHTML=r.decisions.map((d,i)=>`<div class="md-chain-step"><i>${i+1}</i><div><b>${d.title}</b><small>${d.value}</small></div></div>`).join('');
$('mdConflicts').innerHTML=(r.conflicts.length?r.conflicts:['No major creative conflicts detected.']).map(x=>`<div class="md-message ${r.conflicts.length?'warn':'good'}">${x}</div>`).join('');
$('mdReasons').innerHTML=r.reasons.map(x=>`<div class="md-message info">${x}</div>`).join('');
$('mdModuleActions').innerHTML=[['Apply STYLE','style'],['Genre Evolution','genre'],['Instrument Evolution','instrument'],['Vocal Director','vocal'],['Song Blueprint','blueprint'],['Success Predictor','predictor']].map(x=>`<button data-md-action="${x[1]}">${x[0]}</button>`).join('');document.querySelectorAll('[data-md-action]').forEach(b=>b.onclick=()=>applyPart(b.dataset.mdAction));
$('mdMasterPlan').value=planText();$('mdStatus').textContent=`Direction complete · coherence ${r.score}/100.`}
function applyPart(k){if(!result)return;if(k==='style')window.NSWConnections?.setStyle(result.style);if(k==='genre')window.NSWConnections?.navigate('genreEvolutionView');if(k==='instrument'){window.NSWConnections?.navigate('instrumentEvolutionView');const e=$('ieGenre');if(e){e.value=result.decisions[0].value.toLowerCase().includes('anime')?'anime':result.decisions[0].value.toLowerCase().includes('metal')?'metal':result.decisions[0].value.toLowerCase().includes('nordic')?'folk':'cinematic';e.dispatchEvent(new Event('change',{bubbles:true}))}$('ieSmart')?.click()}if(k==='vocal'){window.NSWConnections?.navigate('vocalDirectorView');$('vdSmartDirector')?.click()}if(k==='blueprint')window.NSWConnections?.navigate('blueprintView');if(k==='predictor'){window.NSWConnections?.setStyle(result.style);window.NSWConnections?.sync('studio-to-predictor')}}
function applyAll(){if(!result)return;window.NSWConnections?.setStyle(result.style);const bpm=$('bpm');if(bpm){bpm.value=parse(result.decisions[1].value);bpm.dispatchEvent(new Event('input',{bubbles:true}))}if($('mdMode').value!=='safe'){applyPart('instrument');applyPart('vocal')}setTimeout(()=>window.NSWConnections?.sync('studio-to-predictor'),180);$('mdStatus').textContent='All compatible director decisions were applied.'}
function planText(){if(!result)return'';return['AI MUSIC DIRECTOR – MASTER PLAN',`Brief: ${result.brief}`,`Mode: ${result.mode}`,`Target duration: ${result.duration}`,`Coherence: ${result.score}/100`,'',...result.decisions.map(x=>`${x.title}: ${x.value}\nReason: ${x.reason}`),'',`STYLE: ${result.style}`].join('\n\n')}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch(e){}}function exportJson(){if(!result)return;const b=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ai-music-director-plan.json';a.click()}
function saveProject(){if(!result)return;let pm;try{pm=JSON.parse(localStorage.getItem('nsw-project-manager-v4')||'null')}catch(e){}const p=pm?.projects?.find(x=>x.id===pm.activeProjectId)||pm?.projects?.[0],t=p?.tracks?.[0];if(!t){$('mdStatus').textContent='No active project track found.';return}t.aiMusicDirector=JSON.parse(JSON.stringify(result));t.updated=Date.now();p.updated=Date.now();localStorage.setItem('nsw-project-manager-v4',JSON.stringify(pm));$('mdStatus').textContent=`Director plan saved to ${p.name} · ${t.title}.`}
function init(){if(!$('mdDirect'))return;$('mdBrief').oninput=()=>{$('mdBriefStats').textContent=`${$('mdBrief').value.trim().split(/\s+/).filter(Boolean).length} words`};$('mdDirect').onclick=direct;$('mdApplyAll').onclick=applyAll;$('mdCopyPlan').onclick=()=>copy(planText());$('mdExport').onclick=exportJson;$('mdSaveProject').onclick=saveProject;$('mdExample').onclick=()=>{$('mdBrief').value='A dark German Viking anime opening about a warrior returning from the shadow realm. Female lead, deep male narrator, choir, Tagelharpa, Taiko, cinematic strings and a huge electronic finale.';$('mdBrief').dispatchEvent(new Event('input'))};$('mdClear').onclick=()=>{$('mdBrief').value='';$('mdResults').classList.add('hidden');result=null};$('mdImportStudio').onclick=()=>{const s=window.NSWConnections?.snapshot();$('mdBrief').value=`Current Studio direction: ${s?.modules.style.data?.style||''}\nLyrics concept: ${(s?.modules.lyrics.data?.lyrics||'').slice(0,600)}`;$('mdBrief').dispatchEvent(new Event('input'))};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
