
(function(){'use strict';const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));let data=[],sel=null,drag=null,next=1;
const P={'Anime Opening':['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Bridge','Final Chorus','Outro'],'Viking Cinematic':['Ritual Intro','Verse 1','War Chant','Chorus','March Build','Battle Break','Final Chorus','Saga Outro'],'Metalcore':['Intro','Verse 1','Pre-Chorus','Clean Chorus','Verse 2','Breakdown','Bridge','Final Chorus'],'EDM Festival':['Atmospheric Intro','Build 1','Drop 1','Break','Build 2','Drop 2','Finale','Outro'],'Ballad':['Piano Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Bridge','Final Chorus','Outro'],'Electro Swing':['Vintage Intro','Verse 1','Chorus','Brass Break','Verse 2','Dance Break','Final Chorus','Outro']};
function names(){const s=$('arrSource').value;if(s==='blueprint'&&window.NSW_SONG_BLUEPRINT_LAST?.sections)return window.NSW_SONG_BLUEPRINT_LAST.sections.map(x=>x.name);if(s==='lyrics'){const text=$('lyricsEditor')?.value||'',a=window.NSWMetaTagStackEngine?window.NSWMetaTagStackEngine.parseLyrics(text).sections.map(section=>section.stack.section):[...text.matchAll(/^\s*\[([^\]]+)\]\s*$/gm)].map(x=>x[1].split(':')[0]);if(a.length)return a}if(s==='director'&&window.NSW_AI_MUSIC_DIRECTOR_LAST){const x=window.NSW_AI_MUSIC_DIRECTOR_LAST.decisions.find(x=>x.key==='structure');if(x)return x.value.split(' → ')}return P[$('arrPreset').value]}
function make(name,i,n){let e=25+i/Math.max(1,n-1)*65;const arc=$('arrArc').value,l=name.toLowerCase();if(arc==='waves')e=48+Math.sin(i*1.7)*25+i*2;if(arc==='contrast')e=i%2?82:36;if(arc==='high')e=82;if(/chorus|drop|final|breakdown/.test(l))e+=14;if(/intro|outro|break/.test(l))e-=14;return{id:next++,name,duration:Math.round(180/n),energy:clamp(Math.round(e)),density:/chorus|drop|final/.test(l)?85:/intro|outro/.test(l)?30:55,vocal:/instrumental|drop|break/.test(l)?'Instrumental':/chorus|final/.test(l)?'Lead + Harmony':'Lead Vocal',instruments:/intro/.test(l)?'Piano, Atmosphere':/chorus|drop|final/.test(l)?'Full Core Palette':'Rhythm Section, Main Motif',production:/chorus|drop|final/.test(l)?'Wide, Powerful, Layered':'Controlled, Clear',transition:/pre|build/.test(l)?'Riser into next section':/outro/.test(l)?'Long fade':'Smooth transition',purpose:/chorus|drop/.test(l)?'Main payoff':/bridge|break/.test(l)?'Contrast and reset':'Story development',notes:''}}
function secs(x){const[a,b]=x.split(':').map(Number);return a*60+b}function tm(s){return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function generate(){const n=names();data=n.map((x,i)=>make(x,i,n.length));sel=data[0]?.id;normalize();$('arrStatus').textContent=`Generated ${data.length} sections.`}
function normalize(){if(!data.length)return;const total=secs($('arrDuration').value),cur=data.reduce((a,b)=>a+b.duration,0)||1;let used=0;data.forEach((x,i)=>{x.duration=i===data.length-1?total-used:Math.max(8,Math.round(x.duration/cur*total));used+=x.duration});render()}
function render(){timeline();lanes();editor();analyse();output();window.NSW_ARRANGEMENT_DESIGNER_LAST={sections:JSON.parse(JSON.stringify(data)),duration:$('arrDuration').value,output:plan(),updatedAt:Date.now()};$('arrBadge').textContent=`${data.length} sections · ${tm(data.reduce((a,b)=>a+b.duration,0))}`}
function timeline(){const z=+$('arrZoom').value/100;$('arrTimeline').innerHTML=data.map(x=>`<article draggable="true" data-id="${x.id}" class="arr-section ${x.id===sel?'active':''}" style="width:${Math.max(115,x.duration*2.2*z)}px"><b>${x.name}</b><small>${x.duration}s · ${x.purpose}</small><i style="width:${x.energy}%"></i></article>`).join('');document.querySelectorAll('.arr-section').forEach(e=>{e.onclick=()=>{sel=+e.dataset.id;render()};e.ondragstart=()=>drag=+e.dataset.id;e.ondragover=v=>v.preventDefault();e.ondrop=v=>{v.preventDefault();const t=+e.dataset.id,a=data.findIndex(x=>x.id===drag),b=data.findIndex(x=>x.id===t),[it]=data.splice(a,1);data.splice(b,0,it);render()}});let total=data.reduce((a,b)=>a+b.duration,0),m=[];for(let i=0;i<=total;i+=30)m.push(`<span>${tm(i)}</span>`);$('arrRuler').innerHTML=m.join('')}
function lanes(){const L=[['Energy',x=>x.energy+'%'],['Vocals',x=>x.vocal],['Instruments',x=>x.instruments],['Density',x=>x.density+'%'],['Production',x=>x.production],['Transition',x=>x.transition]];$('arrLanes').innerHTML=L.map(([n,f])=>`<div class="arr-lane"><span>${n}</span><div class="arr-lane-track">${data.map(x=>`<div class="arr-cell" style="flex:${x.duration}">${f(x)}</div>`).join('')}</div></div>`).join('')}
function editor(){const x=data.find(v=>v.id===sel),h=$('arrEditor');if(!x){h.innerHTML='<div class="feature-empty">Select a section.</div>';return}$('arrSelected').textContent=x.name;h.innerHTML=`<div class="arr-editor-grid"><label>Name<input id="aeName" value="${x.name}"></label><label>Duration<input id="aeDur" type="number" min="8" value="${x.duration}"></label><label>Purpose<input id="aePurpose" value="${x.purpose}"></label><label>Vocals<input id="aeVocal" value="${x.vocal}"></label><label>Instruments<input id="aeInst" value="${x.instruments}"></label><label>Production<input id="aeProd" value="${x.production}"></label><label>Transition<input id="aeTrans" value="${x.transition}"></label><div class="arr-slider"><span>Energy <b id="aeEV">${x.energy}%</b></span><input id="aeE" type="range" min="0" max="100" value="${x.energy}"></div><div class="arr-slider"><span>Density <b id="aeDV">${x.density}%</b></span><input id="aeD" type="range" min="0" max="100" value="${x.density}"></div><label style="grid-column:1/-1">Notes<textarea id="aeNotes">${x.notes}</textarea></label></div><div class="arr-actions"><button class="primary" id="aeSave">Save</button><button id="aeDup">Duplicate</button><button id="aeDel">Delete</button></div>`;$('aeE').oninput=e=>$('aeEV').textContent=e.target.value+'%';$('aeD').oninput=e=>$('aeDV').textContent=e.target.value+'%';$('aeSave').onclick=()=>{Object.assign(x,{name:$('aeName').value,duration:+$('aeDur').value,purpose:$('aePurpose').value,vocal:$('aeVocal').value,instruments:$('aeInst').value,production:$('aeProd').value,transition:$('aeTrans').value,energy:+$('aeE').value,density:+$('aeD').value,notes:$('aeNotes').value});render()};$('aeDup').onclick=()=>{const i=data.indexOf(x),c={...x,id:next++,name:x.name+' Copy'};data.splice(i+1,0,c);sel=c.id;render()};$('aeDel').onclick=()=>{data=data.filter(v=>v.id!==x.id);sel=data[0]?.id;render()}}
function analyse(){const e=data.map(x=>x.energy),warnings=[];if(e.length&&Math.max(...e)-Math.min(...e)<25)warnings.push('Energy contrast is limited.');if(data.filter(x=>x.energy>85).length>3)warnings.push('Too many peak sections reduce impact.');if(!data.some(x=>/bridge|break/i.test(x.name)))warnings.push('No contrast section is defined.');const score=clamp(92-warnings.length*10);$('arrScore').innerHTML=`<div class="arr-big-score">${score}</div><small>Arrangement coherence</small>`;$('arrMessages').innerHTML=(warnings.length?warnings:['No major arrangement conflicts.']).map(x=>`<div class="arr-msg ${warnings.length?'warn':'good'}">${x}</div>`).join('')}
function plan(){let s=0;return data.map(x=>{const e=s+x.duration,directives=[x.vocal,x.instruments,`Energy ${x.energy}%`,x.production,x.transition,`Timing ${tm(s)}–${tm(e)}`],t=window.NSWMetaTagStackEngine?window.NSWMetaTagStackEngine.createStack(x.name,directives,{sort:true}).line:`[${[x.name,...directives].join(' | ')}]`;s=e;return t}).join('\n')}
function output(){$('arrOutput').value=plan()}
function init(){if(!$('arrGenerate'))return;$('arrGenerate').onclick=generate;$('arrNormalize').onclick=normalize;$('arrAdd').onclick=()=>{const x=make('New Section',data.length,data.length+1);data.push(x);sel=x.id;render()};$('arrClear').onclick=()=>{data=[];sel=null;render()};$('arrZoom').oninput=timeline;$('arrCopy').onclick=()=>navigator.clipboard?.writeText(plan());$('arrExport').onclick=()=>{const b=new Blob([JSON.stringify(window.NSW_ARRANGEMENT_DESIGNER_LAST,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='arrangement-designer.json';a.click()};$('arrLyrics').onclick=()=>window.NSWConnections?.appendLyrics(plan());$('arrProject').onclick=()=>{let p;try{p=JSON.parse(localStorage.getItem('nsw-project-manager-v4')||'null')}catch(e){}const pr=p?.projects?.find(x=>x.id===p.activeProjectId)||p?.projects?.[0],t=pr?.tracks?.[0];if(t){t.arrangementDesigner=window.NSW_ARRANGEMENT_DESIGNER_LAST;localStorage.setItem('nsw-project-manager-v4',JSON.stringify(p))}};generate()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
