const GENRE_LIBRARY = {
  "Pop": [
    "Dance Pop",
    "Synth-Pop",
    "Dream Pop",
    "Electropop",
    "Indie Pop",
    "Hyperpop",
    "Art Pop",
    "K-Pop",
    "J-Pop",
    "City Pop",
    "Teen Pop",
    "Baroque Pop",
    "Chamber Pop",
    "Pop Rock",
    "Pop Punk",
    "Power Pop",
    "Orchestral Pop",
    "Ambient Pop",
    "Dark Pop",
    "Europop",
    "Bubblegum Pop",
    "Adult Contemporary",
    "Sophisti-Pop",
    "Psychedelic Pop"
  ],
  "Rock": [
    "Alternative Rock",
    "Hard Rock",
    "Progressive Rock",
    "Indie Rock",
    "Arena Rock",
    "Post-Rock",
    "Math Rock",
    "Garage Rock",
    "Blues Rock",
    "Folk Rock",
    "Gothic Rock",
    "Psychedelic Rock",
    "Surf Rock",
    "Southern Rock",
    "Soft Rock",
    "J-Rock",
    "Anime Rock",
    "Symphonic Rock",
    "Grunge",
    "Noise Rock",
    "Stoner Rock",
    "Art Rock",
    "Emo Rock",
    "Pop Rock",
    "Classic Rock",
    "Industrial Rock"
  ],
  "Metal": [
    "Heavy Metal",
    "Power Metal",
    "Speed Metal",
    "Thrash Metal",
    "Groove Metal",
    "Doom Metal",
    "Death Metal",
    "Melodic Death Metal",
    "Black Metal",
    "Symphonic Black Metal",
    "Symphonic Metal",
    "Folk Metal",
    "Viking Metal",
    "Pagan Metal",
    "Metalcore",
    "Deathcore",
    "Djent",
    "Nu Metal",
    "Industrial Metal",
    "Gothic Metal",
    "Progressive Metal",
    "Sludge Metal",
    "Post-Metal",
    "Alternative Metal",
    "Trap Metal",
    "Neoclassical Metal"
  ],
  "Electronic / EDM": [
    "EDM",
    "Hardstyle",
    "Hard Dance",
    "Hard Bass",
    "Trance",
    "Psytrance",
    "Progressive Trance",
    "Progressive House",
    "Electro House",
    "Future House",
    "Bass House",
    "Deep House",
    "Tech House",
    "Techno",
    "Melodic Techno",
    "Drum & Bass",
    "Liquid Drum & Bass",
    "Neurofunk",
    "Dubstep",
    "Future Bass",
    "Synthwave",
    "Dark Synthwave",
    "Industrial Electronic",
    "Electro",
    "Ambient",
    "Lo-Fi Electronic",
    "Chillstep",
    "Phonk",
    "Future Rave",
    "Big Room",
    "Eurodance",
    "Breakbeat",
    "UK Garage",
    "2-Step",
    "IDM",
    "Downtempo",
    "Trip-Hop"
  ],
  "Hip-Hop / Rap": [
    "Boom Bap",
    "Trap",
    "Drill",
    "Conscious Rap",
    "Horrorcore",
    "Emo Rap",
    "Cloud Rap",
    "Alternative Hip-Hop",
    "Jazz Rap",
    "Gangsta Rap",
    "Pop Rap",
    "UK Drill",
    "Memphis Rap",
    "Old School Hip-Hop",
    "Lo-Fi Hip-Hop",
    "Grime",
    "East Coast Rap",
    "West Coast Rap",
    "Southern Rap",
    "Trap Soul",
    "Rap Rock",
    "Rap Metal"
  ],
  "R&B": [
    "Contemporary R&B",
    "Alternative R&B",
    "Smooth R&B",
    "Quiet Storm",
    "New Jack Swing",
    "Trap Soul",
    "Electro R&B",
    "Progressive R&B",
    "Indie R&B",
    "Slow Jam",
    "R&B Ballad",
    "Neo R&B",
    "Dark R&B"
  ],
  "Soul / Funk / Disco": [
    "Classic Soul",
    "Neo Soul",
    "Motown",
    "Southern Soul",
    "Northern Soul",
    "Blue-Eyed Soul",
    "Psychedelic Soul",
    "Gospel Soul",
    "Soul Ballad",
    "Funk",
    "P-Funk",
    "Disco",
    "Nu-Disco",
    "Boogie",
    "Electro-Funk",
    "Deep Funk",
    "Jazz-Funk",
    "Afro-Funk"
  ],
  "Ballad / Emotional": [
    "Pop Ballad",
    "Rock Ballad",
    "Power Ballad",
    "Piano Ballad",
    "Soul Ballad",
    "R&B Ballad",
    "Metal Ballad",
    "Cinematic Ballad",
    "Acoustic Ballad",
    "Folk Ballad",
    "Country Ballad",
    "Anime Ending Ballad",
    "Emotional Orchestral Ballad",
    "Dark Ballad",
    "Epic Ballad"
  ],
  "Jazz": [
    "Traditional Jazz",
    "Swing",
    "Big Band",
    "Bebop",
    "Hard Bop",
    "Cool Jazz",
    "Modal Jazz",
    "Free Jazz",
    "Smooth Jazz",
    "Jazz Fusion",
    "Jazz-Funk",
    "Latin Jazz",
    "Gypsy Jazz",
    "Vocal Jazz",
    "Nu Jazz",
    "Acid Jazz",
    "Dark Jazz",
    "Cinematic Jazz"
  ],
  "Blues": [
    "Delta Blues",
    "Chicago Blues",
    "Electric Blues",
    "Country Blues",
    "Texas Blues",
    "Piedmont Blues",
    "Blues Rock",
    "Soul Blues",
    "Gospel Blues",
    "Modern Blues",
    "Acoustic Blues"
  ],
  "Country / Americana": [
    "Traditional Country",
    "Modern Country",
    "Country Pop",
    "Country Rock",
    "Alt-Country",
    "Outlaw Country",
    "Bluegrass",
    "Honky-Tonk",
    "Western Swing",
    "Americana",
    "Southern Gothic",
    "Country Ballad",
    "Folk Country"
  ],
  "Folk / Acoustic": [
    "Contemporary Folk",
    "Traditional Folk",
    "Indie Folk",
    "Folk Rock",
    "Acoustic Folk",
    "Dark Folk",
    "Pagan Folk",
    "Nordic Folk",
    "Celtic Folk",
    "Balkan Folk",
    "Slavic Folk",
    "Mediterranean Folk",
    "Appalachian Folk",
    "Singer-Songwriter",
    "Neofolk",
    "World Folk"
  ],
  "Classical / Orchestral": [
    "Baroque",
    "Classical",
    "Romantic",
    "Modern Classical",
    "Neoclassical",
    "Minimalism",
    "Chamber Music",
    "Symphonic",
    "Opera",
    "Choral",
    "Orchestral Suite",
    "Piano Concerto",
    "String Quartet",
    "Sacred Classical",
    "Cinematic Orchestra",
    "Epic Orchestral"
  ],
  "Cinematic / Soundtrack": [
    "Film Score",
    "Trailer Music",
    "Epic Trailer",
    "Dark Fantasy Score",
    "Sci-Fi Score",
    "Adventure Score",
    "Horror Score",
    "Romantic Score",
    "Anime OST",
    "Game OST",
    "Boss Battle Theme",
    "Hero Theme",
    "Character Theme",
    "Ambient Score",
    "Hybrid Orchestral",
    "Post-Apocalyptic Score",
    "Cyberpunk Score"
  ],
  "Anime / Japanese": [
    "Anime Opening",
    "Anime Ending",
    "Anime Rock",
    "J-Rock",
    "J-Pop",
    "Visual Kei",
    "City Pop",
    "Japanese Metal",
    "Japanese Folk Fusion",
    "Anime Ballad",
    "Anime Battle Theme",
    "Isekai OST",
    "Shonen Opening",
    "Dark Fantasy Anime Opening",
    "Idol Pop",
    "Kawaii Metal"
  ],
  "World Music": [
    "African",
    "West African",
    "Afrobeat",
    "Afropop",
    "Highlife",
    "Amapiano",
    "Middle Eastern",
    "Arabic",
    "Persian",
    "Turkish",
    "Indian Classical",
    "Bollywood",
    "Chinese Traditional",
    "Japanese Traditional",
    "Korean Traditional",
    "Southeast Asian",
    "Latin American",
    "Andean",
    "Caribbean",
    "Celtic",
    "Nordic",
    "Balkan",
    "Mediterranean",
    "World Fusion"
  ],
  "Latin": [
    "Salsa",
    "Bachata",
    "Merengue",
    "Reggaeton",
    "Latin Pop",
    "Latin Rock",
    "Bossa Nova",
    "Samba",
    "Tango",
    "Cumbia",
    "Mariachi",
    "Ranchera",
    "Mambo",
    "Cha-Cha-Cha",
    "Bolero",
    "Latin Jazz",
    "Flamenco Fusion"
  ],
  "Reggae / Caribbean": [
    "Roots Reggae",
    "Dub",
    "Dancehall",
    "Ska",
    "Rocksteady",
    "Reggae Fusion",
    "Lovers Rock",
    "Calypso",
    "Soca",
    "Zouk",
    "Caribbean Pop"
  ],
  "Gospel / Spiritual": [
    "Traditional Gospel",
    "Contemporary Gospel",
    "Gospel Choir",
    "Southern Gospel",
    "Black Gospel",
    "Worship",
    "Christian Rock",
    "Christian Pop",
    "Sacred Choral",
    "Spirituals"
  ],
  "Ambient / Chill": [
    "Ambient",
    "Dark Ambient",
    "Space Ambient",
    "Drone",
    "New Age",
    "Meditation",
    "Chillout",
    "Downtempo",
    "Lo-Fi",
    "Chillhop",
    "Sleep Music",
    "Nature Ambient",
    "Ethereal Ambient",
    "Cinematic Ambient"
  ],
  "Experimental": [
    "Avant-Garde",
    "Noise",
    "Musique Concrète",
    "Glitch",
    "IDM",
    "Electroacoustic",
    "Sound Collage",
    "Free Improvisation",
    "Microtonal",
    "Drone Experimental",
    "Industrial Experimental",
    "Art Music"
  ],
  "Fantasy / Thematic": [
    "Dark Fantasy",
    "Heroic Fantasy",
    "Medieval Fantasy",
    "Viking Saga",
    "Pirate",
    "Steampunk",
    "Cyberpunk",
    "Post-Apocalyptic",
    "Dungeon",
    "Dragon Fantasy",
    "Mythological",
    "Oceanic Mystery",
    "Space Opera",
    "Gothic Horror",
    "School Anime",
    "Isekai",
    "Epic Quest"
  ]
};
