
(function(){
'use strict';
const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),uniq=a=>[...new Set(a.filter(Boolean))];
const DATA={
'Rock':{paths:{'Classic to Modern':['Blues Rock','Classic Rock','Hard Rock','Alternative Rock','Modern Arena Rock'],'Heavy Evolution':['Blues Rock','Hard Rock','Heavy Metal','Metalcore','Modern Heavy Hybrid']},stages:{
'Blues Rock':{era:'1960s',roots:['Blues','Rock and Roll'],branches:['Psychedelic Rock','Southern Rock'],dna:['Loose Groove','Guitar Improvisation','Raw Vocal'],bpm:'90–125 BPM',rhythm:'Swinging or straight backbeat',instruments:['Electric Guitar','Bass Guitar','Acoustic Drums','Hammond Organ'],vocals:['Raspy Lead Vocal','Soulful Delivery'],production:['Analog Warmth','Natural Room Sound']},
'Classic Rock':{era:'1970s',roots:['Blues Rock','Rock and Roll'],branches:['Progressive Rock','Glam Rock'],dna:['Memorable Riffs','Strong Backbeat','Anthemic Chorus'],bpm:'100–135 BPM',rhythm:'Steady 4/4 backbeat',instruments:['Electric Guitar','Bass Guitar','Acoustic Drums'],vocals:['Powerful Male Lead','Layered Chorus'],production:['Vintage Console','Moderate Tape Saturation']},
'Hard Rock':{era:'1980s',roots:['Classic Rock'],branches:['Heavy Metal','Arena Rock'],dna:['Heavy Guitar Riffs','Driving Drums','Large Chorus'],bpm:'110–150 BPM',rhythm:'Driving straight groove',instruments:['Distorted Guitar','Bass Guitar','Big Acoustic Drums'],vocals:['Raspy Power Vocal','Gang Backing Vocals'],production:['Wide Guitars','Punchy Drum Mix']},
'Alternative Rock':{era:'1990s–2000s',roots:['Punk','Post-Punk','Classic Rock'],branches:['Indie Rock','Post-Grunge'],dna:['Dynamic Contrast','Textural Guitar','Emotional Hook'],bpm:'95–145 BPM',rhythm:'Flexible backbeat with contrast',instruments:['Textural Electric Guitar','Bass','Acoustic Drums','Ambient Guitar'],vocals:['Intimate Verse Vocal','Explosive Chorus Vocal'],production:['Dry Verses','Wide Chorus']},
'Modern Arena Rock':{era:'2010s–2020s',roots:['Alternative Rock','Arena Rock'],branches:['Electronic Rock','Cinematic Rock'],dna:['Huge Chorus','Electronic Layers','Cinematic Build'],bpm:'105–145 BPM',rhythm:'Punchy modern backbeat',instruments:['Wide Guitars','Hybrid Drums','Synth Layers','Cinematic Percussion'],vocals:['Powerful Lead Vocal','Layered Anthem Choir'],production:['Polished Modern Mix','Massive Stereo Width']},
'Heavy Metal':{era:'1980s',roots:['Hard Rock'],branches:['Power Metal','Thrash Metal'],dna:['Palm-Muted Riffs','Double Kick','Heroic Melody'],bpm:'120–190 BPM',rhythm:'Driving eighth notes and double kick',instruments:['Heavy Rhythm Guitar','Lead Guitar','Bass','Acoustic Drums'],vocals:['Powerful Clean Vocal','High Register'],production:['Tight Guitar Layers','Forward Drums']},
'Metalcore':{era:'2000s–2010s',roots:['Hardcore Punk','Heavy Metal'],branches:['Deathcore','Electronic Metalcore'],dna:['Breakdown','Clean/Scream Contrast','Half-Time Weight'],bpm:'130–190 BPM',rhythm:'Fast verses and half-time breakdowns',instruments:['Low-Tuned Guitars','Punchy Drums','Bass'],vocals:['Screamed Verse','Clean Belting Chorus'],production:['Tight Modern Attack','Controlled Low End']},
'Modern Heavy Hybrid':{era:'2020s',roots:['Metalcore','Electronic Rock'],branches:['Cinematic Metal','Industrial Metalcore'],dna:['Genre Contrast','Electronic Bass','Massive Breakdown'],bpm:'135–180 BPM',rhythm:'Syncopated riffs with electronic pulse',instruments:['Low-Tuned Guitar','Electronic Drums','Sub Bass','Cinematic Percussion'],vocals:['Clean/Scream Separation','Choir Finale'],production:['Hybrid Cinematic Mix','Aggressive Transients']}}},
'Electronic':{paths:{'Club Evolution':['Disco','House','Techno','Progressive House','Modern Festival EDM'],'Bass Evolution':['Dub','Dubstep','Brostep','Future Bass','Cinematic Bass Music']},stages:{
'Disco':{era:'1970s',roots:['Funk','Soul'],branches:['Italo Disco','Hi-NRG'],dna:['Four-on-the-Floor','Syncopated Bass','String Stabs'],bpm:'110–125 BPM',rhythm:'Four-on-the-floor with offbeat groove',instruments:['Disco Strings','Funk Bass','Rhythm Guitar','Acoustic Drums'],vocals:['Soulful Lead Vocal','Group Chorus'],production:['Warm Analog Mix','Natural Compression']},
'House':{era:'1980s–1990s',roots:['Disco','Electronic Dance'],branches:['Deep House','Acid House'],dna:['Four-on-the-Floor','Piano Stabs','Looped Groove'],bpm:'118–128 BPM',rhythm:'Steady club pulse',instruments:['Drum Machine','Piano Stabs','Synth Bass','Vocal Chops'],vocals:['House Diva Vocal','Short Repeated Hook'],production:['Club Mix','Sidechain Pump']},
'Techno':{era:'1990s',roots:['Electronic','Industrial'],branches:['Minimal Techno','Detroit Techno'],dna:['Mechanical Pulse','Hypnotic Repetition','Dark Texture'],bpm:'125–140 BPM',rhythm:'Rigid four-on-the-floor',instruments:['Analog Synth','Drum Machine','Industrial Percussion'],vocals:['Minimal Spoken Vocal','Robotic Phrase'],production:['Dry Punchy Mix','Repetitive Automation']},
'Progressive House':{era:'2000s–2010s',roots:['House','Trance'],branches:['Festival Progressive','Melodic House'],dna:['Long Build','Emotional Chords','Anthemic Drop'],bpm:'126–132 BPM',rhythm:'Four-on-the-floor with extended builds',instruments:['Supersaw Synth','Piano','Electronic Drums','Sub Bass'],vocals:['Emotional Pop Vocal','Large Chorus'],production:['Wide Sidechained Mix','Bright Master']},
'Modern Festival EDM':{era:'2020s',roots:['Progressive House','Big Room'],branches:['Future Rave','Mainstage Hybrid'],dna:['Short Build','Huge Drop','Hybrid Bass'],bpm:'126–150 BPM',rhythm:'Club pulse with impact breaks',instruments:['Hybrid Synth Bass','Festival Lead','Electronic Drums','FX Risers'],vocals:['Short Hook Vocal','Processed Vocal Chop'],production:['Ultra-Wide Mix','Heavy Sidechain','Massive Drop Impact']},
'Dub':{era:'1970s',roots:['Reggae'],branches:['Dub Techno','Trip-Hop'],dna:['Deep Bass','Delay Space','Sparse Rhythm'],bpm:'70–100 BPM',rhythm:'Half-time reggae pulse',instruments:['Deep Bass','Organic Drums','Delay Guitar'],vocals:['Sparse Toasting','Echo Vocal'],production:['Tape Delay','Spring Reverb']},
'Dubstep':{era:'2000s',roots:['UK Garage','Dub'],branches:['Brostep','Post-Dubstep'],dna:['Half-Time Beat','Sub Bass','Dark Space'],bpm:'138–142 BPM',rhythm:'Half-time bass groove',instruments:['Sub Bass','Electronic Drums','Dark Pads'],vocals:['Minimal Vocal Phrase','Atmospheric Vocal'],production:['Deep Sub Mix','Wide Reverb']},
'Brostep':{era:'2010s',roots:['Dubstep'],branches:['Riddim','Hybrid Trap'],dna:['Aggressive Bass Modulation','Drop Contrast','Sharp Transients'],bpm:'140–150 BPM',rhythm:'Half-time drop with syncopated bass',instruments:['Growl Bass','Electronic Drums','Impact FX'],vocals:['Shouted Build Vocal','Processed Samples'],production:['Aggressive Compression','Bright Bass Design']},
'Future Bass':{era:'2010s',roots:['Dubstep','Trap'],branches:['Melodic Bass','Future Pop'],dna:['Pitch-Bent Chords','Emotional Drop','Vocal Chops'],bpm:'130–160 BPM',rhythm:'Half-time beat with syncopated chords',instruments:['Lush Synth Chords','Sub Bass','Vocal Chops'],vocals:['Airy Pop Vocal','Chopped Harmony'],production:['Wide Colorful Mix','Soft Sidechain']},
'Cinematic Bass Music':{era:'2020s',roots:['Future Bass','Trailer Music'],branches:['Orchestral Bass','Game Trailer EDM'],dna:['Orchestral Build','Hybrid Drop','Narrative Dynamics'],bpm:'120–155 BPM',rhythm:'Cinematic pulses into bass drops',instruments:['Orchestra','Hybrid Bass','Cinematic Percussion','Choir'],vocals:['Ethereal Vocal','Trailer Choir'],production:['Cinematic Hybrid Mix','Massive Low-End Impact']}}},
'Hip-Hop':{paths:{'Rap Evolution':['Old School Hip-Hop','Boom Bap','Gangsta Rap','Trap','Modern Cinematic Rap'],'Alternative Evolution':['Boom Bap','Jazz Rap','Conscious Rap','Alternative Hip-Hop','Experimental Art Rap']},stages:{
'Old School Hip-Hop':{era:'1980s',roots:['Funk','Disco'],branches:['Boom Bap','Electro'],dna:['Breakbeat','Party Flow','Simple Hook'],bpm:'90–115 BPM',rhythm:'Looped breakbeat groove',instruments:['Drum Break','Funk Bass','Turntable Scratch'],vocals:['Rhythmic Rap Vocal','Group Shouts'],production:['Dry Sample Mix','Raw Drum Loop']},
'Boom Bap':{era:'1990s',roots:['Old School Hip-Hop'],branches:['Jazz Rap','Underground Rap'],dna:['Hard Kick/Snare','Sample Loop','Dense Bars'],bpm:'82–98 BPM',rhythm:'Head-nod breakbeat',instruments:['Sampled Piano','Dusty Drums','Bass Loop'],vocals:['Close-Mic Rap Vocal','Clear Word Emphasis'],production:['Vinyl Dust','Punchy Mono-Centered Drums']},
'Gangsta Rap':{era:'1990s',roots:['Boom Bap','West Coast Funk'],branches:['G-Funk','Street Rap'],dna:['Dark Narrative','Heavy Groove','Memorable Hook'],bpm:'82–105 BPM',rhythm:'Laid-back or hard breakbeat',instruments:['Synth Bass','Drum Machine','Dark Keys'],vocals:['Deep Rap Vocal','Narrative Delivery'],production:['Heavy Low End','Dry Forward Vocal']},
'Trap':{era:'2010s',roots:['Southern Hip-Hop'],branches:['Drill','Melodic Trap'],dna:['Hi-Hat Rolls','808 Bass','Sparse Melody'],bpm:'130–160 BPM',rhythm:'Half-time trap groove',instruments:['808 Bass','Trap Drums','Dark Bell','Ambient Pad'],vocals:['Rhythmic Rap Vocal','Ad-Lib Layers'],production:['Sub-Heavy Mix','Crisp Hi-Hats']},
'Modern Cinematic Rap':{era:'2020s',roots:['Trap','Trailer Music'],branches:['Anime Rap','Game Rap'],dna:['Narrative Verse','Cinematic Build','Massive Hook'],bpm:'90–150 BPM',rhythm:'Trap or boom-bap foundation with cinematic accents',instruments:['808 Bass','Cinematic Strings','Brass','Hybrid Drums'],vocals:['Clear Rap Lead','Choir Hook','Narrator'],production:['Wide Cinematic Mix','Impactful Low End']},
'Jazz Rap':{era:'1990s',roots:['Boom Bap','Jazz'],branches:['Neo-Soul Hip-Hop','Lo-Fi Rap'],dna:['Jazz Samples','Relaxed Flow','Warm Harmony'],bpm:'78–100 BPM',rhythm:'Loose boom-bap swing',instruments:['Rhodes Piano','Upright Bass','Jazz Drums','Saxophone'],vocals:['Relaxed Rap Vocal','Spoken Hook'],production:['Warm Sample Texture','Soft Compression']},
'Conscious Rap':{era:'2000s',roots:['Jazz Rap','Boom Bap'],branches:['Political Rap','Storytelling Rap'],dna:['Message Focus','Clear Lyrics','Emotional Hook'],bpm:'80–110 BPM',rhythm:'Steady lyric-friendly groove',instruments:['Piano','Strings','Boom-Bap Drums'],vocals:['Clear Storytelling Rap','Soulful Hook'],production:['Vocal-Forward Mix','Controlled Dynamics']},
'Alternative Hip-Hop':{era:'2010s',roots:['Conscious Rap','Electronic'],branches:['Cloud Rap','Art Rap'],dna:['Genre Mixing','Unusual Texture','Personal Narrative'],bpm:'75–145 BPM',rhythm:'Flexible hip-hop pulse',instruments:['Experimental Synth','Organic Samples','Hybrid Drums'],vocals:['Characterful Rap Vocal','Layered Spoken Voice'],production:['Textural Mix','Creative Vocal Effects']},
'Experimental Art Rap':{era:'2020s',roots:['Alternative Hip-Hop','Art Pop'],branches:['Abstract Rap','Industrial Rap'],dna:['Nonlinear Structure','Extreme Texture','Voice as Instrument'],bpm:'70–160 BPM',rhythm:'Unstable or changing groove',instruments:['Glitch Percussion','Distorted Synth','Found Sound'],vocals:['Spoken/Rapped Hybrid','Processed Vocal Layers'],production:['Experimental Stereo Design','Abrupt Dynamic Contrast']}}},
'Folk & Nordic':{paths:{'Nordic Evolution':['Traditional Nordic Folk','Neo-Folk','Viking Folk','Nordic Cinematic','Viking EDM'],'Celtic Evolution':['Traditional Celtic','Celtic Folk Rock','Celtic Metal','Cinematic Celtic','Celtic Electronic']},stages:{
'Traditional Nordic Folk':{era:'Traditional',roots:['Regional Folk'],branches:['Neo-Folk','Ritual Folk'],dna:['Modal Melody','Drone','Organic Rhythm'],bpm:'70–120 BPM',rhythm:'Free pulse or folk dance rhythm',instruments:['Tagelharpa','Nyckelharpa','Frame Drum','Wood Flute'],vocals:['Nordic Chant','Raw Folk Vocal'],production:['Natural Acoustic Space','Minimal Processing']},
'Neo-Folk':{era:'1990s–2000s',roots:['Traditional Folk','Darkwave'],branches:['Dark Folk','Pagan Folk'],dna:['Dark Acoustic Texture','Repetitive Motif','Intimate Vocal'],bpm:'70–115 BPM',rhythm:'Restrained folk pulse',instruments:['Acoustic Guitar','Frame Drum','Drone Strings'],vocals:['Low Intimate Vocal','Group Chant'],production:['Dark Room Tone','Organic Dynamics']},
'Viking Folk':{era:'2010s',roots:['Nordic Folk','Pagan Folk'],branches:['Ritual Viking','Folk Metal'],dna:['War Chant','Tribal Percussion','Modal Drone'],bpm:'80–130 BPM',rhythm:'Marching or ritual pulse',instruments:['Tagelharpa','War Drums','Horn','Bone Flute'],vocals:['Deep Male Chant','Female Ritual Vocal','Group Shouts'],production:['Large Natural Reverb','Heavy Organic Percussion']},
'Nordic Cinematic':{era:'2010s–2020s',roots:['Viking Folk','Film Score'],branches:['Game Soundtrack','Dark Nordic Trailer'],dna:['Orchestral Expansion','Choir','Narrative Build'],bpm:'70–135 BPM',rhythm:'Slow pulse into cinematic crescendo',instruments:['Tagelharpa','Orchestra','Cinematic Percussion','Choir'],vocals:['Deep Narrator','Ethereal Female Vocal','Male Choir'],production:['Wide Cinematic Mix','Large Hall Space']},
'Viking EDM':{era:'2020s',roots:['Viking Folk','EDM'],branches:['Nordic Techno','Folk Bass Music'],dna:['Folk Motif','Electronic Pulse','Massive Drop'],bpm:'120–150 BPM',rhythm:'Four-on-the-floor or half-time electronic groove',instruments:['Tagelharpa','Electronic Drums','Synth Bass','War Horn'],vocals:['Nordic Chant','Processed Choir','Deep Spoken Vocal'],production:['Hybrid Folk/Electronic Mix','Heavy Sidechain']},
'Traditional Celtic':{era:'Traditional',roots:['Regional Folk'],branches:['Celtic Folk Rock'],dna:['Dance Melody','Ornamentation','Acoustic Ensemble'],bpm:'90–150 BPM',rhythm:'Jig, reel or ballad pulse',instruments:['Tin Whistle','Fiddle','Bodhrán','Celtic Harp'],vocals:['Clear Folk Vocal','Group Chorus'],production:['Natural Acoustic Mix','Room Ambience']},
'Celtic Folk Rock':{era:'1970s–1990s',roots:['Traditional Celtic','Rock'],branches:['Celtic Punk','Celtic Metal'],dna:['Folk Melody','Rock Backbeat','Singalong Chorus'],bpm:'105–155 BPM',rhythm:'Rock groove with folk dance accents',instruments:['Fiddle','Electric Guitar','Bodhrán','Acoustic Drums'],vocals:['Folk Rock Lead','Group Singalong'],production:['Organic Rock Mix','Forward Folk Instruments']},
'Celtic Metal':{era:'2000s',roots:['Celtic Folk Rock','Heavy Metal'],branches:['Folk Metal','Pagan Metal'],dna:['Heavy Riff','Folk Lead','Epic Chorus'],bpm:'120–190 BPM',rhythm:'Metal drive with jig accents',instruments:['Heavy Guitar','Tin Whistle','Fiddle','Double-Kick Drums'],vocals:['Powerful Clean Vocal','Harsh Vocal Contrast'],production:['Tight Metal Mix','Bright Folk Lead']},
'Cinematic Celtic':{era:'2010s',roots:['Celtic Folk','Film Score'],branches:['Fantasy Soundtrack'],dna:['Emotional Theme','Orchestra','Heroic Build'],bpm:'70–130 BPM',rhythm:'Flexible cinematic pulse',instruments:['Celtic Harp','Tin Whistle','Orchestra','Cinematic Percussion'],vocals:['Ethereal Female Vocal','Choir'],production:['Wide Orchestral Mix','Large Hall Reverb']},
'Celtic Electronic':{era:'2020s',roots:['Cinematic Celtic','Electronic'],branches:['Celtic EDM','Fantasy Bass'],dna:['Folk Hook','Electronic Groove','Festival Lift'],bpm:'118–150 BPM',rhythm:'Electronic dance pulse with folk phrasing',instruments:['Tin Whistle','Synth Bass','Electronic Drums','Fiddle'],vocals:['Folk Pop Vocal','Layered Choir'],production:['Polished Hybrid Mix','Sidechained Folk Layers']}}}
};
const PRESETS=[['Anime Rock Evolution','Rock','Classic to Modern','Modern Arena Rock'],['Viking EDM Path','Folk & Nordic','Nordic Evolution','Viking EDM'],['Cinematic Rap Path','Hip-Hop','Rap Evolution','Modern Cinematic Rap'],['Festival EDM Path','Electronic','Club Evolution','Modern Festival EDM'],['Metalcore Mutation','Rock','Heavy Evolution','Modern Heavy Hybrid'],['Dark Nordic Trailer','Folk & Nordic','Nordic Evolution','Nordic Cinematic'],['Art Rap Mutation','Hip-Hop','Alternative Evolution','Experimental Art Rap'],['Cinematic Bass','Electronic','Bass Evolution','Cinematic Bass Music']];
let activeFamily='Rock',activePath='Classic to Modern',activeStage='Modern Arena Rock',fusionText='';
function stage(){return DATA[activeFamily].stages[activeStage]}
function families(){$('geFamily').innerHTML=Object.keys(DATA).map(x=>`<option>${x}</option>`).join('');$('geFamily').value=activeFamily}
function paths(){$('gePath').innerHTML=Object.keys(DATA[activeFamily].paths).map(x=>`<option>${x}</option>`).join('');if(!DATA[activeFamily].paths[activePath])activePath=Object.keys(DATA[activeFamily].paths)[0];$('gePath').value=activePath;eras()}
function eras(){const list=DATA[activeFamily].paths[activePath];$('geEra').innerHTML=list.map(x=>`<option>${x}</option>`).join('');if(!list.includes(activeStage))activeStage=list[list.length-1];$('geEra').value=activeStage;$('geEraSlider').max=list.length-1;$('geEraSlider').value=list.indexOf(activeStage);$('gePathCount').textContent=`${list.length} stages`}
function renderTimeline(){const list=DATA[activeFamily].paths[activePath];$('geTimeline').innerHTML=list.map((x,i)=>{const s=DATA[activeFamily].stages[x];return`<article class="ge-stage ${x===activeStage?'active':''}" data-stage="${x}"><small>${s.era}</small><b>${x}</b><span>${s.dna.slice(0,2).join(' · ')}</span></article>`}).join('');document.querySelectorAll('[data-stage]').forEach(e=>e.onclick=()=>{activeStage=e.dataset.stage;$('geEra').value=activeStage;$('geEraSlider').value=list.indexOf(activeStage);render()})}
function renderBranch(){const s=stage(),desc=Object.entries(DATA[activeFamily].paths).flatMap(([p,a])=>a.filter(x=>x!==activeStage&&a.indexOf(x)>a.indexOf(activeStage))).slice(0,4);$('geActiveStage').textContent=`${activeStage} · ${s.era}`;$('geBranchMap').innerHTML=[['Roots',s.roots.join(', ')],['Related branches',s.branches.join(', ')],['Modern descendants',uniq(desc).join(', ')||'Current endpoint'],['Core identity',s.dna.join(', ')]].map(([a,b])=>`<div class="ge-branch"><small>${a}</small><b>${b}</b></div>`).join('')}
function chips(id,a){$(id).innerHTML=a.map(x=>`<span class="ge-chip">${x}</span>`).join('')}
function metric(a,b){return`<div class="ge-metric"><span>${a}</span><b>${b}</b></div>`}
function compatibility(a,b){if(a===b)return 100;const A=DATA[activeFamily].stages[a],B=findStage(b);if(!B)return 55;let s=48;const words=x=>new Set((x.dna.join(' ')+' '+x.instruments.join(' ')+' '+x.production.join(' ')).toLowerCase().split(/\W+/));const aw=words(A),bw=words(B);for(const x of aw)if(bw.has(x))s+=3;if(A.roots.some(x=>B.roots.includes(x)))s+=12;if(/electronic|edm|techno|house|bass/i.test(b))s+=activeFamily==='Electronic'?20:8;if(/cinematic|orchestral/i.test(b))s+=10;return clamp(s,25,95)}
function findStage(name){for(const f of Object.values(DATA))if(f.stages[name])return f.stages[name];return null}
function secondaryOptions(){const all=[];for(const [f,d] of Object.entries(DATA))for(const x of Object.keys(d.stages))if(x!==activeStage)all.push(x);$('geSecondary').innerHTML=all.map(x=>`<option>${x}</option>`).join('');$('gePrimary').value=activeStage}
function warnings(){const sec=$('geSecondary').value,score=compatibility(activeStage,sec),out=[];if(score<45)out.push('This fusion has weak shared DNA and may lose the primary genre identity.');if($('geBlend').value==='strong'&&score<65)out.push('A strong hybrid is risky at this compatibility level.');if(stage().instruments.length+((findStage(sec)?.instruments||[]).length)>11)out.push('Combining both complete instrument palettes would be overcrowded.');if(!out.length)out.push('No major fusion conflict detected.');$('geWarnings').innerHTML=out.map(x=>`<div class="ge-message ${out.length===1&&out[0].startsWith('No major')?'good':'warn'}">${x}</div>`).join('');$('geFusionScore').textContent=`Compatibility ${score}%`;return score}
function styleText(){const s=stage(),goal=$('geGoal').value,mods={authentic:['Authentic Era Production','Organic Performance'],modern:['Modern Production','Clear Dynamic Mix'],cinematic:['Cinematic Expansion','Large Dynamic Arc','Orchestral Support'],experimental:['Experimental Genre Mutation','Unexpected Texture','Strong Contrast'],commercial:['Accessible Hook','Focused Arrangement','Polished Production']}[goal];return uniq([activeStage,...s.dna,...s.instruments,...s.vocals,...s.production,...mods,s.bpm,s.rhythm,fusionText]).flat().filter(Boolean).join(', ')}
function analyze(){const s=stage(),sec=$('geSecondary').value,comp=compatibility(activeStage,sec),coherence=clamp(72+s.dna.length*3-(fusionText&&comp<55?18:0)-($('geBlend').value==='strong'&&comp<65?10:0));$('geScore').textContent=coherence;$('geScoreBar').style.width=coherence+'%';$('geBadge').textContent=`${activeFamily} · ${activeStage} · ${s.era} · local map`;chips('geDNA',[activeStage,...s.dna]);$('geRhythm').innerHTML=metric('Tempo',s.bpm)+metric('Rhythm',s.rhythm)+metric('Era',s.era);chips('geInstruments',s.instruments);chips('geVocals',s.vocals);chips('geProduction',s.production);$('geStyleOutput').value=styleText();window.NSW_GENRE_EVOLUTION_LAST={family:activeFamily,path:activePath,stage:activeStage,goal:$('geGoal').value,fusion:fusionText,style:$('geStyleOutput').value,updatedAt:Date.now()};warnings()}
function render(){families();paths();eras();renderTimeline();renderBranch();secondaryOptions();analyze()}
function buildFusion(){const sec=$('geSecondary').value,B=findStage(sec),strength=$('geBlend').value,focus=$('geFusionFocus').value,score=compatibility(activeStage,sec),count=strength==='light'?1:strength==='balanced'?2:3;let source=focus==='rhythm'?[B.rhythm,B.bpm]:focus==='instruments'?B.instruments:focus==='production'?B.production:focus==='vocals'?B.vocals:B.dna;const selected=Array.isArray(source)?source.slice(0,count):[source];fusionText=`${strength==='light'?'with subtle':strength==='balanced'?'supported by':'strongly fused with'} ${sec} ${focus}: ${selected.join(', ')}`;$('geFusionResult').innerHTML=`<b>${activeStage} + ${sec}</b><br>${fusionText}<br><small>Compatibility ${score}% · primary identity remains ${activeStage}</small>`;analyze()}
function presets(){$('gePresetCount').textContent=`${PRESETS.length} presets`;$('gePresetGrid').innerHTML=PRESETS.map(p=>`<button class="ge-preset" data-preset="${p[0]}"><b>${p[0]}</b><small>${p[1]} · ${p[2]} → ${p[3]}</small></button>`).join('');document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=PRESETS.find(x=>x[0]===b.dataset.preset);activeFamily=p[1];activePath=p[2];activeStage=p[3];fusionText='';render()})}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch(e){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}}
function apply(){const e=$('customStyle');if(!e)return;e.value=$('geStyleOutput').value;e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Genre Evolution STYLE applied.')}
function saveProject(){let pm;try{pm=JSON.parse(localStorage.getItem('nsw-project-manager-v4')||'null')}catch(e){}if(!pm?.projects?.length)return;const p=pm.projects.find(x=>x.id===pm.activeProjectId)||pm.projects[0],t=p.tracks?.[0];if(!t)return;t.genreEvolution={family:activeFamily,path:activePath,stage:activeStage,goal:$('geGoal').value,fusion:fusionText,style:$('geStyleOutput').value,updatedAt:Date.now()};t.updated=Date.now();p.updated=Date.now();localStorage.setItem('nsw-project-manager-v4',JSON.stringify(pm));if(typeof showToast==='function')showToast('Genre Evolution saved to Project Manager.')}
function init(){if(!$('geGenerate'))return;presets();render();$('geFamily').onchange=e=>{activeFamily=e.target.value;activePath=Object.keys(DATA[activeFamily].paths)[0];activeStage=DATA[activeFamily].paths[activePath].slice(-1)[0];fusionText='';render()};$('gePath').onchange=e=>{activePath=e.target.value;activeStage=DATA[activeFamily].paths[activePath].slice(-1)[0];fusionText='';render()};$('geEra').onchange=e=>{activeStage=e.target.value;fusionText='';render()};$('geEraSlider').oninput=e=>{activeStage=DATA[activeFamily].paths[activePath][+e.target.value];fusionText='';render()};$('geGoal').onchange=analyze;$('geGenerate').onclick=analyze;$('geBuildFusion').onclick=buildFusion;$('geSecondary').onchange=warnings;$('geBlend').onchange=warnings;$('geUseBuilder').onclick=()=>{const raw=String($('subgenre')?.value||$('genreFamily')?.value||'').toLowerCase();for(const [f,d] of Object.entries(DATA)){for(const s of Object.keys(d.stages)){if(raw.includes(s.toLowerCase().split(' ')[0])){activeFamily=f;for(const [p,a] of Object.entries(d.paths))if(a.includes(s)){activePath=p;activeStage=s;break}render();return}}}};$('geRandom').onclick=()=>{activeFamily=Object.keys(DATA)[Math.floor(Math.random()*Object.keys(DATA).length)];activePath=Object.keys(DATA[activeFamily].paths)[Math.floor(Math.random()*Object.keys(DATA[activeFamily].paths).length)];const a=DATA[activeFamily].paths[activePath];activeStage=a[Math.floor(Math.random()*a.length)];fusionText='';render()};$('geReset').onclick=()=>{activeFamily='Rock';activePath='Classic to Modern';activeStage='Modern Arena Rock';fusionText='';render()};$('geCopyStyle').onclick=async()=>{await copy($('geStyleOutput').value);if(typeof showToast==='function')showToast('Genre Evolution STYLE copied.')};$('geApplyStyle').onclick=apply;$('geSaveProject').onclick=saveProject}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
