
(function(){
'use strict';const $=id=>document.getElementById(id);let step=0,result=null;const values={mood:'epic',voice:'Female Lead Vocal',world:'Medieval Europe',energy:'Controlled Build',risk:'creative'};
const labels={mood:'Stimmung',voice:'Stimme',world:'Klangwelt',energy:'Energie',risk:'Kreativität'};
function selectGroup(id,key){document.querySelectorAll(`#${id} button`).forEach(b=>b.onclick=()=>{values[key]=b.dataset.value;document.querySelectorAll(`#${id} button`).forEach(x=>x.classList.toggle('selected',x===b));summary()});const first=document.querySelector(`#${id} button`);if(first)first.click()}
function show(){document.querySelectorAll('.guided-step').forEach((x,i)=>x.classList.toggle('active',i===step));$('guidedProgressBar').style.width=((step+1)/6*100)+'%';$('guidedProgressLabel').textContent=`Schritt ${step+1} von 6`;$('guidedBack').disabled=step===0;$('guidedNext').classList.toggle('hidden',step===5);$('guidedFinish').classList.toggle('hidden',step!==5);summary()}
function summary(){const idea=$('guidedIdea')?.value||'Noch keine Songidee';$('guidedSelection').innerHTML=`<div class="guided-selection-item"><small>Songidee</small><b>${idea.slice(0,100)}</b></div>`+Object.entries(values).map(([k,v])=>`<div class="guided-selection-item"><small>${labels[k]}</small><b>${v}</b></div>`).join('')}
function finish(){const idea=$('guidedIdea').value.trim();if(!idea){step=0;show();$('guidedIdea').focus();return}const prompt=`${idea}. Mood: ${values.mood}. Voice: ${values.voice}. World music direction: ${values.world}. Energy: ${values.energy}.`;const profile=values.risk==='safe'?'safe':values.risk==='experimental'?'bold':'balanced';const r=window.NSWSongDirectorCore?.buildDirectorResult(prompt,{profile,goal:'song',duration:'3:00',language:'auto',useLearning:false});if(!r)return;let style=r.style;if(values.risk==='safe')style=style.split(',').slice(0,12).join(', ');if(values.risk==='experimental')style=window.NSWConnections?.mergeStyle([style,'Unexpected Genre Contrast','Experimental Transitions','Extreme Dynamic Contrast'])||style;result={...r,style};$('guidedStyleOutput').value=style;$('guidedMetaOutput').value=r.lyricsBlueprint;$('guidedMetaWrap').classList.toggle('hidden',!$('guidedMetaTags').checked);$('guidedScore').textContent=(values.risk==='safe'?94:values.risk==='creative'?87:76)+'%';$('guidedExplain').textContent=`Das Studio hat ${r.parsed.primaryGenre.label} erkannt und mit ${values.world}, ${values.voice} und ${values.energy} verbunden. Die wichtigsten Instrumente sind ${r.parsed.instruments.slice(0,5).join(', ')}.`;$('guidedResult').classList.remove('hidden');$('guidedResult').scrollIntoView({behavior:'smooth'})}
function mode(which){document.body.classList.toggle('guided-active',which==='guided');$('guidedView').classList.toggle('active',which==='guided');if(which==='guided'){document.querySelectorAll('.view:not(#guidedView)').forEach(v=>v.classList.remove('active'));$('guidedModeButton').classList.add('active');$('simpleModeButton').classList.remove('active');$('advancedModeButton').classList.remove('active')}else $('guidedModeButton').classList.remove('active')}
function init(){if(!$('guidedModeButton'))return;$('guidedModeButton').onclick=()=>mode('guided');$('simpleModeButton').addEventListener('click',()=>mode('other'));$('advancedModeButton').addEventListener('click',()=>mode('other'));$('guidedNext').onclick=()=>{if(step===0&&!$('guidedIdea').value.trim())return;step=Math.min(5,step+1);show()};$('guidedBack').onclick=()=>{step=Math.max(0,step-1);show()};$('guidedFinish').onclick=finish;$('guidedIdea').oninput=summary;selectGroup('guidedMood','mood');selectGroup('guidedVoice','voice');selectGroup('guidedWorld','world');selectGroup('guidedEnergy','energy');selectGroup('guidedRisk','risk');$('guidedCopy').onclick=()=>navigator.clipboard?.writeText($('guidedStyleOutput').value);$('guidedApply').onclick=()=>{if(!result)return;window.NSWConnections?.setStyle(result.style)};$('guidedAdvanced').onclick=()=>{$('advancedModeButton').click();setTimeout(()=>document.querySelector('.nav[data-view="styleView"]')?.click(),50)};show()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
