(function(){'use strict';
const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),uniq=a=>[...new Set(a.filter(Boolean))];
const FAMILIES={Strings:['Violin','Cello','Tagelharpa'],Guitars:['Electric Guitar','Acoustic Guitar'],Keys:['Piano','Synthesizer'],Winds:['Flute','Duduk'],Brass:['Trumpet','French Horn'],Percussion:['Acoustic Drums','Taiko'],World:['Koto','Shamisen']};
const PROFILE={
'Violin':['bright expressive','anime rock cinematic folk'],'Cello':['warm deep emotional','cinematic ballad folk metal'],'Tagelharpa':['raw ancient droning','folk cinematic metal'],'Electric Guitar':['powerful energetic','rock metal anime pop'],'Acoustic Guitar':['warm intimate organic','folk ballad pop rock'],'Piano':['clear emotional harmonic','ballad pop cinematic jazz anime'],'Synthesizer':['electronic adaptable atmospheric','edm anime cinematic pop rap'],'Flute':['airy lyrical light','folk cinematic ballad anime'],'Duduk':['dark breathy ancient','cinematic folk ballad'],'Trumpet':['bright bold triumphant','jazz cinematic pop swing'],'French Horn':['noble warm cinematic','cinematic anime metal'],'Acoustic Drums':['organic powerful dynamic','rock metal pop jazz anime'],'Taiko':['massive ritual cinematic','cinematic anime folk metal'],'Koto':['delicate bright Japanese','anime folk cinematic'],'Shamisen':['sharp percussive dramatic','anime folk rock cinematic']};
const ROLES=['Lead Melody','Countermelody','Harmony Layer','Rhythmic Pulse','Ostinato','Drone','Atmospheric Texture','Bass Foundation','Accent Hits','Call and Response','Transition Effect'];
const ART=['Natural Sustained','Short Staccato','Legato','Tremolo','Pizzicato','Muted','Aggressive Attack','Soft Bowed','Plucked Pulse','Glissando','Harmonics','Distorted Performance'];
const REG=['Low Register','Low-Mid Register','Mid Register','Upper-Mid Register','High Register','Wide Register Range'];
const MOV=['Long Sustained Notes','Slow Melodic Phrases','Stepwise Melody','Wide Interval Leaps','Rapid Repeating Pattern','Syncopated Rhythm','Driving Eighth-Note Pulse','Arpeggiated Movement','Improvised Phrasing'];
const DYN=['Restrained','Gradual Build','Controlled Contrast','Powerful','Explosive Accents','Massive Crescendo','Soft Emotional Swells','Constant Driving Energy'];
const PROD=['Natural Room Recording','Dry Close-Mic','Warm Analog Production','Wide Stereo Layer','Large Hall Reverb','Cinematic Hybrid Processing','Heavy Distortion','Granular Texture','Sidechained Electronic Layer','Vintage Radio Texture'];
const PLACE=['Throughout the Song','Intro Only','Verses','Pre-Chorus Build','Chorus','Bridge','Breakdown','Final Chorus','Outro'];
const PRI=['Primary Focus','Strong Supporting Layer','Subtle Supporting Layer','Background Texture','Momentary Accent'];
const STAGES=[['Identity','Natural Identity','Lead Melody','Natural Sustained','Mid Register','Slow Melodic Phrases','Restrained','Natural Room Recording','Throughout the Song'],['Articulation','Expressive Articulation','Lead Melody','Legato','Upper-Mid Register','Stepwise Melody','Soft Emotional Swells','Dry Close-Mic','Verses'],['Arrangement','Arrangement Role','Countermelody','Short Staccato','Mid Register','Arpeggiated Movement','Gradual Build','Wide Stereo Layer','Pre-Chorus Build'],['Cinematic','Cinematic Expansion','Harmony Layer','Tremolo','Wide Register Range','Wide Interval Leaps','Massive Crescendo','Large Hall Reverb','Chorus'],['Hybrid','Modern Hybrid Mutation','Rhythmic Pulse','Distorted Performance','Mid Register','Syncopated Rhythm','Powerful','Cinematic Hybrid Processing','Breakdown'],['Signature','Signature Finale','Lead Melody','Legato','High Register','Improvised Phrasing','Massive Crescendo','Wide Stereo Layer','Final Chorus']];
const PRESETS={'Anime Guitar Hero':['Guitars','Electric Guitar','cinematic','anime',5],'Nordic Tagelharpa Hybrid':['Strings','Tagelharpa','modern','folk',4],'Cinematic Cello Pulse':['Strings','Cello','cinematic','cinematic',3],'Electro Koto':['World','Koto','modern','edm',4],'Epic Taiko War Drums':['Percussion','Taiko','aggressive','cinematic',5],'Dark Duduk Atmosphere':['Winds','Duduk','emotional','cinematic',4],'Jazz Trumpet Evolution':['Brass','Trumpet','authentic','jazz',2],'Festival Synth Evolution':['Keys','Synthesizer','modern','edm',5],'Emotional Piano Arc':['Keys','Piano','emotional','ballad',5],'Metal Drum Mutation':['Percussion','Acoustic Drums','aggressive','metal',4]};
let family='Strings',instrument='Violin',stage=0,layers=[],next=1,custom={};
function opt(a,v){return a.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}
function item(i=stage){if(typeof i==='string')return layers.find(x=>x.id===i);const r=STAGES[i],c=custom[i]||{};return{id:String(i),name:`${instrument} ${r[1]}`,role:r[2],art:r[3],reg:r[4],mov:r[5],dyn:r[6],prod:r[7],place:r[8],priority:i===5?'Primary Focus':i>=3?'Strong Supporting Layer':'Subtle Supporting Layer',presence:55+i*8,complexity:25+i*10,human:80-i*5,width:30+i*10,notes:'',...c}}
function current(){return item(stage)}
function renderSelectors(){$('ieFamily').innerHTML=opt(Object.keys(FAMILIES),family);$('ieInstrument').innerHTML=opt(FAMILIES[family],instrument)}
function timeline(){$('ieTimeline').innerHTML=STAGES.map((r,i)=>{const x=item(i);return`<button class="ie-stage ${stage===i?'active':''}" data-stage="${i}"><small>Stage ${i+1}</small><b>${x.name}</b><p>${x.role}<br>${x.art}</p></button>`}).join('');document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{stage=+b.dataset.stage;$('ieStageSlider').value=stage;render()});$('ieStageLabel').textContent=`Stage ${typeof stage==='number'?stage+1:'Layer'} of 6`}
function rolemap(){const x=current(),nodes=[['Primary Instrument',instrument,x.role,true],['Harmony Support',layers.find(y=>y.role==='Harmony Layer')?.name||'Optional','Chord and width'],['Rhythm Support',layers.find(y=>/Rhythmic|Ostinato/.test(y.role))?.name||'Optional','Pulse and motion'],['Texture Support',layers.find(y=>/Texture|Drone/.test(y.role))?.name||'Optional','Atmosphere and depth'],['Bass Support',layers.find(y=>y.role==='Bass Foundation')?.name||'Optional','Low-end foundation']];$('ieRoleMap').innerHTML=nodes.map(n=>`<article class="ie-role-node ${n[3]?'primary':''}"><b>${n[0]}</b><small>${n[1]}</small><span>${n[2]}</span></article>`).join('');$('ieRoleCount').textContent=`${1+layers.length} active roles`}
function inspector(){const x=current();$('ieInspector').innerHTML=`<h3>${x.name}</h3><p style="color:#aec4ce;font-size:10px">${PROFILE[instrument][0]} instrument direction for ${$('ieGoal').value} evolution.</p><div class="ie-detail-grid">${[['Role',x.role],['Articulation',x.art],['Register',x.reg],['Movement',x.mov],['Dynamics',x.dyn],['Production',x.prod],['Placement',x.place],['Priority',x.priority]].map(v=>`<div class="ie-detail"><small>${v[0]}</small><b>${v[1]}</b></div>`).join('')}</div>`}
function lab(){const x=current();$('ieLabStage').textContent=x.name;$('ieRole').innerHTML=opt(ROLES,x.role);$('ieArticulation').innerHTML=opt(ART,x.art);$('ieRegister').innerHTML=opt(REG,x.reg);$('ieMovement').innerHTML=opt(MOV,x.mov);$('ieDynamics').innerHTML=opt(DYN,x.dyn);$('ieProduction').innerHTML=opt(PROD,x.prod);$('iePlacement').innerHTML=opt(PLACE,x.place);$('iePriority').innerHTML=opt(PRI,x.priority);for(const k of ['Presence','Complexity','Human','Width']){$('ie'+k).value=x[k.toLowerCase()];$('ie'+k+'Value').textContent=x[k.toLowerCase()]+'%'}$('ieNotes').value=x.notes||''}
function save(){const v={role:$('ieRole').value,art:$('ieArticulation').value,reg:$('ieRegister').value,mov:$('ieMovement').value,dyn:$('ieDynamics').value,prod:$('ieProduction').value,place:$('iePlacement').value,priority:$('iePriority').value,presence:+$('iePresence').value,complexity:+$('ieComplexity').value,human:+$('ieHuman').value,width:+$('ieWidth').value,notes:$('ieNotes').value};if(typeof stage==='number')custom[stage]={...(custom[stage]||{}),...v};else Object.assign(layers.find(x=>x.id===stage),v);render()}
function addLayer(){const x=current();layers.push({...x,id:'layer'+next++,name:`${instrument} Supporting Layer ${layers.length+1}`,role:'Harmony Layer',priority:'Subtle Supporting Layer',presence:40});stage=layers.at(-1).id;render()}
function duplicate(){const x=current();layers.push({...x,id:'layer'+next++,name:x.name+' Layer',priority:'Subtle Supporting Layer',presence:Math.max(25,x.presence-20)});stage=layers.at(-1).id;render()}
function remove(){if(typeof stage==='number')return $('ieStatus').textContent='Core stages cannot be removed.';layers=layers.filter(x=>x.id!==stage);stage=0;render()}
function genre(){const v=$('ieGenre').value;if(v!=='auto')return v;return String($('subgenre')?.value||$('genreFamily')?.value||'cinematic').toLowerCase()}
function smart(){const g=genre();$('ieGoal').value=g.includes('metal')?'aggressive':g.includes('edm')?'modern':g.includes('ballad')?'emotional':g.includes('cinematic')||g.includes('anime')?'cinematic':'authentic';stage=g.includes('edm')||g.includes('metal')?4:g.includes('cinematic')||g.includes('anime')?3:2;$('ieStageSlider').value=stage;render();$('ieStatus').textContent=`Smart direction applied for ${g}.`}
function analysis(){const x=current(),fit=PROFILE[instrument][1].includes(genre()),warn=[];let score=fit?82:64;if(x.presence>85&&x.priority.includes('Subtle'))warn.push('High presence conflicts with a subtle layer priority.');if(x.human<35&&x.prod.includes('Natural'))warn.push('Low human feel conflicts with natural production.');if(x.width>85&&x.prod.includes('Dry'))warn.push('Very wide stereo conflicts with dry close-mic production.');if(layers.length>5)warn.push('Too many layers may overload the arrangement.');score=clamp(score-warn.length*9+Math.min(8,layers.length*2));$('ieScore').textContent=score;$('ieScoreBar').style.width=score+'%';$('ieWarnings').innerHTML=(warn.length?warn:['No major instrument conflicts detected.']).map(v=>`<div class="ie-msg ${warn.length?'warn':'good'}">${v}</div>`).join('');const rec=[];if(!layers.length)rec.push('Add one supporting layer for harmony, rhythm or texture.');if(x.place==='Throughout the Song'&&x.presence>80)rec.push('Limit a high-presence instrument to key sections.');if(!rec.length)rec.push('The instrument plan is focused and practical.');$('ieRecommendations').innerHTML=rec.map(v=>`<div class="ie-msg info">${v}</div>`).join('');$('ieMetrics').innerHTML=[['Instrument',instrument],['Stage',typeof stage==='number'?stage+1:'Layer'],['Layers',layers.length],['Genre Fit',fit?'Strong':'Experimental'],['Goal',$('ieGoal').value],['Score',score]].map(v=>`<div class="ie-metric"><small>${v[0]}</small><b>${v[1]}</b></div>`).join('')}
function dna(){const x=current();return uniq([instrument,x.name,x.role,x.art,x.reg,x.mov,x.dyn,x.prod,x.place,x.priority,`${x.presence}% presence`,`${x.human}% human feel`,...layers.map(y=>`${y.name}: ${y.role}, ${y.art}, ${y.prod}, ${y.place}`)]).join(', ')}
function placementSection(place){return{'Throughout the Song':'Instrumental','Intro Only':'Intro','Verses':'Verse','Pre-Chorus Build':'Pre-Chorus'}[place]||place}
function stackDirectives(x){return[`${instrument} ${x.role}, ${x.art}`,x.dyn,x.prod]}
function tags(){const engine=window.NSWMetaTagStackEngine;return[current(),...layers].reduce((out,x)=>{const line=engine?engine.createStack(placementSection(x.place),stackDirectives(x)).line:`[${placementSection(x.place)} | ${stackDirectives(x).join(' | ')}]`;return engine?engine.mergeStackDocument(out,line,{repeatLast:true}).text:[out,line].filter(Boolean).join('\n')},'')}
function applyLyrics(){
 const editor=$('lyricsEditor'),engine=window.NSWMetaTagStackEngine;if(!editor)return;
 if(!engine){editor.value=(editor.value.trim()?editor.value.trim()+'\n\n':'')+tags();editor.dispatchEvent(new Event('input',{bubbles:true}));return}
 let text=engine.migrateLyrics(editor.value).text;
 [current(),...layers].forEach(x=>{
  const parsed=engine.parseLyrics(text),place=x.place;
  let targets=parsed.sections;
  if(place!=='Throughout the Song'){
   const mapped=placementSection(place).toLowerCase();
   targets=parsed.sections.filter(section=>place==='Verses'?/\bverse\b/i.test(section.stack.section):section.stack.section.toLowerCase()===mapped);
  }
  if(!targets.length){text=engine.mergeSection(text,placementSection(place),stackDirectives(x)).text;return}
  const occurrences=new Map();
  targets.forEach(target=>{const key=target.stack.section.toLowerCase(),occurrence=occurrences.get(key)||0;occurrences.set(key,occurrence+1);text=engine.mergeSection(text,target.stack.section,stackDirectives(x),{occurrence}).text});
 });
 editor.value=text;editor.dispatchEvent(new Event('input',{bubbles:true}));
}
function table(){$('ieTableBody').innerHTML=[...STAGES.map((_,i)=>item(i)),...layers].map((x,i)=>`<tr><td>${x.name}</td><td>${x.role}</td><td>${x.art}</td><td>${x.reg}</td><td>${x.mov}</td><td>${x.dyn}</td><td>${x.prod}</td><td>${x.place}</td></tr>`).join('')}
function expose(){window.NSW_INSTRUMENT_EVOLUTION_LAST={family,instrument,goal:$('ieGoal').value,genre:genre(),stage,layers:JSON.parse(JSON.stringify(layers)),dna:dna(),sectionTags:tags(),updatedAt:Date.now()}}
function render(){renderSelectors();timeline();rolemap();inspector();lab();table();analysis();$('ieDNA').value=dna();$('iePathBadge').textContent=`${instrument} · ${$('ieGoal').value}`;$('ieBadge').textContent=`${instrument} · ${1+layers.length} roles · local direction`;expose()}
function plan(){return`INSTRUMENT EVOLUTION PLAN\nInstrument: ${instrument}\nGoal: ${$('ieGoal').value}\nGenre: ${genre()}\n\n${dna()}\n\nSECTION METATAGS\n${tags()}`}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch(e){}}function download(n,t,type='text/plain'){const b=new Blob([t],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click()}
function saveProject(){let pm;try{pm=JSON.parse(localStorage.getItem('nsw-project-manager-v4')||'null')}catch(e){}const p=pm?.projects?.find(x=>x.id===pm.activeProjectId)||pm?.projects?.[0],t=p?.tracks?.[0];if(!t)return $('ieStatus').textContent='No active project track.';t.instrumentEvolution=window.NSW_INSTRUMENT_EVOLUTION_LAST;t.updated=Date.now();p.updated=Date.now();localStorage.setItem('nsw-project-manager-v4',JSON.stringify(pm));$('ieStatus').textContent=`Saved to ${p.name} · ${t.title}.`}
function presetGrid(){$('iePresetCount').textContent=Object.keys(PRESETS).length+' presets';$('iePresetGrid').innerHTML=Object.keys(PRESETS).map(n=>`<button class="ie-preset" data-preset="${n}"><b>${n}</b><small>${PRESETS[n][1]} · ${PRESETS[n][2]}</small></button>`).join('');document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=PRESETS[b.dataset.preset];family=p[0];instrument=p[1];$('ieGoal').value=p[2];$('ieGenre').value=p[3];stage=p[4];layers=[];custom={};$('ieStageSlider').value=stage;render()})}
function init(){if(!$('ieGenerate'))return;presetGrid();render();$('ieFamily').onchange=e=>{family=e.target.value;instrument=FAMILIES[family][0];stage=0;layers=[];custom={};render()};$('ieInstrument').onchange=e=>{instrument=e.target.value;stage=0;layers=[];custom={};render()};$('ieGenerate').onclick=()=>{stage=0;layers=[];custom={};render()};$('ieSmart').onclick=smart;$('ieAddLayer').onclick=addLayer;$('ieReset').onclick=()=>{stage=0;layers=[];custom={};render()};$('ieStageSlider').oninput=e=>{stage=+e.target.value;render()};['Presence','Complexity','Human','Width'].forEach(k=>$('ie'+k).oninput=e=>$('ie'+k+'Value').textContent=e.target.value+'%');$('ieSaveStage').onclick=save;$('ieDuplicateStage').onclick=duplicate;$('ieRemoveLayer').onclick=remove;$('ieCopyDNA').onclick=()=>copy(dna());$('ieCopyPlan').onclick=()=>copy(plan());$('ieExportJson').onclick=()=>download('instrument-evolution.json',JSON.stringify(window.NSW_INSTRUMENT_EVOLUTION_LAST,null,2),'application/json');$('ieExportTxt').onclick=()=>download('instrument-evolution.txt',plan());$('ieApplyStyle').onclick=()=>{const e=$('customStyle');if(e){e.value=uniq([...String(e.value||'').split(',').map(x=>x.trim()),...dna().split(',').map(x=>x.trim())]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}};$('ieApplyLyrics').onclick=applyLyrics;$('ieSaveProject').onclick=saveProject}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
