
(function(){'use strict';const $=id=>document.getElementById(id),uniq=a=>[...new Set(a.map(x=>x.trim()).filter(Boolean))];let N=[],E=[],sel=0,lean=[];
const D={Tagelharpa:['Drone / Rhythm','Low-Mid',['folk','drone','bowed']],Taiko:['Percussion','Low',['percussion','cinematic','attack']],'Cinematic Strings':['Harmony','Wide',['strings','cinematic','harmony']],Choir:['Vocal Texture','Mid-High',['vocal','cinematic','harmony']],Piano:['Harmony / Lead','Wide',['keys','harmony','attack']],'Electric Guitar':['Rhythm / Lead','Mid',['guitar','rock','attack']],Synthesizer:['Texture / Lead','Wide',['electronic','texture','lead']],'Deep Bass':['Bass Foundation','Low',['bass','electronic','foundation']],'Acoustic Drums':['Percussion','Wide',['percussion','attack','groove']],Cello:['Low Harmony / Lead','Low-Mid',['strings','warm','lead']],Duduk:['Lead / Texture','Mid',['wind','lead','breathy']],Koto:['Lead / Rhythm','Mid-High',['plucked','lead','attack']],Shamisen:['Lead / Rhythm','Mid',['plucked','attack','folk']],'French Horn':['Harmony / Lead','Mid',['brass','cinematic','harmony']],'Brass Section':['Accent / Harmony','Mid-High',['brass','attack','harmony']],'Electronic Drums':['Percussion','Wide',['percussion','electronic','groove']]};
function meta(n){const x=D[n]||['Supporting Layer','Mid',['texture']];return{role:x[0],band:x[1],tags:x[2]}}function names(){const s=$('igrSource').value;if(s==='custom')return uniq($('igrCustom').value.split(','));if(s==='evolution'&&window.NSW_INSTRUMENT_EVOLUTION_LAST)return uniq([window.NSW_INSTRUMENT_EVOLUTION_LAST.instrument,...(window.NSW_INSTRUMENT_EVOLUTION_LAST.layers||[]).map(x=>x.name)]);if(s==='arrangement'&&window.NSW_ARRANGEMENT_DESIGNER_LAST)return uniq(window.NSW_ARRANGEMENT_DESIGNER_LAST.sections.flatMap(x=>x.instruments.split(',')));const st=$('styleOutput')?.value||$('customStyle')?.value||'';let f=Object.keys(D).filter(x=>st.toLowerCase().includes(x.toLowerCase()));if(window.NSW_AI_MUSIC_DIRECTOR_LAST)f.push(...(window.NSW_AI_MUSIC_DIRECTOR_LAST.decisions.find(x=>x.key==='instrument')?.value.split(',')||[]));return uniq(f.length?f:['Piano','Cinematic Strings','Acoustic Drums','Choir'])}
function score(a,b){const A=meta(a),B=meta(b);let s=55,shared=A.tags.filter(x=>B.tags.includes(x));s+=shared.length*8;if(A.role===B.role)s-=18;if(A.band===B.band)s-=12;if(A.tags.includes('percussion')&&B.tags.includes('percussion'))s-=22;if(A.tags.includes('bass')&&B.tags.includes('bass'))s-=28;if(A.tags.includes('lead')&&B.tags.includes('lead'))s-=12;if((A.tags.includes('harmony')&&B.tags.includes('lead'))||(B.tags.includes('harmony')&&A.tags.includes('lead')))s+=18;if((A.tags.includes('percussion')&&!B.tags.includes('percussion'))||(B.tags.includes('percussion')&&!A.tags.includes('percussion')))s+=8;return Math.max(0,Math.min(100,s))}
function build(){const a=names(),cx=450,cy=280,r=190;N=a.map((n,i)=>({id:i,name:n,meta:meta(n),x:cx+Math.cos(-Math.PI/2+i*2*Math.PI/a.length)*r,y:cy+Math.sin(-Math.PI/2+i*2*Math.PI/a.length)*r}));E=[];for(let i=0;i<N.length;i++)for(let j=i+1;j<N.length;j++){const s=score(N[i].name,N[j].name);E.push({a:i,b:j,score:s,type:s>=72?'support':s<45?'conflict':'neutral'})}sel=0;analyse();render();$('igrStatus').textContent=`Built ${N.length} nodes and ${E.length} relationships.`}
function analyse(){const avg=E.length?Math.round(E.reduce((a,b)=>a+b.score,0)/E.length):0;lean=[...N].sort((a,b)=>E.filter(e=>e.a===b.id||e.b===b.id).reduce((x,y)=>x+y.score,0)-E.filter(e=>e.a===a.id||e.b===a.id).reduce((x,y)=>x+y.score,0)).slice(0,Math.min(6,N.length)).map(x=>x.name);window.NSW_INSTRUMENT_GRAPH_LAST={nodes:N,edges:E,score:avg,leanPalette:lean,updatedAt:Date.now()}}
function render(){const f=$('igrFocus').value,edges=E.filter(e=>f==='all'||e.type===f||f==='masking'&&e.score<50);$('igrGraph').innerHTML=edges.map(e=>`<line class="igr-edge ${e.type}" x1="${N[e.a].x}" y1="${N[e.a].y}" x2="${N[e.b].x}" y2="${N[e.b].y}"></line>`).join('')+N.map(n=>`<g class="igr-node ${n.id===sel?'selected':''}" data-id="${n.id}" transform="translate(${n.x},${n.y})"><circle r="34"></circle><text text-anchor="middle" y="-2">${n.name.length>14?n.name.slice(0,13)+'…':n.name}</text><text text-anchor="middle" y="13" style="font-size:8px;fill:#8194a0">${n.meta.band}</text></g>`).join('');document.querySelectorAll('[data-id]').forEach(g=>g.onclick=()=>{sel=+g.dataset.id;render()});$('igrCount').textContent=`${N.length} instruments`;const x=N.find(n=>n.id===sel),rel=E.filter(e=>e.a===sel||e.b===sel).map(e=>({n:N[e.a===sel?e.b:e.a].name,s:e.score})).sort((a,b)=>b.s-a.s);$('igrInspector').innerHTML=x?`<div class="igr-card"><h3>${x.name}</h3><p>${x.meta.role}<br>${x.meta.band}<br>${x.meta.tags.join(', ')}</p></div><div class="igr-card"><h3>Strongest relationships</h3><p>${rel.slice(0,4).map(v=>`${v.n}: ${v.s}`).join('<br>')}</p></div>`:'';const c=E.filter(e=>e.type==='conflict');$('igrScore').innerHTML=`<div class="igr-big">${window.NSW_INSTRUMENT_GRAPH_LAST.score}</div><small>Average compatibility</small>`;$('igrWarnings').innerHTML=(c.length?c.map(e=>`${N[e.a].name} and ${N[e.b].name} may compete (${e.score}).`):['No strong pairwise conflicts.']).map(v=>`<div class="igr-warn ${c.length?'warn':'good'}">${v}</div>`).join('');$('igrBadge').textContent=`${N.length} nodes · ${c.length} conflicts`;matrix();$('igrReport').value=report()}
function matrix(){let h='<table class="igr-table"><tr><th>Instrument</th>'+N.map(n=>`<th>${n.name}</th>`).join('')+'</tr>';N.forEach((a,i)=>{h+=`<tr><th>${a.name}</th>`+N.map((b,j)=>i===j?'<td>—</td>':`<td class="${score(a.name,b.name)>=72?'pos':score(a.name,b.name)<45?'neg':''}">${score(a.name,b.name)}</td>`).join('')+'</tr>'});$('igrMatrix').innerHTML=h+'</table>'}
function report(){return['INSTRUMENT RELATIONSHIP REPORT',`Average compatibility: ${window.NSW_INSTRUMENT_GRAPH_LAST?.score||0}`,`Lean palette: ${lean.join(', ')}`,'',...E.map(e=>`${N[e.a].name} ↔ ${N[e.b].name}: ${e.score} ${e.type}`)].join('\n')}
function apply(){const e=$('customStyle');if(!e)return;const old=e.value.split(',').map(x=>x.trim()).filter(x=>!Object.keys(D).some(n=>x.toLowerCase().includes(n.toLowerCase())));e.value=[...old,...lean].join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}
function init(){if(!$('igrBuild'))return;$('igrBuild').onclick=build;$('igrFocus').onchange=render;$('igrLean').onclick=()=>{$('igrCustom').value=lean.join(', ');$('igrStatus').textContent='Lean palette placed in custom field.'};$('igrReset').onclick=build;$('igrApply').onclick=apply;$('igrCopy').onclick=()=>navigator.clipboard?.writeText(report());$('igrExport').onclick=()=>{const b=new Blob([JSON.stringify(window.NSW_INSTRUMENT_GRAPH_LAST,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='instrument-relationship-graph.json';a.click()};build()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
