
(function(){
'use strict';
const $=id=>document.getElementById(id),D=window.NSW_WORLD_MUSIC_DATA;let active='',selected=new Set(),list=[];
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function filtered(){const q=$('iexSearch').value.toLowerCase(),w=$('iexWorld').value,f=$('iexFamily').value,s=$('iexStatus').value;return D.instruments.filter(i=>(!q||JSON.stringify(i).toLowerCase().includes(q))&&(!w||i.world===w)&&(!f||i.family===f)&&(!s||i.status===s))}
function renderGrid(){list=filtered();$('iexCount').textContent=`${list.length} instruments`;$('iexGrid').innerHTML=list.map(i=>`<article class="iex-card ${i.name===active?'active':''}" data-name="${esc(i.name)}"><input class="iex-check" type="checkbox" data-check="${esc(i.name)}" ${selected.has(i.name)?'checked':''}><h3>${esc(i.name)}</h3><p>${esc(i.world)}<br>${esc(i.performance)}</p><footer><span>${esc(i.family)}</span><span class="iex-status-${i.status.toLowerCase()}">${i.status}</span></footer></article>`).join('');document.querySelectorAll('.iex-card').forEach(c=>c.onclick=e=>{if(e.target.matches('input'))return;active=c.dataset.name;renderDetail();renderGrid()});document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.check):selected.delete(c.dataset.check);renderCompare()})}
function item(){return D.instruments.find(x=>x.name===active)||list[0]||D.instruments[0]}
function renderDetail(){const i=item();active=i.name;$('iexDetail').innerHTML=`<div class="iex-detail-hero"><h2>${esc(i.name)}</h2><p>${esc(i.world)} · ${esc(i.family)} · ${esc(i.status)}</p></div><div class="iex-profile-grid">${[['Sound Character',i.character],['Performance',i.performance],['Frequency Range',i.range],['Suno Status',i.status]].map(x=>`<div class="iex-profile-item"><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('')}</div>${sec('Best Genres',i.genres)}${sec('Excellent Pairings',i.pairs)}${sec('Possible Conflicts',i.avoid)}<div class="iex-detail-section"><h3>Suggested STYLE Phrase</h3><div class="iex-chips"><span class="iex-chip">${esc(`${i.name}, ${i.performance}, ${i.character}, ${i.range} register`)}</span></div></div>`}
function sec(n,a){return`<div class="iex-detail-section"><h3>${n}</h3><div class="iex-chips">${a.map(x=>`<span class="iex-chip">${esc(x)}</span>`).join('')}</div></div>`}
function renderCompare(){const a=[...selected].map(n=>D.instruments.find(x=>x.name===n)).filter(Boolean);$('iexBadge').textContent=`${D.instruments.length} instruments · ${a.length} selected`;if(!a.length){$('iexCompare').innerHTML='<div class="feature-empty">Select instruments to compare and build a palette.</div>';$('iexOutput').value='';return}let h='<table class="iex-table"><tr><th>Instrument</th><th>World</th><th>Family</th><th>Range</th><th>Character</th><th>Status</th></tr>'+a.map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.world)}</td><td>${esc(i.family)}</td><td>${esc(i.range)}</td><td>${esc(i.character)}</td><td>${i.status}</td></tr>`).join('')+'</table>';const warnings=[];for(let x=0;x<a.length;x++)for(let y=x+1;y<a.length;y++){if(a[x].range===a[y].range&&a[x].family===a[y].family)warnings.push(`${a[x].name} and ${a[y].name} may overlap in ${a[x].range}.`);if(a[x].avoid.includes(a[y].name)||a[y].avoid.includes(a[x].name))warnings.push(`${a[x].name} and ${a[y].name} are marked as a possible conflict.`)}h+=(warnings.length?warnings:['The selected palette has no obvious high-risk overlap.']).map(x=>`<div class="iex-mask-warning ${warnings.length?'warn':'good'}">${esc(x)}</div>`).join('');$('iexCompare').innerHTML=h;const out=a.map(i=>`${i.name}, ${i.performance}, ${i.character}, ${i.range} register`).join(', ');$('iexOutput').value=out;window.NSW_INSTRUMENT_ENCYCLOPEDIA_LAST={instruments:a,palette:out,warnings,updatedAt:Date.now()}}
function apply(){const v=$('iexOutput').value,e=$('customStyle');if(!v||!e)return;e.value=window.NSWConnections?.mergeStyle([e.value,v])||[e.value,v].filter(Boolean).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}
function init(){if(!$('iexSearchBtn')||!D)return;const worlds=[...new Set(D.instruments.map(x=>x.world))].sort(),families=[...new Set(D.instruments.map(x=>x.family))].sort();$('iexWorld').innerHTML='<option value="">All worlds</option>'+worlds.map(x=>`<option>${x}</option>`).join('');$('iexFamily').innerHTML='<option value="">All families</option>'+families.map(x=>`<option>${x}</option>`).join('');['iexSearch','iexWorld','iexFamily','iexStatus'].forEach(id=>$(id).oninput=renderGrid);$('iexSearchBtn').onclick=renderGrid;$('iexCompareBtn').onclick=renderCompare;$('iexClearCompare').onclick=()=>{selected.clear();renderGrid();renderCompare()};$('iexRandom').onclick=()=>{const i=D.instruments[Math.floor(Math.random()*D.instruments.length)];active=i.name;$('iexSearch').value=i.name;renderGrid();renderDetail()};$('iexCopyPalette').onclick=()=>navigator.clipboard?.writeText($('iexOutput').value);$('iexApplyStyle').onclick=apply;$('iexSendEvolution').onclick=()=>{const a=[...selected];if(!a.length)return;window.NSW_INSTRUMENT_EVOLUTION_LAST={family:'Encyclopedia Palette',instrument:a[0],layers:a.slice(1).map((n,i)=>({id:'iex_'+i,name:n,role:'Supporting Layer'})),dna:$('iexOutput').value,updatedAt:Date.now()};window.NSWConnections?.navigate('instrumentEvolutionView')};$('iexSendGraph').onclick=()=>{const a=[...selected];if(!a.length)return;window.NSWConnections?.navigate('instrumentGraphView');setTimeout(()=>{if($('igrSource'))$('igrSource').value='custom';if($('igrCustom'))$('igrCustom').value=a.join(', ');$('igrBuild')?.click()},80)};active=D.instruments[0].name;renderGrid();renderDetail();renderCompare();$('iexStatusText').textContent=`${D.instruments.length} instruments loaded.`}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
