/* Nordlicht Soundworks Prompt Studio v2.1 – Knowledge Engine */
const KNOWLEDGE_ENGINE_VERSION="2.1.0";
const KNOWLEDGE_PROFILES=[
 {match:/electro swing|swing house|neo swing/i, label:"Electro Swing", production:"Hybrid Production",mix:"Wide Stereo Mix",dynamics:"Verse restrained, chorus explosive",drums:"Punchy Drums",vocals:"Layered Wide Vocals",master:"Warm Analog Master",rhythm:"Swing",tempo:"Upbeat",energy:"Explosive",harmony:"Rich Extended Chords",complexity:"Rich",melody:"Hook-Driven",shape:"Quiet Verse, Explosive Chorus",extras:["Analog Warmth","Punchy Transients","Clear Vocal Presence"]},
 {match:/metalcore|deathcore|modern metal/i,label:"Metalcore",production:"Studio Quality Production",mix:"Layered and Dense Mix",dynamics:"Abrupt contrast sections",drums:"Compressed Modern Drums",vocals:"Double-Tracked Lead Vocal",master:"Modern Streaming Master",rhythm:"Half-Time",tempo:"Fast",energy:"Extreme",harmony:"Power Chords",complexity:"Moderate",melody:"Hook-Driven",shape:"Controlled Contrast",extras:["Punchy Transients","Controlled Low End","Layered Vocals"]},
 {match:/viking|nordic|pagan folk/i,label:"Viking / Nordic",production:"Raw Organic Production",mix:"Dynamic Mix",dynamics:"Gradual Build-Up",drums:"Natural Live Drums",vocals:"Large Hall Vocal",master:"Natural Acoustic Master",rhythm:"Marching",tempo:"Mid-Tempo",energy:"Building",harmony:"Modal",complexity:"Moderate",melody:"Repeated Motif",shape:"Massive Crescendo",extras:["Natural Room Ambience","Analog Warmth"]},
 {match:/anime|j-pop|j-rock/i,label:"Anime / Japanese",production:"Modern Anime Production",mix:"Bright Modern Mix",dynamics:"Soft intro, huge finale",drums:"Compressed Modern Drums",vocals:"Layered Wide Vocals",master:"Modern Streaming Master",rhythm:"Driving",tempo:"Fast",energy:"Explosive",harmony:"Minor",complexity:"Rich",melody:"Ascending",shape:"Emotional Lift",extras:["Clear Vocal Presence","Wide Stereo Image","Dynamic Arrangement"]},
 {match:/edm|festival|house|trance|hardstyle/i,label:"Electronic / EDM",production:"Festival Production",mix:"Huge Low-End Mix",dynamics:"Drop-driven arrangement",drums:"Deep Electronic Drums",vocals:"Layered Wide Vocals",master:"Loud Club Master",rhythm:"Driving",tempo:"Upbeat",energy:"Explosive",harmony:"Minor",complexity:"Simple",melody:"Hook-Driven",shape:"Gradual Build",extras:["Deep Sub Weight","Punchy Transients","Wide Stereo Image"]},
 {match:/cinematic|trailer|orchestral|soundtrack/i,label:"Cinematic",production:"Cinematic Production",mix:"Dynamic Mix",dynamics:"Wide cinematic dynamics",drums:"Huge Room Drums",vocals:"Large Hall Vocal",master:"Dynamic Cinematic Master",rhythm:"Straight",tempo:"Mid-Tempo",energy:"Building",harmony:"Minor",complexity:"Rich",melody:"Ascending",shape:"Huge Finale",extras:["Natural Room Ambience","Wide Stereo Image","Dynamic Arrangement"]},
 {match:/lo-fi|ambient|chill/i,label:"Ambient / Lo-Fi",production:"Raw Organic Production",mix:"Dark and Moody Mix",dynamics:"Gradual Build-Up",drums:"Warm Vintage Drums",vocals:"Intimate Close-Mic Vocal",master:"Warm Analog Master",rhythm:"Relaxed",tempo:"Slow",energy:"Calm",harmony:"Rich Extended Chords",complexity:"Moderate",melody:"Repeated Motif",shape:"Controlled Contrast",extras:["Tape Saturation","Analog Warmth"]},
 {match:/.*/,label:"Universal",production:"Studio Quality Production",mix:"Dynamic Mix",dynamics:"Gradual Build-Up",drums:"Punchy Drums",vocals:"Clean Centered Vocal",master:"Modern Streaming Master",rhythm:"Straight",tempo:"Mid-Tempo",energy:"Balanced",harmony:"Minor",complexity:"Moderate",melody:"Hook-Driven",shape:"Gradual Build",extras:["Clear Vocal Presence","Controlled Low End"]}
];
function knowledgeContext(){return [document.getElementById("genreFamily")?.value,document.getElementById("subgenre")?.value,document.getElementById("secondGenre")?.value,document.getElementById("songType")?.value].filter(Boolean).join(" ")}
function currentKnowledgeProfile(){const ctx=knowledgeContext();return KNOWLEDGE_PROFILES.find(p=>p.match.test(ctx))||KNOWLEDGE_PROFILES.at(-1)}
function setKnowledgeSelect(id,value){const el=document.getElementById(id);if(!el)return false;const ok=[...el.options].some(o=>o.value===value);if(ok)el.value=value;return ok}
function productionKnowledgeSuggestion(){const p=currentKnowledgeProfile();return {profile:p.label,production:p.production,mix:p.mix,dynamics:p.dynamics,drumMix:p.drums,vocalProduction:p.vocals,mastering:p.master,extras:p.extras}}
function theoryKnowledgeSuggestion(){const p=currentKnowledgeProfile();return {profile:p.label,rhythmFeel:p.rhythm,tempoCharacterTheory:p.tempo,songEnergyProfile:p.energy,harmonyMode:p.harmony,harmonyComplexity:p.complexity,melodyMotion:p.melody,theoryDynamics:p.shape}}
function applyProductionKnowledge(){const s=productionKnowledgeSuggestion();["production","mix","dynamics","drumMix","vocalProduction","mastering"].forEach(k=>setKnowledgeSelect(k,s[k]));if(typeof appState!=="undefined")appState.productionExtras=[...new Set([...(appState.productionExtras||[]),...s.extras])];if(typeof renderDynamicLists==="function")renderDynamicLists();if(typeof generateOutput==="function")generateOutput()}
function applyTheoryKnowledge(){const s=theoryKnowledgeSuggestion();["rhythmFeel","tempoCharacterTheory","songEnergyProfile","harmonyMode","harmonyComplexity","melodyMotion","theoryDynamics"].forEach(k=>setKnowledgeSelect(k,s[k]));if(typeof generateOutput==="function")generateOutput()}
function compatibilityCards(){const p=currentKnowledgeProfile();const selected=typeof appState!=="undefined"?(appState.instruments||[]):[];const profile=typeof musicProfile==="function"?musicProfile(document.getElementById("genreFamily")?.value||"Pop",document.getElementById("subgenre")?.value||""):null;const good=selected.filter(x=>profile?.instruments?.includes(x)).slice(0,4);const unusual=selected.filter(x=>!profile?.instruments?.includes(x)).slice(0,4);return [{type:"good",title:"✓ Starke Basis",text:`${p.label}: ${p.rhythm}, ${p.harmony}, ${p.master}`},{type:good.length?"good":"warn",title:"✓ Passende Instrumente",text:good.length?good.join(", "):"Noch keine genretypischen Instrumente gewählt"},{type:unusual.length?"warn":"good",title:unusual.length?"⚠ Experimentelle Kombination":"✓ Keine Konflikte",text:unusual.length?unusual.join(", "):"Aktuelle Auswahl ist konsistent"}]}
function refreshKnowledgePanels(){const p=productionKnowledgeSuggestion(),t=theoryKnowledgeSuggestion();const ps=document.getElementById("productionSuggestionText");if(ps)ps.textContent=`${p.profile}: ${p.production} · ${p.drumMix} · ${p.mastering}`;const ts=document.getElementById("theorySuggestionText");if(ts)ts.textContent=`${t.profile}: ${t.rhythmFeel} · ${t.harmonyMode} · ${t.melodyMotion} · ${t.theoryDynamics}`;const cp=document.getElementById("compatibilityPanel");if(cp)cp.innerHTML=compatibilityCards().map(c=>`<div class="compatibility-card compatibility-${c.type}"><strong>${c.title}</strong><small>${c.text}</small></div>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("applyProductionSuggestions")?.addEventListener("click",applyProductionKnowledge);document.getElementById("applyTheorySuggestions")?.addEventListener("click",applyTheoryKnowledge);setTimeout(refreshKnowledgePanels,0)});
