
(function(){
'use strict';
const $=id=>document.getElementById(id),KEY='nsw-learning-feedback-v2',LEGACY='nsw-learning-feedback-v1',clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),low=s=>String(s||'').toLowerCase().trim();
const uniq=a=>{const s=new Set();return a.filter(x=>{const k=low(x);if(!k||s.has(k))return false;s.add(k);return true})};
const TERMS={
 genre:['rock','metal','metalcore','deathcore','pop','k-pop','j-pop','jazz','swing','electro swing','folk','viking','nordic','rap','hip-hop','trap','drill','phonk','edm','electronic','techno','house','trance','dubstep','drum & bass','dnb','synthwave','cinematic','orchestral','classical','country','reggae','ambient','lo-fi','ballad','blues','funk','soul','r&b','punk','hardstyle'],
 vocal:['vocal','voice','choir','rap vocal','spoken','narrator','growl','scream','whisper','falsetto','soprano','alto','tenor','baritone','duet','male lead','female lead','children choir','gang shouts'],
 instrument:['piano','guitar','bass','drum','strings','violin','cello','sax','trumpet','trombone','clarinet','flute','synth','orchestra','brass','tagelharpa','nyckelharpa','duduk','oud','shamisen','koto','taiko','harp','organ','accordion','banjo','mandolin','horn','percussion'],
 production:['production','mix','master','stereo','mono','reverb','delay','compression','sidechain','saturation','tape','vinyl','polished','studio quality','radio-ready','dynamic mix','wide mix','cinematic production','high fidelity','low end','transient'],
 structure:['intro','verse','pre-chorus','chorus','hook','bridge','drop','build','breakdown','outro','final chorus','instrumental','solo','coda'],
 mood:['dark','sad','emotional','happy','hopeful','heroic','aggressive','dreamy','romantic','melancholic','playful','mysterious','triumphant','intimate','epic','nostalgic','warm','cold','sacred','mythic'],
 theory:['major','minor','modal','chord','harmony','melody','arpeggio','syncop','swing feel','shuffle','half-time','double-time','groove','rhythm','crescendo','dynamic contrast','key change','bpm','time signature']
};
let data=load(),detected=[],editingId=null;
function load(){
 let d=[];try{d=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){}
 if(!d.length){try{const old=JSON.parse(localStorage.getItem(LEGACY)||'[]');d=old.map((x,i)=>({id:Date.now()+i,prompt:x.prompt||'',rating:+x.rating||3,accuracy:+x.rating||3,positive:x.positive||'Overall Style',negative:x.negative||'Nothing',vocalResult:'neutral',instrumentResult:'neutral',productionResult:'neutral',outcome:(+x.rating>=4?'keeper':+x.rating<=2?'reject':'retry'),notes:'Imported from Learning Engine 1.0',time:x.time||Date.now()}));if(d.length)save(d)}catch(e){}}return d
}
function save(next=data){data=next;localStorage.setItem(KEY,JSON.stringify(data))}
function tokens(text){return uniq(String(text||'').split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean)).slice(0,40)}
function classify(term){for(const[k,a]of Object.entries(TERMS))if(a.some(x=>low(term).includes(x)))return k;return'other'}
function analyzePrompt(text){detected=tokens(text).map(term=>({term,category:classify(term)}));$('learnDetectedCount').textContent=`${detected.length} detected items`;$('learnDetectedTags').innerHTML=detected.length?detected.map(x=>`<span class="learning2-chip">${x.term} · ${x.category}</span>`).join(''):'<span class="dna-empty">No prompt DNA detected.</span>';return detected}
function weight(entry){const recency=Math.max(.65,1-Math.max(0,Date.now()-entry.time)/(1000*60*60*24*365)*.25),quality=((entry.rating-3)*1.4+(entry.accuracy-3)*.6),outcome=entry.outcome==='keeper'?1.5:entry.outcome==='reject'?-1.4:entry.outcome==='idea'?.2:0;return(quality+outcome)*recency}
function model(){
 const termMap={},categoryMap={genre:0,vocal:0,instrument:0,production:0,structure:0,mood:0,theory:0,other:0},problemMap={},aspectGood={},aspectBad={};
 data.forEach(e=>{const w=weight(e),ts=tokens(e.prompt);ts.forEach(t=>{const k=low(t);if(!termMap[k])termMap[k]={term:t,score:0,count:0,pos:0,neg:0,category:classify(t)};termMap[k].score+=w;termMap[k].count++;if(w>0)termMap[k].pos++;if(w<0){termMap[k].neg++;problemMap[k]=(problemMap[k]||0)+Math.abs(w)}});Object.keys(categoryMap).forEach(c=>{if(ts.some(t=>classify(t)===c))categoryMap[c]+=w});if(e.positive)aspectGood[e.positive]=(aspectGood[e.positive]||0)+Math.max(0,w+1);if(e.negative&&e.negative!=='Nothing')aspectBad[e.negative]=(aspectBad[e.negative]||0)+Math.max(0,1-w);[['Vocals',e.vocalResult],['Instruments',e.instrumentResult],['Production',e.productionResult]].forEach(([a,v])=>{if(['excellent','good'].includes(v))aspectGood[a]=(aspectGood[a]||0)+(v==='excellent'?2:1);if(!['neutral','excellent','good'].includes(v))aspectBad[a]=(aspectBad[a]||0)+1.5})});
 const terms=Object.values(termMap),preferences=terms.filter(x=>x.score>1.5&&x.pos>=2).sort((a,b)=>b.score-a.score),problems=terms.filter(x=>x.score<-.8||x.neg>=2).sort((a,b)=>a.score-b.score),avg=data.length?data.reduce((a,b)=>a+b.rating,0)/data.length:0,accuracy=data.length?data.reduce((a,b)=>a+b.accuracy,0)/data.length:0,keep=data.length?data.filter(x=>x.outcome==='keeper').length/data.length*100:0;
 const confidence=clamp(Math.round(data.length*7+preferences.length*2-Math.max(0,3-data.length)*8),0,100),stability=clamp(Math.round(45+Math.min(35,preferences.filter(x=>x.count>=3).length*7)+Math.min(20,data.length*2)-problems.length),0,100);
 return{terms,preferences,problems,categoryMap,aspectGood,aspectBad,avg,accuracy,keep,confidence,stability}
}
function formatNum(n,d=1){return Number(n||0).toFixed(d)}
function tasteSummary(m){
 if(data.length<3)return'More ratings are needed before a stable taste profile can be generated.';
 const cats=Object.entries(m.categoryMap).sort((a,b)=>b[1]-a[1]),topCats=cats.filter(x=>x[1]>0).slice(0,2).map(x=>x[0]),prefs=m.preferences.slice(0,3).map(x=>x.term);
 let s=topCats.length?`Your strongest positive signals currently come from ${topCats.join(' and ')} choices.`:'Your preferences are still mixed.';
 if(prefs.length)s+=` Repeated favorites include ${prefs.join(', ')}.`;if(m.keep<35)s+=' The keep rate is still low, so future feedback should focus on what Suno actually changed.';return s
}
function progressMetrics(m){return[['Ratings',data.length],['Confidence',m.confidence+'%'],['Stable preferences',m.preferences.filter(x=>x.count>=3).length],['Problem patterns',m.problems.length]]}
function render(){
 const m=model();$('learnCount').textContent=`${data.length} ratings · Local only`;$('learnProfileConfidence').textContent=`Profile confidence ${m.confidence}%`;$('learnProfileScore').textContent=m.confidence;$('learnProfileBar').style.width=m.confidence+'%';$('learnTasteSummary').textContent=tasteSummary(m);
 $('learnTopPreferences').innerHTML=m.preferences.length?m.preferences.slice(0,8).map(x=>`<span class="learning2-chip">${x.term}</span>`).join(''):'<span class="dna-empty">No stable preferences yet.</span>';
 $('learnAvoidances').innerHTML=m.problems.length?m.problems.slice(0,8).map(x=>`<span class="learning2-chip negative">${x.term}</span>`).join(''):'<span class="dna-empty">No repeated problems yet.</span>';
 $('learnProgressMetrics').innerHTML=progressMetrics(m).map(([a,b])=>`<div class="learning2-metric"><small>${a}</small><b>${b}</b></div>`).join('');
 $('learnAverageRating').textContent=data.length?formatNum(m.avg):'--';$('learnKeepRate').textContent=data.length?Math.round(m.keep)+'%':'--';$('learnAccuracyScore').textContent=data.length?formatNum(m.accuracy):'--';$('learnStability').textContent=data.length?m.stability+'%':'--';
 const recent=data.slice(-5),older=data.slice(-10,-5),recentAvg=recent.length?recent.reduce((a,b)=>a+b.rating,0)/recent.length:0,olderAvg=older.length?older.reduce((a,b)=>a+b.rating,0)/older.length:recentAvg,delta=recentAvg-olderAvg;$('learnAverageTrend').textContent=data.length<6?'More ratings needed':delta>.2?'Recent results improving':delta<-.2?'Recent results declining':'Recent results stable';
 const max=Math.max(1,...Object.values(m.categoryMap).map(Math.abs));$('learnCategoryBars').innerHTML=Object.entries(m.categoryMap).filter(([k])=>k!=='other').map(([k,v])=>{const width=Math.abs(v)/max*50;return`<div class="learning2-bar-row"><span>${k}</span><div class="learning2-bar-track"><i class="${v>=0?'positive':'negative'}" style="width:${width}%"></i></div><b>${v>=0?'+':''}${formatNum(v)}</b></div>`}).join('');
 $('learnProfile').innerHTML=m.preferences.length?m.preferences.slice(0,12).map((x,i)=>`<div class="learning2-ranked-item"><b>${i+1}. ${x.term}</b><span>${formatNum(x.score)} · ${x.count}×</span></div>`).join(''):'<div class="feature-empty">No favorite DNA yet.</div>';
 $('learnProblemPatterns').innerHTML=m.problems.length?m.problems.slice(0,12).map((x,i)=>`<div class="learning2-ranked-item"><b>${i+1}. ${x.term}</b><span>${formatNum(x.score)} · ${x.neg} weak</span></div>`).join(''):'<div class="feature-empty">No repeated problem patterns.</div>';
 const rec=[];const topGood=Object.entries(m.aspectGood).sort((a,b)=>b[1]-a[1])[0],topBad=Object.entries(m.aspectBad).sort((a,b)=>b[1]-a[1])[0];if(topGood)rec.push(`Keep emphasizing ${topGood[0].toLowerCase()}; it is repeatedly linked to positive results.`);if(topBad)rec.push(`Review ${topBad[0].toLowerCase()} settings before generating; this is the most repeated weakness.`);if(m.preferences.length)rec.push(`Build new prompts around ${m.preferences.slice(0,3).map(x=>x.term).join(', ')}.`);if(m.problems.length)rec.push(`Use ${m.problems.slice(0,3).map(x=>x.term).join(', ')} carefully or exclude them.`);if(m.accuracy<3&&data.length>=3)rec.push('Prompt accuracy is low; shorten prompts and reduce competing instructions.');if(m.keep<40&&data.length>=5)rec.push('The keeper rate is low; change one major variable per retry to learn faster.');if(!rec.length)rec.push('Save several results before personalized recommendations become reliable.');$('learnRecommendations').innerHTML=rec.map(x=>`<li>${x}</li>`).join('');
 renderHistory();return m
}
function renderHistory(){
 const rating=$('learnHistoryRating')?.value||'all',outcome=$('learnHistoryOutcome')?.value||'all',q=low($('learnHistorySearch')?.value||'');const rows=data.filter(x=>(rating==='all'||String(x.rating)===rating)&&(outcome==='all'||x.outcome===outcome)&&(!q||low(x.prompt+' '+(x.notes||'')).includes(q))).slice().reverse();
 $('learnHistory').innerHTML=rows.length?rows.map(x=>`<article class="learning2-history-item"><div class="learning2-history-head"><h3>${'★'.repeat(x.rating)}${'☆'.repeat(5-x.rating)} · ${x.positive}</h3><small>${new Date(x.time).toLocaleString()}</small></div><p>${escapeHtml(x.prompt.slice(0,300))}</p>${x.notes?`<p><b>Notes:</b> ${escapeHtml(x.notes)}</p>`:''}<div class="learning2-history-meta"><span>Accuracy ${x.accuracy}/5</span><span>Weak: ${x.negative}</span><span>${x.outcome}</span><span>Vocals: ${x.vocalResult}</span><span>Instruments: ${x.instrumentResult}</span><span>Production: ${x.productionResult}</span></div><div class="learning2-history-actions"><button data-learn-edit="${x.id}">Edit</button><button data-learn-use="${x.id}">Use Prompt</button><button data-learn-delete="${x.id}">Delete</button></div></article>`).join(''):'<div class="feature-empty">No feedback matches the selected filters.</div>';
 document.querySelectorAll('[data-learn-delete]').forEach(b=>b.onclick=()=>{data=data.filter(x=>x.id!==Number(b.dataset.learnDelete));save();render()});document.querySelectorAll('[data-learn-use]').forEach(b=>b.onclick=()=>{const x=data.find(y=>y.id===Number(b.dataset.learnUse));if(x){$('learnPrompt').value=x.prompt;analyzePrompt(x.prompt)}});document.querySelectorAll('[data-learn-edit]').forEach(b=>b.onclick=()=>editEntry(Number(b.dataset.learnEdit)))
}
function editEntry(id){const x=data.find(y=>y.id===id);if(!x)return;editingId=id;$('learnPrompt').value=x.prompt;$('learnRating').value=x.rating;$('learnAccuracy').value=x.accuracy;$('learnPositive').value=x.positive;$('learnNegative').value=x.negative;$('learnVocalResult').value=x.vocalResult;$('learnInstrumentResult').value=x.instrumentResult;$('learnProductionResult').value=x.productionResult;$('learnOutcome').value=x.outcome;$('learnNotes').value=x.notes||'';analyzePrompt(x.prompt);$('learnSave').textContent='💾 UPDATE FEEDBACK';$('learnStatus').textContent='Editing an existing feedback entry.';window.scrollTo({top:0,behavior:'smooth'})}
function collect(){return{id:editingId||Date.now(),prompt:$('learnPrompt').value.trim(),rating:+$('learnRating').value,accuracy:+$('learnAccuracy').value,positive:$('learnPositive').value,negative:$('learnNegative').value,vocalResult:$('learnVocalResult').value,instrumentResult:$('learnInstrumentResult').value,productionResult:$('learnProductionResult').value,outcome:$('learnOutcome').value,notes:$('learnNotes').value.trim(),time:editingId?(data.find(x=>x.id===editingId)?.time||Date.now()):Date.now()}}
function saveFeedback(){const x=collect();if(!x.prompt){$('learnStatus').textContent='Add a STYLE prompt or result description first.';return}if(editingId){data=data.map(y=>y.id===editingId?x:y)}else data.push(x);save();editingId=null;$('learnSave').textContent='💾 SAVE FEEDBACK';$('learnStatus').textContent='Feedback saved locally.';render()}
function applyPreferences(){const m=model(),terms=m.preferences.slice(0,6).map(x=>x.term),e=$('customStyle');if(!e||!terms.length)return;e.value=uniq([...tokens(e.value),...terms]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Learned preferences applied.')}
function applyAvoid(){const m=model(),terms=m.problems.slice(0,6).map(x=>x.term),e=$('customExclude');if(!e||!terms.length)return;e.value=uniq([...tokens(e.value),...terms]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Learned exclusions applied.')}
function createPreset(){const m=model(),prefs=m.preferences.slice(0,8).map(x=>x.term),avoids=m.problems.slice(0,6).map(x=>x.term);if(!prefs.length){$('learnStatus').textContent='More positive feedback is needed for a personal preset.';return}const payload={name:`Personal Learning Profile ${new Date().toLocaleDateString()}`,style:prefs.join(', '),exclude:avoids.join(', '),source:'Learning Engine 2.0',created:Date.now()};localStorage.setItem('nsw-learning-personal-preset',JSON.stringify(payload));if(typeof showToast==='function')showToast('Personal preset created locally.');$('learnStatus').textContent='Personal preset saved locally and ready for future integration.'}
function exportData(){const payload={version:2,exportedAt:new Date().toISOString(),feedback:data};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='nordlicht-learning-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(file){const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result),incoming=Array.isArray(parsed)?parsed:parsed.feedback;if(!Array.isArray(incoming))throw new Error('Invalid file');const byId=new Map(data.map(x=>[x.id,x]));incoming.forEach(x=>{if(x&&x.prompt)byId.set(x.id||Date.now()+Math.random(),{...x,id:x.id||Date.now()+Math.random()})});data=[...byId.values()];save();render();$('learnStatus').textContent=`Imported ${incoming.length} feedback entries.`}catch(e){$('learnStatus').textContent='Could not import this learning-data file.'}};r.readAsText(file)}
function reset(){if(confirm('Delete all local Learning Engine data?')){data=[];save();editingId=null;render();$('learnStatus').textContent='All local learning data was deleted.'}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function init(){
 if(!$('learnSave'))return;$('learnSave').onclick=saveFeedback;$('learnCurrent').onclick=()=>{$('learnPrompt').value=$('styleOutput')?.value||'';analyzePrompt($('learnPrompt').value)};$('learnAnalyzePrompt').onclick=()=>analyzePrompt($('learnPrompt').value);$('learnPrompt').addEventListener('input',()=>{clearTimeout(window.__learnTimer);window.__learnTimer=setTimeout(()=>analyzePrompt($('learnPrompt').value),250)});$('learnReset').onclick=reset;$('learnApply').onclick=applyPreferences;$('learnApplyAvoid').onclick=applyAvoid;$('learnGeneratePreset').onclick=createPreset;$('learnExport').onclick=exportData;$('learnImport').onclick=()=>$('learnImportFile').click();$('learnImportFile').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};['learnHistoryRating','learnHistoryOutcome'].forEach(id=>$(id).onchange=renderHistory);$('learnHistorySearch').oninput=renderHistory;render();analyzePrompt('')
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
