(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const STORE = 'nswLyricsPhase4.v1';
  const SECTION_RE = /^\s*\[(Intro|Ambient Intro|Opening|Cold Open|Movement(?:\s+[IVX]+|\s+\d+)?|Verse(?:\s+\d+)?|Pre[- ]?Chorus|Chorus|Final Chorus|Post[- ]?Chorus|Hook|Final Hook|Refrain|Bridge|Break|Dialogue Break|Build(?:-?Up)?|Pre-Drop|Drop|Second Drop|Final Drop|Breakdown|Heavy Breakdown|Half-Time Breakdown|Dance Break|Rap Break|Ensemble Chorus|Instrumental(?: Break| Verse| Chorus| Build| Drop| Finale)?|Solo|Guitar Solo|Interlude|Climax|Finale|Coda|Outro|End|Fade Out)(?:\s*:[^\]]*)?\]\s*$/i;
  const I18N = {
    de:{composer_title:'Smart Structure Builder',composer_optional:'Optional · standardmäßig aus',mode_off:'Aus',mode_template:'Vorlage',mode_smart:'Smart generieren',genre_preset:'Genre-Preset',include_tags:'Passende MetaTags ergänzen',replace_existing:'Vorhandenen Text ersetzen',preview:'Vorschau',apply_structure:'Struktur anwenden',song_map:'Live Song Map',no_sections:'Noch keine Abschnitte',planner_title:'Vocal-, Instrument- & Energieplaner',reset_plan:'Plan zurücksetzen',apply_plan:'Plan als MetaTags einfügen',score_title:'Song Score 2.0',advisor_title:'Smart Advisor 2.0',section:'Abschnitt',vocal:'Stimme',instruments:'Instrumente',energy:'Energie',lyrics:'Lyrics',structure:'Struktur',vocals:'Stimmen',dynamics:'Dynamik',metatags:'MetaTags',genre_fit:'Genre-Fit',overall:'Gesamt',off_hint:'Der Builder ist aus und verändert nichts.',select_mode:'Wähle Vorlage oder Smart generieren.',applied:'Struktur wurde angewendet.',plan_applied:'Plan wurde als MetaTags eingefügt.',no_plan:'Noch kein Plan verfügbar.',clean:'Der Songaufbau wirkt ausgewogen.',add_chorus:'Ein klarer Refrain würde die Wiedererkennbarkeit erhöhen.',add_verse:'Mindestens eine Strophe verbessert die Erzählstruktur.',energy_flat:'Die Energiekurve ist sehr gleichmäßig. Mehr Kontrast könnte helfen.',too_many_tags:'Einige Abschnitte enthalten sehr viele MetaTags.',long_section:'Mindestens ein Abschnitt ist deutlich länger als die übrigen.',add_instrumental:'Eine Instrumentalpassage könnte dem Song mehr Luft geben.',vocal_variety:'Ein gezielter Vocal-Wechsel könnte das Finale verstärken.',saved:'Phase-4-Plan gespeichert.'},
    en:{composer_title:'Smart Structure Builder',composer_optional:'Optional · off by default',mode_off:'Off',mode_template:'Template',mode_smart:'Smart generate',genre_preset:'Genre preset',include_tags:'Add matching MetaTags',replace_existing:'Replace existing text',preview:'Preview',apply_structure:'Apply structure',song_map:'Live Song Map',no_sections:'No sections yet',planner_title:'Vocal, Instrument & Energy Planner',reset_plan:'Reset plan',apply_plan:'Insert plan as MetaTags',score_title:'Song Score 2.0',advisor_title:'Smart Advisor 2.0',section:'Section',vocal:'Vocal',instruments:'Instruments',energy:'Energy',lyrics:'Lyrics',structure:'Structure',vocals:'Vocals',dynamics:'Dynamics',metatags:'MetaTags',genre_fit:'Genre fit',overall:'Overall',off_hint:'The builder is off and changes nothing.',select_mode:'Select Template or Smart generate.',applied:'Structure applied.',plan_applied:'Plan inserted as MetaTags.',no_plan:'No plan available yet.',clean:'The song structure looks balanced.',add_chorus:'A clear chorus would improve recognition.',add_verse:'At least one verse improves the narrative structure.',energy_flat:'The energy curve is very even. More contrast may help.',too_many_tags:'Some sections contain many MetaTags.',long_section:'At least one section is much longer than the others.',add_instrumental:'An instrumental passage could give the song more room.',vocal_variety:'A deliberate vocal change could strengthen the finale.',saved:'Phase 4 plan saved.'},
  };
  Object.assign(I18N, {
    fr:{...I18N.en,composer_title:'Constructeur de structure intelligent',composer_optional:'Facultatif · désactivé par défaut',mode_off:'Désactivé',mode_template:'Modèle',mode_smart:'Génération intelligente',genre_preset:'Préréglage de genre',include_tags:'Ajouter les MetaTags adaptés',replace_existing:'Remplacer le texte existant',preview:'Aperçu',apply_structure:'Appliquer la structure',song_map:'Carte du morceau',no_sections:'Aucune section',planner_title:'Planificateur voix, instruments et énergie',reset_plan:'Réinitialiser le plan',apply_plan:'Insérer le plan comme MetaTags',score_title:'Score du morceau 2.0',advisor_title:'Conseiller intelligent 2.0',section:'Section',vocal:'Voix',instruments:'Instruments',energy:'Énergie',lyrics:'Paroles',structure:'Structure',vocals:'Voix',dynamics:'Dynamique',metatags:'MetaTags',genre_fit:'Adéquation au genre',overall:'Global'},
    es:{...I18N.en,composer_title:'Constructor inteligente de estructura',composer_optional:'Opcional · desactivado por defecto',mode_off:'Desactivado',mode_template:'Plantilla',mode_smart:'Generación inteligente',genre_preset:'Preajuste de género',include_tags:'Añadir MetaTags adecuados',replace_existing:'Reemplazar texto existente',preview:'Vista previa',apply_structure:'Aplicar estructura',song_map:'Mapa de la canción',no_sections:'Sin secciones',planner_title:'Planificador de voz, instrumentos y energía',reset_plan:'Restablecer plan',apply_plan:'Insertar plan como MetaTags',score_title:'Puntuación de canción 2.0',advisor_title:'Asesor inteligente 2.0',vocal:'Voz',energy:'Energía',lyrics:'Letra',structure:'Estructura',vocals:'Voces',dynamics:'Dinámica',genre_fit:'Ajuste de género',overall:'Total'},
    it:{...I18N.en,composer_title:'Costruttore intelligente della struttura',composer_optional:'Opzionale · disattivato per impostazione predefinita',mode_off:'Disattivato',mode_template:'Modello',mode_smart:'Generazione intelligente',genre_preset:'Preset di genere',include_tags:'Aggiungi MetaTag adatti',replace_existing:'Sostituisci testo esistente',preview:'Anteprima',apply_structure:'Applica struttura',song_map:'Mappa del brano',no_sections:'Nessuna sezione',planner_title:'Pianificatore voce, strumenti ed energia',reset_plan:'Reimposta piano',apply_plan:'Inserisci piano come MetaTag',score_title:'Punteggio brano 2.0',advisor_title:'Consulente intelligente 2.0',vocal:'Voce',energy:'Energia',lyrics:'Testo',structure:'Struttura',vocals:'Voci',dynamics:'Dinamica',genre_fit:'Coerenza col genere',overall:'Totale'},
    pt:{...I18N.en,composer_title:'Construtor inteligente de estrutura',composer_optional:'Opcional · desligado por padrão',mode_off:'Desligado',mode_template:'Modelo',mode_smart:'Gerar de forma inteligente',genre_preset:'Predefinição de género',include_tags:'Adicionar MetaTags adequadas',replace_existing:'Substituir texto existente',preview:'Pré-visualização',apply_structure:'Aplicar estrutura',song_map:'Mapa da música',no_sections:'Sem secções',planner_title:'Planeador de voz, instrumentos e energia',reset_plan:'Repor plano',apply_plan:'Inserir plano como MetaTags',score_title:'Pontuação da música 2.0',advisor_title:'Conselheiro inteligente 2.0',vocal:'Voz',energy:'Energia',lyrics:'Letra',structure:'Estrutura',vocals:'Vozes',dynamics:'Dinâmica',genre_fit:'Adequação ao género',overall:'Total'},
    'pt-BR':{...I18N.en,composer_title:'Construtor inteligente de estrutura',composer_optional:'Opcional · desligado por padrão',mode_off:'Desligado',mode_template:'Modelo',mode_smart:'Gerar de forma inteligente',genre_preset:'Predefinição de gênero',include_tags:'Adicionar MetaTags adequadas',replace_existing:'Substituir texto existente',preview:'Prévia',apply_structure:'Aplicar estrutura',song_map:'Mapa da música',no_sections:'Sem seções',planner_title:'Planejador de voz, instrumentos e energia',reset_plan:'Redefinir plano',apply_plan:'Inserir plano como MetaTags',score_title:'Pontuação da música 2.0',advisor_title:'Consultor inteligente 2.0',vocal:'Voz',energy:'Energia',lyrics:'Letra',structure:'Estrutura',vocals:'Vozes',dynamics:'Dinâmica',genre_fit:'Adequação ao gênero',overall:'Total'},
    nl:{...I18N.en,composer_title:'Slimme structuurbouwer',composer_optional:'Optioneel · standaard uit',mode_off:'Uit',mode_template:'Sjabloon',mode_smart:'Slim genereren',genre_preset:'Genrepreset',include_tags:'Passende MetaTags toevoegen',replace_existing:'Bestaande tekst vervangen',preview:'Voorbeeld',apply_structure:'Structuur toepassen',song_map:'Songkaart',no_sections:'Nog geen secties',planner_title:'Vocaal-, instrument- en energieplanner',reset_plan:'Plan resetten',apply_plan:'Plan als MetaTags invoegen',score_title:'Songscore 2.0',advisor_title:'Slimme adviseur 2.0',vocal:'Vocaal',energy:'Energie',lyrics:'Songtekst',structure:'Structuur',vocals:'Vocalen',dynamics:'Dynamiek',genre_fit:'Genrepassendheid',overall:'Totaal'},
    pl:{...I18N.en,composer_title:'Inteligentny kreator struktury',composer_optional:'Opcjonalny · domyślnie wyłączony',mode_off:'Wyłączony',mode_template:'Szablon',mode_smart:'Generuj inteligentnie',genre_preset:'Ustawienie gatunku',include_tags:'Dodaj pasujące MetaTagi',replace_existing:'Zastąp istniejący tekst',preview:'Podgląd',apply_structure:'Zastosuj strukturę',song_map:'Mapa utworu',no_sections:'Brak sekcji',planner_title:'Planer wokalu, instrumentów i energii',reset_plan:'Resetuj plan',apply_plan:'Wstaw plan jako MetaTagi',score_title:'Ocena utworu 2.0',advisor_title:'Inteligentny doradca 2.0',vocal:'Wokal',energy:'Energia',lyrics:'Tekst',structure:'Struktura',vocals:'Wokale',dynamics:'Dynamika',genre_fit:'Zgodność z gatunkiem',overall:'Łącznie'},
    tr:{...I18N.en,composer_title:'Akıllı yapı oluşturucu',composer_optional:'İsteğe bağlı · varsayılan olarak kapalı',mode_off:'Kapalı',mode_template:'Şablon',mode_smart:'Akıllı oluştur',genre_preset:'Tür ön ayarı',include_tags:'Uygun MetaTagleri ekle',replace_existing:'Mevcut metni değiştir',preview:'Önizleme',apply_structure:'Yapıyı uygula',song_map:'Şarkı haritası',no_sections:'Henüz bölüm yok',planner_title:'Vokal, enstrüman ve enerji planlayıcı',reset_plan:'Planı sıfırla',apply_plan:'Planı MetaTag olarak ekle',score_title:'Şarkı puanı 2.0',advisor_title:'Akıllı danışman 2.0',vocal:'Vokal',energy:'Enerji',lyrics:'Sözler',structure:'Yapı',vocals:'Vokaller',dynamics:'Dinamikler',genre_fit:'Tür uyumu',overall:'Genel'},
    ru:{...I18N.en,composer_title:'Умный конструктор структуры',composer_optional:'Необязательно · по умолчанию выключено',mode_off:'Выкл.',mode_template:'Шаблон',mode_smart:'Умная генерация',genre_preset:'Пресет жанра',include_tags:'Добавить подходящие MetaTags',replace_existing:'Заменить существующий текст',preview:'Предпросмотр',apply_structure:'Применить структуру',song_map:'Карта песни',no_sections:'Разделов пока нет',planner_title:'Планировщик вокала, инструментов и энергии',reset_plan:'Сбросить план',apply_plan:'Вставить план как MetaTags',score_title:'Оценка песни 2.0',advisor_title:'Умный советник 2.0',vocal:'Вокал',energy:'Энергия',lyrics:'Текст',structure:'Структура',vocals:'Вокал',dynamics:'Динамика',genre_fit:'Соответствие жанру',overall:'Итого'},
    ja:{...I18N.en,composer_title:'スマート構成ビルダー',composer_optional:'任意・初期設定ではオフ',mode_off:'オフ',mode_template:'テンプレート',mode_smart:'スマート生成',genre_preset:'ジャンルプリセット',include_tags:'適切なMetaTagを追加',replace_existing:'既存のテキストを置換',preview:'プレビュー',apply_structure:'構成を適用',song_map:'ソングマップ',no_sections:'セクションはまだありません',planner_title:'ボーカル・楽器・エネルギープランナー',reset_plan:'プランをリセット',apply_plan:'プランをMetaTagとして挿入',score_title:'ソングスコア 2.0',advisor_title:'スマートアドバイザー 2.0',vocal:'ボーカル',instruments:'楽器',energy:'エネルギー',lyrics:'歌詞',structure:'構成',vocals:'ボーカル',dynamics:'ダイナミクス',genre_fit:'ジャンル適合度',overall:'総合'},
    ko:{...I18N.en,composer_title:'스마트 구조 빌더',composer_optional:'선택 사항 · 기본값 꺼짐',mode_off:'꺼짐',mode_template:'템플릿',mode_smart:'스마트 생성',genre_preset:'장르 프리셋',include_tags:'알맞은 MetaTag 추가',replace_existing:'기존 텍스트 교체',preview:'미리보기',apply_structure:'구조 적용',song_map:'곡 지도',no_sections:'아직 섹션이 없습니다',planner_title:'보컬·악기·에너지 플래너',reset_plan:'계획 초기화',apply_plan:'계획을 MetaTag로 삽입',score_title:'곡 점수 2.0',advisor_title:'스마트 어드바이저 2.0',vocal:'보컬',instruments:'악기',energy:'에너지',lyrics:'가사',structure:'구조',vocals:'보컬',dynamics:'다이내믹',genre_fit:'장르 적합도',overall:'종합'},
    'zh-CN':{...I18N.en,composer_title:'智能歌曲结构生成器',composer_optional:'可选 · 默认关闭',mode_off:'关闭',mode_template:'模板',mode_smart:'智能生成',genre_preset:'曲风预设',include_tags:'添加匹配的MetaTag',replace_existing:'替换现有文本',preview:'预览',apply_structure:'应用结构',song_map:'歌曲结构图',no_sections:'暂无段落',planner_title:'人声、乐器与能量规划器',reset_plan:'重置规划',apply_plan:'将规划作为MetaTag插入',score_title:'歌曲评分 2.0',advisor_title:'智能建议 2.0',vocal:'人声',instruments:'乐器',energy:'能量',lyrics:'歌词',structure:'结构',vocals:'人声',dynamics:'动态',genre_fit:'曲风匹配',overall:'总分'}
  });
  const FALLBACKS={fr:'en',es:'en',it:'en',pt:'en','pt-BR':'en',nl:'en',pl:'en',tr:'en',ru:'en',ja:'en',ko:'en','zh-CN':'en'};
  const PRESETS={
    anime_opening:{name:'Anime Opening',bpm:148,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Instrumental Break','Verse 2','Bridge','Final Chorus','Outro'],tags:{Intro:['Cinematic Production','Gradual Build'],Chorus:['Powerful Vocal','Layered Arrangement'],Bridge:['Emotional Vocal','Rising Intensity'],'Final Chorus':['Massive Choir','Massive Climax']}},
    anime_ending:{name:'Anime Ending',bpm:102,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Bridge','Final Chorus','Outro'],tags:{Intro:['Piano Only','Soft and Intimate'],Bridge:['Emotional Lift'],Outro:['Fade Out']}},
    metal:{name:'Metal',bpm:160,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Breakdown','Verse 2','Chorus','Guitar Solo','Heavy Breakdown','Final Chorus','Outro'],tags:{Intro:['Heavy Low End'],Breakdown:['Half-Time Feel','Growled Vocal'],'Guitar Solo':['Technical Solo'],'Final Chorus':['Powerful Vocal','Peak Intensity']}},
    metalcore:{name:'Metalcore',bpm:170,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Breakdown','Verse 2','Chorus','Bridge','Heavy Breakdown','Final Chorus'],tags:{Verse:['Harsh Vocal'],Chorus:['Clean Vocal','Soaring Vocal'],Breakdown:['Half-Time Breakdown','Gang Shouts']}},
    viking:{name:'Viking / Folk',bpm:118,sections:['Intro','Verse 1','Chorus','Instrumental Break','Verse 2','Bridge','Final Chorus','Outro'],tags:{Intro:['Distant Choir','Gradual Instrument Entry'],Chorus:['Male Choir','Marching Rhythm'],'Instrumental Break':['Instrumental: Tagelharpa'],'Final Chorus':['Massive Choir','Triumphant']}},
    edm:{name:'EDM',bpm:128,sections:['Ambient Intro','Build-Up','Drop','Break','Verse 1','Build-Up','Second Drop','Bridge','Final Drop','Outro'],tags:{'Build-Up':['Riser','Rising Intensity'],Drop:['Four-on-the-Floor','Heavy Low End'],'Second Drop':['Layered Arrangement'],'Final Drop':['Peak Intensity']}},
    trance:{name:'Trance',bpm:138,sections:['Ambient Intro','Build-Up','Drop','Break','Build-Up','Second Drop','Climax','Outro'],tags:{'Ambient Intro':['Atmospheric Sound Design'],Break:['Ethereal Vocal'],Climax:['Massive Climax']}},
    dnb:{name:'Drum & Bass',bpm:174,sections:['Intro','Build-Up','Drop','Verse 1','Break','Second Drop','Bridge','Final Drop','Outro'],tags:{Drop:['Broken Beat','Heavy Groove'],Break:['Half-Time Feel'],'Final Drop':['Peak Intensity']}},
    kpop:{name:'K-Pop',bpm:122,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Rap Break','Verse 2','Pre-Chorus','Chorus','Dance Break','Bridge','Final Chorus','Outro'],tags:{'Rap Break':['Fast Rap'],'Dance Break':['Instrumental Drop'],'Final Chorus':['Layered Vocals','Choir Crescendo']}},
    jpop:{name:'J-Pop',bpm:142,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Instrumental Break','Verse 2','Pre-Chorus','Chorus','Bridge','Final Chorus','Outro'],tags:{Chorus:['Bright Vocal','Full Arrangement'],Bridge:['Emotional Lift']}},
    hiphop:{name:'Hip-Hop',bpm:92,sections:['Intro','Verse 1','Hook','Verse 2','Hook','Bridge','Final Hook','Outro'],tags:{Verse:['Rap Vocal'],Hook:['Layered Vocals'],Bridge:['Beat Switch']}},
    trap:{name:'Trap',bpm:140,sections:['Intro','Verse 1','Pre-Chorus','Hook','Verse 2','Hook','Break','Final Hook','Outro'],tags:{Verse:['Rap Vocal','Heavy Low End'],Hook:['Melodic Vocal'],Break:['Half-Time']}},
    synthwave:{name:'Synthwave',bpm:110,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Instrumental Break','Verse 2','Bridge','Final Chorus','Outro'],tags:{Intro:['Analog Production','Atmospheric Sound Design'],'Instrumental Break':['Synth Solo'],Outro:['Fade Out']}},
    cinematic:{name:'Cinematic / Game OST',bpm:88,sections:['Opening','Movement I','Build-Up','Climax','Interlude','Movement II','Finale','Coda'],tags:{Opening:['Sparse Arrangement'],Climax:['Orchestral Arrangement','Massive Climax'],Finale:['Full Arrangement','Epic Choir']}},
    pop:{name:'Pop',bpm:116,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Pre-Chorus','Chorus','Bridge','Final Chorus','Outro'],tags:{Chorus:['Catchy Melody','Layered Vocals'],Bridge:['Dynamic Contrast']}},
    ballad:{name:'Ballad',bpm:76,sections:['Intro','Verse 1','Chorus','Verse 2','Chorus','Bridge','Final Chorus','Outro'],tags:{Intro:['Piano Only','Soft and Intimate'],Bridge:['Slow Crescendo'],'Final Chorus':['Emotional Vocal','Full Arrangement']}},
    country:{name:'Country',bpm:104,sections:['Intro','Verse 1','Chorus','Verse 2','Chorus','Instrumental Break','Bridge','Final Chorus','Outro'],tags:{'Instrumental Break':['Acoustic Guitar Solo'],Chorus:['Harmony Vocals']}},
    schlager:{name:'Schlager',bpm:124,sections:['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Pre-Chorus','Chorus','Bridge','Final Chorus','Outro'],tags:{Chorus:['Bright Vocal','Full Arrangement'],'Final Chorus':['Key Change','Choir Crescendo']}},
    musical:{name:'Musical',bpm:112,sections:['Opening','Verse 1','Pre-Chorus','Chorus','Dialogue Break','Verse 2','Ensemble Chorus','Bridge','Finale'],tags:{Opening:['Narrated Vocal'],Chorus:['Operatic Vocal'],'Ensemble Chorus':['Mixed Choir'],Finale:['Massive Climax']}},
    phonk:{name:'Phonk',bpm:150,sections:['Intro','Build-Up','Drop','Verse 1','Break','Second Drop','Outro'],tags:{Drop:['Distorted Mix','Heavy Low End'],Break:['Telephone Effect'],'Second Drop':['Peak Intensity']}}
  };
  const VOCALS=['None','Female Vocal','Male Vocal','Deep Male Spoken','Whispered Vocal','Clean Vocal','Growled Vocal','Screamed Vocal','Male and Female Duet','Mixed Choir','Children\'s Choir','Call and Response'];
  const INSTRUMENTS=['Piano','Strings','Electric Guitar','Acoustic Guitar','Bass','Drums','Synth','Full Orchestra','Choir','Brass','Tagelharpa','Nyckelharpa','Shamisen','Taiko','Duduk'];
  let plan={}; let dragIndex=null;
  function lang(){const v=document.documentElement.lang||localStorage.getItem('language')||'en';return I18N[v]?v:(FALLBACKS[v]||'en')}
  function t(k){return (I18N[lang()]||I18N.en)[k]||I18N.en[k]||k}
  function toast(m){window.showToast?window.showToast(m):console.info(m)}
  function editor(){return $('lyricsEditor')}
  function sections(){return (editor()?.value||'').split('\n').map((l,i)=>({label:l.trim(),line:i+1,index:i})).filter(x=>SECTION_RE.test(x.label))}
  function sectionName(label){return label.replace(/^\[|\]$/g,'').split(':')[0].trim()}
  function preset(){return PRESETS[$('p4GenrePreset')?.value]||PRESETS.anime_opening}
  function selectedMode(){return document.querySelector('input[name="p4Mode"]:checked')?.value||'off'}
  function makeStructure(){
    const mode=selectedMode(); if(mode==='off') return '';
    const p=preset(), withTags=$('p4IncludeTags')?.checked;
    return p.sections.map((sec,i)=>{let out=`[${sec}]`; if(withTags){const candidates=[...(p.tags[sec]||p.tags[sec.replace(/\s+\d+$/,'')]||[])]; if(mode==='smart'&&i===0&&!candidates.length)candidates.push('Gradual Build'); out+=candidates.map(x=>`\n[${x}]`).join('')} return out+'\n';}).join('\n').trim();
  }
  function updatePreview(){const pre=$('p4StructurePreview'); if(!pre)return; const mode=selectedMode(); pre.textContent=mode==='off'?t('off_hint'):(makeStructure()||t('select_mode'));}
  function applyStructure(){const value=makeStructure(); if(!value)return toast(t('select_mode')); const ed=editor(); const replace=$('p4ReplaceLyrics')?.checked; ed.value=replace||!ed.value.trim()?value:`${ed.value.trim()}\n\n${value}`; ed.dispatchEvent(new Event('input',{bubbles:true})); const p=preset(); const bpm=$('bpm'); if(bpm){bpm.value=p.bpm;bpm.dispatchEvent(new Event('input',{bubbles:true}));} toast(t('applied')); setTimeout(refreshAll,20)}
  function initPresetSelect(){const sel=$('p4GenrePreset'); if(!sel)return; sel.innerHTML=Object.entries(PRESETS).map(([k,p])=>`<option value="${k}">${p.name} · ${p.bpm} BPM</option>`).join('');}
  function defaultsFor(sec,i,total){const n=sectionName(sec.label).toLowerCase(); let vocal='Female Vocal'; if(/instrumental|solo|drop|break/.test(n))vocal='None'; else if(/bridge/.test(n))vocal='Deep Male Spoken'; else if(/final|chorus|hook/.test(n))vocal='Mixed Choir'; let energy=/intro|opening/.test(n)?25:/verse/.test(n)?45:/pre|build/.test(n)?68:/chorus|hook|drop/.test(n)?84:/bridge|break/.test(n)?55:/final|climax/.test(n)?96:60; const instruments=/intro/.test(n)?['Piano','Strings']:/chorus|final/.test(n)?['Drums','Bass','Full Orchestra','Choir']:/drop/.test(n)?['Drums','Bass','Synth']:['Drums','Bass','Piano']; return {vocal,energy,instruments};}
  function syncPlan(){const ss=sections(); const next={}; ss.forEach((s,i)=>{const key=s.label+'@'+s.line; next[key]=plan[key]||defaultsFor(s,i,ss.length)});plan=next;save()}
  function renderPlanner(){const root=$('p4PlannerRows');if(!root)return;syncPlan();const ss=sections(); if(!ss.length){root.innerHTML=`<small>${t('no_plan')}</small>`;return} root.innerHTML=ss.map((s,i)=>{const key=s.label+'@'+s.line,p=plan[key];return `<div class="phase4-planner-row" data-key="${encodeURIComponent(key)}"><b>${escapeHtml(s.label)}</b><label><span>${t('vocal')}</span><select data-plan="vocal">${VOCALS.map(v=>`<option ${v===p.vocal?'selected':''}>${v}</option>`).join('')}</select></label><label><span>${t('instruments')}</span><select data-plan="instrument">${INSTRUMENTS.map(v=>`<option>${v}</option>`).join('')}</select><button type="button" data-add-instrument>＋</button></label><div class="phase4-instrument-chips">${p.instruments.map(v=>`<button type="button" data-remove-instrument="${escapeHtml(v)}">${escapeHtml(v)} ×</button>`).join('')}</div><label class="phase4-energy"><span>${t('energy')} <output>${p.energy}%</output></span><input data-plan="energy" type="range" min="0" max="100" value="${p.energy}"></label></div>`}).join('');
    root.querySelectorAll('.phase4-planner-row').forEach(row=>{const key=decodeURIComponent(row.dataset.key);row.querySelector('[data-plan="vocal"]').onchange=e=>{plan[key].vocal=e.target.value;save();renderScores()};row.querySelector('[data-plan="energy"]').oninput=e=>{plan[key].energy=+e.target.value;e.target.closest('label').querySelector('output').value=e.target.value+'%';save();renderScores()};row.querySelector('[data-add-instrument]').onclick=()=>{const v=row.querySelector('[data-plan="instrument"]').value;if(!plan[key].instruments.includes(v))plan[key].instruments.push(v);save();renderPlanner()};row.querySelectorAll('[data-remove-instrument]').forEach(b=>b.onclick=()=>{plan[key].instruments=plan[key].instruments.filter(v=>v!==b.dataset.removeInstrument);save();renderPlanner()})});
  }
  function applyPlan(){const ed=editor(),lines=ed.value.split('\n'),ss=sections(); if(!ss.length)return toast(t('no_plan')); for(let i=ss.length-1;i>=0;i--){const s=ss[i],key=s.label+'@'+s.line,p=plan[key]||defaultsFor(s,i,ss.length),tags=[];if(p.vocal&&p.vocal!=='None')tags.push(`[${p.vocal}]`);if(p.instruments.length)tags.push(`[Music: ${p.instruments.join(', ')}]`);tags.push(`[Energy: ${p.energy}%]`);lines.splice(s.index+1,0,...tags)} ed.value=lines.join('\n');ed.dispatchEvent(new Event('input',{bubbles:true}));toast(t('plan_applied'));setTimeout(refreshAll,20)}
  function renderMap(){const root=$('p4SongMap');if(!root)return;const ss=sections();if(!ss.length){root.innerHTML=`<small>${t('no_sections')}</small>`;return}root.innerHTML=ss.map((s,i)=>`<button draggable="true" data-map-index="${i}" title="Line ${s.line}"><span>${i+1}</span>${escapeHtml(sectionName(s.label))}</button>`).join('<i>›</i>');root.querySelectorAll('button').forEach(b=>{b.onclick=()=>{const ed=editor(),lines=ed.value.split('\n'),pos=lines.slice(0,ss[+b.dataset.mapIndex].index).join('\n').length+(ss[+b.dataset.mapIndex].index?1:0);ed.focus();ed.setSelectionRange(pos,pos)};b.ondragstart=()=>dragIndex=+b.dataset.mapIndex;b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();moveSection(dragIndex,+b.dataset.mapIndex)}})}
  function moveSection(from,to){if(from==null||from===to)return;const ed=editor(),lines=ed.value.split('\n'),ss=sections();const blocks=ss.map((s,i)=>lines.slice(s.index,ss[i+1]?.index??lines.length));const block=blocks.splice(from,1)[0];blocks.splice(to,0,block);const prefix=lines.slice(0,ss[0].index);ed.value=[...prefix,...blocks.flat()].join('\n');ed.dispatchEvent(new Event('input',{bubbles:true}));dragIndex=null;setTimeout(refreshAll,20)}
  function metrics(){const text=editor()?.value||'',ss=sections(),words=text.trim()?text.trim().split(/\s+/).length:0,tags=(text.match(/^\s*\[[^\]\n]+\]\s*$/gm)||[]).length;const hasVerse=ss.some(s=>/verse/i.test(s.label)),hasChorus=ss.some(s=>/chorus|hook|refrain/i.test(s.label));syncPlan();const energies=Object.values(plan).map(p=>p.energy),range=energies.length?Math.max(...energies)-Math.min(...energies):0,vocalSet=new Set(Object.values(plan).map(p=>p.vocal).filter(v=>v&&v!=='None'));const lyric=Math.min(100,Math.max(15,100-Math.abs(words-320)/4));const structure=Math.min(100,(ss.length?35:0)+(hasVerse?25:0)+(hasChorus?25:0)+(ss.length>=7?15:ss.length*2));const vocals=Math.min(100,30+vocalSet.size*18+(vocalSet.has('Mixed Choir')?10:0));const dynamics=Math.min(100,35+range*1.1);const meta=Math.min(100,25+Math.min(tags,25)*3);const genre=Math.min(100,50+(ss.length>=preset().sections.length-2?20:0)+(hasVerse&&hasChorus?30:0));const overall=Math.round((lyric+structure+vocals+dynamics+meta+genre)/6);return {lyrics:lyric,structure,vocals,dynamics,metatags:meta,genre_fit:genre,overall,words,tags,ss,range}}
  function renderScores(){const m=metrics(),root=$('p4ScoreGrid');if(!root)return;$('p4OverallScore').textContent=Math.round(m.overall);root.innerHTML=['lyrics','structure','vocals','dynamics','metatags','genre_fit'].map(k=>`<div><span>${t(k)}</span><b>${Math.round(m[k])}</b><i><em style="width:${Math.round(m[k])}%"></em></i></div>`).join('')}
  function renderAdvisor(){const m=metrics(),items=[];if(!m.ss.some(s=>/chorus|hook|refrain/i.test(s.label)))items.push(t('add_chorus'));if(!m.ss.some(s=>/verse/i.test(s.label)))items.push(t('add_verse'));if(m.range<25&&m.ss.length>2)items.push(t('energy_flat'));if(m.tags>m.ss.length*6&&m.ss.length)items.push(t('too_many_tags'));const details=getSectionWordCounts();if(details.some(x=>x.words>Math.max(100,(m.words/Math.max(1,m.ss.length))*1.8)))items.push(t('long_section'));if(!m.ss.some(s=>/instrumental|solo|break/i.test(s.label))&&m.ss.length>=6)items.push(t('add_instrumental'));if(new Set(Object.values(plan).map(p=>p.vocal)).size<2&&m.ss.length>=5)items.push(t('vocal_variety'));if(!items.length)items.push(t('clean'));$('p4AdvisorList').innerHTML=items.map((x,i)=>`<div class="${i?'tip':'lead'}"><span>${i?'→':'✓'}</span><small>${escapeHtml(x)}</small></div>`).join('')}
  function getSectionWordCounts(){const lines=(editor()?.value||'').split('\n'),ss=sections();return ss.map((s,i)=>({words:lines.slice(s.index+1,ss[i+1]?.index??lines.length).filter(l=>!/^\s*\[/.test(l)).join(' ').trim().split(/\s+/).filter(Boolean).length}))}
  function save(){localStorage.setItem(STORE,JSON.stringify({plan,preset:$('p4GenrePreset')?.value,mode:selectedMode(),include:$('p4IncludeTags')?.checked,replace:$('p4ReplaceLyrics')?.checked}))}
  function load(){try{const d=JSON.parse(localStorage.getItem(STORE)||'{}');plan=d.plan||{};if(d.preset&&PRESETS[d.preset])$('p4GenrePreset').value=d.preset;if(d.mode)document.querySelector(`input[name="p4Mode"][value="${d.mode}"]`)?.click();if(typeof d.include==='boolean')$('p4IncludeTags').checked=d.include;if(typeof d.replace==='boolean')$('p4ReplaceLyrics').checked=d.replace}catch{}}
  function localize(){document.querySelectorAll('[data-p4]').forEach(el=>el.textContent=t(el.dataset.p4));updatePreview();renderPlanner();renderMap();renderScores();renderAdvisor()}
  function refreshAll(){renderMap();renderPlanner();renderScores();renderAdvisor();updatePreview()}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function init(){if(!$('phase4Composer')||!editor())return;initPresetSelect();load();localize();document.querySelectorAll('input[name="p4Mode"]').forEach(r=>r.onchange=()=>{save();updatePreview()});$('p4GenrePreset').onchange=()=>{save();updatePreview();renderScores()};$('p4IncludeTags').onchange=()=>{save();updatePreview()};$('p4ReplaceLyrics').onchange=save;$('p4PreviewStructure').onclick=updatePreview;$('p4ApplyStructure').onclick=applyStructure;$('p4ApplyPlan').onclick=applyPlan;$('p4ResetPlan').onclick=()=>{plan={};save();renderPlanner();renderScores();renderAdvisor()};$('p4RefreshMap').onclick=refreshAll;$('p4RefreshAdvisor').onclick=renderAdvisor;editor().addEventListener('input',()=>setTimeout(refreshAll,30));window.addEventListener('languageChanged',localize);document.addEventListener('nsw-language-changed',localize);const obs=new MutationObserver(()=>localize());obs.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});}
  window.NSWLyricsPhase4={refresh:refreshAll,getModel:()=>({sections:sections(),plan,metrics:metrics(),preset:$('p4GenrePreset')?.value})};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
