
(function(){
'use strict';
const $=id=>document.getElementById(id),low=s=>String(s||'').toLowerCase().trim(),uniq=a=>[...new Set(a.filter(x=>x&&x!=='None'))],clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const ADV=['theoryIntelKeyCenter','theoryIntelScale','theoryIntelMeter','theoryIntelProgression','theoryIntelPattern','theoryIntelMelodicDevice'];
const DEVICES=['Pedal Tone','Ostinato','Call and Response','Countermelody','Layered Harmony','Key Change','Rhythmic Break','Tension and Release','Motif Development','Chromatic Passing Tones','Open Fifths','Suspended Chords'];
const PRESETS=[
 {id:'pop',name:'Modern Pop Hook',desc:'Accessible harmony and memorable lift',legacy:['Straight','Upbeat','Building','Major','Moderate','Ascending','Emotional Lift'],adv:['C Major','Major Scale','4/4 Time','I–V–vi–IV','Straight Eighth-Note Pulse','Ascending Motif'],devices:['Layered Harmony','Tension and Release']},
 {id:'dark',name:'Dark Cinematic',desc:'Minor tension and gradual scale',legacy:['Driving','Mid-Tempo','Building','Minor','Rich','Repeated Motif','Massive Crescendo'],adv:['D Minor','Harmonic Minor','4/4 Time','i–VI–III–VII','Half-Time Groove','Repeated Leitmotif'],devices:['Pedal Tone','Ostinato','Motif Development']},
 {id:'anime',name:'Anime Opening',desc:'Fast momentum and emotional chorus',legacy:['Driving','Fast','Explosive','Minor','Rich','Ascending','Emotional Lift'],adv:['E Minor','Natural Minor','4/4 Time','i–VI–III–VII','Double-Time Drive','Ascending Motif'],devices:['Countermelody','Layered Harmony','Key Change']},
 {id:'viking',name:'Nordic Modal',desc:'Ancient modal weight and repetition',legacy:['Marching','Mid-Tempo','Building','Modal','Moderate','Repeated Motif','Massive Crescendo'],adv:['D Minor','Dorian Mode','6/8 Time','Modal Drone','Half-Time Groove','Repeated Leitmotif'],devices:['Pedal Tone','Open Fifths','Ostinato']},
 {id:'jazz',name:'Jazz & Swing',desc:'Extended harmony and syncopation',legacy:['Swing','Upbeat','Grooving','Rich Extended Chords','Rich','Hook-Driven','Controlled Contrast'],adv:['C Major','Mixolydian Mode','4/4 Time','ii–V–I','Swing Shuffle','Call and Response Melody'],devices:['Chromatic Passing Tones','Call and Response','Countermelody']},
 {id:'metal',name:'Heavy Breakdown',desc:'Minor power and rhythmic contrast',legacy:['Half-Time','Fast','Extreme','Power Chords','Moderate','Repeated Motif','Controlled Contrast'],adv:['B Minor','Phrygian Mode','4/4 Time','i–VII–VI–VII','Half-Time Groove','Repeated Leitmotif'],devices:['Rhythmic Break','Open Fifths','Tension and Release']},
 {id:'ballad',name:'Emotional Ballad',desc:'Simple harmony and melodic space',legacy:['Straight','Slow','Emotional','Minor','Simple','Ascending','Gradual Build'],adv:['A Minor','Natural Minor','6/8 Time','vi–IV–I–V','Straight Eighth-Note Pulse','Stepwise Melody'],devices:['Layered Harmony','Tension and Release']},
 {id:'experimental',name:'Experimental Pulse',desc:'Odd meter and evolving tension',legacy:['Polyrhythmic','Variable','Unpredictable','Modal','Complex','Wide Leaps','Abrupt Contrast'],adv:['C Minor','Whole Tone Scale','7/8 Time','Pedal Tone Harmony','Polyrhythmic Pulse','Wide Interval Leaps'],devices:['Ostinato','Chromatic Passing Tones','Motif Development']}
];
const CONCEPTS=[
 {name:'Major Scale',category:'Scale',complexity:'basic',energy:'medium',description:'Bright, stable tonal center often used for accessible hooks.',genres:['Pop','Country','Rock','Folk'],effect:['Clear resolution','Positive character'],avoid:['Very dark unresolved mood'],alts:['Mixolydian Mode','Pentatonic Scale'],prompt:'Major Scale harmony'},
 {name:'Natural Minor',category:'Scale',complexity:'basic',energy:'medium',description:'Flexible minor color for emotional, dark or dramatic songs.',genres:['Pop','Rock','Metal','Anime','Cinematic'],effect:['Melancholy','Drama','Emotional tension'],avoid:['Bright celebratory tone'],alts:['Harmonic Minor','Dorian Mode'],prompt:'Natural Minor tonality'},
 {name:'Harmonic Minor',category:'Scale',complexity:'intermediate',energy:'high',description:'Minor scale with a strong dramatic leading tone.',genres:['Metal','Cinematic','Middle Eastern Fusion','Classical'],effect:['Exotic tension','Dramatic resolution'],avoid:['Relaxed lo-fi mood'],alts:['Natural Minor','Phrygian Mode'],prompt:'Harmonic Minor color'},
 {name:'Dorian Mode',category:'Mode',complexity:'intermediate',energy:'medium',description:'Minor mode with a brighter sixth, useful for Nordic and modal music.',genres:['Nordic Folk','Jazz','Rock','Cinematic'],effect:['Ancient strength','Hopeful minor color'],avoid:['Simple mainstream pop if not needed'],alts:['Natural Minor','Mixolydian Mode'],prompt:'Dorian modal harmony'},
 {name:'Phrygian Mode',category:'Mode',complexity:'intermediate',energy:'high',description:'Dark mode with a tense flattened second.',genres:['Metal','Flamenco','Cinematic','Experimental'],effect:['Threat','Darkness','Exotic tension'],avoid:['Gentle bright ballads'],alts:['Harmonic Minor','Natural Minor'],prompt:'Phrygian mode tension'},
 {name:'Mixolydian Mode',category:'Mode',complexity:'intermediate',energy:'medium',description:'Major mode with a bluesy flattened seventh.',genres:['Rock','Funk','Jazz','Folk'],effect:['Open groove','Roots character'],avoid:['Strict classical resolution'],alts:['Major Scale','Blues Scale'],prompt:'Mixolydian groove'},
 {name:'Pentatonic Scale',category:'Scale',complexity:'basic',energy:'medium',description:'Five-note scale that supports clear, singable melodies.',genres:['Pop','Rock','Folk','Country'],effect:['Memorable melody','Open phrasing'],avoid:['Highly chromatic writing'],alts:['Major Scale','Blues Scale'],prompt:'Pentatonic melodic phrasing'},
 {name:'Blues Scale',category:'Scale',complexity:'basic',energy:'medium',description:'Pentatonic base with a blue note for grit and expression.',genres:['Blues','Rock','Jazz','Hip-Hop'],effect:['Grit','Soulful tension'],avoid:['Pure classical tone'],alts:['Pentatonic Scale','Mixolydian Mode'],prompt:'Blues-scale melodic color'},
 {name:'I–V–vi–IV',category:'Chord Progression',complexity:'basic',energy:'medium',description:'Highly accessible pop progression with strong familiarity.',genres:['Pop','Rock','Country','Anime'],effect:['Immediate hook support','Clear emotional arc'],avoid:['Avoid overuse when originality is the priority'],alts:['vi–IV–I–V','I–vi–IV–V'],prompt:'I–V–vi–IV chord movement'},
 {name:'vi–IV–I–V',category:'Chord Progression',complexity:'basic',energy:'medium',description:'Emotional pop progression starting from the relative minor.',genres:['Pop','Ballad','Anime','Rock'],effect:['Emotional lift','Strong chorus support'],avoid:['Very dark unresolved music'],alts:['I–V–vi–IV','i–VI–III–VII'],prompt:'vi–IV–I–V emotional progression'},
 {name:'i–VI–III–VII',category:'Chord Progression',complexity:'basic',energy:'high',description:'Minor progression common in dramatic rock, metal and anime music.',genres:['Metal','Rock','Anime','Cinematic'],effect:['Heroic minor drive','Large chorus'],avoid:['Minimal ambient music'],alts:['i–VII–VI–VII','Natural Minor drone'],prompt:'i–VI–III–VII minor progression'},
 {name:'ii–V–I',category:'Chord Progression',complexity:'intermediate',energy:'medium',description:'Core jazz cadence that creates tension and release.',genres:['Jazz','Soul','City Pop','Bossa Nova'],effect:['Sophisticated resolution','Harmonic movement'],avoid:['Raw modal drone'],alts:['I–vi–IV–V'],prompt:'ii–V–I harmonic movement'},
 {name:'Modal Drone',category:'Harmony',complexity:'basic',energy:'medium',description:'Sustains a tonal center while melody and rhythm evolve above it.',genres:['Nordic Folk','Ambient','Cinematic','World'],effect:['Ancient atmosphere','Hypnotic focus'],avoid:['Rapid functional harmony'],alts:['Pedal Tone Harmony','Ostinato'],prompt:'Modal drone foundation'},
 {name:'4/4 Time',category:'Meter',complexity:'basic',energy:'medium',description:'The most flexible and widely understood meter.',genres:['Most genres'],effect:['Stable pulse','Accessible groove'],avoid:['Only avoid when an unusual meter is intentional'],alts:['6/8 Time','3/4 Time'],prompt:'4/4 time signature'},
 {name:'6/8 Time',category:'Meter',complexity:'basic',energy:'medium',description:'Compound meter with a flowing or marching two-beat feel.',genres:['Ballad','Folk','Cinematic','Metal'],effect:['Rolling motion','Epic sway'],avoid:['Straight club groove'],alts:['3/4 Time','12/8 Time'],prompt:'6/8 flowing rhythm'},
 {name:'7/8 Time',category:'Meter',complexity:'advanced',energy:'high',description:'Asymmetrical meter for progressive and experimental rhythm.',genres:['Progressive Rock','Math Rock','Experimental','Game OST'],effect:['Unease','Forward instability'],avoid:['Simple singalong pop'],alts:['5/4 Time','4/4 Time'],prompt:'7/8 asymmetric pulse'},
 {name:'Syncopated Groove',category:'Rhythm',complexity:'intermediate',energy:'high',description:'Places accents away from the strongest beats.',genres:['Funk','Hip-Hop','Jazz','Pop','Electronic'],effect:['Movement','Groove','Rhythmic surprise'],avoid:['Very rigid march'],alts:['Straight Eighth-Note Pulse','Swing Shuffle'],prompt:'Syncopated groove'},
 {name:'Half-Time Groove',category:'Rhythm',complexity:'basic',energy:'high',description:'Makes the pulse feel slower and heavier while BPM can remain high.',genres:['Metalcore','Trap','Rock','Dubstep'],effect:['Weight','Breakdown impact'],avoid:['Light dance swing'],alts:['Double-Time Drive','Straight pulse'],prompt:'Heavy half-time groove'},
 {name:'Double-Time Drive',category:'Rhythm',complexity:'basic',energy:'high',description:'Creates faster perceived motion over the same harmonic pace.',genres:['Punk','Metal','Anime','Drum & Bass'],effect:['Urgency','Forward momentum'],avoid:['Intimate slow ballad'],alts:['Half-Time Groove'],prompt:'Double-time rhythmic drive'},
 {name:'Swing Shuffle',category:'Rhythm',complexity:'basic',energy:'medium',description:'Uneven subdivision that creates a swinging pulse.',genres:['Jazz','Blues','Electro Swing','Rockabilly'],effect:['Bounce','Vintage groove'],avoid:['Rigid techno pulse'],alts:['Syncopated Groove','Straight pulse'],prompt:'Swing shuffle rhythm'},
 {name:'Ostinato',category:'Arrangement',complexity:'intermediate',energy:'medium',description:'Repeating musical figure that anchors the arrangement.',genres:['Cinematic','Electronic','Minimalism','Metal'],effect:['Hypnosis','Momentum','Unity'],avoid:['Too many competing motifs'],alts:['Repeated Leitmotif','Pedal Tone'],prompt:'Persistent rhythmic ostinato'},
 {name:'Countermelody',category:'Melody',complexity:'advanced',energy:'medium',description:'Secondary melody that complements the lead line.',genres:['Anime','Orchestral','Pop','Progressive Rock'],effect:['Depth','Emotional layering'],avoid:['Already overcrowded chorus'],alts:['Layered Harmony','Call and Response'],prompt:'Supporting countermelody'},
 {name:'Call and Response',category:'Melody',complexity:'basic',energy:'high',description:'Alternates musical or vocal phrases for interaction.',genres:['Gospel','Blues','Hip-Hop','Folk','Pop'],effect:['Participation','Conversation','Hook strength'],avoid:['Continuous solo monologue'],alts:['Countermelody'],prompt:'Call-and-response phrasing'},
 {name:'Key Change',category:'Harmony',complexity:'intermediate',energy:'high',description:'Shifts tonal center for contrast or final-chorus lift.',genres:['Pop','Anime','Musical Theatre','Gospel'],effect:['Final lift','Dramatic escalation'],avoid:['Very short songs or already complex harmony'],alts:['Dynamic crescendo','Harmony lift'],prompt:'Final chorus key change'},
 {name:'Tension and Release',category:'Dynamics',complexity:'basic',energy:'high',description:'Alternates restraint and resolution to shape emotional impact.',genres:['All genres'],effect:['Narrative movement','Stronger chorus'],avoid:['Constant maximum intensity'],alts:['Gradual Build','Controlled Contrast'],prompt:'Clear tension-and-release arc'},
 {name:'Motif Development',category:'Composition',complexity:'advanced',energy:'medium',description:'Transforms a recognizable motif across the song.',genres:['Cinematic','Classical','Progressive','Game OST'],effect:['Unity','Storytelling','Evolution'],avoid:['Unrelated section ideas'],alts:['Repeated Leitmotif','Ostinato'],prompt:'Developing recurring motif'}
];
let activePreset=null,selectedConcept=null,activeDevices=new Set();
function val(id){return $(id)?.value||'None'}function setSelect(id,value){const e=$(id);if(!e)return false;let o=[...e.options].find(x=>low(x.value)===low(value)||low(x.textContent)===low(value));if(!o)o=[...e.options].find(x=>low(x.textContent).includes(low(value))||low(value).includes(low(x.textContent)));if(o){e.value=o.value;e.dispatchEvent(new Event('change',{bubbles:true}));return true}return false}
function currentGenre(){return $('subgenre')?.value||$('genreFamily')?.value||$('mainGenre')?.value||''}
function chain(){return uniq([val('rhythmFeel'),val('tempoCharacterTheory'),val('songEnergyProfile'),val('harmonyMode'),val('harmonyComplexity'),val('melodyMotion'),val('theoryDynamics'),...ADV.map(val),...activeDevices])}
function conflicts(items){const j=low(items.join(' ')),out=[];if(j.includes('major scale')&&j.includes('natural minor'))out.push('Major and Natural Minor are both selected as the primary tonal system.');if(j.includes('4/4 time')&&j.includes('7/8 time'))out.push('Two different primary meters are selected.');if(j.includes('straight eighth')&&j.includes('swing shuffle'))out.push('Straight and swung subdivision conflict unless used in separate sections.');if(j.includes('simple')&&j.includes('complex'))out.push('Harmony complexity contains opposing instructions.');if(j.includes('slow')&&j.includes('double-time'))out.push('Slow tempo and double-time can work, but the intended perceived pulse should be clearer.');return out}
function genreFit(items){const g=low(currentGenre()),j=low(items.join(' '));if(!g)return 72;let s=72;if(/pop|anime|j-pop/.test(g)&&/4\/4|major|minor|i–v|vi–iv|ascending|layered harmony/.test(j))s+=16;if(/metal|rock/.test(g)&&/minor|phrygian|half-time|double-time|open fifth|power/.test(j))s+=16;if(/jazz|swing|soul/.test(g)&&/ii–v–i|swing|mixolydian|syncop|extended/.test(j))s+=18;if(/folk|viking|nordic/.test(g)&&/dorian|modal|6\/8|drone|open fifth/.test(j))s+=18;if(/cinematic|orchestral|soundtrack/.test(g)&&/motif|ostinato|crescendo|minor|pedal/.test(j))s+=17;if(/edm|house|techno/.test(g)&&/4\/4|four-on|syncop|ostinato|tension/.test(j))s+=14;if(/ambient|lo-fi/.test(g)&&/whole tone|stepwise|slow|modal|drone/.test(j))s+=12;return clamp(s)}
function completeness(){const groups=[[val('rhythmFeel')],[val('harmonyMode')],[val('melodyMotion')],[val('theoryDynamics')],ADV.map(val),[...activeDevices]],filled=groups.filter(g=>g.some(x=>x&&x!=='None')).length;return Math.round(filled/groups.length*100)}
function analyze(){const items=chain(),warn=conflicts(items),complete=completeness(),fit=genreFit(items),clarity=clamp(100-Math.max(0,items.length-13)*5-warn.length*13),score=Math.round(complete*.35+fit*.4+clarity*.25);$('theoryIntelScore').textContent=score;$('theoryIntelScoreBar').style.width=score+'%';$('theoryIntelCompatibility').textContent=`Compatibility ${fit}%`;$('theoryIntelSummary').textContent=items.length?`The plan combines ${items.slice(0,4).join(', ')}${items.length>4?' with additional musical detail':''}. ${currentGenre()?`It is evaluated against ${currentGenre()}.`:'Choose a genre for more precise guidance.'}`:'Choose theory settings to create a coherent musical plan.';$('theoryIntelMetrics').innerHTML=[['Completeness',complete+'%'],['Genre fit',fit+'%'],['Clarity',clarity+'%'],['Elements',items.length]].map(([a,b])=>`<div class="theory-intelligence-metric"><small>${a}</small><b>${b}</b></div>`).join('');$('theoryIntelWarnings').innerHTML=warn.length?warn.map(x=>`<div class="theory-intelligence-message warn">${x}</div>`).join(''):'<div class="theory-intelligence-message good">No direct theory conflicts detected.</div>';const rec=[];if(val('theoryIntelScale')==='None')rec.push('Choose one tonal color or mode.');if(val('theoryIntelMeter')==='None')rec.push('A meter clarifies the rhythmic foundation.');if(val('theoryIntelProgression')==='None')rec.push('Add a progression only when harmonic direction matters.');if(val('theoryIntelPattern')==='None')rec.push('Choose one main rhythmic feel instead of several competing patterns.');if(items.length>14)rec.push('The theory prompt is dense; remove secondary details for clearer Suno interpretation.');if(fit<65)rec.push('Several choices are unusual for the current genre.');$('theoryIntelRecommendations').innerHTML=(rec.length?rec:['The theory plan is focused and coherent.']).map(x=>`<div class="theory-intelligence-message ${rec.length?'info':'good'}">${x}</div>`).join('');$('theoryIntelDNA').value=items.join(', ');return{items,score,fit,complete,clarity,warn}}
function renderPresets(){$('theoryIntelPresetGrid').innerHTML=PRESETS.map(p=>`<button class="theory-preset-card ${activePreset===p.id?'active':''}" data-theory-preset="${p.id}"><b>${p.name}</b><small>${p.desc}</small></button>`).join('');document.querySelectorAll('[data-theory-preset]').forEach(b=>b.onclick=()=>applyPreset(PRESETS.find(p=>p.id===b.dataset.theoryPreset)))}
function applyPreset(p){if(!p)return;activePreset=p.id;['rhythmFeel','tempoCharacterTheory','songEnergyProfile','harmonyMode','harmonyComplexity','melodyMotion','theoryDynamics'].forEach((id,i)=>setSelect(id,p.legacy[i]));ADV.forEach((id,i)=>{$(id).value=p.adv[i]||'None'});activeDevices=new Set(p.devices||[]);renderDevices();renderPresets();analyze();if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast(`${p.name} theory applied.`)}
function resetTheory(){['rhythmFeel','tempoCharacterTheory','songEnergyProfile','harmonyMode','harmonyComplexity','melodyMotion','theoryDynamics'].forEach(id=>setSelect(id,'None'));ADV.forEach(id=>$(id).value='None');activeDevices.clear();activePreset=null;renderDevices();renderPresets();analyze();if(typeof generateOutput==='function')generateOutput()}
function renderDevices(){$('theoryIntelDevices').innerHTML=DEVICES.map(x=>`<button class="theory-device ${activeDevices.has(x)?'active':''}" data-device="${x}">${x}</button>`).join('');document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{activeDevices.has(b.dataset.device)?activeDevices.delete(b.dataset.device):activeDevices.add(b.dataset.device);activePreset=null;renderDevices();renderPresets();analyze()})}
function smartPreset(){const g=low(currentGenre());let id=/anime|j-pop/.test(g)?'anime':/metal|hard rock|deathcore|metalcore/.test(g)?'metal':/jazz|swing|soul/.test(g)?'jazz':/viking|nordic|folk/.test(g)?'viking':/cinematic|soundtrack|orchestral/.test(g)?'dark':/ballad|acoustic/.test(g)?'ballad':/experimental|math|progressive/.test(g)?'experimental':'pop';applyPreset(PRESETS.find(x=>x.id===id))}
function applyDNA(){const e=$('customStyle'),dna=$('theoryIntelDNA').value.trim();if(!e||!dna)return;e.value=uniq([...e.value.split(',').map(x=>x.trim()),...dna.split(',').map(x=>x.trim())]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if($('includeTheory'))$('includeTheory').checked=true;if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Music Theory DNA added to STYLE.')}
async function copyDNA(){try{await navigator.clipboard.writeText($('theoryIntelDNA').value)}catch(e){$('theoryIntelDNA').select();document.execCommand('copy')}if(typeof showToast==='function')showToast('Music Theory DNA copied.')}
function catOptions(){uniq(CONCEPTS.map(x=>x.category)).sort().forEach(x=>$('theoryIntelLibraryCategory').add(new Option(x,x)))}
function pass(c){const cat=$('theoryIntelLibraryCategory').value,comp=$('theoryIntelLibraryComplexity').value,en=$('theoryIntelLibraryEnergy').value,q=low($('theoryIntelLibrarySearch').value);if(cat!=='all'&&c.category!==cat)return false;if(comp!=='all'&&c.complexity!==comp)return false;if(en!=='all'&&c.energy!==en)return false;if(q&&!low([c.name,c.description,c.category,...c.genres,...c.effect,...c.avoid].join(' ')).includes(q))return false;return true}
function renderLibrary(){const arr=CONCEPTS.filter(pass);$('theoryIntelLibraryCount').textContent=`${arr.length} concepts`;$('theoryIntelBadge').textContent=`${CONCEPTS.length} concepts · ${PRESETS.length} presets · local knowledge`;$('theoryIntelLibraryGrid').innerHTML=arr.map(c=>`<article class="theory-library-card ${selectedConcept?.name===c.name?'active':''}" data-concept="${encodeURIComponent(c.name)}"><h3>${c.name}</h3><small>${c.category}</small><div class="theory-library-badges"><span class="theory-library-badge ${c.complexity}">${c.complexity}</span><span class="theory-library-badge">${c.energy}</span></div><p>${c.description}</p><div class="theory-library-chips">${c.genres.slice(0,3).map(x=>`<span>${x}</span>`).join('')}</div></article>`).join('');$('theoryIntelLibraryEmpty').hidden=arr.length>0;document.querySelectorAll('[data-concept]').forEach(e=>e.onclick=()=>{selectedConcept=CONCEPTS.find(x=>x.name===decodeURIComponent(e.dataset.concept));renderLibrary();renderConcept()})}
function chips(a){return`<div class="theory-library-chips">${a.map(x=>`<span>${x}</span>`).join('')}</div>`}
function renderConcept(){if(!selectedConcept)return;const c=selectedConcept;$('theoryIntelLibraryInspector').innerHTML=`<div class="theory-library-detail"><h2>${c.name}</h2><div class="theory-library-badges"><span class="theory-library-badge ${c.complexity}">${c.complexity}</span><span class="theory-library-badge">${c.category}</span><span class="theory-library-badge">${c.energy} energy</span></div><p>${c.description}</p><div class="theory-library-section"><h4>Typical genres</h4>${chips(c.genres)}</div><div class="theory-library-section"><h4>Musical effect</h4>${chips(c.effect)}</div><div class="theory-library-section"><h4>Use carefully with</h4>${chips(c.avoid)}</div><div class="theory-library-section"><h4>Alternatives</h4>${chips(c.alts)}</div><div class="theory-library-section"><h4>Suno-friendly phrase</h4><p>${c.prompt}</p></div><div class="theory-library-detail-actions"><button id="theoryIntelCopyConcept">Copy phrase</button><button id="theoryIntelAddConcept">Add to DNA</button><button class="primary" id="theoryIntelAddStyle">Add to STYLE</button></div></div>`;$('theoryIntelCopyConcept').onclick=async()=>{try{await navigator.clipboard.writeText(c.prompt)}catch(e){}if(typeof showToast==='function')showToast('Theory phrase copied.')};$('theoryIntelAddConcept').onclick=()=>addConcept(c.prompt,false);$('theoryIntelAddStyle').onclick=()=>addConcept(c.prompt,true)}
function addConcept(text,toStyle){if(toStyle){const e=$('customStyle');e.value=uniq([...e.value.split(',').map(x=>x.trim()),text]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}else{activeDevices.add(text);renderDevices();analyze()}if(typeof showToast==='function')showToast('Theory concept added.')}
function init(){if(!$('theoryIntelPresetGrid'))return;renderPresets();renderDevices();catOptions();renderLibrary();['rhythmFeel','tempoCharacterTheory','songEnergyProfile','harmonyMode','harmonyComplexity','melodyMotion','theoryDynamics',...ADV].forEach(id=>{if($(id))$(id).addEventListener('change',()=>{activePreset=null;renderPresets();analyze()})});['theoryIntelLibraryCategory','theoryIntelLibraryComplexity','theoryIntelLibraryEnergy'].forEach(id=>$(id).onchange=renderLibrary);$('theoryIntelLibrarySearch').oninput=renderLibrary;$('theoryIntelResetPreset').onclick=resetTheory;$('theoryIntelSmartDevices').onclick=smartPreset;$('theoryIntelCopyDNA').onclick=copyDNA;$('theoryIntelApplyDNA').onclick=applyDNA;const old=$('applyTheorySuggestions');if(old)old.addEventListener('click',()=>setTimeout(analyze,20));analyze()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
