
(function(){
'use strict';
const $=id=>document.getElementById(id),low=s=>String(s||'').toLowerCase().trim(),uniq=a=>[...new Set(a.filter(x=>x&&x!=='None'))],clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const EXTRA_IDS=['productionIntelLowEnd','productionIntelStereo','productionIntelSpace','productionIntelTexture','productionIntelTransients','productionIntelVocalPlacement'];
const PRESETS=[
 {id:'modern',name:'Modern & Polished',desc:'Clear, controlled and radio-ready',production:'Studio Quality Production',mix:'Clean and Polished Mix',dynamics:'Verse restrained, chorus explosive',drums:'Compressed Modern Drums',vocals:'Double-Tracked Lead Vocal',master:'Modern Streaming Master',extras:['Controlled Low End','Wide Stereo Image','Natural Room Ambience','Clean Digital Texture','Punchy Transients','Forward Lead Vocal']},
 {id:'cinematic',name:'Cinematic & Epic',desc:'Wide dynamics, orchestra and scale',production:'Cinematic Production',mix:'Dynamic Mix',dynamics:'Wide cinematic dynamics',drums:'Huge Cinematic Drums',vocals:'Large Hall Vocal',master:'Cinematic Dynamic Master',extras:['Deep Sub Weight','Expansive Cinematic Width','Large Hall Reverb','Analog Warmth','Natural Dynamic Transients','Large Hall Vocal']},
 {id:'festival',name:'Festival & EDM',desc:'Impact, width and controlled sub',production:'Festival Production',mix:'Huge Low-End Mix',dynamics:'Drop-driven arrangement',drums:'Punchy Electronic Drums',vocals:'Layered Wide Vocals',master:'Loud Festival Master',extras:['Huge Festival Sub','Wide Stereo Image','Long Atmospheric Reverb','Clean Digital Texture','Sharp Modern Attack','Wide Layered Vocal']},
 {id:'organic',name:'Organic & Natural',desc:'Live room, warmth and dynamics',production:'Raw Organic Production',mix:'Raw and Organic Mix',dynamics:'Gradual Build-Up',drums:'Natural Live Drums',vocals:'Intimate Close-Mic Vocal',master:'Natural Acoustic Master',extras:['Natural Acoustic Low End','Focused Center Image','Natural Room Ambience','Analog Warmth','Natural Dynamic Transients','Intimate Close-Mic Vocal']},
 {id:'vintage',name:'Vintage & Analog',desc:'Tape warmth and restrained width',production:'Hybrid Production',mix:'Warm Vintage Mix',dynamics:'Controlled dynamic contrast',drums:'Vintage Drum Sound',vocals:'Vintage Radio Vocal',master:'Warm Analog Master',extras:['Warm Bass Foundation','Intimate Narrow Stereo','Warm Plate Reverb','Tape Saturation','Soft Rounded Transients','Vintage Radio Vocal']},
 {id:'dark',name:'Dark & Heavy',desc:'Dense, aggressive and low-end focused',production:'Studio Quality Production',mix:'Dark and Moody Mix',dynamics:'Abrupt contrast sections',drums:'Compressed Modern Drums',vocals:'Forward Lead Vocal',master:'Modern Streaming Master',extras:['Controlled Low End','Wide Stereo Image','Dry Close Room','Industrial Distortion','Compressed Impact','Forward Lead Vocal']},
 {id:'lofi',name:'Lo-Fi & Intimate',desc:'Soft, dusty and close',production:'Raw Organic Production',mix:'Warm Vintage Mix',dynamics:'Soft intro, gentle progression',drums:'Soft Lo-Fi Drums',vocals:'Intimate Close-Mic Vocal',master:'Warm Analog Master',extras:['Warm Bass Foundation','Intimate Narrow Stereo','Dry Close Room','Lo-Fi Dust','Soft Rounded Transients','Intimate Close-Mic Vocal']},
 {id:'anime',name:'Anime & Dynamic',desc:'Bright, energetic and emotional',production:'Modern Anime Production',mix:'Bright Modern Mix',dynamics:'Soft intro, huge finale',drums:'Compressed Modern Drums',vocals:'Layered Wide Vocals',master:'Modern Streaming Master',extras:['Controlled Low End','Wide Stereo Image','Natural Room Ambience','Clean Digital Texture','Punchy Transients','Wide Layered Vocal']}
];
const TECHNIQUES=[
 {name:'Wide Stereo Image',category:'Stereo',reliability:'core',energy:'medium',description:'Expands supporting elements across the stereo field while keeping the lead focused.',genres:['Pop','Rock','EDM','Anime','Cinematic'],good:['Layered vocals','Synths','Guitars','Orchestra'],avoid:['Vintage Mono Character'],alternatives:['Focused Center Image','Expansive Cinematic Width'],prompt:'Wide Stereo Image'},
 {name:'Focused Center Image',category:'Stereo',reliability:'core',energy:'medium',description:'Keeps the lead, bass and main groove focused in the center for clarity.',genres:['Hip-Hop','Pop','Rock','Acoustic'],good:['Lead vocals','Bass','Kick drum'],avoid:['Overly dense layering'],alternatives:['Intimate Narrow Stereo','Wide Stereo Image'],prompt:'Focused Center Image'},
 {name:'Expansive Cinematic Width',category:'Stereo',reliability:'advanced',energy:'high',description:'Creates large orchestral width and depth for cinematic material.',genres:['Cinematic','Trailer','Game OST','Symphonic Metal'],good:['Orchestra','Choir','Cinematic percussion'],avoid:['Vintage Mono Character'],alternatives:['Wide Stereo Image'],prompt:'Expansive Cinematic Width'},
 {name:'Vintage Mono Character',category:'Stereo',reliability:'advanced',energy:'low',description:'Reduces width for a vintage radio, early jazz or archival feel.',genres:['Jazz','Swing','Blues','Vintage Pop'],good:['Brass','Upright bass','Vintage vocal'],avoid:['Wide Stereo Image'],alternatives:['Intimate Narrow Stereo'],prompt:'Vintage Mono Character'},
 {name:'Controlled Low End',category:'Low End',reliability:'core',energy:'medium',description:'Keeps bass powerful but defined without overwhelming the mix.',genres:['All genres'],good:['Bass','Kick','Low strings'],avoid:['Huge Festival Sub when subtlety is required'],alternatives:['Tight Bass','Deep Sub Weight'],prompt:'Controlled Low End'},
 {name:'Deep Sub Weight',category:'Low End',reliability:'core',energy:'high',description:'Adds strong sub-bass presence for cinematic and electronic impact.',genres:['EDM','Hip-Hop','Cinematic','Trap'],good:['Synth bass','808','Cinematic percussion'],avoid:['Natural acoustic arrangements'],alternatives:['Huge Festival Sub','Controlled Low End'],prompt:'Deep Sub Weight'},
 {name:'Tight Bass',category:'Low End',reliability:'core',energy:'medium',description:'Short, controlled bass response that supports rhythmic clarity.',genres:['Rock','Metal','Funk','Pop'],good:['Bass guitar','Kick drum','Rhythm guitar'],avoid:['Long ambient tails'],alternatives:['Controlled Low End'],prompt:'Tight Bass'},
 {name:'Natural Acoustic Low End',category:'Low End',reliability:'advanced',energy:'low',description:'Preserves realistic body from upright bass, cello, piano and room sound.',genres:['Folk','Jazz','Classical','Acoustic'],good:['Upright bass','Cello','Piano'],avoid:['Huge Festival Sub'],alternatives:['Warm Bass Foundation'],prompt:'Natural Acoustic Low End'},
 {name:'Punchy Transients',category:'Dynamics',reliability:'core',energy:'high',description:'Emphasizes attack and impact in drums and rhythmic instruments.',genres:['Rock','Metal','EDM','Pop'],good:['Drums','Percussion','Rhythm guitar'],avoid:['Soft ambient production'],alternatives:['Sharp Modern Attack','Natural Dynamic Transients'],prompt:'Punchy Transients'},
 {name:'Natural Dynamic Transients',category:'Dynamics',reliability:'advanced',energy:'medium',description:'Preserves natural attack and performance variation without heavy compression.',genres:['Folk','Jazz','Classical','Acoustic'],good:['Live drums','Piano','Strings'],avoid:['Loud Festival Master'],alternatives:['Soft Rounded Transients'],prompt:'Natural Dynamic Transients'},
 {name:'Compressed Impact',category:'Dynamics',reliability:'advanced',energy:'high',description:'Creates dense, controlled impact suited to heavy modern arrangements.',genres:['Metalcore','EDM','Trailer','Industrial'],good:['Heavy drums','Distorted guitars','Impacts'],avoid:['Natural acoustic master'],alternatives:['Punchy Transients'],prompt:'Compressed Impact'},
 {name:'Analog Warmth',category:'Texture',reliability:'core',energy:'medium',description:'Adds gentle harmonic warmth and a less clinical character.',genres:['Pop','Rock','Jazz','Folk','Cinematic'],good:['Vocals','Piano','Guitars','Strings'],avoid:['Ultra-clean futuristic production'],alternatives:['Tape Saturation','Clean Digital Texture'],prompt:'Analog Warmth'},
 {name:'Tape Saturation',category:'Texture',reliability:'core',energy:'medium',description:'Adds vintage harmonic density and slightly softened transients.',genres:['Rock','Jazz','Lo-Fi','Vintage Pop'],good:['Drums','Vocals','Bass','Piano'],avoid:['Sharp Modern Attack'],alternatives:['Analog Warmth','Vinyl Texture'],prompt:'Tape Saturation'},
 {name:'Lo-Fi Dust',category:'Texture',reliability:'advanced',energy:'low',description:'Adds imperfect, dusty and intimate texture for lo-fi styles.',genres:['Lo-Fi','Bedroom Pop','Ambient','Chillhop'],good:['Soft drums','Piano','Jazz guitar'],avoid:['High Fidelity Mix'],alternatives:['Vinyl Texture','Tape Saturation'],prompt:'Lo-Fi Dust'},
 {name:'Industrial Distortion',category:'Texture',reliability:'experimental',energy:'high',description:'Adds abrasive distortion and mechanical density.',genres:['Industrial','Cyberpunk','Metal','Experimental'],good:['Synth bass','Percussion','Guitars'],avoid:['Clean acoustic production'],alternatives:['Tape Saturation'],prompt:'Industrial Distortion'},
 {name:'Natural Room Ambience',category:'Space',reliability:'core',energy:'medium',description:'Provides believable room depth without washing out the arrangement.',genres:['Rock','Folk','Jazz','Pop'],good:['Live drums','Vocals','Acoustic instruments'],avoid:['Very long atmospheric reverb'],alternatives:['Dry Close Room','Large Hall Reverb'],prompt:'Natural Room Ambience'},
 {name:'Large Hall Reverb',category:'Space',reliability:'core',energy:'high',description:'Creates scale and depth for choir, orchestra and epic vocals.',genres:['Cinematic','Classical','Symphonic Metal','Viking'],good:['Choir','Orchestra','Large vocals'],avoid:['Dry Close Room'],alternatives:['Long Atmospheric Reverb'],prompt:'Large Hall Reverb'},
 {name:'Warm Plate Reverb',category:'Space',reliability:'core',energy:'medium',description:'Adds smooth vocal or snare depth without an overly large room.',genres:['Pop','Rock','Soul','Vintage'],good:['Lead vocal','Snare','Guitar'],avoid:['Dry Close Room'],alternatives:['Natural Room Ambience'],prompt:'Warm Plate Reverb'},
 {name:'Dub Delay Space',category:'Space',reliability:'advanced',energy:'medium',description:'Uses rhythmic delay for spacious reggae, dub and experimental production.',genres:['Dub','Reggae','Electronic','Experimental'],good:['Vocals','Guitar','Percussion'],avoid:['Dense fast lyrics'],alternatives:['Long Atmospheric Reverb'],prompt:'Dub Delay Space'},
 {name:'Intimate Close-Mic Vocal',category:'Vocals',reliability:'core',energy:'low',description:'Places the singer close and emotionally present.',genres:['Ballad','Acoustic','Lo-Fi','Pop'],good:['Soft lead vocal','Whisper','Piano'],avoid:['Large Hall Vocal'],alternatives:['Forward Lead Vocal'],prompt:'Intimate Close-Mic Vocal'},
 {name:'Forward Lead Vocal',category:'Vocals',reliability:'core',energy:'high',description:'Keeps the lead vocal clear and present over a dense arrangement.',genres:['Pop','Rock','Metal','Hip-Hop'],good:['Lead vocals','Dense instruments'],avoid:['Distant Ethereal Vocal'],alternatives:['Intimate Close-Mic Vocal'],prompt:'Forward Lead Vocal'},
 {name:'Wide Layered Vocal',category:'Vocals',reliability:'core',energy:'high',description:'Creates a broad chorus vocal using layers and harmonies.',genres:['Pop','Anime','EDM','Rock'],good:['Chorus','Backing vocals','Harmonies'],avoid:['Vintage Mono Character'],alternatives:['Large Hall Vocal'],prompt:'Wide Layered Vocal'},
 {name:'Vintage Radio Vocal',category:'Vocals',reliability:'advanced',energy:'medium',description:'Creates a filtered vintage vocal tone for intros, bridges or retro styles.',genres:['Electro Swing','Vintage Pop','Industrial','Concept Music'],good:['Spoken voice','Intro','Bridge'],avoid:['High Fidelity lead vocal throughout'],alternatives:['Intimate Close-Mic Vocal'],prompt:'Vintage Radio Vocal'},
 {name:'Modern Streaming Master',category:'Mastering',reliability:'core',energy:'high',description:'Polished, controlled and competitively loud modern mastering.',genres:['Pop','Rock','Metal','EDM','Anime'],good:['Modern production','Strong transients'],avoid:['Natural acoustic master'],alternatives:['Warm Analog Master'],prompt:'Modern Streaming Master'},
 {name:'Warm Analog Master',category:'Mastering',reliability:'core',energy:'medium',description:'Softer, warmer master with less clinical brightness.',genres:['Jazz','Rock','Folk','Lo-Fi','Vintage Pop'],good:['Analog texture','Natural dynamics'],avoid:['Ultra-bright modern mix'],alternatives:['Natural Acoustic Master'],prompt:'Warm Analog Master'},
 {name:'Cinematic Dynamic Master',category:'Mastering',reliability:'advanced',energy:'high',description:'Retains wide dynamic range for cinematic builds and climaxes.',genres:['Cinematic','Trailer','Orchestral','Game OST'],good:['Orchestra','Choir','Cinematic percussion'],avoid:['Constant maximum loudness'],alternatives:['Modern Streaming Master'],prompt:'Cinematic Dynamic Master'},
 {name:'Natural Acoustic Master',category:'Mastering',reliability:'advanced',energy:'low',description:'Preserves natural dynamics and acoustic detail.',genres:['Classical','Folk','Jazz','Acoustic'],good:['Live instruments','Room ambience'],avoid:['Loud Festival Master'],alternatives:['Warm Analog Master'],prompt:'Natural Acoustic Master'},
 {name:'Loud Festival Master',category:'Mastering',reliability:'advanced',energy:'high',description:'Creates loud, dense impact for festival electronic music.',genres:['EDM','Hardstyle','Dubstep','Festival Pop'],good:['Drops','Synth bass','Electronic drums'],avoid:['Natural acoustic dynamics'],alternatives:['Modern Streaming Master'],prompt:'Loud Festival Master'}
];
const CONFLICTS=[
 ['Vintage Mono Character','Wide Stereo Image'],['Vintage Mono Character','Expansive Cinematic Width'],
 ['Dry Close Room','Large Hall Reverb'],['Dry Close Room','Long Atmospheric Reverb'],
 ['Clean Digital Texture','Lo-Fi Dust'],['Clean Digital Texture','Industrial Distortion'],
 ['Soft Rounded Transients','Sharp Modern Attack'],['Soft Rounded Transients','Compressed Impact'],
 ['Intimate Close-Mic Vocal','Large Hall Vocal'],['Intimate Close-Mic Vocal','Distant Ethereal Vocal'],
 ['Natural Acoustic Low End','Huge Festival Sub'],['Natural Acoustic Master','Loud Festival Master'],
 ['Warm Analog Master','Ultra-Clean Digital Master']
];
let activePreset=null,selectedTechnique=null;
function val(id){return $(id)?.value||'None'}function setSelect(id,value){const e=$(id);if(!e)return false;let o=[...e.options].find(x=>low(x.value)===low(value)||low(x.textContent)===low(value));if(!o)o=[...e.options].find(x=>low(x.textContent).includes(low(value))||low(value).includes(low(x.textContent)));if(o){e.value=o.value;e.dispatchEvent(new Event('change',{bubbles:true}));return true}return false}
function currentGenre(){return $('subgenre')?.value||$('genreFamily')?.value||$('mainGenre')?.value||''}
function selectedFeatures(){const extra=EXTRA_IDS.map(val),legacy=[];document.querySelectorAll('#productionExtras .chip.active,#productionExtras .chip.selected,#productionExtras button.active,#productionExtras button.selected').forEach(x=>legacy.push(x.dataset.value||x.textContent.trim()));return uniq([...extra,...legacy])}
function chain(){return uniq([val('production'),val('mix'),val('dynamics'),val('drumMix'),val('vocalProduction'),val('mastering'),...selectedFeatures()])}
function conflictMessages(items){const out=[];CONFLICTS.forEach(([a,b])=>{if(items.some(x=>low(x).includes(low(a)))&&items.some(x=>low(x).includes(low(b))))out.push(`${a} conflicts with ${b}.`)});const p=low(val('production')),m=low(val('mix')),master=low(val('mastering'));if(p.includes('raw organic')&&m.includes('clean and polished'))out.push('Raw Organic Production and Clean and Polished Mix may pull in different directions.');if(m.includes('huge low-end')&&selectedFeatures().includes('Natural Acoustic Low End'))out.push('Huge Low-End Mix may overpower the selected natural acoustic low end.');if(master.includes('festival')&&currentGenre()&&/folk|classical|acoustic|jazz/i.test(currentGenre()))out.push('A loud festival master is unusual for the current acoustic-oriented genre.');return uniq(out)}
function profileCompleteness(items){const groups=[[val('production')],[val('mix')],[val('dynamics')],[val('drumMix')],[val('vocalProduction')],[val('mastering')],[...EXTRA_IDS.map(val)]],filled=groups.filter(g=>g.some(x=>x&&x!=='None')).length;return Math.round(filled/groups.length*100)}
function genreFit(items){const g=low(currentGenre());if(!g)return 70;let score=72;const joined=low(items.join(' '));if(/edm|house|trance|dubstep|hardstyle/.test(g)){if(/festival|sub|wide|electronic|sidechain/.test(joined))score+=18;if(/natural acoustic|mono/.test(joined))score-=12}if(/metal|rock/.test(g)){if(/punchy|dense|wide|transient|modern/.test(joined))score+=15;if(/lo-fi dust|soft rounded/.test(joined))score-=8}if(/jazz|swing|folk|acoustic|classical/.test(g)){if(/warm|natural|organic|analog|room/.test(joined))score+=16;if(/festival|huge sub|industrial distortion/.test(joined))score-=15}if(/cinematic|soundtrack|orchestral/.test(g)){if(/cinematic|hall|dynamic|expansive|deep sub/.test(joined))score+=18}if(/pop|anime|j-pop/.test(g)){if(/polished|bright|wide|layered|streaming/.test(joined))score+=14}return clamp(score)}
function analyze(){
 const items=chain(),conflicts=conflictMessages(items),complete=profileCompleteness(items),fit=genreFit(items),clarity=clamp(100-Math.max(0,items.length-12)*4-conflicts.length*12),score=Math.round(complete*.35+fit*.4+clarity*.25);
 $('productionIntelScore').textContent=score;$('productionIntelScoreBar').style.width=score+'%';$('productionIntelCompatibility').textContent=`Compatibility ${fit}%`;
 $('productionIntelSummary').textContent=items.length?`The chain combines ${items.slice(0,4).join(', ')}${items.length>4?' and additional detail':''}. ${currentGenre()?`It is evaluated against ${currentGenre()}.`:'Choose a genre for more precise compatibility guidance.'}`:'Choose production settings to build a coherent chain.';
 const metrics=[['Completeness',complete+'%'],['Genre fit',fit+'%'],['Clarity',clarity+'%'],['Chain elements',items.length]];$('productionIntelMetrics').innerHTML=metrics.map(([a,b])=>`<div class="production-intelligence-metric"><small>${a}</small><b>${b}</b></div>`).join('');
 $('productionIntelWarnings').innerHTML=conflicts.length?conflicts.map(x=>`<div class="production-intelligence-message warn">${x}</div>`).join(''):'<div class="production-intelligence-message good">No direct production conflicts detected.</div>';
 const rec=[];if(val('production')==='None')rec.push('Choose a production foundation before adding detailed effects.');if(val('mix')==='None')rec.push('Add one clear mix character.');if(val('mastering')==='None')rec.push('Add a mastering direction to complete the chain.');if(val('productionIntelLowEnd')==='None')rec.push('A low-end direction improves bass and kick clarity.');if(val('productionIntelSpace')==='None')rec.push('Choose one room or reverb concept rather than stacking several.');if(items.length>13)rec.push('The chain is dense. Remove less important terms for clearer Suno interpretation.');if(fit<65)rec.push('Several choices are unusual for the current genre; consider a matching preset.');$('productionIntelRecommendations').innerHTML=(rec.length?rec:['The production chain is focused and complete.']).map(x=>`<div class="production-intelligence-message ${rec.length?'info':'good'}">${x}</div>`).join('');
 $('productionIntelDNA').value=items.join(', ');return{score,fit,complete,clarity,items,conflicts}
}
function renderPresets(){$('productionIntelPresetGrid').innerHTML=PRESETS.map(p=>`<button class="production-preset-card ${activePreset===p.id?'active':''}" data-prod-preset="${p.id}"><b>${p.name}</b><small>${p.desc}</small></button>`).join('');document.querySelectorAll('[data-prod-preset]').forEach(b=>b.onclick=()=>applyPreset(PRESETS.find(p=>p.id===b.dataset.prodPreset)))}
function applyPreset(p){if(!p)return;activePreset=p.id;setSelect('production',p.production);setSelect('mix',p.mix);setSelect('dynamics',p.dynamics);setSelect('drumMix',p.drums);setSelect('vocalProduction',p.vocals);setSelect('mastering',p.master);EXTRA_IDS.forEach((id,i)=>{$(id).value=p.extras[i]||'None'});renderPresets();analyze();if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast(`${p.name} production applied.`)}
function resetProduction(){['production','mix','dynamics','drumMix','vocalProduction','mastering'].forEach(id=>setSelect(id,'None'));EXTRA_IDS.forEach(id=>$(id).value='None');activePreset=null;renderPresets();analyze();if(typeof generateOutput==='function')generateOutput()}
function smartPreset(){const g=low(currentGenre());let p;if(/anime|j-pop|jpop/.test(g))p=PRESETS.find(x=>x.id==='anime');else if(/edm|house|trance|dubstep|hardstyle/.test(g))p=PRESETS.find(x=>x.id==='festival');else if(/cinematic|soundtrack|orchestral|trailer/.test(g))p=PRESETS.find(x=>x.id==='cinematic');else if(/folk|jazz|swing|acoustic|classical|viking|nordic/.test(g))p=PRESETS.find(x=>x.id==='organic');else if(/metal|industrial/.test(g))p=PRESETS.find(x=>x.id==='dark');else p=PRESETS.find(x=>x.id==='modern');applyPreset(p)}
function applyDNA(){const dna=$('productionIntelDNA').value.trim();if(!dna)return;const area=$('customStyle');if(area){const existing=area.value.split(',').map(x=>x.trim()).filter(Boolean),next=uniq([...existing,...dna.split(',').map(x=>x.trim())]);area.value=next.join(', ');area.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Production DNA added to STYLE.')}}
async function copyDNA(){try{await navigator.clipboard.writeText($('productionIntelDNA').value)}catch(e){$('productionIntelDNA').select();document.execCommand('copy')}if(typeof showToast==='function')showToast('Production DNA copied.')}
function categoryOptions(){const cats=uniq(TECHNIQUES.map(x=>x.category)).sort();cats.forEach(x=>$('productionIntelLibraryCategory').add(new Option(x,x)))}
function techniquePass(t){const cat=$('productionIntelLibraryCategory').value,rel=$('productionIntelLibraryReliability').value,en=$('productionIntelLibraryEnergy').value,q=low($('productionIntelLibrarySearch').value);if(cat!=='all'&&t.category!==cat)return false;if(rel!=='all'&&t.reliability!==rel)return false;if(en!=='all'&&t.energy!==en)return false;if(q&&!low([t.name,t.description,t.category,...t.genres,...t.good,...t.avoid].join(' ')).includes(q))return false;return true}
function renderLibrary(){const arr=TECHNIQUES.filter(techniquePass);$('productionIntelLibraryCount').textContent=`${arr.length} techniques`;$('productionIntelBadge').textContent=`${TECHNIQUES.length} techniques · ${PRESETS.length} presets · local knowledge`;$('productionIntelLibraryGrid').innerHTML=arr.map(t=>`<article class="production-library-card ${selectedTechnique?.name===t.name?'active':''}" data-tech="${encodeURIComponent(t.name)}"><h3>${t.name}</h3><small>${t.category}</small><div class="production-library-badges"><span class="production-library-badge ${t.reliability}">${t.reliability}</span><span class="production-library-badge">${t.energy}</span></div><p>${t.description}</p><div class="production-library-chips">${t.genres.slice(0,3).map(x=>`<span>${x}</span>`).join('')}</div></article>`).join('');$('productionIntelLibraryEmpty').hidden=arr.length>0;document.querySelectorAll('[data-tech]').forEach(e=>e.onclick=()=>{selectedTechnique=TECHNIQUES.find(x=>x.name===decodeURIComponent(e.dataset.tech));renderLibrary();renderTechnique()})}
function chips(a){return`<div class="production-library-chips">${a.map(x=>`<span>${x}</span>`).join('')}</div>`}
function renderTechnique(){if(!selectedTechnique)return;const t=selectedTechnique;$('productionIntelLibraryInspector').innerHTML=`<div class="production-library-detail"><h2>${t.name}</h2><div class="production-library-badges"><span class="production-library-badge ${t.reliability}">${t.reliability}</span><span class="production-library-badge">${t.category}</span><span class="production-library-badge">${t.energy} energy</span></div><p>${t.description}</p><div class="production-library-section"><h4>Best suited genres</h4>${chips(t.genres)}</div><div class="production-library-section"><h4>Works well with</h4>${chips(t.good)}</div><div class="production-library-section"><h4>Avoid or use carefully with</h4>${chips(t.avoid)}</div><div class="production-library-section"><h4>Alternatives</h4>${chips(t.alternatives)}</div><div class="production-library-section"><h4>Suno-friendly phrase</h4><p>${t.prompt}</p></div><div class="production-library-detail-actions"><button id="productionIntelCopyTechnique">Copy phrase</button><button id="productionIntelAddTechnique">Add to chain</button><button class="primary" id="productionIntelAddStyle">Add to STYLE</button></div></div>`;$('productionIntelCopyTechnique').onclick=async()=>{try{await navigator.clipboard.writeText(t.prompt)}catch(e){}if(typeof showToast==='function')showToast('Production phrase copied.')};$('productionIntelAddTechnique').onclick=()=>addTechnique(t.prompt,false);$('productionIntelAddStyle').onclick=()=>addTechnique(t.prompt,true)}
function addTechnique(text,toStyle){if(toStyle){const e=$('customStyle');e.value=uniq([...e.value.split(',').map(x=>x.trim()),text]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}else{const free=EXTRA_IDS.find(id=>val(id)==='None');if(free){const e=$(free),o=[...e.options].find(x=>low(x.value)===low(text));if(o)e.value=o.value;else{const opt=new Option(text,text);e.add(opt);e.value=text}}else{$('customStyle').value=uniq([...$('customStyle').value.split(',').map(x=>x.trim()),text]).join(', ')}analyze()}if(typeof showToast==='function')showToast('Production technique added.')}
function init(){
 if(!$('productionIntelPresetGrid'))return;renderPresets();categoryOptions();renderLibrary();
 ['production','mix','dynamics','drumMix','vocalProduction','mastering',...EXTRA_IDS].forEach(id=>{if($(id))$(id).addEventListener('change',()=>{activePreset=null;renderPresets();analyze()})});
 ['productionIntelLibraryCategory','productionIntelLibraryReliability','productionIntelLibraryEnergy'].forEach(id=>$(id).onchange=renderLibrary);$('productionIntelLibrarySearch').oninput=renderLibrary;
 $('productionIntelResetPreset').onclick=resetProduction;$('productionIntelSmartFeatures').onclick=smartPreset;$('productionIntelSmartExclusions').onclick=()=>{const ex=[];const g=low(currentGenre());if(/folk|classical|acoustic|jazz/.test(g))ex.push('Overcompressed Master','Huge Festival Sub');if(/edm|electronic/.test(g))ex.push('Loose Acoustic Timing','Weak Low End');if(/metal|rock/.test(g))ex.push('Soft Transients','Thin Guitars');$('customExclude').value=uniq([...$('customExclude').value.split(',').map(x=>x.trim()),...ex]).join(', ');if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Production exclusions suggested.')};
 $('productionIntelCopyDNA').onclick=copyDNA;$('productionIntelApplyDNA').onclick=applyDNA;
 const oldApply=$('applyProductionSuggestions');if(oldApply)oldApply.addEventListener('click',()=>setTimeout(analyze,20));
 analyze()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
