
(function(){
'use strict';
const $=id=>document.getElementById(id);
const KEY='nsw-project-manager-v4', DB_NAME='nsw-project-assets-v1', STORE='assets';
const CHECKS=[
 ['idea','Idea / concept'],['style','STYLE prompt'],['lyrics','Lyrics'],['blueprint','Song Blueprint'],
 ['suno','Suno generation'],['selection','Final version selected'],['cover','Track artwork'],['video','Video / visualizer'],
 ['description','Release description'],['metadata','Release metadata'],['upload','Distributor upload'],['published','Published']
];
let state=load(),activeProjectId=state.activeProjectId||null,activeTrackId=null,saveTimer=null,dbPromise=null;
function uid(prefix){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function now(){return Date.now()}
function blankTrack(number=1,title='New Track'){return{id:uid('track'),number,title,status:'idea',priority:'normal',notes:'',style:'',lyrics:'',blueprint:'',exclude:'',sunoLink:'',youtubeLink:'',spotifyLink:'',youtubeDescription:'',releaseNotes:'',releaseDate:'',identifier:'',finalDuration:'',checklist:Object.fromEntries(CHECKS.map(([k])=>[k,false])),versions:[],assets:[],vocalDirector:null,successPrediction:null,successPredictionHistory:[],genreEvolution:null,instrumentEvolution:null,studioAssistantPlan:null,aiMusicDirector:null,arrangementDesigner:null,instrumentGraph:null,vocalDirectorV2:null,musicTheoryDirector:null,songDirectorAI:null,aiProducer:null,studioIntelligence:null,worldMusicAtlas:null,instrumentEncyclopedia:null,created:now(),updated:now()}}
function blankProject(name='New Project'){return{id:uid('project'),name,description:'',type:'Album',targetTracks:12,status:'planning',tracks:[],created:now(),updated:now()}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.projects))return x}catch(e){}const p=blankProject('My First Project');p.tracks.push(blankTrack(1,'Track 01'));return{version:4,projects:[p],activeProjectId:p.id}}
function persist(){state.activeProjectId=activeProjectId;localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function project(){return state.projects.find(x=>x.id===activeProjectId)||state.projects[0]||null}
function track(){return project()?.tracks.find(x=>x.id===activeTrackId)||null}
function scheduleSave(){clearTimeout(saveTimer);$('pmSaveStatus').textContent='Saving changes...';saveTimer=setTimeout(()=>{saveForm();$('pmSaveStatus').textContent='All changes saved locally.'},450)}
function trackProgress(t){return Math.round(Object.values(t.checklist||{}).filter(Boolean).length/CHECKS.length*100)}
function projectProgress(p){if(!p||!p.tracks.length)return 0;return Math.round(p.tracks.reduce((a,t)=>a+trackProgress(t),0)/p.tracks.length)}
function fmtDate(ts){return ts?new Date(ts).toLocaleDateString():'—'}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function bytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB'],i=Math.min(u.length-1,Math.floor(Math.log(n)/Math.log(1024)));return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function totalAssets(p){return p.tracks.reduce((a,t)=>a+(t.assets?.length||0),0)}
function totalVersions(p){return p.tracks.reduce((a,t)=>a+(t.versions?.length||0),0)}
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{if(!('indexedDB'in window)){resolve(null);return}const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function putAsset(record){const db=await openDB();if(!db)return false;return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function getAsset(id){const db=await openDB();if(!db)return null;return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function deleteAssetBlob(id){const db=await openDB();if(!db)return;return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function ensureActive(){const p=project();if(!p){activeTrackId=null;return}if(!p.tracks.some(x=>x.id===activeTrackId))activeTrackId=p.tracks[0]?.id||null}
function renderProjectSelect(){const s=$('pmProjectSelect');s.innerHTML=state.projects.map(p=>`<option value="${p.id}" ${p.id===activeProjectId?'selected':''}>${escapeHtml(p.name)}</option>`).join('')||'<option>No projects</option>'}
function renderDashboard(){const p=project();if(!p)return;const progress=projectProgress(p);$('pmProjectTitle').textContent=p.name;$('pmProjectDescription').textContent=p.description||`${p.type} · ${p.tracks.length}/${p.targetTracks} planned tracks`;$('pmProjectProgress').textContent=progress+'%';$('pmProjectProgressRing').style.setProperty('--pm-progress',progress+'%');$('pmStatTracks').textContent=p.tracks.length;$('pmStatCompleted').textContent=p.tracks.filter(t=>trackProgress(t)===100).length;$('pmStatAssets').textContent=totalAssets(p);$('pmStatVersions').textContent=totalVersions(p);$('pmStatUpdated').textContent=fmtDate(p.updated);$('pmProjectDescriptionInput').value=p.description||'';$('pmProjectType').value=p.type||'Album';$('pmTargetTracks').value=p.targetTracks||12;$('pmProjectStatus').value=p.status||'planning';$('pmStorageBadge').textContent=`${state.projects.length} projects · ${state.projects.reduce((a,x)=>a+x.tracks.length,0)} tracks · local storage`}
function renderTrackList(){const p=project();if(!p)return;const q=($('pmTrackSearch')?.value||'').toLowerCase(),filter=$('pmTrackFilter')?.value||'all';const rows=p.tracks.slice().sort((a,b)=>a.number-b.number).filter(t=>(filter==='all'||t.status===filter)&&(!q||(t.title+' '+t.notes).toLowerCase().includes(q)));$('pmTrackCount').textContent=`${rows.length} of ${p.tracks.length} tracks`;$('pmTrackList').innerHTML=rows.length?rows.map(t=>{const pr=trackProgress(t);return`<article class="project-manager-track-item ${t.id===activeTrackId?'active':''}" data-track-id="${t.id}"><div class="project-manager-track-item-top"><b>${String(t.number).padStart(2,'0')} · ${escapeHtml(t.title)}</b><small>${pr}%</small></div><div class="project-manager-track-progress"><i style="width:${pr}%"></i></div><div class="project-manager-track-meta"><span>${t.status}</span><span>${t.versions?.length||0} versions · ${t.assets?.length||0} assets</span></div></article>`}).join(''):'<div class="feature-empty">No tracks match this filter.</div>';document.querySelectorAll('[data-track-id]').forEach(e=>e.onclick=()=>{saveForm();activeTrackId=e.dataset.trackId;renderAll()})}
function renderChecklist(t){$('pmChecklist').innerHTML=CHECKS.map(([k,label])=>`<label class="project-manager-check ${t.checklist?.[k]?'done':''}"><input type="checkbox" data-pm-check="${k}" ${t.checklist?.[k]?'checked':''}>${label}</label>`).join('');document.querySelectorAll('[data-pm-check]').forEach(e=>e.onchange=()=>{t.checklist[e.dataset.pmCheck]=e.checked;t.updated=now();project().updated=now();persist()})}
function populateTrack(t){$('pmTrackNumber').value=t.number;$('pmTrackTitle').value=t.title;$('pmTrackStatus').value=t.status;$('pmTrackPriority').value=t.priority;$('pmTrackNotes').value=t.notes||'';$('pmTrackStyle').value=t.style||'';$('pmTrackLyrics').value=t.lyrics||'';$('pmTrackBlueprint').value=t.blueprint||'';$('pmTrackExclude').value=t.exclude||'';$('pmSunoLink').value=t.sunoLink||'';$('pmYoutubeLink').value=t.youtubeLink||'';$('pmSpotifyLink').value=t.spotifyLink||'';$('pmYoutubeDescription').value=t.youtubeDescription||'';$('pmReleaseNotes').value=t.releaseNotes||'';$('pmReleaseDate').value=t.releaseDate||'';$('pmTrackIdentifier').value=t.identifier||'';$('pmFinalDuration').value=t.finalDuration||'';$('pmTrackTitleDisplay').textContent=`${String(t.number).padStart(2,'0')} · ${t.title}`;$('pmTrackSubtitle').textContent=`${t.status} · ${trackProgress(t)}% complete · updated ${fmtDate(t.updated)}`;renderChecklist(t);renderVersions(t);renderAssets(t)}
function renderTrackWorkspace(){ensureActive();const t=track();$('pmTrackEmpty').classList.toggle('hidden',!!t);$('pmTrackWorkspace').classList.toggle('hidden',!t);if(t)populateTrack(t)}
function saveForm(){const p=project(),t=track();if(!p)return;p.description=$('pmProjectDescriptionInput')?.value||p.description;p.type=$('pmProjectType')?.value||p.type;p.targetTracks=+$('pmTargetTracks')?.value||p.targetTracks;p.status=$('pmProjectStatus')?.value||p.status;if(t){t.number=+$('pmTrackNumber').value||t.number;t.title=$('pmTrackTitle').value.trim()||t.title;t.status=$('pmTrackStatus').value;t.priority=$('pmTrackPriority').value;t.notes=$('pmTrackNotes').value;t.style=$('pmTrackStyle').value;t.lyrics=$('pmTrackLyrics').value;t.blueprint=$('pmTrackBlueprint').value;t.exclude=$('pmTrackExclude').value;t.sunoLink=$('pmSunoLink').value;t.youtubeLink=$('pmYoutubeLink').value;t.spotifyLink=$('pmSpotifyLink').value;t.youtubeDescription=$('pmYoutubeDescription').value;t.releaseNotes=$('pmReleaseNotes').value;t.releaseDate=$('pmReleaseDate').value;t.identifier=$('pmTrackIdentifier').value;t.finalDuration=$('pmFinalDuration').value;t.updated=now()}p.updated=now();state.activeProjectId=activeProjectId;localStorage.setItem(KEY,JSON.stringify(state))}
function snapshot(t,label){return{id:uid('version'),label:label||`Version ${t.versions.length+1}`,created:now(),style:t.style,lyrics:t.lyrics,blueprint:t.blueprint,exclude:t.exclude,notes:t.notes,status:t.status,vocalDirector:t.vocalDirector?JSON.parse(JSON.stringify(t.vocalDirector)):null,successPrediction:t.successPrediction?JSON.parse(JSON.stringify(t.successPrediction)):null,genreEvolution:t.genreEvolution?JSON.parse(JSON.stringify(t.genreEvolution)):null,instrumentEvolution:t.instrumentEvolution?JSON.parse(JSON.stringify(t.instrumentEvolution)):null,studioAssistantPlan:t.studioAssistantPlan?JSON.parse(JSON.stringify(t.studioAssistantPlan)):null,aiMusicDirector:t.aiMusicDirector?JSON.parse(JSON.stringify(t.aiMusicDirector)):null,arrangementDesigner:t.arrangementDesigner?JSON.parse(JSON.stringify(t.arrangementDesigner)):null,instrumentGraph:t.instrumentGraph?JSON.parse(JSON.stringify(t.instrumentGraph)):null,vocalDirectorV2:t.vocalDirectorV2?JSON.parse(JSON.stringify(t.vocalDirectorV2)):null,musicTheoryDirector:t.musicTheoryDirector?JSON.parse(JSON.stringify(t.musicTheoryDirector)):null,songDirectorAI:t.songDirectorAI?JSON.parse(JSON.stringify(t.songDirectorAI)):null,aiProducer:t.aiProducer?JSON.parse(JSON.stringify(t.aiProducer)):null,studioIntelligence:t.studioIntelligence?JSON.parse(JSON.stringify(t.studioIntelligence)):null,worldMusicAtlas:t.worldMusicAtlas?JSON.parse(JSON.stringify(t.worldMusicAtlas)):null,instrumentEncyclopedia:t.instrumentEncyclopedia?JSON.parse(JSON.stringify(t.instrumentEncyclopedia)):null}}
function createVersion(){saveForm();const t=track();if(!t)return;const label=prompt('Version name',`Version ${t.versions.length+1}`);if(label===null)return;t.versions.push(snapshot(t,label));t.updated=now();project().updated=now();persist()}
function renderVersions(t){$('pmVersionList').innerHTML=t.versions?.length?t.versions.slice().reverse().map(v=>`<article class="project-manager-version"><div class="project-manager-version-head"><div><h4>${escapeHtml(v.label)}</h4><p>${new Date(v.created).toLocaleString()} · ${v.status}</p></div><div class="project-manager-version-actions"><button data-version-restore="${v.id}">Restore</button><button data-version-delete="${v.id}">Delete</button></div></div><p>${escapeHtml((v.style||'No STYLE saved').slice(0,250))}</p></article>`).join(''):'<div class="feature-empty">No snapshots yet.</div>';document.querySelectorAll('[data-version-restore]').forEach(b=>b.onclick=()=>{const v=t.versions.find(x=>x.id===b.dataset.versionRestore);if(!v)return;if(confirm(`Restore ${v.label}?`)){Object.assign(t,{style:v.style,lyrics:v.lyrics,blueprint:v.blueprint,exclude:v.exclude,notes:v.notes,status:v.status,vocalDirector:v.vocalDirector||null,successPrediction:v.successPrediction||null,genreEvolution:v.genreEvolution||null,instrumentEvolution:v.instrumentEvolution||null,studioAssistantPlan:v.studioAssistantPlan||null,aiMusicDirector:v.aiMusicDirector||null,arrangementDesigner:v.arrangementDesigner||null,instrumentGraph:v.instrumentGraph||null,vocalDirectorV2:v.vocalDirectorV2||null,musicTheoryDirector:v.musicTheoryDirector||null,songDirectorAI:v.songDirectorAI||null,aiProducer:v.aiProducer||null,studioIntelligence:v.studioIntelligence||null,worldMusicAtlas:v.worldMusicAtlas||null,instrumentEncyclopedia:v.instrumentEncyclopedia||null,updated:now()});persist()}});document.querySelectorAll('[data-version-delete]').forEach(b=>b.onclick=()=>{t.versions=t.versions.filter(x=>x.id!==b.dataset.versionDelete);persist()})}
async function renderAssets(t){const box=$('pmAssetGrid');box.innerHTML=t.assets?.length?t.assets.map(a=>`<article class="project-manager-asset"><div class="project-manager-asset-preview" data-asset-preview="${a.id}">${a.type?.startsWith('image/')?'🖼️':a.type?.startsWith('audio/')?'🎵':'📄'}</div><b title="${escapeHtml(a.name)}">${escapeHtml(a.name)}</b><small>${bytes(a.size)} · ${fmtDate(a.created)}</small><div class="project-manager-asset-actions"><button data-asset-open="${a.id}">Open</button><button data-asset-delete="${a.id}">Delete</button></div></article>`).join(''):'<div class="feature-empty">No assets uploaded for this track.</div>';for(const a of t.assets||[]){if(a.type?.startsWith('image/')){try{const record=await getAsset(a.id);if(record?.blob){const url=URL.createObjectURL(record.blob),el=document.querySelector(`[data-asset-preview="${a.id}"]`);if(el){el.innerHTML=`<img src="${url}" alt="">`;el.querySelector('img').onload=()=>URL.revokeObjectURL(url)}}}catch(e){}}}document.querySelectorAll('[data-asset-open]').forEach(b=>b.onclick=async()=>{const r=await getAsset(b.dataset.assetOpen);if(!r?.blob){alert('The binary asset is not available in this browser.');return}const url=URL.createObjectURL(r.blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)});document.querySelectorAll('[data-asset-delete]').forEach(b=>b.onclick=async()=>{const id=b.dataset.assetDelete;if(!confirm('Delete this asset?'))return;t.assets=t.assets.filter(x=>x.id!==id);await deleteAssetBlob(id);persist()})}
async function uploadAssets(files){const t=track();if(!t)return;for(const file of files){const id=uid('asset'),meta={id,name:file.name,type:file.type||'application/octet-stream',size:file.size,created:now()};try{await putAsset({id,blob:file})}catch(e){alert(`Could not store ${file.name}. Browser storage may be full.`);continue}t.assets.push(meta)}t.updated=now();project().updated=now();persist()}
function captureStudio(){const t=track();if(!t)return;saveForm();t.style=$('styleOutput')?.value||$('customStyle')?.value||t.style;t.lyrics=$('lyricsEditor')?.value||t.lyrics;t.exclude=$('excludeOutput')?.value||$('customExclude')?.value||t.exclude;if(window.NSW_VOCAL_DIRECTOR_LAST)t.vocalDirector=JSON.parse(JSON.stringify(window.NSW_VOCAL_DIRECTOR_LAST));if(window.NSW_SUCCESS_PREDICTOR_LAST)t.successPrediction=JSON.parse(JSON.stringify(window.NSW_SUCCESS_PREDICTOR_LAST));if(window.NSW_GENRE_EVOLUTION_LAST)t.genreEvolution=JSON.parse(JSON.stringify(window.NSW_GENRE_EVOLUTION_LAST));if(window.NSW_INSTRUMENT_EVOLUTION_LAST)t.instrumentEvolution=JSON.parse(JSON.stringify(window.NSW_INSTRUMENT_EVOLUTION_LAST));if(window.NSW_STUDIO_ASSISTANT_LAST)t.studioAssistantPlan=JSON.parse(JSON.stringify(window.NSW_STUDIO_ASSISTANT_LAST));if(window.NSW_AI_MUSIC_DIRECTOR_LAST)t.aiMusicDirector=JSON.parse(JSON.stringify(window.NSW_AI_MUSIC_DIRECTOR_LAST));if(window.NSW_ARRANGEMENT_DESIGNER_LAST)t.arrangementDesigner=JSON.parse(JSON.stringify(window.NSW_ARRANGEMENT_DESIGNER_LAST));if(window.NSW_INSTRUMENT_GRAPH_LAST)t.instrumentGraph=JSON.parse(JSON.stringify(window.NSW_INSTRUMENT_GRAPH_LAST));if(window.NSW_VOCAL_DIRECTOR_V2_LAST)t.vocalDirectorV2=JSON.parse(JSON.stringify(window.NSW_VOCAL_DIRECTOR_V2_LAST));if(window.NSW_MUSIC_THEORY_DIRECTOR_LAST)t.musicTheoryDirector=JSON.parse(JSON.stringify(window.NSW_MUSIC_THEORY_DIRECTOR_LAST));if(window.NSW_SONG_DIRECTOR_LAST)t.songDirectorAI=JSON.parse(JSON.stringify(window.NSW_SONG_DIRECTOR_LAST));if(window.NSW_AI_PRODUCER_LAST)t.aiProducer=JSON.parse(JSON.stringify(window.NSW_AI_PRODUCER_LAST));if(window.NSW_STUDIO_INTELLIGENCE_LAST)t.studioIntelligence=JSON.parse(JSON.stringify(window.NSW_STUDIO_INTELLIGENCE_LAST));if(window.NSW_WORLD_MUSIC_LAST)t.worldMusicAtlas=JSON.parse(JSON.stringify(window.NSW_WORLD_MUSIC_LAST));if(window.NSW_INSTRUMENT_ENCYCLOPEDIA_LAST)t.instrumentEncyclopedia=JSON.parse(JSON.stringify(window.NSW_INSTRUMENT_ENCYCLOPEDIA_LAST));if(window.NSW_SONG_BLUEPRINT_LAST)t.blueprint=JSON.stringify(window.NSW_SONG_BLUEPRINT_LAST,null,2);else if($('bpTableBody')&&$('bpTableBody').children.length)t.blueprint=Array.from($('bpTableBody').rows).map(r=>Array.from(r.cells).map(c=>c.textContent.trim()).join(' | ')).join('\n');t.updated=now();project().updated=now();persist();$('pmSaveStatus').textContent='Current Studio data captured.'}
function restoreStudio(){const t=track();if(!t)return;if($('customStyle')){$('customStyle').value=t.style;$('customStyle').dispatchEvent(new Event('input',{bubbles:true}))}if($('lyricsEditor')){$('lyricsEditor').value=t.lyrics;$('lyricsEditor').dispatchEvent(new Event('input',{bubbles:true}))}if($('customExclude')){$('customExclude').value=t.exclude;$('customExclude').dispatchEvent(new Event('input',{bubbles:true}))}if(typeof generateOutput==='function')generateOutput();if(typeof showToast==='function')showToast('Track data restored to Studio.');$('pmSaveStatus').textContent='Track data restored to available Studio fields.'}
function renderAll(){ensureActive();renderProjectSelect();renderDashboard();renderTrackList();renderTrackWorkspace()}
function newProject(){const name=prompt('Project name','New Album');if(!name)return;const p=blankProject(name);state.projects.push(p);activeProjectId=p.id;activeTrackId=null;persist()}
function renameProject(){const p=project();if(!p)return;const name=prompt('New project name',p.name);if(name){p.name=name;p.updated=now();persist()}}
function duplicateProject(){const p=project();if(!p)return;const copy=JSON.parse(JSON.stringify(p));copy.id=uid('project');copy.name=p.name+' Copy';copy.created=copy.updated=now();copy.tracks.forEach(t=>{t.id=uid('track');t.versions=(t.versions||[]).map(v=>({...v,id:uid('version')}));t.assets=[]});state.projects.push(copy);activeProjectId=copy.id;activeTrackId=copy.tracks[0]?.id||null;persist()}
async function deleteProject(){const p=project();if(!p||!confirm(`Delete project "${p.name}"?`))return;for(const t of p.tracks)for(const a of t.assets||[])await deleteAssetBlob(a.id);state.projects=state.projects.filter(x=>x.id!==p.id);if(!state.projects.length)state.projects.push(blankProject('New Project'));activeProjectId=state.projects[0].id;activeTrackId=null;persist()}
function addTrack(){const p=project();if(!p)return;const number=Math.max(0,...p.tracks.map(x=>x.number))+1,t=blankTrack(number,`Track ${String(number).padStart(2,'0')}`);p.tracks.push(t);activeTrackId=t.id;p.updated=now();persist()}
function duplicateTrack(){const p=project(),t=track();if(!p||!t)return;const copy=JSON.parse(JSON.stringify(t));copy.id=uid('track');copy.number=Math.max(0,...p.tracks.map(x=>x.number))+1;copy.title=t.title+' Copy';copy.created=copy.updated=now();copy.versions=(copy.versions||[]).map(v=>({...v,id:uid('version')}));copy.assets=[];p.tracks.push(copy);activeTrackId=copy.id;persist()}
async function deleteTrack(){const p=project(),t=track();if(!p||!t||!confirm(`Delete "${t.title}"?`))return;for(const a of t.assets||[])await deleteAssetBlob(a.id);p.tracks=p.tracks.filter(x=>x.id!==t.id);activeTrackId=p.tracks[0]?.id||null;p.updated=now();persist()}
function moveTrack(delta){const p=project(),i=p.tracks.findIndex(x=>x.id===activeTrackId),j=i+delta;if(i<0||j<0||j>=p.tracks.length)return;[p.tracks[i],p.tracks[j]]=[p.tracks[j],p.tracks[i]];p.tracks.forEach((t,n)=>t.number=n+1);persist()}
function exportProject(){saveForm();const p=project();if(!p)return;const payload={format:'Nordlicht Soundworks Project',version:4,exportedAt:new Date().toISOString(),project:p,notice:'Binary assets are not included. Asset metadata is retained.'};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=p.name.replace(/[^\w\-]+/g,'_')+'_project.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importProject(file){const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result),p=parsed.project||parsed;if(!p||!Array.isArray(p.tracks))throw new Error('Invalid project');p.id=uid('project');p.name=(p.name||'Imported Project')+' (Imported)';p.created=p.updated=now();p.tracks.forEach((t,i)=>{t.id=uid('track');t.number=t.number||i+1;t.assets=[];t.versions=(t.versions||[]).map(v=>({...v,id:uid('version')}));t.checklist={...Object.fromEntries(CHECKS.map(([k])=>[k,false])),...(t.checklist||{})}});state.projects.push(p);activeProjectId=p.id;activeTrackId=p.tracks[0]?.id||null;persist()}catch(e){alert('This is not a valid Nordlicht project file.')}};r.readAsText(file)}
async function copyField(id){const text=$(id)?.value||'';try{await navigator.clipboard.writeText(text)}catch(e){const el=$(id);el.select();document.execCommand('copy')}if(typeof showToast==='function')showToast('Copied.')}
function setupTabs(){document.querySelectorAll('[data-pm-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-pm-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-pm-panel]').forEach(x=>x.classList.toggle('active',x.dataset.pmPanel===b.dataset.pmTab))})}
function setupAutoSave(){const ids=['pmProjectDescriptionInput','pmProjectType','pmTargetTracks','pmProjectStatus','pmTrackNumber','pmTrackTitle','pmTrackStatus','pmTrackPriority','pmTrackNotes','pmTrackStyle','pmTrackLyrics','pmTrackBlueprint','pmTrackExclude','pmSunoLink','pmYoutubeLink','pmSpotifyLink','pmYoutubeDescription','pmReleaseNotes','pmReleaseDate','pmTrackIdentifier','pmFinalDuration'];ids.forEach(id=>{const e=$(id);if(e){e.addEventListener('input',scheduleSave);e.addEventListener('change',scheduleSave)}})}
function init(){
 if(!$('projectManagerView'))return;ensureActive();setupTabs();setupAutoSave();renderAll();
 $('pmProjectSelect').onchange=e=>{saveForm();activeProjectId=e.target.value;activeTrackId=null;renderAll()};$('pmNewProject').onclick=newProject;$('pmRenameProject').onclick=renameProject;$('pmDuplicateProject').onclick=duplicateProject;$('pmDeleteProject').onclick=deleteProject;$('pmAddTrack').onclick=addTrack;$('pmTrackSearch').oninput=renderTrackList;$('pmTrackFilter').onchange=renderTrackList;$('pmSaveTrack').onclick=()=>{saveForm();persist();$('pmSaveStatus').textContent='Track saved locally.'};$('pmDuplicateTrack').onclick=duplicateTrack;$('pmDeleteTrack').onclick=deleteTrack;$('pmMoveTrackUp').onclick=()=>moveTrack(-1);$('pmMoveTrackDown').onclick=()=>moveTrack(1);$('pmCompleteAll').onclick=()=>{const t=track();if(!t)return;CHECKS.forEach(([k])=>t.checklist[k]=true);persist()};$('pmCaptureCurrent').onclick=captureStudio;$('pmRestoreCurrent').onclick=restoreStudio;$('pmCreateVersion').onclick=createVersion;$('pmNewVersion').onclick=createVersion;$('pmUploadAsset').onclick=()=>$('pmAssetInput').click();$('pmAssetInput').onchange=e=>{uploadAssets([...e.target.files]);e.target.value=''};$('pmExportProject').onclick=exportProject;$('pmImportProject').onclick=()=>$('pmImportFile').click();$('pmImportFile').onchange=e=>{if(e.target.files[0])importProject(e.target.files[0]);e.target.value=''};document.querySelectorAll('[data-copy-field]').forEach(b=>b.onclick=()=>copyField(b.dataset.copyField))
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
