(function(){
"use strict";
const $=id=>document.getElementById(id);
const STORE="nsw_studio_mode_v220";
const choices={
 songTypes:["anime","ballad","edm","metalcore","viking","cinematic","kpop","lofi","instrumental","custom"],
 moods:["none","happy","sad","epic","aggressive","dreamy","romantic","dark","hopeful"],
 palettes:["none","acoustic","rock","orchestral","electronic","nordic","japanese","oriental","retro","medieval"],
 tempos:["slow","medium","fast","veryfast","auto"],voices:["female","male","duet","instrumental"]
};
const paletteNames={
 acoustic:["Acoustic Guitar","Piano","Upright Bass","Cajón","Violin"],rock:["Electric Guitar","Bass Guitar","Drum Kit","Distorted Guitar","Rock Drums"],orchestral:["Violin","Cello","French Horn","Orchestral Percussion","Grand Piano"],electronic:["Synthesizer","Analog Synth","Drum Machine","Sub Bass","Electronic Drums"],nordic:["Tagelharpa","Nyckelharpa","Jouhikko","War Horn","Frame Drum"],japanese:["Shamisen","Koto","Taiko","Shakuhachi","Biwa"],oriental:["Oud","Ney","Darbuka","Qanun","Bendir"],retro:["Upright Bass","Brass Section","Clarinet","Vintage Piano","Saxophone"],medieval:["Hurdy-Gurdy","Lute","Frame Drum","Bagpipes","Harp"]
};
const moodTerms={happy:["Happy","Joyful","Uplifting","Playful"],sad:["Sad","Melancholic","Sorrowful","Heartbroken"],epic:["Epic","Triumphant","Heroic","Majestic"],aggressive:["Aggressive","Angry","Furious","Intense"],dreamy:["Dreamy","Ethereal","Floating","Mystical"],romantic:["Romantic","Tender","Intimate","Passionate"],dark:["Dark","Ominous","Sinister","Haunting"],hopeful:["Hopeful","Inspiring","Optimistic","Emotional"]};
function setMode(mode){
 const simple=mode==="simple";document.body.classList.toggle("simple-mode",simple);$("simpleModeButton")?.classList.toggle("active",simple);$("advancedModeButton")?.classList.toggle("active",!simple);localStorage.setItem(STORE,mode);if(simple){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$("simpleView")?.classList.add("active");syncSimpleFromAdvanced();score();}else{$("simpleView")?.classList.remove("active");const activeNav=document.querySelector(".nav.active");$(activeNav?.dataset.view||"randomView")?.classList.add("active");}
 }
 function selectContains(sel,terms,fallback){if(!sel)return false;const opts=[...sel.options];const found=opts.find(o=>terms.some(t=>(o.textContent+" "+o.value).toLowerCase().includes(t.toLowerCase())));if(found){sel.value=found.value;sel.dispatchEvent(new Event("change",{bubbles:true}));return true}if(fallback!==undefined){sel.value=fallback;sel.dispatchEvent(new Event("change",{bubbles:true}))}return false}
 function fillGenres(){const s=$("simpleGenre"),g=$("genreFamily");if(!s||!g)return;s.innerHTML="";[...g.options].filter(o=>o.value!=="None").forEach(o=>s.add(new Option(o.textContent,o.value)));s.value=g.value!=="None"?g.value:(s.options[0]?.value||"");}
 function applyVoice(v){const inst=$("vocalMode");if(v==="instrumental"){document.querySelector('input[name="vocalMode"][value="instrumental"]')?.click();return}document.querySelector('input[name="vocalMode"][value="vocals"]')?.click();const lead=$("leadVoice");if(v==="female")selectContains(lead,["female lead","female"]);if(v==="male")selectContains(lead,["male lead","male"]);if(v==="duet"){selectContains(lead,["duet"]);selectContains($("secondVoice"),["female","male"])} }
 function applyMood(v){const e=$("emotion");if(v==="none"){selectContains(e,["none","keine"],e.options[0]?.value);return}selectContains(e,moodTerms[v]||[v]);}
 function applyTempo(v){if(v==="auto"){const c=typeof smartBpmCandidates==="function"?smartBpmCandidates():[120];$("bpm").value=c[Math.floor(c.length/2)]||120}else{const ranges={slow:[62,88],medium:[96,124],fast:[128,158],veryfast:[165,205]},r=ranges[v]||ranges.medium;$("bpm").value=Math.round((r[0]+r[1])/2)}$("bpm").dispatchEvent(new Event("input",{bubbles:true}));}
 function applyPalette(v){if(v==="none")return;const names=paletteNames[v]||[];if(typeof INSTRUMENT_DB!=="undefined"){const available=INSTRUMENT_DB.map(x=>x.name);appState.instruments=names.map(n=>available.find(a=>a.toLowerCase().includes(n.toLowerCase()))).filter(Boolean).slice(0,5);if(typeof renderDynamicLists==="function")renderDynamicLists();}}
 function applySimple(){const preset=document.querySelector("[data-simple-preset].active")?.dataset.simplePreset;if(preset&&preset!=="custom"&&typeof quickPreset==="function")quickPreset(preset);const g=$("simpleGenre");if(g&&$("genreFamily")){ $("genreFamily").value=g.value;$("genreFamily").dispatchEvent(new Event("change",{bubbles:true}));}applyVoice($("simpleVoice").value);applyMood($("simpleMood").value);applyTempo($("simpleTempo").value);applyPalette($("simpleInstrumentPalette").value);if(typeof renderKnowledgeSuggestions==="function")renderKnowledgeSuggestions();if(typeof generateOutput==="function")generateOutput();score();if(typeof showToast==="function")showToast("Smart Prompt erstellt");}
 function syncSimpleFromAdvanced(){fillGenres();if($("simpleGenre")&&$("genreFamily"))$("simpleGenre").value=$("genreFamily").value;}
 function rand(a){return a[Math.floor(Math.random()*a.length)]}
 function setPreset(v){document.querySelectorAll("[data-simple-preset]").forEach(b=>b.classList.toggle("active",b.dataset.simplePreset===v));}
 function randomize(all){if(all||$("simpleRandomSongType").checked)setPreset(rand(choices.songTypes.filter(x=>x!=="custom")));if(all||$("simpleRandomGenre").checked){const s=$("simpleGenre");if(s?.options.length)s.selectedIndex=Math.floor(Math.random()*s.options.length)}if(all||$("simpleRandomVoice").checked)$("simpleVoice").value=rand(choices.voices);if(all||$("simpleRandomMood").checked)$("simpleMood").value=rand(choices.moods.filter(x=>all?x!=="none":true));if(all||$("simpleRandomInstruments").checked)$("simpleInstrumentPalette").value=rand(choices.palettes.filter(x=>all?x!=="none":true));if(all||$("simpleRandomTempo").checked)$("simpleTempo").value=rand(choices.tempos);applySimple();}
 function score(){let s=72;const preset=document.querySelector("[data-simple-preset].active")?.dataset.simplePreset;const mood=$("simpleMood")?.value,pal=$("simpleInstrumentPalette")?.value,temp=$("simpleTempo")?.value;if(preset)s+=5;if(mood&&mood!=="none")s+=5;if(pal&&pal!=="none")s+=6;if(temp==="auto")s+=5;if((preset==="viking"&&pal==="nordic")||(preset==="anime"&&pal==="japanese")||(preset==="edm"&&pal==="electronic")||(preset==="cinematic"&&pal==="orchestral")||(preset==="metalcore"&&pal==="rock"))s+=7;if(preset==="metalcore"&&mood==="dreamy")s-=5;if(preset==="lofi"&&temp==="veryfast")s-=9;s=Math.max(45,Math.min(99,s));$("simpleQualityValue").textContent=s+"%";$("simpleQualityBar").style.width=s+"%";$("simpleQualityHint").textContent=s>=92?"Sehr stimmige Kombination – bereit für Suno.":s>=82?"Gute Kombination mit kreativem Spielraum.":"Experimentelle Mischung – kann überraschende Ergebnisse liefern.";}
 function reset(){setPreset("custom");if($("simpleGenre"))$("simpleGenre").selectedIndex=0;$("simpleVoice").value="female";$("simpleTempo").value="medium";$("simpleMood").value="none";$("simpleInstrumentPalette").value="none";score();}
 function init(){if(!$("simpleModeButton"))return;fillGenres();$("simpleModeButton").onclick=()=>setMode("simple");$("advancedModeButton").onclick=()=>setMode("advanced");document.querySelectorAll("[data-simple-preset]").forEach(b=>b.onclick=()=>{setPreset(b.dataset.simplePreset);score()});["simpleGenre","simpleVoice","simpleTempo","simpleMood","simpleInstrumentPalette"].forEach(id=>$(id)?.addEventListener("change",score));$("simpleGenerate").onclick=applySimple;$("simpleRandomize").onclick=()=>randomize(false);$("simpleSurprise").onclick=()=>randomize(true);$("simpleReset").onclick=reset;setPreset("custom");setMode(localStorage.getItem(STORE)||"advanced");}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
