
(function(){
'use strict';
const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),uniq=a=>[...new Set(a.filter(Boolean))];
const TEMPLATES={
 'Anime Opening':['Intro','Verse 1','Pre-Chorus','Chorus','Instrumental','Verse 2','Bridge','Final Chorus','Outro'],
 'Classic Song':['Intro','Verse 1','Chorus','Verse 2','Chorus','Bridge','Final Chorus','Outro'],
 'Viking Epic':['Atmospheric Intro','Verse 1','Chant','Chorus','Instrumental','Verse 2','War Build','Final Chorus','Outro'],
 'Rap Song':['Intro','Verse 1','Hook','Verse 2','Hook','Bridge','Final Hook','Outro'],
 'EDM Track':['Intro','Build','Drop','Break','Second Build','Second Drop','Outro'],
 'Cinematic Build':['Ambient Intro','Movement I','Build','Climax','Quiet Passage','Finale','Outro'],
 'Metalcore Breakdown':['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Breakdown','Bridge','Final Chorus','Outro'],
 'Electro Swing':['Vintage Intro','Verse 1','Chorus','Brass Break','Verse 2','Dance Break','Final Chorus','Outro'],
 'Ballad':['Piano Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Bridge','Final Chorus','Outro'],
 'Game Boss Theme':['Omen Intro','Phase I','Escalation','Phase II','Break','Final Phase','Victory Coda']
};
const PRESET_INFO={
 'Anime Opening':'Fast, emotional and chorus-driven','Classic Song':'Balanced familiar structure','Viking Epic':'Chants, builds and mythic finale',
 'Rap Song':'Verse and hook focus','EDM Track':'Build-and-drop arrangement','Cinematic Build':'Large dynamic arc',
 'Metalcore Breakdown':'Heavy contrast and breakdown','Electro Swing':'Vintage sections with dance energy','Ballad':'Emotional gradual build','Game Boss Theme':'Multi-phase dramatic escalation'
};
const VOCALS=['Instrumental','Lead Vocal','Female Lead Vocal','Male Lead Vocal','Rap Vocal','Deep Male Spoken','Choir','Gang Shouts','Duet','Ethereal Vocal'];
const DYNAMICS=['Soft and Intimate','Restrained','Gradual Build','Driving','Powerful','Explosive','Breakdown Weight','Massive Crescendo','Calm Resolution'];
const TRANSITIONS=['Direct Cut','Short Fill','Riser','Drum Fill','Cymbal Swell','Silence Break','Reverse Effect','Key Change','Crossfade','Hard Stop'];
const INSTRUMENT_SETS=['Piano','Electric Guitar','Heavy Rhythm Guitar','Strings','Orchestra','Synthesizer','Tagelharpa','Brass Section','Electronic Drums','Acoustic Drums','Cinematic Percussion','Choir','Deep Bass','War Horns'];
let current=[],selectedId=null,dragId=null,nextId=1;
function fmt(sec){sec=Math.max(0,Math.round(sec));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function fromLyrics(){const t=$('lyricsEditor')?.value||$('lyricsOutput')?.value||'';if(window.NSWMetaTagStackEngine)return window.NSWMetaTagStackEngine.parseLyrics(t).sections.map(section=>section.stack.section);return[...t.matchAll(/^\s*\[([^\]]+)\]\s*$/gm)].map(m=>m[1]).filter(x=>/intro|verse|chorus|bridge|drop|build|outro|hook|solo|break|final|movement|instrumental|chant|phase|coda/i.test(x))}
function role(name){const n=name.toLowerCase();if(/chorus|hook|drop|climax|final|phase ii|final phase/.test(n))return'Peak';if(/intro|outro|coda|quiet|break/.test(n))return'Transition';return'Development'}
function vocal(name){const n=name.toLowerCase();if(/instrumental|drop|break|solo|intro|outro|coda|movement/.test(n))return'Instrumental';if(/chant/.test(n))return'Choir';if(/rap|verse/.test(n)&&/rap/i.test($('bpTemplate').value))return'Rap Vocal';return'Lead Vocal'}
function instruments(name){const n=name.toLowerCase(),template=$('bpTemplate').value;let x=[];if(/viking/i.test(template))x=['Tagelharpa','Cinematic Percussion','War Horns'];else if(/anime/i.test(template))x=['Electric Guitar','Strings','Synthesizer'];else if(/edm/i.test(template))x=['Synthesizer','Electronic Drums','Deep Bass'];else if(/electro swing/i.test(template))x=['Brass Section','Piano','Deep Bass'];else if(/metalcore/i.test(template))x=['Heavy Rhythm Guitar','Acoustic Drums','Deep Bass'];else if(/cinematic|boss/i.test(template))x=['Orchestra','Cinematic Percussion','Choir'];else if(/ballad/i.test(template))x=['Piano','Strings'];else x=['Piano','Acoustic Drums'];if(/intro|quiet|break/.test(n))x=x.slice(0,2);return x}
function baseEnergy(name,i,total){const shape=$('bpEnergyShape').value,t=total<=1?0:i/(total-1),peak=/chorus|hook|drop|climax|final|phase ii|final phase/.test(name.toLowerCase());let e=50;if(shape==='build')e=25+t*60;if(shape==='waves')e=45+Math.sin(t*Math.PI*4)*22+t*18;if(shape==='early')e=35+Math.sin(Math.min(1,t*1.5)*Math.PI)*55;if(shape==='late')e=22+Math.pow(t,1.8)*72;if(shape==='constant')e=75+(i%2?8:0);if(shape==='cinematic')e=20+Math.sin(t*Math.PI)*48+t*28;if(peak)e+=12;if(/intro|quiet|break|outro|coda/.test(name.toLowerCase()))e-=15;return clamp(Math.round(e),8,100)}
function durations(names,total){const weights=names.map(n=>/verse|movement|phase/i.test(n)?1.25:/chorus|hook|drop|climax|final/i.test(n)?1.05:/intro|outro|break|build|pre-chorus|coda/i.test(n)?.7:1),sum=weights.reduce((a,b)=>a+b,0);return weights.map(w=>Math.max(8,Math.round(total*w/sum)))}
function generate(names){
 const total=Number($('bpTargetDuration').value),durs=durations(names,total);
 current=names.map((name,i)=>({id:nextId++,name,duration:durs[i],energy:baseEnergy(name,i,names.length),vocal:vocal(name),instruments:instruments(name),dynamics:/final|climax|drop|chorus|hook/i.test(name)?'Powerful':/intro|quiet|outro/i.test(name)?'Soft and Intimate':'Gradual Build',transition:i===names.length-1?'Hard Stop':/build|pre-chorus/i.test(name)?'Riser':'Short Fill',role:role(name)}));selectedId=current[0]?.id||null;render()
}
function create(){let names=[];if($('bpSource').value==='lyrics')names=fromLyrics();if($('bpSource').value==='template'||!names.length)names=TEMPLATES[$('bpTemplate').value];if($('bpSource').value==='blank')names=['Intro','Verse 1','Chorus','Outro'];generate([...names]);$('bpStatus').textContent=`Blueprint created with ${current.length} sections.`}
function startTimes(){let n=0;return current.map(x=>{const s=n;n+=x.duration;return s})}
function totalDuration(){return current.reduce((a,b)=>a+Number(b.duration||0),0)}
function renderTimeline(){
 const total=Math.max(1,totalDuration()),zoom=Number($('bpZoom').value)/100,starts=startTimes();
 $('bpTimeline').innerHTML=current.map((x,i)=>`<article draggable="true" class="blueprint2-block ${selectedId===x.id?'active':''}" data-id="${x.id}" style="width:${Math.max(92,x.duration/total*850*zoom)}px"><b>${x.name}</b><small>${fmt(starts[i])}–${fmt(starts[i]+x.duration)} · ${x.energy}%</small><div class="blueprint2-block-tools"><button data-move="-1" title="Move left">←</button><button data-move="1" title="Move right">→</button><button data-delete="1" title="Delete">×</button></div><div class="blueprint2-block-energy"><i style="width:${x.energy}%"></i></div></article>`).join('');
 document.querySelectorAll('.blueprint2-block').forEach(el=>{
  el.onclick=e=>{if(e.target.closest('button'))return;selectedId=Number(el.dataset.id);renderTimeline();renderInspector()};
  el.ondragstart=()=>{dragId=Number(el.dataset.id);el.classList.add('dragging')};el.ondragend=()=>{dragId=null;el.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'))};
  el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over')};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();el.classList.remove('drag-over');const target=Number(el.dataset.id);if(dragId&&target!==dragId){const from=current.findIndex(x=>x.id===dragId),to=current.findIndex(x=>x.id===target),[item]=current.splice(from,1);current.splice(to,0,item);render()}};
 });
 document.querySelectorAll('[data-move]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=Number(b.closest('[data-id]').dataset.id),i=current.findIndex(x=>x.id===id),to=i+Number(b.dataset.move);if(to>=0&&to<current.length){[current[i],current[to]]=[current[to],current[i]];render()}});
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=Number(b.closest('[data-id]').dataset.id);current=current.filter(x=>x.id!==id);if(selectedId===id)selectedId=current[0]?.id||null;render()});
 const marks=6;$('bpRuler').innerHTML=Array.from({length:marks+1},(_,i)=>`<span class="blueprint2-ruler-mark" style="left:${i/marks*100}%">${fmt(total*i/marks)}</span>`).join('')
}
function renderChart(){
 const w=1000,h=230,pad=30,total=Math.max(1,totalDuration()),starts=startTimes(),pts=current.map((x,i)=>({x:pad+(starts[i]+x.duration/2)/total*(w-pad*2),y:h-pad-x.energy/100*(h-pad*2),s:x}));if(!pts.length){$('bpEnergyChart').innerHTML='';return}
 const line=pts.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+','+p.y.toFixed(1)).join(' '),area=`M${pts[0].x},${h-pad} `+pts.map(p=>`L${p.x},${p.y}`).join(' ')+` L${pts[pts.length-1].x},${h-pad} Z`;
 $('bpEnergyChart').innerHTML=`<defs><linearGradient id="bpGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#66e5d0" stop-opacity=".55"/><stop offset="100%" stop-color="#5d7cff" stop-opacity=".04"/></linearGradient></defs><path d="${area}" fill="url(#bpGrad)"/><path d="${line}" fill="none" stroke="#8debd8" stroke-width="4" vector-effect="non-scaling-stroke"/>${pts.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="6" fill="#e8fff9"><title>${p.s.name}: ${p.s.energy}%</title></circle>`).join('')}`;
 const peak=current.slice().sort((a,b)=>b.energy-a.energy)[0];$('bpPeakLabel').textContent=`Peak: ${peak?.name||'—'} · ${peak?.energy||0}%`
}
function optionList(a,v){return a.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}
function renderInspector(){
 const x=current.find(y=>y.id===selectedId),h=$('bpInspector');if(!x){h.innerHTML='<div class="blueprint2-inspector-empty"><span>🧩</span><h3>Select a section</h3><p>Edit its complete arrangement DNA.</p></div>';return}
 h.innerHTML=`<h3>🧩 Section DNA</h3><div class="blueprint2-inspector-grid"><label class="full">Section Name<input id="bpEditName" value="${escapeHtml(x.name)}"></label><label>Duration (sec)<input id="bpEditDuration" type="number" min="4" max="180" value="${x.duration}"></label><label>Energy<input id="bpEditEnergy" type="range" min="0" max="100" value="${x.energy}"><span id="bpEditEnergyValue">${x.energy}%</span></label><label>Vocal Role<select id="bpEditVocal">${optionList(VOCALS,x.vocal)}</select></label><label>Dynamics<select id="bpEditDynamics">${optionList(DYNAMICS,x.dynamics)}</select></label><label>Transition<select id="bpEditTransition">${optionList(TRANSITIONS,x.transition)}</select></label><label>Section Role<select id="bpEditRole">${optionList(['Introduction','Development','Build','Peak','Breakdown','Transition','Resolution'],x.role)}</select></label><label class="full">Instruments<input id="bpEditInstruments" value="${escapeHtml(x.instruments.join(', '))}" placeholder="Piano, Strings, Drums"></label></div><div class="blueprint2-inspector-actions"><button id="bpDuplicateSection">Duplicate</button><button id="bpDeleteSection">Delete</button><button class="primary" id="bpSaveSection">Save Section</button></div>`;
 $('bpEditEnergy').oninput=e=>$('bpEditEnergyValue').textContent=e.target.value+'%';$('bpSaveSection').onclick=()=>{x.name=$('bpEditName').value.trim()||x.name;x.duration=clamp(Number($('bpEditDuration').value),4,180);x.energy=clamp(Number($('bpEditEnergy').value));x.vocal=$('bpEditVocal').value;x.dynamics=$('bpEditDynamics').value;x.transition=$('bpEditTransition').value;x.role=$('bpEditRole').value;x.instruments=uniq($('bpEditInstruments').value.split(',').map(s=>s.trim()));render();$('bpStatus').textContent=`${x.name} updated.`};$('bpDeleteSection').onclick=()=>{current=current.filter(y=>y.id!==x.id);selectedId=current[0]?.id||null;render()};$('bpDuplicateSection').onclick=()=>{const i=current.findIndex(y=>y.id===x.id),copy={...x,id:nextId++,name:x.name+' Copy',instruments:[...x.instruments]};current.splice(i+1,0,copy);selectedId=copy.id;render()}
}
function analyze(){
 const total=totalDuration(),energies=current.map(x=>x.energy),avg=energies.length?energies.reduce((a,b)=>a+b,0)/energies.length:0,peaks=current.filter(x=>x.energy>=80),instrumental=current.filter(x=>x.vocal==='Instrumental').length,vocalChanges=current.slice(1).filter((x,i)=>x.vocal!==current[i].vocal).length;
 const warnings=[],rec=[];if(current.length<5)warnings.push('The structure is very short and may feel underdeveloped.');if(current.length>12)warnings.push('Many sections may make the arrangement difficult to follow.');if(!current.some(x=>/chorus|hook|drop|climax|final/i.test(x.name)))warnings.push('No obvious main peak section is labelled.');if(peaks.length>Math.max(3,current.length*.45))warnings.push('Too many high-energy sections reduce contrast.');if(Math.max(...energies,0)-Math.min(...energies,100)<25)warnings.push('The energy curve has little contrast.');if(total<Number($('bpTargetDuration').value)-15||total>Number($('bpTargetDuration').value)+15)warnings.push('Total duration differs noticeably from the selected target.');if(instrumental===0)rec.push('Consider one instrumental or breathing section.');if(vocalChanges===0&&current.length>5)rec.push('A vocal-role change could improve contrast.');if(!current.some(x=>/bridge|break|quiet|breakdown/i.test(x.name)))rec.push('A contrasting bridge or break can strengthen the final peak.');if(current.some(x=>x.instruments.length>6))rec.push('One or more sections contain many instruments; simplify the palette.');if(!rec.length)rec.push('The arrangement has a clear structure and useful contrast.');
 const durationFit=clamp(100-Math.abs(total-Number($('bpTargetDuration').value))*1.5),contrast=clamp((Math.max(...energies,0)-Math.min(...energies,100))*1.4),structure=clamp(55+(current.length>=6&&current.length<=10?25:0)+(current.some(x=>/chorus|hook|drop|climax|final/i.test(x.name))?20:0)),clarity=clamp(100-warnings.length*12-current.filter(x=>x.instruments.length>6).length*7),score=Math.round((durationFit+contrast+structure+clarity)/4);
 $('bpScore').textContent=score;$('bpScoreBar').style.width=score+'%';$('bpStatusBadge').textContent=`${current.length} sections · ${fmt(total)} · local blueprint`;
 $('bpSummary').innerHTML=[['Sections',current.length],['Total Duration',fmt(total)],['Average Energy',Math.round(avg)+'%'],['Peak Sections',peaks.length],['Instrumental',instrumental],['Vocal Changes',vocalChanges]].map(([a,b])=>`<div class="blueprint2-summary-item"><small>${a}</small><b>${b}</b></div>`).join('');
 $('bpWarnings').innerHTML=(warnings.length?warnings:['No major arrangement issues detected.']).map(x=>`<div class="blueprint2-message ${warnings.length?'warn':'good'}">${x}</div>`).join('');$('bpRecommendations').innerHTML=rec.map(x=>`<div class="blueprint2-message info">${x}</div>`).join('');return{score,warnings,rec}
}
function renderTable(){const starts=startTimes();$('bpTableBody').innerHTML=current.map((x,i)=>`<tr data-table-id="${x.id}"><td>${fmt(starts[i])}–${fmt(starts[i]+x.duration)}</td><td>${escapeHtml(x.name)}</td><td>${x.duration}s</td><td>${x.energy}%</td><td>${escapeHtml(x.vocal)}</td><td>${escapeHtml(x.instruments.join(', ')||'—')}</td><td>${escapeHtml(x.dynamics)}</td><td>${escapeHtml(x.transition)}</td></tr>`).join('');document.querySelectorAll('[data-table-id]').forEach(r=>r.onclick=()=>{selectedId=Number(r.dataset.tableId);renderTimeline();renderInspector()})}
function blueprintDirectives(x){return[x.vocal,x.instruments.join(', '),x.dynamics,`Energy ${x.energy}%`,x.transition,x.role]}
function pipeDocument(){const engine=window.NSWMetaTagStackEngine;return current.map(x=>engine?engine.createStack(x.name,blueprintDirectives(x),{sort:true}).line:`[${[x.name,...blueprintDirectives(x)].join(' | ')}]`).join('\n\n')}
function render(){renderTimeline();renderChart();renderInspector();renderTable();const report=analyze();$('bpDurationBadge').textContent=`${fmt(totalDuration())} total`;legacy();window.NSW_SONG_BLUEPRINT_LAST={template:$('bpTemplate').value,duration:totalDuration(),sections:JSON.parse(JSON.stringify(current)),pipeStacks:pipeDocument(),score:report.score,updatedAt:Date.now()}}
function legacy(){$('bpMap').innerHTML=current.map(x=>`<div>${x.name} · ${x.energy}%</div>`).join('');$('bpEnergy').innerHTML=current.map(x=>`<span style="height:${x.energy}%"></span>`).join('')}
function normalize(){const target=Number($('bpTargetDuration').value),sum=Math.max(1,totalDuration()),raw=current.map(x=>Math.max(4,Math.round(x.duration*target/sum))),diff=target-raw.reduce((a,b)=>a+b,0);if(raw.length)raw[raw.length-1]+=diff;current.forEach((x,i)=>x.duration=Math.max(4,raw[i]));render();$('bpStatus').textContent=`Duration normalized to ${fmt(target)}.`}
function addSection(){const x={id:nextId++,name:'New Section',duration:20,energy:50,vocal:'Lead Vocal',instruments:['Piano'],dynamics:'Gradual Build',transition:'Short Fill',role:'Development'};current.push(x);selectedId=x.id;render()}
function summaryText(){const starts=startTimes();return[`SONG BLUEPRINT`,`Template: ${$('bpTemplate').value}`,`Total duration: ${fmt(totalDuration())}`,'',...current.map((x,i)=>`${fmt(starts[i])}–${fmt(starts[i]+x.duration)} | ${x.name} | ${x.energy}% | ${x.vocal} | ${x.instruments.join(', ')} | ${x.dynamics} | ${x.transition}`)].join('\n')}
async function copyText(t){try{await navigator.clipboard.writeText(t)}catch(e){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}}
function download(name,text,type='text/plain'){const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function applyLyrics(){const e=$('lyricsEditor');if(!e||!current.length)return;const engine=window.NSWMetaTagStackEngine,document=pipeDocument();e.value=engine?engine.mergeStackDocument(e.value,document).text:e.value.trim()?`${e.value.trim()}\n\n${document}`:document;e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof showToast==='function')showToast('Blueprint Pipe-Stacks applied to Lyrics Workspace.')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderPresets(){$('bpPresetCount').textContent=`${Object.keys(TEMPLATES).length} presets`;$('bpPresetGrid').innerHTML=Object.keys(TEMPLATES).map(x=>`<button class="blueprint2-preset-card" data-bp-preset="${x}"><b>${x}</b><small>${PRESET_INFO[x]}</small></button>`).join('');document.querySelectorAll('[data-bp-preset]').forEach(b=>b.onclick=()=>{$('bpTemplate').value=b.dataset.bpPreset;$('bpSource').value='template';generate([...TEMPLATES[b.dataset.bpPreset]]);$('bpStatus').textContent=`${b.dataset.bpPreset} preset applied.`})}
function init(){
 if(!$('bpGenerate'))return;renderPresets();$('bpGenerate').onclick=create;$('bpAddSection').onclick=addSection;$('bpNormalize').onclick=normalize;$('bpReset').onclick=create;$('bpZoom').oninput=renderTimeline;$('bpEnergyShape').onchange=()=>{current.forEach((x,i)=>x.energy=baseEnergy(x.name,i,current.length));render()};$('bpTargetDuration').onchange=normalize;
 $('bpCopySummary').onclick=async()=>{await copyText(summaryText());if(typeof showToast==='function')showToast('Blueprint summary copied.')};$('bpExport').onclick=()=>download('song-blueprint.json',JSON.stringify({template:$('bpTemplate').value,targetDuration:Number($('bpTargetDuration').value),sections:current},null,2),'application/json');$('bpExportTxt').onclick=()=>download('song-blueprint.txt',summaryText());$('bpApplyLyrics').onclick=applyLyrics;create()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
