const STORY_LIBRARY = {
  "worlds": {
    "Fantasy": [
      "High Fantasy",
      "Dark Fantasy",
      "Low Fantasy",
      "Grimdark",
      "Heroic Fantasy",
      "Sword and Sorcery",
      "Magic Academy",
      "Ancient Kingdom",
      "Lost Empire",
      "Floating Kingdoms",
      "Crystal Civilization",
      "Dragon Empire",
      "Elven Forest",
      "Dwarven Kingdom",
      "Shadow Realm",
      "Demon Realm",
      "Angelic Kingdom",
      "Necromancer Lands",
      "Elemental World",
      "Monster Hunter World",
      "Dungeon World",
      "Isekai World",
      "JRPG World",
      "MMORPG World",
      "Soulslike Kingdom",
      "Enchanted Forest",
      "Cursed Castle",
      "Forgotten Ruins",
      "Arcane City",
      "Mage Republic",
      "Witch Coven Lands",
      "Fairy Kingdom",
      "Giant Realm",
      "Underworld",
      "Celestial Realm",
      "Clockwork Fantasy",
      "Desert Fantasy",
      "Frozen Fantasy Kingdom",
      "Ocean Fantasy",
      "Sky Islands",
      "Dream Kingdom",
      "Nightmare Realm",
      "Portal Fantasy",
      "Mythical Beast Sanctuary",
      "Forbidden Library",
      "Ancient Prophecy World",
      "Royal Court Fantasy",
      "Rebel Kingdom",
      "Holy Empire",
      "Corrupted Empire"
    ],
    "Sci-Fi & Future": [
      "Cyberpunk Megacity",
      "Space Opera",
      "Galactic War",
      "AI Apocalypse",
      "Robot Uprising",
      "Alien Invasion",
      "Colony Planet",
      "Time Travel",
      "Multiverse",
      "Parallel Earth",
      "Post-Human Society",
      "Nanotech Future",
      "Space Exploration",
      "Lost Spaceship",
      "Deep Space Horror",
      "Neon City",
      "Android Society",
      "Interstellar Empire",
      "Dyson Sphere Civilization",
      "Terraforming Frontier",
      "Quantum Reality",
      "Virtual Reality World",
      "Simulation Prison",
      "Mars Colony",
      "Lunar City",
      "Generation Ship",
      "Alien Ocean Planet",
      "Cosmic Horror",
      "Biopunk Future",
      "Solarpunk Utopia",
      "Dieselpunk Future",
      "Atompunk World",
      "Retro-Futurism",
      "Mecha War",
      "Kaiju Defense Force",
      "Starship Academy",
      "Galactic Rebellion",
      "Space Pirates",
      "Wormhole Network",
      "First Contact",
      "Cybernetic Underworld",
      "Orbital Station",
      "Planetary Civil War",
      "Machine Consciousness",
      "Synthetic Eden",
      "Dark Matter Realm",
      "Cryogenic Ark",
      "Exoplanet Jungle",
      "Asteroid Mining Colony",
      "Post-Singularity World"
    ],
    "Historical & Cultural": [
      "Viking Age",
      "Samurai Era",
      "Medieval Europe",
      "Roman Empire",
      "Ancient Greece",
      "Ancient Egypt",
      "Persian Empire",
      "Celtic World",
      "Mongol Empire",
      "Pirate Age",
      "Wild West",
      "Renaissance Italy",
      "Napoleonic Era",
      "Victorian London",
      "Feudal Japan",
      "Three Kingdoms China",
      "Silk Road",
      "Aztec Empire",
      "Maya Civilization",
      "Inca Empire",
      "Ottoman Empire",
      "Byzantine Empire",
      "Ancient Mesopotamia",
      "Spartan City-State",
      "Crusader Kingdom",
      "Age of Exploration",
      "Industrial Revolution",
      "Belle Époque",
      "Roaring Twenties",
      "Prohibition Era",
      "World War Resistance",
      "Cold War Espionage",
      "Ancient India",
      "Polynesian Voyagers",
      "African Kingdoms",
      "Caribbean Colonial Era",
      "Hanseatic Cities",
      "Germanic Tribes",
      "Slavic Folklore Lands",
      "Arabian Golden Age"
    ],
    "Anime & Game": [
      "High School Anime",
      "Magic School Anime",
      "Isekai Adventure",
      "Shonen Battle World",
      "Seinen Dark World",
      "Shojo Romance World",
      "Mecha Academy",
      "Idol Industry",
      "Monster Tamer World",
      "Card Battle World",
      "Tournament Arc",
      "Dungeon Crawler",
      "Guild Adventure",
      "Visual Novel World",
      "Dating Sim World",
      "Survival Game",
      "Battle Royale",
      "Virtual MMO",
      "Gacha Fantasy",
      "JRPG Kingdom",
      "Tactical RPG War",
      "Roguelike Dungeon",
      "Soulslike Ruins",
      "Cozy Farming World",
      "Anime Sports Academy",
      "Superhero Academy",
      "Demon Slayer World",
      "Spirit Detective World",
      "Magical Girl City",
      "Cyber Anime World",
      "Post-Apocalyptic Anime",
      "Anime Music Academy",
      "Delinquent School",
      "Ninja Clan World",
      "Pirate Anime Seas",
      "Dragon Rider Academy",
      "Alchemy Kingdom",
      "Summoner Academy",
      "Martial Arts Sect",
      "Reverse Isekai City"
    ],
    "Modern & Crime": [
      "Modern Metropolis",
      "Small Town Drama",
      "K-Drama School",
      "Corporate Thriller",
      "Mafia Underworld",
      "Detective Noir",
      "Street Racing",
      "Formula Racing",
      "Football Championship",
      "Military Base",
      "Secret Agent Network",
      "Survival Wilderness",
      "Zombie Outbreak",
      "Hospital Drama",
      "Love Story City",
      "Psychological Horror House",
      "Courtroom Drama",
      "Prison Story",
      "Heist Crew",
      "Gang Territory",
      "Underground Fight Club",
      "Music Industry",
      "Rock Band Tour",
      "Nightclub Scene",
      "Urban Legends",
      "Political Conspiracy",
      "Tech Startup",
      "Celebrity Scandal",
      "Firefighter Unit",
      "Police Procedural",
      "Rescue Mission",
      "Mountain Expedition",
      "Arctic Research Station",
      "Desert Rally",
      "Cruise Ship Mystery",
      "Theme Park Horror",
      "Suburban Nightmare",
      "Road Trip",
      "Festival Summer",
      "Post-Pandemic Society"
    ],
    "Horror & Supernatural": [
      "Haunted Mansion",
      "Gothic Village",
      "Vampire Kingdom",
      "Werewolf Territory",
      "Demon-Infested City",
      "Lovecraftian Coast",
      "Cursed Forest",
      "Abandoned Asylum",
      "Ghost Ship",
      "Zombie Wasteland",
      "Occult Academy",
      "Witch Trial Village",
      "Possessed Cathedral",
      "Infernal City",
      "Limbo",
      "Purgatory",
      "Nightmare Dimension",
      "Backrooms Labyrinth",
      "Body Horror Laboratory",
      "Folk Horror Community",
      "Cosmic Cult",
      "Ancient Tomb",
      "Cursed Carnival",
      "Haunted Hotel",
      "Dollmaker Workshop",
      "Plague Town",
      "Silent Hillscape",
      "Monster Island",
      "Cryptid Forest",
      "Apocalyptic Rapture",
      "Demonic Court",
      "Vampire Masquerade",
      "Undead Empire",
      "Forbidden Ritual Site",
      "Shadow People City",
      "Sleep Paralysis Realm",
      "Mirror Dimension",
      "Blood Moon Village",
      "Graveyard Kingdom",
      "Eldritch Library"
    ],
    "Nature & Adventure": [
      "Oceanic Mystery",
      "Frozen North",
      "Volcanic Island",
      "Deep Jungle",
      "Ancient Desert",
      "Mountain Kingdom",
      "Underwater Civilization",
      "Lost Island",
      "Stormy Archipelago",
      "Endless Steppe",
      "Sacred Valley",
      "Crystal Caves",
      "Underground Sea",
      "Floating Reef",
      "Arctic Expedition",
      "Amazon Adventure",
      "Sahara Caravan",
      "Himalayan Monastery",
      "Wild River Journey",
      "Prehistoric World",
      "Dinosaur Island",
      "Giant Forest",
      "Mushroom Kingdom",
      "Coral City",
      "Whale Migration",
      "Deserted Coast",
      "Moonlit Lake",
      "Autumn Village",
      "Eternal Winter",
      "Endless Summer",
      "Thunder Plains",
      "Aurora Kingdom",
      "Toxic Swamp",
      "Sacred Grove",
      "Hidden Waterfall",
      "Skyship Voyage",
      "Polar Night",
      "Monsoon City",
      "Earthquake Zone",
      "Solar Storm Wilderness"
    ],
    "Thematic & Abstract": [
      "Dreamscape",
      "Memory Palace",
      "Emotional Inner World",
      "Musical Universe",
      "Color Kingdom",
      "Clockwork City",
      "Surrealist World",
      "Infinite Library",
      "Theater of Life",
      "Digital Memory",
      "Fractured Timeline",
      "Hall of Mirrors",
      "World Between Worlds",
      "Endless Staircase",
      "Living Painting",
      "Forgotten Childhood",
      "Collective Unconscious",
      "Time Loop City",
      "Afterlife Station",
      "Cosmic Courtroom",
      "Personified Emotions",
      "Seven Deadly Sins Realm",
      "Zodiac Kingdom",
      "Tarot World",
      "Seasonal Kingdoms",
      "Elemental Nations",
      "Music Festival Universe",
      "Battle of Ideas",
      "Language World",
      "Mathematical Dimension",
      "Chess Kingdom",
      "Dream Hotel",
      "Memory Train",
      "Soul Archive",
      "Celestial Orchestra",
      "Shadow of the Self",
      "World of Masks",
      "The Last Song",
      "Silent Universe",
      "Infinite Ocean"
    ],
    "Generated Epic Worlds": [
      "Ancient Kingdom",
      "Ancient Empire",
      "Ancient Citadel",
      "Ancient Forest",
      "Ancient Archipelago",
      "Ancient Metropolis",
      "Ancient Sanctuary",
      "Ancient Wasteland",
      "Ancient Academy",
      "Ancient Labyrinth",
      "Ancient Frontier",
      "Ancient Dimension",
      "Ancient Colony",
      "Ancient Republic",
      "Ancient Dynasty",
      "Forgotten Kingdom",
      "Forgotten Empire",
      "Forgotten Citadel",
      "Forgotten Forest",
      "Forgotten Archipelago",
      "Forgotten Metropolis",
      "Forgotten Sanctuary",
      "Forgotten Wasteland",
      "Forgotten Academy",
      "Forgotten Labyrinth",
      "Forgotten Frontier",
      "Forgotten Dimension",
      "Forgotten Colony",
      "Forgotten Republic",
      "Forgotten Dynasty",
      "Hidden Kingdom",
      "Hidden Empire",
      "Hidden Citadel",
      "Hidden Forest",
      "Hidden Archipelago",
      "Hidden Metropolis",
      "Hidden Sanctuary",
      "Hidden Wasteland",
      "Hidden Academy",
      "Hidden Labyrinth",
      "Hidden Frontier",
      "Hidden Dimension",
      "Hidden Colony",
      "Hidden Republic",
      "Hidden Dynasty",
      "Cursed Kingdom",
      "Cursed Empire",
      "Cursed Citadel",
      "Cursed Forest",
      "Cursed Archipelago",
      "Cursed Metropolis",
      "Cursed Sanctuary",
      "Cursed Wasteland",
      "Cursed Academy",
      "Cursed Labyrinth",
      "Cursed Frontier",
      "Cursed Dimension",
      "Cursed Colony",
      "Cursed Republic",
      "Cursed Dynasty",
      "Sacred Kingdom",
      "Sacred Empire",
      "Sacred Citadel",
      "Sacred Forest",
      "Sacred Archipelago",
      "Sacred Metropolis",
      "Sacred Sanctuary",
      "Sacred Wasteland",
      "Sacred Academy",
      "Sacred Labyrinth",
      "Sacred Frontier",
      "Sacred Dimension",
      "Sacred Colony",
      "Sacred Republic",
      "Sacred Dynasty",
      "Burning Kingdom",
      "Burning Empire",
      "Burning Citadel",
      "Burning Forest",
      "Burning Archipelago",
      "Burning Metropolis",
      "Burning Sanctuary",
      "Burning Wasteland",
      "Burning Academy",
      "Burning Labyrinth",
      "Burning Frontier",
      "Burning Dimension",
      "Burning Colony",
      "Burning Republic",
      "Burning Dynasty",
      "Frozen Kingdom",
      "Frozen Empire",
      "Frozen Citadel",
      "Frozen Forest",
      "Frozen Archipelago",
      "Frozen Metropolis",
      "Frozen Sanctuary",
      "Frozen Wasteland",
      "Frozen Academy",
      "Frozen Labyrinth",
      "Frozen Frontier",
      "Frozen Dimension",
      "Frozen Colony",
      "Frozen Republic",
      "Frozen Dynasty",
      "Shattered Kingdom",
      "Shattered Empire",
      "Shattered Citadel",
      "Shattered Forest",
      "Shattered Archipelago",
      "Shattered Metropolis",
      "Shattered Sanctuary",
      "Shattered Wasteland",
      "Shattered Academy",
      "Shattered Labyrinth",
      "Shattered Frontier",
      "Shattered Dimension",
      "Shattered Colony",
      "Shattered Republic",
      "Shattered Dynasty",
      "Eternal Kingdom",
      "Eternal Empire",
      "Eternal Citadel",
      "Eternal Forest",
      "Eternal Archipelago",
      "Eternal Metropolis",
      "Eternal Sanctuary",
      "Eternal Wasteland",
      "Eternal Academy",
      "Eternal Labyrinth",
      "Eternal Frontier",
      "Eternal Dimension",
      "Eternal Colony",
      "Eternal Republic",
      "Eternal Dynasty",
      "Lost Kingdom",
      "Lost Empire",
      "Lost Citadel",
      "Lost Forest",
      "Lost Archipelago",
      "Lost Metropolis",
      "Lost Sanctuary",
      "Lost Wasteland",
      "Lost Academy",
      "Lost Labyrinth",
      "Lost Frontier",
      "Lost Dimension",
      "Lost Colony",
      "Lost Republic",
      "Lost Dynasty",
      "Neon Kingdom",
      "Neon Empire",
      "Neon Citadel",
      "Neon Forest",
      "Neon Archipelago",
      "Neon Metropolis",
      "Neon Sanctuary",
      "Neon Wasteland",
      "Neon Academy",
      "Neon Labyrinth",
      "Neon Frontier",
      "Neon Dimension",
      "Neon Colony",
      "Neon Republic",
      "Neon Dynasty",
      "Celestial Kingdom",
      "Celestial Empire",
      "Celestial Citadel",
      "Celestial Forest",
      "Celestial Archipelago",
      "Celestial Metropolis",
      "Celestial Sanctuary",
      "Celestial Wasteland",
      "Celestial Academy",
      "Celestial Labyrinth",
      "Celestial Frontier",
      "Celestial Dimension",
      "Celestial Colony",
      "Celestial Republic",
      "Celestial Dynasty",
      "Infernal Kingdom",
      "Infernal Empire",
      "Infernal Citadel",
      "Infernal Forest",
      "Infernal Archipelago",
      "Infernal Metropolis",
      "Infernal Sanctuary",
      "Infernal Wasteland",
      "Infernal Academy",
      "Infernal Labyrinth",
      "Infernal Frontier",
      "Infernal Dimension",
      "Infernal Colony",
      "Infernal Republic",
      "Infernal Dynasty",
      "Twilight Kingdom",
      "Twilight Empire",
      "Twilight Citadel",
      "Twilight Forest",
      "Twilight Archipelago",
      "Twilight Metropolis",
      "Twilight Sanctuary",
      "Twilight Wasteland",
      "Twilight Academy",
      "Twilight Labyrinth",
      "Twilight Frontier",
      "Twilight Dimension",
      "Twilight Colony",
      "Twilight Republic",
      "Twilight Dynasty",
      "Obsidian Kingdom",
      "Obsidian Empire",
      "Obsidian Citadel",
      "Obsidian Forest",
      "Obsidian Archipelago",
      "Obsidian Metropolis",
      "Obsidian Sanctuary",
      "Obsidian Wasteland",
      "Obsidian Academy",
      "Obsidian Labyrinth",
      "Obsidian Frontier",
      "Obsidian Dimension",
      "Obsidian Colony",
      "Obsidian Republic",
      "Obsidian Dynasty",
      "Emerald Kingdom",
      "Emerald Empire",
      "Emerald Citadel",
      "Emerald Forest",
      "Emerald Archipelago",
      "Emerald Metropolis",
      "Emerald Sanctuary",
      "Emerald Wasteland",
      "Emerald Academy",
      "Emerald Labyrinth",
      "Emerald Frontier",
      "Emerald Dimension",
      "Emerald Colony",
      "Emerald Republic",
      "Emerald Dynasty",
      "Crimson Kingdom",
      "Crimson Empire",
      "Crimson Citadel",
      "Crimson Forest",
      "Crimson Archipelago",
      "Crimson Metropolis",
      "Crimson Sanctuary",
      "Crimson Wasteland",
      "Crimson Academy",
      "Crimson Labyrinth",
      "Crimson Frontier",
      "Crimson Dimension",
      "Crimson Colony",
      "Crimson Republic",
      "Crimson Dynasty",
      "Silver Kingdom",
      "Silver Empire",
      "Silver Citadel",
      "Silver Forest",
      "Silver Archipelago",
      "Silver Metropolis",
      "Silver Sanctuary",
      "Silver Wasteland",
      "Silver Academy",
      "Silver Labyrinth",
      "Silver Frontier",
      "Silver Dimension",
      "Silver Colony",
      "Silver Republic",
      "Silver Dynasty",
      "Golden Kingdom",
      "Golden Empire",
      "Golden Citadel",
      "Golden Forest",
      "Golden Archipelago",
      "Golden Metropolis",
      "Golden Sanctuary",
      "Golden Wasteland",
      "Golden Academy",
      "Golden Labyrinth",
      "Golden Frontier",
      "Golden Dimension",
      "Golden Colony",
      "Golden Republic",
      "Golden Dynasty",
      "Phantom Kingdom",
      "Phantom Empire",
      "Phantom Citadel",
      "Phantom Forest",
      "Phantom Archipelago",
      "Phantom Metropolis",
      "Phantom Sanctuary",
      "Phantom Wasteland",
      "Phantom Academy",
      "Phantom Labyrinth",
      "Phantom Frontier",
      "Phantom Dimension",
      "Phantom Colony",
      "Phantom Republic",
      "Phantom Dynasty"
    ]
  },
  "emotions": {
    "Positive": [
      "Hopeful",
      "Inspired",
      "Triumphant",
      "Joyful",
      "Relieved",
      "Determined",
      "Victorious",
      "Proud",
      "Brave",
      "Passionate",
      "Content",
      "Grateful",
      "Excited",
      "Optimistic",
      "Playful",
      "Confident",
      "Free",
      "Loved",
      "Peaceful",
      "Motivated",
      "Empowered",
      "Celebratory",
      "Curious",
      "Amazed",
      "Reborn",
      "Forgiving",
      "Trusting",
      "Tender",
      "Warmhearted",
      "Adventurous"
    ],
    "Dark": [
      "Despair",
      "Rage",
      "Vengeance",
      "Fear",
      "Madness",
      "Grief",
      "Loneliness",
      "Emptiness",
      "Obsession",
      "Betrayal",
      "Hatred",
      "Jealousy",
      "Guilt",
      "Shame",
      "Regret",
      "Hopelessness",
      "Panic",
      "Dread",
      "Paranoia",
      "Resentment",
      "Bitterness",
      "Numbness",
      "Alienation",
      "Humiliation",
      "Frustration",
      "Helplessness",
      "Terror",
      "Anguish",
      "Torment",
      "Corruption",
      "Bloodlust",
      "Cruelty",
      "Defeat",
      "Abandonment",
      "Mourning"
    ],
    "Mystical": [
      "Divine",
      "Ethereal",
      "Ancient",
      "Mysterious",
      "Sacred",
      "Arcane",
      "Dreamlike",
      "Haunting",
      "Otherworldly",
      "Celestial",
      "Prophetic",
      "Enchanted",
      "Spiritual",
      "Transcendent",
      "Ritualistic",
      "Cosmic",
      "Mythic",
      "Uncanny",
      "Hypnotic",
      "Magical",
      "Fateful",
      "Timeless",
      "Reverent",
      "Awestruck",
      "Supernatural"
    ],
    "Complex": [
      "Bittersweet",
      "Nostalgic",
      "Melancholic",
      "Conflicted",
      "Longing",
      "Yearning",
      "Ambivalent",
      "Wistful",
      "Reflective",
      "Stoic",
      "Defiant",
      "Resolute",
      "Vulnerable",
      "Intimate",
      "Suspicious",
      "Restless",
      "Anxious",
      "Overwhelmed",
      "Protective",
      "Devoted",
      "Possessive",
      "Rebellious",
      "Honorable",
      "Noble",
      "Solemn",
      "Dignified",
      "Romantic",
      "Seductive",
      "Fragile",
      "Cathartic"
    ],
    "High Energy": [
      "Aggressive",
      "Explosive",
      "Furious",
      "Ferocious",
      "Chaotic",
      "Relentless",
      "Adrenalized",
      "Wild",
      "Unstoppable",
      "Savage",
      "Heroic",
      "Epic",
      "Majestic",
      "Powerful",
      "Commanding",
      "Intense",
      "Urgent",
      "Driven",
      "Reckless",
      "Battle-ready",
      "Dominant",
      "Fearless",
      "Revolutionary",
      "Invincible",
      "Overpowered"
    ],
    "Calm": [
      "Calm",
      "Gentle",
      "Serene",
      "Soft",
      "Meditative",
      "Relaxed",
      "Dreamy",
      "Quiet",
      "Patient",
      "Comforting",
      "Soothing",
      "Sleepy",
      "Floating",
      "Weightless",
      "Minimal",
      "Delicate",
      "Innocent",
      "Pure",
      "Humble",
      "Grounded",
      "Organic",
      "Pastoral",
      "Cozy",
      "Safe",
      "Healing"
    ],
    "Nuanced Combinations": [
      "Deep Hope",
      "Deep Grief",
      "Deep Joy",
      "Deep Rage",
      "Deep Longing",
      "Deep Courage",
      "Deep Fear",
      "Deep Love",
      "Deep Pride",
      "Deep Sorrow",
      "Deep Wonder",
      "Deep Resolve",
      "Deep Desire",
      "Deep Peace",
      "Deep Rebellion",
      "Quiet Hope",
      "Quiet Grief",
      "Quiet Joy",
      "Quiet Rage",
      "Quiet Longing",
      "Quiet Courage",
      "Quiet Fear",
      "Quiet Love",
      "Quiet Pride",
      "Quiet Sorrow",
      "Quiet Wonder",
      "Quiet Resolve",
      "Quiet Desire",
      "Quiet Peace",
      "Quiet Rebellion",
      "Burning Hope",
      "Burning Grief",
      "Burning Joy",
      "Burning Rage",
      "Burning Longing",
      "Burning Courage",
      "Burning Fear",
      "Burning Love",
      "Burning Pride",
      "Burning Sorrow",
      "Burning Wonder",
      "Burning Resolve",
      "Burning Desire",
      "Burning Peace",
      "Burning Rebellion",
      "Frozen Hope",
      "Frozen Grief",
      "Frozen Joy",
      "Frozen Rage",
      "Frozen Longing",
      "Frozen Courage",
      "Frozen Fear",
      "Frozen Love",
      "Frozen Pride",
      "Frozen Sorrow",
      "Frozen Wonder",
      "Frozen Resolve",
      "Frozen Desire",
      "Frozen Peace",
      "Frozen Rebellion",
      "Hidden Hope",
      "Hidden Grief",
      "Hidden Joy",
      "Hidden Rage",
      "Hidden Longing",
      "Hidden Courage",
      "Hidden Fear",
      "Hidden Love",
      "Hidden Pride",
      "Hidden Sorrow",
      "Hidden Wonder",
      "Hidden Resolve",
      "Hidden Desire",
      "Hidden Peace",
      "Hidden Rebellion",
      "Sudden Hope",
      "Sudden Grief",
      "Sudden Joy",
      "Sudden Rage",
      "Sudden Longing",
      "Sudden Courage",
      "Sudden Fear",
      "Sudden Love",
      "Sudden Pride",
      "Sudden Sorrow",
      "Sudden Wonder",
      "Sudden Resolve",
      "Sudden Desire",
      "Sudden Peace",
      "Sudden Rebellion",
      "Unspoken Hope",
      "Unspoken Grief",
      "Unspoken Joy",
      "Unspoken Rage",
      "Unspoken Longing",
      "Unspoken Courage",
      "Unspoken Fear",
      "Unspoken Love",
      "Unspoken Pride",
      "Unspoken Sorrow",
      "Unspoken Wonder",
      "Unspoken Resolve",
      "Unspoken Desire",
      "Unspoken Peace",
      "Unspoken Rebellion",
      "Endless Hope",
      "Endless Grief",
      "Endless Joy",
      "Endless Rage",
      "Endless Longing",
      "Endless Courage",
      "Endless Fear",
      "Endless Love",
      "Endless Pride",
      "Endless Sorrow",
      "Endless Wonder",
      "Endless Resolve",
      "Endless Desire",
      "Endless Peace",
      "Endless Rebellion",
      "Fragile Hope",
      "Fragile Grief",
      "Fragile Joy",
      "Fragile Rage",
      "Fragile Longing",
      "Fragile Courage",
      "Fragile Fear",
      "Fragile Love",
      "Fragile Pride",
      "Fragile Sorrow",
      "Fragile Wonder",
      "Fragile Resolve",
      "Fragile Desire",
      "Fragile Peace",
      "Fragile Rebellion",
      "Fierce Hope",
      "Fierce Grief",
      "Fierce Joy",
      "Fierce Rage",
      "Fierce Longing",
      "Fierce Courage",
      "Fierce Fear",
      "Fierce Love",
      "Fierce Pride",
      "Fierce Sorrow",
      "Fierce Wonder",
      "Fierce Resolve",
      "Fierce Desire",
      "Fierce Peace",
      "Fierce Rebellion",
      "Sacred Hope",
      "Sacred Grief",
      "Sacred Joy",
      "Sacred Rage",
      "Sacred Longing",
      "Sacred Courage",
      "Sacred Fear",
      "Sacred Love",
      "Sacred Pride",
      "Sacred Sorrow",
      "Sacred Wonder",
      "Sacred Resolve",
      "Sacred Desire",
      "Sacred Peace",
      "Sacred Rebellion",
      "Dark Hope",
      "Dark Grief",
      "Dark Joy",
      "Dark Rage",
      "Dark Longing",
      "Dark Courage",
      "Dark Fear",
      "Dark Love",
      "Dark Pride",
      "Dark Sorrow",
      "Dark Wonder",
      "Dark Resolve",
      "Dark Desire",
      "Dark Peace",
      "Dark Rebellion",
      "Radiant Hope",
      "Radiant Grief",
      "Radiant Joy",
      "Radiant Rage",
      "Radiant Longing",
      "Radiant Courage",
      "Radiant Fear",
      "Radiant Love",
      "Radiant Pride",
      "Radiant Sorrow",
      "Radiant Wonder",
      "Radiant Resolve",
      "Radiant Desire",
      "Radiant Peace",
      "Radiant Rebellion",
      "Restless Hope",
      "Restless Grief",
      "Restless Joy",
      "Restless Rage",
      "Restless Longing",
      "Restless Courage",
      "Restless Fear",
      "Restless Love",
      "Restless Pride",
      "Restless Sorrow",
      "Restless Wonder",
      "Restless Resolve",
      "Restless Desire",
      "Restless Peace",
      "Restless Rebellion",
      "Bittersweet Hope",
      "Bittersweet Grief",
      "Bittersweet Joy",
      "Bittersweet Rage",
      "Bittersweet Longing",
      "Bittersweet Courage",
      "Bittersweet Fear",
      "Bittersweet Love",
      "Bittersweet Pride",
      "Bittersweet Sorrow",
      "Bittersweet Wonder",
      "Bittersweet Resolve",
      "Bittersweet Desire",
      "Bittersweet Peace",
      "Bittersweet Rebellion"
    ]
  },
  "scenes": {
    "Hero Journey": [
      "Hero Awakening",
      "Call to Adventure",
      "Refusal of the Call",
      "First Departure",
      "Crossing the Threshold",
      "Mentor Appears",
      "First Trial",
      "Training Arc",
      "Hidden Power Awakens",
      "Transformation",
      "Return of the Hero",
      "Coronation",
      "New Beginning",
      "Legacy Passed On",
      "Final Revelation"
    ],
    "Battle": [
      "Final Boss Fight",
      "Last Stand",
      "War Declaration",
      "Battle Begins",
      "Castle Siege",
      "Dragon Battle",
      "Pirate Battle",
      "Naval Battle",
      "Street Fight",
      "Tournament Final",
      "Duel at Dawn",
      "Ambush",
      "Counterattack",
      "Army Charge",
      "Defending the Gate",
      "Battle in the Sky",
      "Mecha Showdown",
      "Kaiju Attack",
      "Sword Duel",
      "Magic Duel",
      "Sacrifice in Battle",
      "Victory Celebration",
      "Defeat and Retreat",
      "Berserker Rampage",
      "Rebellion Begins"
    ],
    "Drama": [
      "First Love",
      "First Kiss",
      "Farewell",
      "Betrayal",
      "Funeral",
      "Reunion",
      "Confession",
      "Breakup",
      "Family Revelation",
      "Lost Friendship",
      "Wedding",
      "Birth",
      "Deathbed Promise",
      "Letter from the Past",
      "Secret Exposed",
      "Public Humiliation",
      "Forgiveness",
      "Unrequited Love",
      "Jealous Confrontation",
      "Emotional Breakdown",
      "Silent Goodbye",
      "Homecoming",
      "Childhood Memory",
      "Hospital Vigil",
      "Last Conversation"
    ],
    "Mystery & Horror": [
      "Haunted Discovery",
      "Murder Investigation",
      "Monster Reveal",
      "Cursed Object Found",
      "Ritual Gone Wrong",
      "Ghost Appearance",
      "Door Opens by Itself",
      "Lost in the Fog",
      "Basement Discovery",
      "Possession",
      "Escape from the Killer",
      "Ancient Tomb Opens",
      "Blood Moon Rising",
      "Cult Ceremony",
      "Nightmare Sequence",
      "Mirror Doppelgänger",
      "Radio Signal from Nowhere",
      "Missing Person Clue",
      "Forbidden Book Read",
      "The Truth Is Worse",
      "Final Girl Escape",
      "Creature in the Woods",
      "Abandoned Village",
      "Time Loop Realization",
      "Unreliable Memory"
    ],
    "Adventure": [
      "Journey Starts",
      "Arrival in a New World",
      "Portal Opening",
      "Summoning",
      "Dungeon Crawl",
      "Treasure Discovery",
      "Ship Departure",
      "Storm at Sea",
      "Mountain Ascent",
      "Desert Crossing",
      "Forest Chase",
      "Cave Exploration",
      "Ruins Exploration",
      "Secret Passage",
      "Map Revealed",
      "Ancient Artifact Found",
      "Lost City Discovered",
      "Skyship Launch",
      "Underwater Dive",
      "Island Landing",
      "Campfire Reflection",
      "Crossroads Decision",
      "Companion Joins",
      "Companion Leaves",
      "Return Home"
    ],
    "Sci-Fi": [
      "First Contact",
      "Spaceship Launch",
      "Hyperjump",
      "Alien City Arrival",
      "AI Awakening",
      "Robot Rebellion",
      "Cybernetic Upgrade",
      "Virtual Reality Entry",
      "System Failure",
      "Space Station Evacuation",
      "Planet Destruction",
      "Time Machine Activation",
      "Timeline Split",
      "Clone Revelation",
      "Android Sacrifice",
      "Data Heist",
      "Neon City Chase",
      "Mecha Activation",
      "Orbital Battle",
      "Cryosleep Awakening",
      "Signal from Deep Space",
      "Black Hole Approach",
      "Terraforming Begins",
      "Humanity Leaves Earth",
      "Simulation Revealed"
    ],
    "Performance & Sport": [
      "Concert Opening",
      "Massive Festival Drop",
      "Backstage Breakdown",
      "Audition",
      "Debut Performance",
      "Final Encore",
      "Crowd Sings Along",
      "Band Reunion",
      "Studio Recording",
      "Songwriting Night",
      "Championship Final",
      "Penalty Shootout",
      "Race Start",
      "Final Lap",
      "Comeback Victory",
      "Training Montage",
      "Locker Room Speech",
      "Underdog Upset",
      "Record Broken",
      "Team Celebration"
    ],
    "Cinematic Variations": [
      "Awakening of the King",
      "Awakening of the Hero",
      "Awakening of the Shadow",
      "Awakening at Midnight",
      "Awakening under the Blood Moon",
      "Awakening in the Frozen City",
      "Awakening beyond the Horizon",
      "Awakening inside the Dream",
      "Awakening at the Final Gate",
      "Awakening before the Gods",
      "Departure of the King",
      "Departure of the Hero",
      "Departure of the Shadow",
      "Departure at Midnight",
      "Departure under the Blood Moon",
      "Departure in the Frozen City",
      "Departure beyond the Horizon",
      "Departure inside the Dream",
      "Departure at the Final Gate",
      "Departure before the Gods",
      "Return of the King",
      "Return of the Hero",
      "Return of the Shadow",
      "Return at Midnight",
      "Return under the Blood Moon",
      "Return in the Frozen City",
      "Return beyond the Horizon",
      "Return inside the Dream",
      "Return at the Final Gate",
      "Return before the Gods",
      "Fall of the King",
      "Fall of the Hero",
      "Fall of the Shadow",
      "Fall at Midnight",
      "Fall under the Blood Moon",
      "Fall in the Frozen City",
      "Fall beyond the Horizon",
      "Fall inside the Dream",
      "Fall at the Final Gate",
      "Fall before the Gods",
      "Rise of the King",
      "Rise of the Hero",
      "Rise of the Shadow",
      "Rise at Midnight",
      "Rise under the Blood Moon",
      "Rise in the Frozen City",
      "Rise beyond the Horizon",
      "Rise inside the Dream",
      "Rise at the Final Gate",
      "Rise before the Gods",
      "Sacrifice of the King",
      "Sacrifice of the Hero",
      "Sacrifice of the Shadow",
      "Sacrifice at Midnight",
      "Sacrifice under the Blood Moon",
      "Sacrifice in the Frozen City",
      "Sacrifice beyond the Horizon",
      "Sacrifice inside the Dream",
      "Sacrifice at the Final Gate",
      "Sacrifice before the Gods",
      "Revelation of the King",
      "Revelation of the Hero",
      "Revelation of the Shadow",
      "Revelation at Midnight",
      "Revelation under the Blood Moon",
      "Revelation in the Frozen City",
      "Revelation beyond the Horizon",
      "Revelation inside the Dream",
      "Revelation at the Final Gate",
      "Revelation before the Gods",
      "Transformation of the King",
      "Transformation of the Hero",
      "Transformation of the Shadow",
      "Transformation at Midnight",
      "Transformation under the Blood Moon",
      "Transformation in the Frozen City",
      "Transformation beyond the Horizon",
      "Transformation inside the Dream",
      "Transformation at the Final Gate",
      "Transformation before the Gods",
      "Escape of the King",
      "Escape of the Hero",
      "Escape of the Shadow",
      "Escape at Midnight",
      "Escape under the Blood Moon",
      "Escape in the Frozen City",
      "Escape beyond the Horizon",
      "Escape inside the Dream",
      "Escape at the Final Gate",
      "Escape before the Gods",
      "Confrontation of the King",
      "Confrontation of the Hero",
      "Confrontation of the Shadow",
      "Confrontation at Midnight",
      "Confrontation under the Blood Moon",
      "Confrontation in the Frozen City",
      "Confrontation beyond the Horizon",
      "Confrontation inside the Dream",
      "Confrontation at the Final Gate",
      "Confrontation before the Gods",
      "Coronation of the King",
      "Coronation of the Hero",
      "Coronation of the Shadow",
      "Coronation at Midnight",
      "Coronation under the Blood Moon",
      "Coronation in the Frozen City",
      "Coronation beyond the Horizon",
      "Coronation inside the Dream",
      "Coronation at the Final Gate",
      "Coronation before the Gods",
      "Summoning of the King",
      "Summoning of the Hero",
      "Summoning of the Shadow",
      "Summoning at Midnight",
      "Summoning under the Blood Moon",
      "Summoning in the Frozen City",
      "Summoning beyond the Horizon",
      "Summoning inside the Dream",
      "Summoning at the Final Gate",
      "Summoning before the Gods"
    ]
  },
  "atmospheres": {
    "Cinematic": [
      "Cinematic",
      "Epic",
      "Massive",
      "Trailer-like",
      "Blockbuster",
      "Wide and immersive",
      "Grandiose",
      "Heroic",
      "Monumental",
      "Sweeping",
      "High-stakes",
      "Dramatic orchestral",
      "AAA game cinematic",
      "Anime cinematic",
      "Slow-motion battle"
    ],
    "Natural": [
      "Frozen",
      "Burning",
      "Stormy",
      "Rain-soaked",
      "Foggy",
      "Snow-covered",
      "Desert-dry",
      "Ocean mist",
      "Thunderous",
      "Windy",
      "Moonlit",
      "Sunrise glow",
      "Sunset melancholy",
      "Autumnal",
      "Tropical",
      "Arctic",
      "Volcanic",
      "Underwater",
      "Forest ambience",
      "Mountain air"
    ],
    "Mystical": [
      "Holy",
      "Corrupted",
      "Magical",
      "Cosmic",
      "Heavenly",
      "Infernal",
      "Haunted",
      "Ethereal",
      "Arcane",
      "Ancient temple ambience",
      "Celestial battlefield",
      "Ritualistic",
      "Dreamlike",
      "Otherworldly",
      "Prophetic",
      "Sacred",
      "Enchanted",
      "Phantom-like",
      "Mythological",
      "Timeless"
    ],
    "Urban & Future": [
      "Industrial",
      "Neon dystopia",
      "Cybernetic",
      "Futuristic",
      "Retro-futuristic",
      "Noir city",
      "Rainy neon streets",
      "Underground club",
      "Abandoned factory",
      "Radioactive wasteland",
      "High-tech laboratory",
      "Orbital station",
      "Holographic city",
      "Digital void",
      "Machine room",
      "Crowded metropolis",
      "Empty subway",
      "Rooftop at night",
      "Corporate tower",
      "Data center"
    ],
    "Emotional": [
      "Intimate and emotional",
      "Warm and nostalgic",
      "Melancholic",
      "Lonely",
      "Romantic",
      "Bittersweet",
      "Hopeful",
      "Tender",
      "Fragile",
      "Heartbreaking",
      "Cathartic",
      "Peaceful",
      "Comforting",
      "Wistful",
      "Somber",
      "Triumphant",
      "Defiant",
      "Desperate",
      "Mournful",
      "Reborn"
    ],
    "Horror": [
      "Claustrophobic",
      "Sinister",
      "Dread-filled",
      "Uncanny",
      "Eldritch",
      "Gothic",
      "Possessed",
      "Nightmarish",
      "Paranoid",
      "Blood-soaked",
      "Funereal",
      "Silent and threatening",
      "Distorted reality",
      "Cursed ambience",
      "Abandoned hospital",
      "Creaking mansion",
      "Whispering darkness",
      "Chilling emptiness",
      "Ritual horror",
      "Cosmic dread"
    ],
    "Production Feel": [
      "Organic",
      "Raw",
      "Polished",
      "Vintage",
      "Lo-fi haze",
      "Saturated tape",
      "Crystal-clear",
      "Wide stereo",
      "Intimate mono",
      "Reverberant hall",
      "Dry close-mic",
      "Dense and layered",
      "Minimal and sparse",
      "Compressed and aggressive",
      "Dynamic and breathing",
      "Bright and glossy",
      "Dark and muddy",
      "Airy and spacious",
      "Punchy and modern",
      "Warm analog"
    ],
    "Atmospheric Combinations": [
      "Ancient Temple atmosphere",
      "Ancient Battlefield atmosphere",
      "Ancient City atmosphere",
      "Ancient Forest atmosphere",
      "Ancient Ocean atmosphere",
      "Ancient Cathedral atmosphere",
      "Ancient Wasteland atmosphere",
      "Ancient Palace atmosphere",
      "Ancient Laboratory atmosphere",
      "Ancient Night atmosphere",
      "Ancient Horizon atmosphere",
      "Ancient Void atmosphere",
      "Ancient Storm atmosphere",
      "Ancient Dream atmosphere",
      "Ancient Ritual atmosphere",
      "Frozen Temple atmosphere",
      "Frozen Battlefield atmosphere",
      "Frozen City atmosphere",
      "Frozen Forest atmosphere",
      "Frozen Ocean atmosphere",
      "Frozen Cathedral atmosphere",
      "Frozen Wasteland atmosphere",
      "Frozen Palace atmosphere",
      "Frozen Laboratory atmosphere",
      "Frozen Night atmosphere",
      "Frozen Horizon atmosphere",
      "Frozen Void atmosphere",
      "Frozen Storm atmosphere",
      "Frozen Dream atmosphere",
      "Frozen Ritual atmosphere",
      "Burning Temple atmosphere",
      "Burning Battlefield atmosphere",
      "Burning City atmosphere",
      "Burning Forest atmosphere",
      "Burning Ocean atmosphere",
      "Burning Cathedral atmosphere",
      "Burning Wasteland atmosphere",
      "Burning Palace atmosphere",
      "Burning Laboratory atmosphere",
      "Burning Night atmosphere",
      "Burning Horizon atmosphere",
      "Burning Void atmosphere",
      "Burning Storm atmosphere",
      "Burning Dream atmosphere",
      "Burning Ritual atmosphere",
      "Sacred Temple atmosphere",
      "Sacred Battlefield atmosphere",
      "Sacred City atmosphere",
      "Sacred Forest atmosphere",
      "Sacred Ocean atmosphere",
      "Sacred Cathedral atmosphere",
      "Sacred Wasteland atmosphere",
      "Sacred Palace atmosphere",
      "Sacred Laboratory atmosphere",
      "Sacred Night atmosphere",
      "Sacred Horizon atmosphere",
      "Sacred Void atmosphere",
      "Sacred Storm atmosphere",
      "Sacred Dream atmosphere",
      "Sacred Ritual atmosphere",
      "Corrupted Temple atmosphere",
      "Corrupted Battlefield atmosphere",
      "Corrupted City atmosphere",
      "Corrupted Forest atmosphere",
      "Corrupted Ocean atmosphere",
      "Corrupted Cathedral atmosphere",
      "Corrupted Wasteland atmosphere",
      "Corrupted Palace atmosphere",
      "Corrupted Laboratory atmosphere",
      "Corrupted Night atmosphere",
      "Corrupted Horizon atmosphere",
      "Corrupted Void atmosphere",
      "Corrupted Storm atmosphere",
      "Corrupted Dream atmosphere",
      "Corrupted Ritual atmosphere",
      "Neon Temple atmosphere",
      "Neon Battlefield atmosphere",
      "Neon City atmosphere",
      "Neon Forest atmosphere",
      "Neon Ocean atmosphere",
      "Neon Cathedral atmosphere",
      "Neon Wasteland atmosphere",
      "Neon Palace atmosphere",
      "Neon Laboratory atmosphere",
      "Neon Night atmosphere",
      "Neon Horizon atmosphere",
      "Neon Void atmosphere",
      "Neon Storm atmosphere",
      "Neon Dream atmosphere",
      "Neon Ritual atmosphere",
      "Celestial Temple atmosphere",
      "Celestial Battlefield atmosphere",
      "Celestial City atmosphere",
      "Celestial Forest atmosphere",
      "Celestial Ocean atmosphere",
      "Celestial Cathedral atmosphere",
      "Celestial Wasteland atmosphere",
      "Celestial Palace atmosphere",
      "Celestial Laboratory atmosphere",
      "Celestial Night atmosphere",
      "Celestial Horizon atmosphere",
      "Celestial Void atmosphere",
      "Celestial Storm atmosphere",
      "Celestial Dream atmosphere",
      "Celestial Ritual atmosphere",
      "Infernal Temple atmosphere",
      "Infernal Battlefield atmosphere",
      "Infernal City atmosphere",
      "Infernal Forest atmosphere",
      "Infernal Ocean atmosphere",
      "Infernal Cathedral atmosphere",
      "Infernal Wasteland atmosphere",
      "Infernal Palace atmosphere",
      "Infernal Laboratory atmosphere",
      "Infernal Night atmosphere",
      "Infernal Horizon atmosphere",
      "Infernal Void atmosphere",
      "Infernal Storm atmosphere",
      "Infernal Dream atmosphere",
      "Infernal Ritual atmosphere",
      "Haunted Temple atmosphere",
      "Haunted Battlefield atmosphere",
      "Haunted City atmosphere",
      "Haunted Forest atmosphere",
      "Haunted Ocean atmosphere",
      "Haunted Cathedral atmosphere",
      "Haunted Wasteland atmosphere",
      "Haunted Palace atmosphere",
      "Haunted Laboratory atmosphere",
      "Haunted Night atmosphere",
      "Haunted Horizon atmosphere",
      "Haunted Void atmosphere",
      "Haunted Storm atmosphere",
      "Haunted Dream atmosphere",
      "Haunted Ritual atmosphere",
      "Dreamlike Temple atmosphere",
      "Dreamlike Battlefield atmosphere",
      "Dreamlike City atmosphere",
      "Dreamlike Forest atmosphere",
      "Dreamlike Ocean atmosphere",
      "Dreamlike Cathedral atmosphere",
      "Dreamlike Wasteland atmosphere",
      "Dreamlike Palace atmosphere",
      "Dreamlike Laboratory atmosphere",
      "Dreamlike Night atmosphere",
      "Dreamlike Horizon atmosphere",
      "Dreamlike Void atmosphere",
      "Dreamlike Storm atmosphere",
      "Dreamlike Dream atmosphere",
      "Dreamlike Ritual atmosphere",
      "Industrial Temple atmosphere",
      "Industrial Battlefield atmosphere",
      "Industrial City atmosphere",
      "Industrial Forest atmosphere",
      "Industrial Ocean atmosphere",
      "Industrial Cathedral atmosphere",
      "Industrial Wasteland atmosphere",
      "Industrial Palace atmosphere",
      "Industrial Laboratory atmosphere",
      "Industrial Night atmosphere",
      "Industrial Horizon atmosphere",
      "Industrial Void atmosphere",
      "Industrial Storm atmosphere",
      "Industrial Dream atmosphere",
      "Industrial Ritual atmosphere",
      "Cosmic Temple atmosphere",
      "Cosmic Battlefield atmosphere",
      "Cosmic City atmosphere",
      "Cosmic Forest atmosphere",
      "Cosmic Ocean atmosphere",
      "Cosmic Cathedral atmosphere",
      "Cosmic Wasteland atmosphere",
      "Cosmic Palace atmosphere",
      "Cosmic Laboratory atmosphere",
      "Cosmic Night atmosphere",
      "Cosmic Horizon atmosphere",
      "Cosmic Void atmosphere",
      "Cosmic Storm atmosphere",
      "Cosmic Dream atmosphere",
      "Cosmic Ritual atmosphere",
      "Melancholic Temple atmosphere",
      "Melancholic Battlefield atmosphere",
      "Melancholic City atmosphere",
      "Melancholic Forest atmosphere",
      "Melancholic Ocean atmosphere",
      "Melancholic Cathedral atmosphere",
      "Melancholic Wasteland atmosphere",
      "Melancholic Palace atmosphere",
      "Melancholic Laboratory atmosphere",
      "Melancholic Night atmosphere",
      "Melancholic Horizon atmosphere",
      "Melancholic Void atmosphere",
      "Melancholic Storm atmosphere",
      "Melancholic Dream atmosphere",
      "Melancholic Ritual atmosphere",
      "Triumphant Temple atmosphere",
      "Triumphant Battlefield atmosphere",
      "Triumphant City atmosphere",
      "Triumphant Forest atmosphere",
      "Triumphant Ocean atmosphere",
      "Triumphant Cathedral atmosphere",
      "Triumphant Wasteland atmosphere",
      "Triumphant Palace atmosphere",
      "Triumphant Laboratory atmosphere",
      "Triumphant Night atmosphere",
      "Triumphant Horizon atmosphere",
      "Triumphant Void atmosphere",
      "Triumphant Storm atmosphere",
      "Triumphant Dream atmosphere",
      "Triumphant Ritual atmosphere",
      "Mysterious Temple atmosphere",
      "Mysterious Battlefield atmosphere",
      "Mysterious City atmosphere",
      "Mysterious Forest atmosphere",
      "Mysterious Ocean atmosphere",
      "Mysterious Cathedral atmosphere",
      "Mysterious Wasteland atmosphere",
      "Mysterious Palace atmosphere",
      "Mysterious Laboratory atmosphere",
      "Mysterious Night atmosphere",
      "Mysterious Horizon atmosphere",
      "Mysterious Void atmosphere",
      "Mysterious Storm atmosphere",
      "Mysterious Dream atmosphere",
      "Mysterious Ritual atmosphere"
    ]
  },
  "narratives": {
    "Point of View": [
      "First-person storytelling",
      "Third-person limited",
      "Third-person omniscient",
      "Second-person address",
      "Dual perspective",
      "Multiple narrators",
      "Unreliable narrator",
      "Collective voice",
      "Villain perspective",
      "Hero perspective",
      "Witness perspective"
    ],
    "Time & Structure": [
      "Flashback",
      "Flash-forward",
      "Nonlinear timeline",
      "Parallel story",
      "Time loop narrative",
      "Memory fragments",
      "Dream sequence",
      "Story within a story",
      "Reverse chronology",
      "Episodic chapters",
      "Circular narrative",
      "Prologue narration",
      "Epilogue reflection",
      "Real-time narration",
      "Generational saga"
    ],
    "Format": [
      "Cinematic narrator",
      "Character dialogue",
      "Internal monologue",
      "Diary entry",
      "Letter",
      "Ancient scroll",
      "Prophecy",
      "Radio broadcast",
      "AI log",
      "Mission briefing",
      "Court testimony",
      "News report",
      "Prayer",
      "Confession",
      "War speech",
      "Campfire legend",
      "Bedtime story",
      "Stage monologue",
      "Interrogation",
      "Recorded message"
    ],
    "Arc": [
      "Hero journey",
      "Villain origin story",
      "Revenge arc",
      "Redemption arc",
      "Coming of age",
      "Fall from grace",
      "Rise to power",
      "Mystery reveal",
      "Battle narration",
      "Emotional reflection",
      "Mythic legend",
      "Tragic romance",
      "Forbidden love",
      "Survival story",
      "Quest narrative",
      "Rebellion story",
      "Chosen one prophecy",
      "Found family story",
      "Underdog story",
      "Apocalypse chronicle"
    ],
    "Performance": [
      "Spoken intro",
      "Whispered narration",
      "Deep male narration",
      "Female cinematic narration",
      "Call and response",
      "Choir as narrator",
      "Dialogue-driven",
      "Minimal lyrical fragments",
      "Poetic storytelling",
      "Direct confessional",
      "Epic proclamation",
      "Fragmented thoughts",
      "Stream of consciousness",
      "Question-and-answer",
      "Repeated mantra",
      "Crowd narration",
      "System voice interjections",
      "Character role switching",
      "Narrative chorus",
      "Documentary style"
    ]
  }
};
