(function(root){
'use strict';
const Catalog=root.NSWWorkspaceI18nCatalog;
const DynamicLocales=root.NSWStudioIntelligenceDynamicLocales;
if(!Catalog)return;

const EN=Object.freeze({
 headerDesc:'A central mentor that reads the current Studio state, explains what matters, recommends the next step and coordinates the intelligent tools.',
 commandTitle:'Studio Command',commandDesc:'Describe your goal, ask for advice or let Studio Intelligence inspect the current project.',briefPlaceholder:'Example: Make my Viking EDM anime opening clearer, more emotional and less overloaded.',
 roleLabel:'Intelligence Role',roleMentor:'AI Mentor',roleCoach:'AI Song Coach',roleMixer:'AI Genre Mixer',roleSound:'AI Sound Designer',roleDirector:'Complete Studio Director',
 toneLabel:'Advice Style',toneClear:'Clear & Practical',toneSupportive:'Supportive',toneCritical:'Critical Producer',toneCreative:'Creative Explorer',
 goalLabel:'Goal',goalImprove:'Improve Existing Song',goalBuild:'Build New Song',goalSimplify:'Simplify',goalExperiment:'Experiment',goalFinish:'Finish for Suno',
 automationLabel:'Automation',autoRecommend:'Recommend Only',autoPrepare:'Prepare Changes',autoApply:'Apply Safe Changes',
 readProject:'Read active project',readStyle:'Read current STYLE',readLyrics:'Read Lyrics Workspace',useLearning:'Use local learning history',
 readiness:'Studio Readiness',reportTitle:'Intelligent Studio Report',reportDesc:'Mentor guidance, song coaching, genre logic, sound design and an actionable workflow.',saveSnapshot:'Save Intelligence Snapshot',
 mentorSubtitle:'What to do and why',coachSubtitle:'Strengths and weak points',mixerSubtitle:'How the style blend should work',soundSubtitle:'Section, layer and mix guidance',
 workflowTitle:'Recommended Workflow',workflowDesc:'Complete the song in the most useful order.',actionsTitle:'Prepared Studio Actions',actionsDesc:'Review changes before applying them across connected modules.',
 applySafe:'✅ APPLY SAFE IMPROVEMENTS',openNext:'Open Next Recommended Module',runPipeline:'Run Intelligent Pipeline',undo:'Undo Last Application',
 styleTitle:'Studio Intelligence STYLE',styleDesc:'A coordinated STYLE based on the complete analysis.',historyTitle:'Intelligence History',historyDesc:'Restore earlier Studio analyses.'
});

const L=Object.freeze({
 de:{headerDesc:'Ein zentraler Mentor liest den aktuellen Studio-Stand, erklärt das Wesentliche, empfiehlt den nächsten Schritt und koordiniert die intelligenten Werkzeuge.',commandTitle:'Studio-Steuerung',commandDesc:'Beschreibe dein Ziel, stelle eine Frage oder lasse Studio Intelligence das aktuelle Projekt prüfen.',briefPlaceholder:'Beispiel: Mache mein Viking-EDM-Anime-Opening klarer, emotionaler und weniger überladen.',roleLabel:'Rolle der Intelligenz',roleDirector:'Kompletter Studio Director',toneLabel:'Art der Beratung',toneClear:'Klar & praktisch',toneSupportive:'Unterstützend',toneCritical:'Kritischer Producer',toneCreative:'Kreativer Entdecker',goalLabel:'Ziel',goalImprove:'Vorhandenen Song verbessern',goalBuild:'Neuen Song aufbauen',goalSimplify:'Vereinfachen',goalExperiment:'Experimentieren',goalFinish:'Für Suno fertigstellen',automationLabel:'Automatik',autoRecommend:'Nur empfehlen',autoPrepare:'Änderungen vorbereiten',autoApply:'Sichere Änderungen anwenden',readProject:'Aktives Projekt einlesen',readStyle:'Aktuellen STYLE einlesen',readLyrics:'Lyrics Workspace einlesen',useLearning:'Lokalen Lernverlauf nutzen',readiness:'Studio-Bereitschaft',reportTitle:'Intelligenter Studio-Bericht',reportDesc:'Mentor-Hilfe, Song-Coaching, Genre-Logik, Sounddesign und ein direkt nutzbarer Arbeitsablauf.',saveSnapshot:'Intelligence-Stand speichern',mentorSubtitle:'Was du tun solltest und warum',coachSubtitle:'Stärken und Schwachstellen',mixerSubtitle:'Wie die Genre-Mischung funktionieren sollte',soundSubtitle:'Hinweise zu Abschnitten, Layern und Mix',workflowTitle:'Empfohlener Arbeitsablauf',workflowDesc:'Führe den Song in einer sinnvollen Reihenfolge zum Ziel.',actionsTitle:'Vorbereitete Studio-Aktionen',actionsDesc:'Prüfe die Änderungen, bevor sie in verbundenen Modulen angewendet werden.',applySafe:'✅ SICHERE VERBESSERUNGEN ANWENDEN',openNext:'Nächstes empfohlenes Modul öffnen',runPipeline:'Intelligente Pipeline starten',undo:'Letzte Anwendung rückgängig machen',styleTitle:'Studio-Intelligence-STYLE',styleDesc:'Ein abgestimmter STYLE aus der vollständigen Analyse.',historyTitle:'Intelligence-Verlauf',historyDesc:'Frühere Studio-Analysen wiederherstellen.'},
 fr:{headerDesc:'Un mentor central lit l’état actuel du studio, explique l’essentiel, recommande la prochaine étape et coordonne les outils intelligents.',commandTitle:'Commande du studio',commandDesc:'Décrivez votre objectif, posez une question ou laissez Studio Intelligence examiner le projet actuel.',briefPlaceholder:'Exemple : rendre mon opening anime Viking EDM plus clair, plus émouvant et moins chargé.',roleLabel:'Rôle de l’intelligence',roleDirector:'Directeur complet du studio',toneLabel:'Style de conseil',toneClear:'Clair et pratique',toneSupportive:'Encourageant',toneCritical:'Producteur critique',toneCreative:'Explorateur créatif',goalLabel:'Objectif',goalImprove:'Améliorer le morceau existant',goalBuild:'Créer un nouveau morceau',goalSimplify:'Simplifier',goalExperiment:'Expérimenter',goalFinish:'Finaliser pour Suno',automationLabel:'Automatisation',autoRecommend:'Recommander uniquement',autoPrepare:'Préparer les changements',autoApply:'Appliquer les changements sûrs',readProject:'Lire le projet actif',readStyle:'Lire le STYLE actuel',readLyrics:'Lire le Lyrics Workspace',useLearning:'Utiliser l’historique local',readiness:'Préparation du studio',reportTitle:'Rapport intelligent du studio',reportDesc:'Conseils du mentor, coaching, logique des genres, sound design et déroulement pratique.',saveSnapshot:'Enregistrer l’analyse',mentorSubtitle:'Que faire et pourquoi',coachSubtitle:'Forces et faiblesses',mixerSubtitle:'Comment organiser le mélange des genres',soundSubtitle:'Conseils sur les sections, couches et mix',workflowTitle:'Flux de travail recommandé',workflowDesc:'Terminez le morceau dans l’ordre le plus utile.',actionsTitle:'Actions préparées',actionsDesc:'Vérifiez les changements avant de les appliquer aux modules connectés.',applySafe:'✅ APPLIQUER LES AMÉLIORATIONS SÛRES',openNext:'Ouvrir le prochain module recommandé',runPipeline:'Lancer le flux intelligent',undo:'Annuler la dernière application',styleTitle:'STYLE Studio Intelligence',styleDesc:'Un STYLE coordonné à partir de l’analyse complète.',historyTitle:'Historique Intelligence',historyDesc:'Restaurer des analyses précédentes du studio.'},
 es:{headerDesc:'Un mentor central lee el estado actual del estudio, explica lo importante, recomienda el siguiente paso y coordina las herramientas inteligentes.',commandTitle:'Control del estudio',commandDesc:'Describe tu objetivo, pide consejo o deja que Studio Intelligence revise el proyecto actual.',briefPlaceholder:'Ejemplo: Haz que mi opening anime Viking EDM sea más claro, emotivo y menos recargado.',roleLabel:'Rol de inteligencia',roleDirector:'Director completo del estudio',toneLabel:'Estilo de consejo',toneClear:'Claro y práctico',toneSupportive:'Comprensivo',toneCritical:'Productor crítico',toneCreative:'Explorador creativo',goalLabel:'Objetivo',goalImprove:'Mejorar canción existente',goalBuild:'Crear nueva canción',goalSimplify:'Simplificar',goalExperiment:'Experimentar',goalFinish:'Finalizar para Suno',automationLabel:'Automatización',autoRecommend:'Solo recomendar',autoPrepare:'Preparar cambios',autoApply:'Aplicar cambios seguros',readProject:'Leer proyecto activo',readStyle:'Leer STYLE actual',readLyrics:'Leer Lyrics Workspace',useLearning:'Usar historial de aprendizaje local',readiness:'Preparación del estudio',reportTitle:'Informe inteligente del estudio',reportDesc:'Guía del mentor, coaching, lógica de género, diseño sonoro y flujo de trabajo práctico.',saveSnapshot:'Guardar análisis',mentorSubtitle:'Qué hacer y por qué',coachSubtitle:'Fortalezas y puntos débiles',mixerSubtitle:'Cómo debe funcionar la mezcla de géneros',soundSubtitle:'Guía de secciones, capas y mezcla',workflowTitle:'Flujo recomendado',workflowDesc:'Completa la canción en el orden más útil.',actionsTitle:'Acciones preparadas',actionsDesc:'Revisa los cambios antes de aplicarlos a los módulos conectados.',applySafe:'✅ APLICAR MEJORAS SEGURAS',openNext:'Abrir siguiente módulo recomendado',runPipeline:'Ejecutar flujo inteligente',undo:'Deshacer última aplicación',styleTitle:'STYLE de Studio Intelligence',styleDesc:'Un STYLE coordinado a partir del análisis completo.',historyTitle:'Historial de Intelligence',historyDesc:'Restaurar análisis anteriores del estudio.'},
 it:{headerDesc:'Un mentore centrale legge lo stato dello studio, spiega ciò che conta, consiglia il passo successivo e coordina gli strumenti intelligenti.',commandTitle:'Controllo dello studio',commandDesc:'Descrivi l’obiettivo, chiedi un consiglio oppure lascia che Studio Intelligence esamini il progetto.',briefPlaceholder:'Esempio: rendi il mio opening anime Viking EDM più chiaro, emotivo e meno sovraccarico.',roleLabel:'Ruolo intelligente',roleDirector:'Direttore completo dello studio',toneLabel:'Stile del consiglio',toneClear:'Chiaro e pratico',toneSupportive:'Incoraggiante',toneCritical:'Produttore critico',toneCreative:'Esploratore creativo',goalLabel:'Obiettivo',goalImprove:'Migliora il brano esistente',goalBuild:'Crea un nuovo brano',goalSimplify:'Semplifica',goalExperiment:'Sperimenta',goalFinish:'Finalizza per Suno',automationLabel:'Automazione',autoRecommend:'Solo consigli',autoPrepare:'Prepara modifiche',autoApply:'Applica modifiche sicure',readProject:'Leggi il progetto attivo',readStyle:'Leggi lo STYLE attuale',readLyrics:'Leggi Lyrics Workspace',useLearning:'Usa la cronologia locale',readiness:'Preparazione dello studio',reportTitle:'Rapporto intelligente dello studio',reportDesc:'Guida del mentore, coaching, logica dei generi, sound design e flusso di lavoro pratico.',saveSnapshot:'Salva analisi',mentorSubtitle:'Cosa fare e perché',coachSubtitle:'Punti di forza e debolezze',mixerSubtitle:'Come deve funzionare il mix dei generi',soundSubtitle:'Indicazioni su sezioni, livelli e mix',workflowTitle:'Flusso consigliato',workflowDesc:'Completa il brano nell’ordine più utile.',actionsTitle:'Azioni preparate',actionsDesc:'Controlla le modifiche prima di applicarle ai moduli collegati.',applySafe:'✅ APPLICA MIGLIORAMENTI SICURI',openNext:'Apri il prossimo modulo consigliato',runPipeline:'Avvia flusso intelligente',undo:'Annulla ultima applicazione',styleTitle:'STYLE Studio Intelligence',styleDesc:'Uno STYLE coordinato basato sull’analisi completa.',historyTitle:'Cronologia Intelligence',historyDesc:'Ripristina precedenti analisi dello studio.'},
 pt:{headerDesc:'Um mentor central lê o estado atual do estúdio, explica o que importa, recomenda o próximo passo e coordena as ferramentas inteligentes.',commandTitle:'Controlo do estúdio',commandDesc:'Descreva o objetivo, peça aconselhamento ou deixe o Studio Intelligence analisar o projeto atual.',briefPlaceholder:'Exemplo: tornar a minha abertura anime Viking EDM mais clara, emotiva e menos sobrecarregada.',roleLabel:'Função da inteligência',roleDirector:'Diretor completo do estúdio',toneLabel:'Estilo de aconselhamento',toneClear:'Claro e prático',toneSupportive:'Apoiador',toneCritical:'Produtor crítico',toneCreative:'Explorador criativo',goalLabel:'Objetivo',goalImprove:'Melhorar música existente',goalBuild:'Criar nova música',goalSimplify:'Simplificar',goalExperiment:'Experimentar',goalFinish:'Finalizar para Suno',automationLabel:'Automação',autoRecommend:'Apenas recomendar',autoPrepare:'Preparar alterações',autoApply:'Aplicar alterações seguras',readProject:'Ler projeto ativo',readStyle:'Ler STYLE atual',readLyrics:'Ler Lyrics Workspace',useLearning:'Usar histórico local',readiness:'Preparação do estúdio',reportTitle:'Relatório inteligente do estúdio',reportDesc:'Orientação, coaching, lógica de géneros, sound design e um fluxo de trabalho prático.',saveSnapshot:'Guardar análise',mentorSubtitle:'O que fazer e porquê',coachSubtitle:'Pontos fortes e fracos',mixerSubtitle:'Como deve funcionar a mistura de géneros',soundSubtitle:'Orientação de secções, camadas e mistura',workflowTitle:'Fluxo recomendado',workflowDesc:'Conclua a música pela ordem mais útil.',actionsTitle:'Ações preparadas',actionsDesc:'Reveja as alterações antes de as aplicar aos módulos ligados.',applySafe:'✅ APLICAR MELHORIAS SEGURAS',openNext:'Abrir próximo módulo recomendado',runPipeline:'Executar fluxo inteligente',undo:'Anular última aplicação',styleTitle:'STYLE do Studio Intelligence',styleDesc:'Um STYLE coordenado com base na análise completa.',historyTitle:'Histórico Intelligence',historyDesc:'Restaurar análises anteriores do estúdio.'},
 'pt-BR':{headerDesc:'Um mentor central lê o estado atual do estúdio, explica o que importa, recomenda o próximo passo e coordena as ferramentas inteligentes.',commandTitle:'Controle do estúdio',commandDesc:'Descreva o objetivo, peça orientação ou deixe o Studio Intelligence analisar o projeto atual.',briefPlaceholder:'Exemplo: deixe minha abertura anime Viking EDM mais clara, emotiva e menos carregada.',roleLabel:'Função da inteligência',roleDirector:'Diretor completo do estúdio',toneLabel:'Estilo da orientação',toneClear:'Claro e prático',toneSupportive:'Apoiador',toneCritical:'Produtor crítico',toneCreative:'Explorador criativo',goalLabel:'Objetivo',goalImprove:'Melhorar música existente',goalBuild:'Criar nova música',goalSimplify:'Simplificar',goalExperiment:'Experimentar',goalFinish:'Finalizar para Suno',automationLabel:'Automação',autoRecommend:'Apenas recomendar',autoPrepare:'Preparar alterações',autoApply:'Aplicar alterações seguras',readProject:'Ler projeto ativo',readStyle:'Ler STYLE atual',readLyrics:'Ler Lyrics Workspace',useLearning:'Usar histórico local',readiness:'Preparação do estúdio',reportTitle:'Relatório inteligente do estúdio',reportDesc:'Orientação, coaching, lógica de gêneros, sound design e um fluxo de trabalho prático.',saveSnapshot:'Salvar análise',mentorSubtitle:'O que fazer e por quê',coachSubtitle:'Pontos fortes e fracos',mixerSubtitle:'Como deve funcionar a mistura de gêneros',soundSubtitle:'Orientação de seções, camadas e mixagem',workflowTitle:'Fluxo recomendado',workflowDesc:'Conclua a música na ordem mais útil.',actionsTitle:'Ações preparadas',actionsDesc:'Revise as alterações antes de aplicá-las aos módulos conectados.',applySafe:'✅ APLICAR MELHORIAS SEGURAS',openNext:'Abrir próximo módulo recomendado',runPipeline:'Executar fluxo inteligente',undo:'Desfazer última aplicação',styleTitle:'STYLE do Studio Intelligence',styleDesc:'Um STYLE coordenado com base na análise completa.',historyTitle:'Histórico Intelligence',historyDesc:'Restaurar análises anteriores do estúdio.'},
 nl:{headerDesc:'Een centrale mentor leest de studiostatus, legt uit wat belangrijk is, adviseert de volgende stap en coördineert de slimme hulpmiddelen.',commandTitle:'Studiobesturing',commandDesc:'Beschrijf je doel, vraag advies of laat Studio Intelligence het huidige project bekijken.',briefPlaceholder:'Voorbeeld: maak mijn Viking-EDM-anime-opening duidelijker, emotioneler en minder vol.',roleLabel:'Rol van intelligentie',roleDirector:'Volledige studiodirecteur',toneLabel:'Adviesstijl',toneClear:'Duidelijk en praktisch',toneSupportive:'Ondersteunend',toneCritical:'Kritische producer',toneCreative:'Creatieve ontdekker',goalLabel:'Doel',goalImprove:'Bestaand nummer verbeteren',goalBuild:'Nieuw nummer bouwen',goalSimplify:'Vereenvoudigen',goalExperiment:'Experimenteren',goalFinish:'Klaarmaken voor Suno',automationLabel:'Automatisering',autoRecommend:'Alleen aanbevelen',autoPrepare:'Wijzigingen voorbereiden',autoApply:'Veilige wijzigingen toepassen',readProject:'Actief project lezen',readStyle:'Huidige STYLE lezen',readLyrics:'Lyrics Workspace lezen',useLearning:'Lokale leergeschiedenis gebruiken',readiness:'Studiogereedheid',reportTitle:'Intelligent studiorapport',reportDesc:'Mentoradvies, songcoaching, genrelogica, sounddesign en een bruikbare workflow.',saveSnapshot:'Analyse opslaan',mentorSubtitle:'Wat te doen en waarom',coachSubtitle:'Sterke en zwakke punten',mixerSubtitle:'Hoe de genremix moet werken',soundSubtitle:'Advies voor secties, lagen en mix',workflowTitle:'Aanbevolen workflow',workflowDesc:'Voltooi het nummer in de nuttigste volgorde.',actionsTitle:'Voorbereide studioacties',actionsDesc:'Controleer wijzigingen voordat je ze op verbonden modules toepast.',applySafe:'✅ VEILIGE VERBETERINGEN TOEPASSEN',openNext:'Volgende aanbevolen module openen',runPipeline:'Slimme workflow uitvoeren',undo:'Laatste toepassing ongedaan maken',styleTitle:'Studio Intelligence STYLE',styleDesc:'Een afgestemde STYLE op basis van de volledige analyse.',historyTitle:'Intelligence-geschiedenis',historyDesc:'Eerdere studioanalyses herstellen.'},
 pl:{headerDesc:'Centralny mentor odczytuje stan studia, wyjaśnia najważniejsze elementy, poleca kolejny krok i koordynuje inteligentne narzędzia.',commandTitle:'Sterowanie studiem',commandDesc:'Opisz cel, poproś o poradę lub pozwól Studio Intelligence sprawdzić bieżący projekt.',briefPlaceholder:'Przykład: spraw, aby mój opening anime Viking EDM był wyraźniejszy, bardziej emocjonalny i mniej przeładowany.',roleLabel:'Rola inteligencji',roleDirector:'Pełny dyrektor studia',toneLabel:'Styl porady',toneClear:'Jasny i praktyczny',toneSupportive:'Wspierający',toneCritical:'Krytyczny producent',toneCreative:'Kreatywny odkrywca',goalLabel:'Cel',goalImprove:'Ulepsz istniejący utwór',goalBuild:'Zbuduj nowy utwór',goalSimplify:'Uprość',goalExperiment:'Eksperymentuj',goalFinish:'Dokończ dla Suno',automationLabel:'Automatyzacja',autoRecommend:'Tylko polecaj',autoPrepare:'Przygotuj zmiany',autoApply:'Zastosuj bezpieczne zmiany',readProject:'Odczytaj aktywny projekt',readStyle:'Odczytaj bieżący STYLE',readLyrics:'Odczytaj Lyrics Workspace',useLearning:'Użyj lokalnej historii nauki',readiness:'Gotowość studia',reportTitle:'Inteligentny raport studia',reportDesc:'Porady mentora, coaching, logika gatunków, sound design i praktyczny przepływ pracy.',saveSnapshot:'Zapisz analizę',mentorSubtitle:'Co zrobić i dlaczego',coachSubtitle:'Mocne i słabe strony',mixerSubtitle:'Jak powinno działać łączenie gatunków',soundSubtitle:'Wskazówki dotyczące sekcji, warstw i miksu',workflowTitle:'Zalecany przepływ pracy',workflowDesc:'Dokończ utwór w najbardziej użytecznej kolejności.',actionsTitle:'Przygotowane działania',actionsDesc:'Sprawdź zmiany przed zastosowaniem ich w połączonych modułach.',applySafe:'✅ ZASTOSUJ BEZPIECZNE ULEPSZENIA',openNext:'Otwórz następny zalecany moduł',runPipeline:'Uruchom inteligentny przepływ',undo:'Cofnij ostatnie zastosowanie',styleTitle:'STYLE Studio Intelligence',styleDesc:'Uzgodniony STYLE oparty na pełnej analizie.',historyTitle:'Historia Intelligence',historyDesc:'Przywróć wcześniejsze analizy studia.'},
 tr:{headerDesc:'Merkezi mentor stüdyonun durumunu okur, önemli noktaları açıklar, sonraki adımı önerir ve akıllı araçları koordine eder.',commandTitle:'Stüdyo kontrolü',commandDesc:'Hedefinizi açıklayın, tavsiye isteyin veya Studio Intelligence’ın mevcut projeyi incelemesine izin verin.',briefPlaceholder:'Örnek: Viking EDM anime açılışımı daha net, duygusal ve daha az yoğun yap.',roleLabel:'Zekâ rolü',roleDirector:'Tam stüdyo yönetmeni',toneLabel:'Tavsiye tarzı',toneClear:'Net ve pratik',toneSupportive:'Destekleyici',toneCritical:'Eleştirel prodüktör',toneCreative:'Yaratıcı kâşif',goalLabel:'Hedef',goalImprove:'Mevcut şarkıyı geliştir',goalBuild:'Yeni şarkı oluştur',goalSimplify:'Sadeleştir',goalExperiment:'Deney yap',goalFinish:'Suno için tamamla',automationLabel:'Otomasyon',autoRecommend:'Yalnızca öner',autoPrepare:'Değişiklikleri hazırla',autoApply:'Güvenli değişiklikleri uygula',readProject:'Aktif projeyi oku',readStyle:'Geçerli STYLE’ı oku',readLyrics:'Lyrics Workspace’i oku',useLearning:'Yerel öğrenme geçmişini kullan',readiness:'Stüdyo hazır olma durumu',reportTitle:'Akıllı stüdyo raporu',reportDesc:'Mentor rehberliği, şarkı koçluğu, tür mantığı, ses tasarımı ve uygulanabilir iş akışı.',saveSnapshot:'Analizi kaydet',mentorSubtitle:'Ne yapılmalı ve neden',coachSubtitle:'Güçlü ve zayıf noktalar',mixerSubtitle:'Tür karışımı nasıl çalışmalı',soundSubtitle:'Bölüm, katman ve miks rehberliği',workflowTitle:'Önerilen iş akışı',workflowDesc:'Şarkıyı en yararlı sırayla tamamlayın.',actionsTitle:'Hazırlanan stüdyo eylemleri',actionsDesc:'Bağlı modüllere uygulamadan önce değişiklikleri inceleyin.',applySafe:'✅ GÜVENLİ İYİLEŞTİRMELERİ UYGULA',openNext:'Sonraki önerilen modülü aç',runPipeline:'Akıllı iş akışını çalıştır',undo:'Son uygulamayı geri al',styleTitle:'Studio Intelligence STYLE',styleDesc:'Tam analize dayalı uyumlu bir STYLE.',historyTitle:'Intelligence geçmişi',historyDesc:'Önceki stüdyo analizlerini geri yükleyin.'},
 ru:{headerDesc:'Центральный наставник читает состояние студии, объясняет главное, рекомендует следующий шаг и координирует интеллектуальные инструменты.',commandTitle:'Управление студией',commandDesc:'Опишите цель, задайте вопрос или позвольте Studio Intelligence проверить текущий проект.',briefPlaceholder:'Пример: сделай мой Viking EDM аниме-опенинг яснее, эмоциональнее и менее перегруженным.',roleLabel:'Роль интеллекта',roleDirector:'Полный директор студии',toneLabel:'Стиль совета',toneClear:'Ясно и практично',toneSupportive:'Поддерживающий',toneCritical:'Критичный продюсер',toneCreative:'Творческий исследователь',goalLabel:'Цель',goalImprove:'Улучшить существующую песню',goalBuild:'Создать новую песню',goalSimplify:'Упростить',goalExperiment:'Экспериментировать',goalFinish:'Подготовить для Suno',automationLabel:'Автоматизация',autoRecommend:'Только рекомендации',autoPrepare:'Подготовить изменения',autoApply:'Применить безопасные изменения',readProject:'Прочитать активный проект',readStyle:'Прочитать текущий STYLE',readLyrics:'Прочитать Lyrics Workspace',useLearning:'Использовать локальную историю обучения',readiness:'Готовность студии',reportTitle:'Интеллектуальный отчёт студии',reportDesc:'Советы наставника, коучинг, логика жанров, саунд-дизайн и практический рабочий процесс.',saveSnapshot:'Сохранить анализ',mentorSubtitle:'Что делать и почему',coachSubtitle:'Сильные и слабые стороны',mixerSubtitle:'Как должно работать смешение жанров',soundSubtitle:'Советы по секциям, слоям и миксу',workflowTitle:'Рекомендуемый процесс',workflowDesc:'Завершите песню в наиболее полезном порядке.',actionsTitle:'Подготовленные действия',actionsDesc:'Проверьте изменения перед применением в связанных модулях.',applySafe:'✅ ПРИМЕНИТЬ БЕЗОПАСНЫЕ УЛУЧШЕНИЯ',openNext:'Открыть следующий рекомендуемый модуль',runPipeline:'Запустить интеллектуальный процесс',undo:'Отменить последнее применение',styleTitle:'STYLE Studio Intelligence',styleDesc:'Согласованный STYLE на основе полного анализа.',historyTitle:'История Intelligence',historyDesc:'Восстановить предыдущие анализы студии.'},
 ja:{headerDesc:'中央のメンターがスタジオの状態を読み取り、重要点を説明し、次の手順を提案して各ツールを調整します。',commandTitle:'スタジオ操作',commandDesc:'目標を説明するか質問を入力し、Studio Intelligenceに現在のプロジェクトを確認させます。',briefPlaceholder:'例：Viking EDMのアニメオープニングを、より明瞭で感情的、かつ詰め込みすぎない形にする。',roleLabel:'インテリジェンスの役割',roleDirector:'総合スタジオディレクター',toneLabel:'助言スタイル',toneClear:'明確で実用的',toneSupportive:'支援的',toneCritical:'厳しいプロデューサー',toneCreative:'創造的な探求者',goalLabel:'目標',goalImprove:'既存の曲を改善',goalBuild:'新しい曲を作成',goalSimplify:'簡略化',goalExperiment:'実験',goalFinish:'Suno向けに完成',automationLabel:'自動化',autoRecommend:'提案のみ',autoPrepare:'変更を準備',autoApply:'安全な変更を適用',readProject:'現在のプロジェクトを読む',readStyle:'現在のSTYLEを読む',readLyrics:'Lyrics Workspaceを読む',useLearning:'ローカル学習履歴を使う',readiness:'スタジオ準備度',reportTitle:'インテリジェント・スタジオレポート',reportDesc:'メンター、楽曲コーチ、ジャンル設計、サウンドデザインと実行可能な手順。',saveSnapshot:'分析を保存',mentorSubtitle:'何をするか、その理由',coachSubtitle:'長所と弱点',mixerSubtitle:'ジャンルの融合方法',soundSubtitle:'セクション、レイヤー、ミックスの助言',workflowTitle:'推奨ワークフロー',workflowDesc:'最も効果的な順序で曲を完成させます。',actionsTitle:'準備された操作',actionsDesc:'接続モジュールに適用する前に変更を確認します。',applySafe:'✅ 安全な改善を適用',openNext:'次の推奨モジュールを開く',runPipeline:'インテリジェント処理を実行',undo:'最後の適用を元に戻す',styleTitle:'Studio Intelligence STYLE',styleDesc:'完全な分析に基づく調整済みSTYLE。',historyTitle:'Intelligence履歴',historyDesc:'以前のスタジオ分析を復元します。'},
 ko:{headerDesc:'중앙 멘토가 현재 스튜디오 상태를 읽고 중요한 내용을 설명하며 다음 단계를 추천하고 지능형 도구를 조정합니다.',commandTitle:'스튜디오 제어',commandDesc:'목표를 설명하거나 조언을 요청하고 Studio Intelligence가 현재 프로젝트를 검사하도록 하세요.',briefPlaceholder:'예: Viking EDM 애니메이션 오프닝을 더 선명하고 감성적이며 덜 복잡하게 만들어 주세요.',roleLabel:'지능 역할',roleDirector:'전체 스튜디오 디렉터',toneLabel:'조언 방식',toneClear:'명확하고 실용적',toneSupportive:'지원형',toneCritical:'비판적 프로듀서',toneCreative:'창의적 탐험가',goalLabel:'목표',goalImprove:'기존 곡 개선',goalBuild:'새 곡 만들기',goalSimplify:'단순화',goalExperiment:'실험',goalFinish:'Suno용으로 완성',automationLabel:'자동화',autoRecommend:'추천만',autoPrepare:'변경 준비',autoApply:'안전한 변경 적용',readProject:'활성 프로젝트 읽기',readStyle:'현재 STYLE 읽기',readLyrics:'Lyrics Workspace 읽기',useLearning:'로컬 학습 기록 사용',readiness:'스튜디오 준비도',reportTitle:'지능형 스튜디오 보고서',reportDesc:'멘토 안내, 곡 코칭, 장르 논리, 사운드 디자인과 실행 가능한 작업 흐름.',saveSnapshot:'분석 저장',mentorSubtitle:'무엇을 왜 해야 하는지',coachSubtitle:'강점과 약점',mixerSubtitle:'장르 혼합 방식',soundSubtitle:'섹션, 레이어와 믹스 안내',workflowTitle:'추천 작업 흐름',workflowDesc:'가장 유용한 순서로 곡을 완성합니다.',actionsTitle:'준비된 스튜디오 작업',actionsDesc:'연결된 모듈에 적용하기 전에 변경을 확인하세요.',applySafe:'✅ 안전한 개선 적용',openNext:'다음 추천 모듈 열기',runPipeline:'지능형 작업 흐름 실행',undo:'마지막 적용 취소',styleTitle:'Studio Intelligence STYLE',styleDesc:'전체 분석을 바탕으로 조정된 STYLE.',historyTitle:'Intelligence 기록',historyDesc:'이전 스튜디오 분석을 복원합니다.'},
 'zh-CN':{headerDesc:'中央导师会读取当前工作室状态，解释重点，推荐下一步并协调智能工具。',commandTitle:'工作室控制',commandDesc:'描述目标、提出问题，或让 Studio Intelligence 检查当前项目。',briefPlaceholder:'示例：让我的 Viking EDM 动漫片头更清晰、更有感情，并减少堆叠。',roleLabel:'智能角色',roleDirector:'完整工作室导演',toneLabel:'建议风格',toneClear:'清晰实用',toneSupportive:'支持型',toneCritical:'严格制作人',toneCreative:'创意探索者',goalLabel:'目标',goalImprove:'改进现有歌曲',goalBuild:'创建新歌曲',goalSimplify:'精简',goalExperiment:'实验',goalFinish:'为 Suno 完成',automationLabel:'自动化',autoRecommend:'仅推荐',autoPrepare:'准备更改',autoApply:'应用安全更改',readProject:'读取当前项目',readStyle:'读取当前 STYLE',readLyrics:'读取 Lyrics Workspace',useLearning:'使用本地学习记录',readiness:'工作室准备度',reportTitle:'智能工作室报告',reportDesc:'导师指导、歌曲辅导、流派逻辑、声音设计和可执行流程。',saveSnapshot:'保存分析',mentorSubtitle:'该做什么以及原因',coachSubtitle:'优点与弱点',mixerSubtitle:'流派融合方式',soundSubtitle:'段落、层次和混音指导',workflowTitle:'推荐流程',workflowDesc:'按最有效的顺序完成歌曲。',actionsTitle:'已准备的工作室操作',actionsDesc:'应用到关联模块之前先检查更改。',applySafe:'✅ 应用安全改进',openNext:'打开下一个推荐模块',runPipeline:'运行智能流程',undo:'撤销上次应用',styleTitle:'Studio Intelligence STYLE',styleDesc:'根据完整分析协调出的 STYLE。',historyTitle:'Intelligence 历史',historyDesc:'恢复以前的工作室分析。'}
});

const INITIAL=Object.freeze({
 fr:{brainReady:'Cerveau du studio prêt',readyInspect:'Prêt à examiner le studio.',noAnalysis:'Aucune analyse du studio pour le moment.',nextPlaceholder:'La prochaine étape recommandée apparaîtra ici.',stepCount:'{count} étapes',notGenerated:'Non généré',actionCount:'{count} actions',signalCount:'{count} signaux connectés',historyEmpty:'Aucun historique Studio Intelligence.'},
 es:{brainReady:'Cerebro del estudio listo',readyInspect:'Listo para revisar el estudio.',noAnalysis:'Todavía no hay análisis del estudio.',nextPlaceholder:'El siguiente paso recomendado aparecerá aquí.',stepCount:'{count} pasos',notGenerated:'No generado',actionCount:'{count} acciones',signalCount:'{count} señales conectadas',historyEmpty:'Todavía no hay historial de Studio Intelligence.'},
 it:{brainReady:'Cervello dello studio pronto',readyInspect:'Pronto a esaminare lo studio.',noAnalysis:'Nessuna analisi dello studio disponibile.',nextPlaceholder:'Il prossimo passaggio consigliato apparirà qui.',stepCount:'{count} passaggi',notGenerated:'Non generato',actionCount:'{count} azioni',signalCount:'{count} segnali collegati',historyEmpty:'Nessuna cronologia Studio Intelligence.'},
 pt:{brainReady:'Cérebro do estúdio pronto',readyInspect:'Pronto para analisar o estúdio.',noAnalysis:'Ainda não existe análise do estúdio.',nextPlaceholder:'O próximo passo recomendado aparecerá aqui.',stepCount:'{count} passos',notGenerated:'Não gerado',actionCount:'{count} ações',signalCount:'{count} sinais ligados',historyEmpty:'Ainda não existe histórico Studio Intelligence.'},
 'pt-BR':{brainReady:'Cérebro do estúdio pronto',readyInspect:'Pronto para analisar o estúdio.',noAnalysis:'Ainda não há análise do estúdio.',nextPlaceholder:'O próximo passo recomendado aparecerá aqui.',stepCount:'{count} passos',notGenerated:'Não gerado',actionCount:'{count} ações',signalCount:'{count} sinais conectados',historyEmpty:'Ainda não há histórico do Studio Intelligence.'},
 nl:{brainReady:'Studiobrein gereed',readyInspect:'Klaar om de studio te controleren.',noAnalysis:'Nog geen studioanalyse beschikbaar.',nextPlaceholder:'De volgende aanbevolen stap verschijnt hier.',stepCount:'{count} stappen',notGenerated:'Niet gegenereerd',actionCount:'{count} acties',signalCount:'{count} verbonden signalen',historyEmpty:'Nog geen Studio Intelligence-geschiedenis.'},
 pl:{brainReady:'Mózg studia gotowy',readyInspect:'Gotowe do sprawdzenia studia.',noAnalysis:'Brak analizy studia.',nextPlaceholder:'Tutaj pojawi się następny zalecany krok.',stepCount:'{count} kroków',notGenerated:'Nie wygenerowano',actionCount:'{count} działań',signalCount:'{count} połączonych sygnałów',historyEmpty:'Brak historii Studio Intelligence.'},
 tr:{brainReady:'Stüdyo beyni hazır',readyInspect:'Stüdyoyu incelemeye hazır.',noAnalysis:'Henüz stüdyo analizi yok.',nextPlaceholder:'Önerilen sonraki adım burada görünecek.',stepCount:'{count} adım',notGenerated:'Oluşturulmadı',actionCount:'{count} eylem',signalCount:'{count} bağlı sinyal',historyEmpty:'Henüz Studio Intelligence geçmişi yok.'},
 ru:{brainReady:'Мозг студии готов',readyInspect:'Готово к проверке студии.',noAnalysis:'Анализа студии пока нет.',nextPlaceholder:'Здесь появится следующий рекомендуемый шаг.',stepCount:'{count} шагов',notGenerated:'Не создано',actionCount:'{count} действий',signalCount:'{count} связанных сигналов',historyEmpty:'Истории Studio Intelligence пока нет.'},
 ja:{brainReady:'スタジオブレイン準備完了',readyInspect:'スタジオを確認できます。',noAnalysis:'スタジオ分析はまだありません。',nextPlaceholder:'次の推奨手順がここに表示されます。',stepCount:'{count}ステップ',notGenerated:'未生成',actionCount:'{count}件の操作',signalCount:'{count}個の接続信号',historyEmpty:'Studio Intelligenceの履歴はまだありません。'},
 ko:{brainReady:'스튜디오 브레인 준비됨',readyInspect:'스튜디오를 검사할 준비가 되었습니다.',noAnalysis:'아직 스튜디오 분석이 없습니다.',nextPlaceholder:'다음 추천 단계가 여기에 표시됩니다.',stepCount:'{count}단계',notGenerated:'생성되지 않음',actionCount:'{count}개 작업',signalCount:'{count}개 연결 신호',historyEmpty:'아직 Studio Intelligence 기록이 없습니다.'},
 'zh-CN':{brainReady:'工作室大脑已就绪',readyInspect:'可以检查工作室。',noAnalysis:'尚无工作室分析。',nextPlaceholder:'下一个推荐步骤会显示在这里。',stepCount:'{count} 个步骤',notGenerated:'尚未生成',actionCount:'{count} 个操作',signalCount:'{count} 个已连接信号',historyEmpty:'尚无 Studio Intelligence 历史记录。'}
});

const DYNAMIC=Object.freeze({
 en:Object.freeze({
  noInput:'Add a goal or import Studio context first.',noStyle:'No active STYLE is available. Start with AI Producer or Song Director.',styleAvailable:'A STYLE with {count} terms is available.',longStyle:'The STYLE is long and may benefit from simplification.',healthLow:'The latest Health Check score is {score}/100.',conflicts:'{count} unresolved or recently detected conflict(s).',genreCompetition:'{count} genre signals compete for attention.',primaryIdentity:'{name} is the strongest musical identity.',secondaryIdentity:'{name} can work as a supporting influence.',noVocal:'The STYLE has no clear vocal direction.',vocalPresent:'A vocal direction is present.',noArc:'The STYLE does not clearly describe an energy or section arc.',arcPresent:'The prompt contains section or dynamic guidance.',
  keepBoth:'Keep {primary} as the main identity and use {secondary} only as a supporting color.',keepOne:'Keep {primary} as the main identity.',chooseGenre:'Choose one clear main genre before adding detailed production terms.',firstIssue:'Address the highest-impact issue first: {issue}',coherent:'The concept is coherent; move to arrangement and final validation.',priorities:'Use fewer simultaneous priorities and distribute complexity across song sections.',strengthPrefix:'Strength: {text}',improvePrefix:'Improve: {text}',lyricsDetected:'Lyrics context detected with approximately {count} words.',noLyrics:'No Lyrics Workspace content was detected.',
  mixBoth:'Primary: {primary}. Supporting influence: {secondary}.',corePalette:'Use {items} as the core palette.',supportingPalette:'Introduce {items} only in transitions, bridge or final chorus.',singleGenre:'{primary} is sufficiently clear as a single main identity.',alternatives:'Potential alternatives: {items}.',noBlend:'No reliable genre blend could be detected. Start with AI Producer.',introCustom:'Intro: establish the identity with {items}.',introGeneric:'Intro: establish the identity with one main motif and restrained texture.',verseSound:'Verse: reduce density and protect the vocal range.',chorusSound:'Chorus: widen the mix, strengthen drums and introduce the main hook.',bridgeSound:'Bridge: remove one core layer to create contrast.',finalSound:'Final Chorus: use the full palette, choir or harmony stack and the widest production.',productionAnchor:'Production anchor: {value}.',
  simplifyLabel:'Simplify STYLE',simplifyDetail:'Reduce repeated and low-priority terms.',healthLabel:'Repair Health Issues',healthDetail:'Use the repaired STYLE from Style Health Check.',conflictLabel:'Resolve Conflicts',conflictDetail:'Apply the Conflict Resolver output.',focusLabel:'Focus Genre Blend',focusDetail:'Keep one primary and one supporting genre.',styleLabel:'Apply Coordinated STYLE',styleDetail:'Use the Studio Intelligence STYLE as the new focused master prompt.',producerLabel:'Refresh AI Producer',producerDetail:'Generate recommendations from the coordinated Studio context.',variationLabel:'Create Alternatives',variationDetail:'Generate controlled alternatives after the core is stable.',
  workflowProducer:'Confirm genre, tempo, vocals and palette.',workflowConflict:'Separate contradictory directions.',workflowSimplifier:'Reduce prompt density.',workflowHealth:'Validate final STYLE health.',workflowArrangement:'Plan section energy and layers.',workflowVocals:'Assign performer roles.',workflowTheory:'Confirm key, mode and harmonic arc.',workflowPredictor:'Run final Suno readiness check.',
  brainReady:'Studio brain ready',readyInspect:'Ready to inspect the Studio.',noAnalysis:'No Studio analysis yet.',nextPlaceholder:'The next recommended step will appear here.',stepCount:'{count} steps',notGenerated:'Not generated',
  summaryIssues:'{strengths} strengths and {issues} improvement areas were detected.',summaryGood:'The Studio state is coherent and ready for final development.',metricStrengths:'Strengths',metricIssues:'Issues',metricActions:'Actions',metricWorkflow:'Workflow',metricPrimary:'Primary',metricSecondary:'Secondary',unknown:'Unknown',none:'None',recommendedNext:'Recommended next step:',finalStep:'Final Success Predictor and export.',complete:'complete',includeAction:'Include action',actionCount:'{count} actions',styleReady:'Coordinated STYLE ready',readinessValue:'Readiness {score}/100',signalCount:'{count} connected signals',analysisComplete:'Studio Intelligence analysis complete.',applied:'Applied {count} safe Studio improvement(s).',pipeline:'Intelligent pipeline prepared: coordinated STYLE → Health Check.',undoMissing:'No Studio Intelligence application to undo.',undoDone:'Last Studio Intelligence application undone.',currentStyle:'Current STYLE: {value}',lyricsConcept:'Lyrics concept: {value}',projectName:'Project: {value}',inspectDefault:'Inspect the current Studio and recommend the best next step.',historyContext:'Studio context analysis',load:'Load',historyEmpty:'No Studio Intelligence history yet.',noProject:'No active project track found.',snapshotSaved:'Studio Intelligence snapshot saved.',exportTitle:'STUDIO INTELLIGENCE REPORT',exportReadiness:'Readiness',exportGoal:'Goal',exportWorkflow:'WORKFLOW',exportDone:'DONE',exportNext:'NEXT',exportStyle:'STYLE',example:'Improve my Viking EDM anime opening. Keep female lead and deep male narrator, reduce overload, strengthen the final chorus and make the STYLE safer for Suno.'
 }),
 de:Object.freeze({
  noInput:'Füge zuerst ein Ziel hinzu oder importiere den Studio-Kontext.',noStyle:'Kein aktiver STYLE vorhanden. Beginne mit AI Producer oder Song Director.',styleAvailable:'Ein STYLE mit {count} Begriffen ist vorhanden.',longStyle:'Der STYLE ist lang und sollte möglicherweise vereinfacht werden.',healthLow:'Der letzte Health-Check-Wert liegt bei {score}/100.',conflicts:'{count} ungelöste oder kürzlich erkannte Konflikte.',genreCompetition:'{count} Genre-Signale konkurrieren um die Priorität.',primaryIdentity:'{name} ist die stärkste musikalische Identität.',secondaryIdentity:'{name} eignet sich als unterstützender Einfluss.',noVocal:'Der STYLE enthält keine klare Vocal-Richtung.',vocalPresent:'Eine Vocal-Richtung ist vorhanden.',noArc:'Der STYLE beschreibt noch keinen klaren Energie- oder Abschnittsbogen.',arcPresent:'Der Prompt enthält Abschnitts- oder Dynamikhinweise.',
  keepBoth:'Behalte {primary} als Hauptidentität und nutze {secondary} nur als unterstützende Farbe.',keepOne:'Behalte {primary} als Hauptidentität.',chooseGenre:'Wähle zuerst ein klares Hauptgenre, bevor du Produktionsdetails ergänzt.',firstIssue:'Bearbeite zuerst das wichtigste Problem: {issue}',coherent:'Das Konzept ist stimmig. Fahre mit Arrangement und Abschlussprüfung fort.',priorities:'Nutze weniger gleichzeitige Prioritäten und verteile Komplexität auf die Songabschnitte.',strengthPrefix:'Stärke: {text}',improvePrefix:'Verbessern: {text}',lyricsDetected:'Lyrics-Kontext mit ungefähr {count} Wörtern erkannt.',noLyrics:'Im Lyrics Workspace wurde kein Inhalt erkannt.',
  mixBoth:'Hauptgenre: {primary}. Unterstützender Einfluss: {secondary}.',corePalette:'Nutze {items} als Kernpalette.',supportingPalette:'Setze {items} nur in Übergängen, Bridge oder Schlussrefrain ein.',singleGenre:'{primary} ist als einzelne Hauptidentität ausreichend klar.',alternatives:'Mögliche Alternativen: {items}.',noBlend:'Keine zuverlässige Genre-Mischung erkannt. Beginne mit AI Producer.',introCustom:'Intro: Stelle die Identität mit {items} vor.',introGeneric:'Intro: Stelle die Identität mit einem Hauptmotiv und zurückhaltender Textur vor.',verseSound:'Verse: Reduziere die Dichte und schütze den Vocal-Bereich.',chorusSound:'Chorus: Verbreitere den Mix, verstärke die Drums und führe den Haupthook ein.',bridgeSound:'Bridge: Entferne ein Kern-Layer, um Kontrast zu schaffen.',finalSound:'Final Chorus: Nutze die volle Palette, Chor oder Harmonie-Layer und die größte Breite.',productionAnchor:'Produktionsanker: {value}.',
  simplifyLabel:'STYLE vereinfachen',simplifyDetail:'Wiederholte und unwichtige Begriffe reduzieren.',healthLabel:'Health-Probleme reparieren',healthDetail:'Den reparierten STYLE aus dem Style Health Check verwenden.',conflictLabel:'Konflikte lösen',conflictDetail:'Die Ausgabe des Conflict Resolver anwenden.',focusLabel:'Genre-Mischung fokussieren',focusDetail:'Ein Hauptgenre und einen unterstützenden Einfluss behalten.',styleLabel:'Abgestimmten STYLE anwenden',styleDetail:'Den Studio-Intelligence-STYLE als neuen fokussierten Hauptprompt verwenden.',producerLabel:'AI Producer aktualisieren',producerDetail:'Empfehlungen aus dem abgestimmten Studio-Kontext erzeugen.',variationLabel:'Alternativen erstellen',variationDetail:'Kontrollierte Alternativen erzeugen, nachdem der Kern stabil ist.',
  workflowProducer:'Genre, Tempo, Vocals und Klangpalette bestätigen.',workflowConflict:'Widersprüchliche Richtungen voneinander trennen.',workflowSimplifier:'Prompt-Dichte reduzieren.',workflowHealth:'Abschließende STYLE-Gesundheit prüfen.',workflowArrangement:'Abschnittsenergie und Layer planen.',workflowVocals:'Rollen der Stimmen zuweisen.',workflowTheory:'Tonart, Modus und harmonischen Bogen bestätigen.',workflowPredictor:'Abschließende Suno-Bereitschaft prüfen.',
  brainReady:'Studio-Gehirn bereit',readyInspect:'Bereit, das Studio zu prüfen.',noAnalysis:'Noch keine Studio-Analyse vorhanden.',nextPlaceholder:'Der nächste empfohlene Schritt erscheint hier.',stepCount:'{count} Schritte',notGenerated:'Noch nicht erzeugt',
  summaryIssues:'{strengths} Stärken und {issues} Verbesserungsbereiche erkannt.',summaryGood:'Der Studio-Stand ist stimmig und bereit für die letzte Ausarbeitung.',metricStrengths:'Stärken',metricIssues:'Probleme',metricActions:'Aktionen',metricWorkflow:'Ablauf',metricPrimary:'Hauptgenre',metricSecondary:'Zweitgenre',unknown:'Unbekannt',none:'Keine',recommendedNext:'Empfohlener nächster Schritt:',finalStep:'Abschließender Success Predictor und Export.',complete:'abgeschlossen',includeAction:'Aktion einbeziehen',actionCount:'{count} Aktionen',styleReady:'Abgestimmter STYLE bereit',readinessValue:'Bereitschaft {score}/100',signalCount:'{count} verbundene Signale',analysisComplete:'Studio-Intelligence-Analyse abgeschlossen.',applied:'{count} sichere Studio-Verbesserungen angewendet.',pipeline:'Intelligente Pipeline vorbereitet: abgestimmter STYLE → Health Check.',undoMissing:'Keine Studio-Intelligence-Anwendung zum Rückgängigmachen vorhanden.',undoDone:'Letzte Studio-Intelligence-Anwendung rückgängig gemacht.',currentStyle:'Aktueller STYLE: {value}',lyricsConcept:'Lyrics-Konzept: {value}',projectName:'Projekt: {value}',inspectDefault:'Prüfe das aktuelle Studio und empfehle den besten nächsten Schritt.',historyContext:'Studio-Kontextanalyse',load:'Laden',historyEmpty:'Noch kein Studio-Intelligence-Verlauf vorhanden.',noProject:'Kein aktiver Projekt-Track gefunden.',snapshotSaved:'Studio-Intelligence-Stand gespeichert.',exportTitle:'STUDIO-INTELLIGENCE-BERICHT',exportReadiness:'Bereitschaft',exportGoal:'Ziel',exportWorkflow:'ARBEITSABLAUF',exportDone:'FERTIG',exportNext:'NÄCHSTER SCHRITT',exportStyle:'STYLE',example:'Verbessere mein Viking-EDM-Anime-Opening. Behalte weiblichen Lead und tiefen männlichen Erzähler, reduziere Überladung, stärke den Schlussrefrain und mache den STYLE sicherer für Suno.'
 })
});

const COMMON_KEYS=Object.freeze({clear:'clear',copyReport:'copyReport',exportJson:'exportJson',copyStyle:'copy',health:'runHealth',producer:'sendProducer',clearHistory:'clearHistory'});
const TEXT_BINDINGS=Object.freeze([
 ['#studioIntelligenceView>.view-head p','headerDesc'],['#studioIntelligenceView .si-command-panel .aip-title h2','commandTitle'],['#studioIntelligenceView .si-command-panel .aip-title p','commandDesc'],
 ['#siRole option[value="mentor"]','roleMentor'],['#siRole option[value="coach"]','roleCoach'],['#siRole option[value="mixer"]','roleMixer'],['#siRole option[value="sound"]','roleSound'],['#siRole option[value="director"]','roleDirector'],
 ['#siTone option[value="clear"]','toneClear'],['#siTone option[value="supportive"]','toneSupportive'],['#siTone option[value="critical"]','toneCritical'],['#siTone option[value="creative"]','toneCreative'],
 ['#siGoal option[value="improve"]','goalImprove'],['#siGoal option[value="build"]','goalBuild'],['#siGoal option[value="simplify"]','goalSimplify'],['#siGoal option[value="experiment"]','goalExperiment'],['#siGoal option[value="finish"]','goalFinish'],
 ['#siAutomation option[value="recommend"]','autoRecommend'],['#siAutomation option[value="prepare"]','autoPrepare'],['#siAutomation option[value="apply"]','autoApply'],
 ['#siAnalyze','analyze'],['#siImport','import'],['#siExample','example'],['#siClear','clear'],['#studioIntelligenceView .si-overview-panel .aip-score-head span','readiness'],
 ['#siResults>.aip-title h2','reportTitle'],['#siResults>.aip-title p','reportDesc'],['#siCopyReport','copyReport'],['#siExport','exportJson'],['#siSaveProject','saveSnapshot'],
 ['#siMentor','__dynamic'],['#studioIntelligenceView .si-role-card:nth-child(1) small','mentorSubtitle'],['#studioIntelligenceView .si-role-card:nth-child(2) small','coachSubtitle'],['#studioIntelligenceView .si-role-card:nth-child(3) small','mixerSubtitle'],['#studioIntelligenceView .si-role-card:nth-child(4) small','soundSubtitle'],
 ['#studioIntelligenceView .si-workflow-panel h2','workflowTitle'],['#studioIntelligenceView .si-workflow-panel .aip-title p','workflowDesc'],['#studioIntelligenceView .si-action-panel h2','actionsTitle'],['#studioIntelligenceView .si-action-panel .aip-title p','actionsDesc'],
 ['#siApplySafe','applySafe'],['#siOpenNext','openNext'],['#siRunPipeline','runPipeline'],['#siUndo','undo'],['#studioIntelligenceView .aip-style-panel h2','styleTitle'],['#studioIntelligenceView .aip-style-panel .aip-title p','styleDesc'],
 ['#siCopyStyle','copyStyle'],['#siSendHealth','health'],['#siSendProducer','producer'],['#studioIntelligenceView .si-history-panel h2','historyTitle'],['#studioIntelligenceView .si-history-panel .aip-title p','historyDesc'],['#siClearHistory','clearHistory']
]);
const DIRECT_BINDINGS=Object.freeze([
 ['#siRole','roleLabel'],['#siTone','toneLabel'],['#siGoal','goalLabel'],['#siAutomation','automationLabel'],['#siUseProject','readProject'],['#siUseStyle','readStyle'],['#siUseLyrics','readLyrics'],['#siUseLearning','useLearning']
]);

function language(){return Catalog.languageOf(root.NSWWorkspaceI18n?.getLanguage?.()||root.NSWInterfaceI18n?.getLanguage?.()||document.documentElement.lang)}
function value(key,code=language()){
 if(COMMON_KEYS[key])return Catalog.uiText(code,COMMON_KEYS[key]);
 if(key==='analyze')return `🧠 ${Catalog.uiText(code,'analyze').toUpperCase()}`;
 if(key==='import')return Catalog.uiText(code,'importStyle');
 if(key==='example')return ({en:'Load Example',de:'Beispiel laden',fr:'Charger un exemple',es:'Cargar ejemplo',it:'Carica esempio',pt:'Carregar exemplo','pt-BR':'Carregar exemplo',nl:'Voorbeeld laden',pl:'Wczytaj przykład',tr:'Örneği yükle',ru:'Загрузить пример',ja:'例を読み込む',ko:'예시 불러오기','zh-CN':'加载示例'})[code];
 if(key==='copyStyle')return `${Catalog.uiText(code,'copy')} STYLE`;
 const source=DynamicLocales?.DATA?.[code]?.[key]||DYNAMIC[code]?.[key]||INITIAL[code]?.[key]||DYNAMIC.en[key]||L[code]?.[key]||EN[key]||key;
 return source;
}
function format(key,variables={},code=language()){
 return String(value(key,code)).replace(/\{([^}]+)\}/g,(match,name)=>variables[name]!=null?String(variables[name]):match);
}
function setDirect(control,text){
 const label=control?.closest('label');if(!label)return;
 const node=[...label.childNodes].find(item=>item.nodeType===Node.TEXT_NODE&&item.textContent.trim());
 if(node)node.textContent=text;
}
function apply(){
 const code=language();
 TEXT_BINDINGS.forEach(([selector,key])=>{if(key==='__dynamic')return;document.querySelectorAll(selector).forEach(element=>element.textContent=value(key,code))});
 DIRECT_BINDINGS.forEach(([selector,key])=>document.querySelectorAll(selector).forEach(control=>setDirect(control,value(key,code))));
 const brief=document.getElementById('siBrief');if(brief)brief.placeholder=value('briefPlaceholder',code);
 return code;
}

root.NSWStudioIntelligenceI18n=Object.freeze({VERSION:'7.5.7',languages:Catalog.LANGUAGES,dynamicKeys:Object.freeze(Object.keys(DYNAMIC.en)),language,value,format,apply});
document.addEventListener('nordlicht-language-changed',apply);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})(typeof globalThis!=='undefined'?globalThis:this);
