(function(root,factory){
'use strict';
const api=factory();
if(typeof module==='object'&&module.exports)module.exports=api;
if(root)root.NSWUXFoundationI18n=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

const KEYS=Object.freeze([
 'helpLabel','contextCounter','gotIt','close','searchPlaceholder','noResults',
 'previewTitle','previewIntro','affected','cancel','continueAction','applied','changed','undo','keep','undone',
 'releaseCenterTitle','currentVersion','previousReleases','newBadge','versionLabel','releaseTitle7510',
 'release7510Item1','release7510Item2','release7510Item3','release7510Item4','release7510Item5','noCoreChanges'
]);

const ROWS={
 en:['Explain this area','Context help','Got it','Close','Search modules…','No matching module found.','Review changes','This action can update several connected areas. Review them before continuing.','Affected areas','Cancel','Apply changes','Change applied','Changed','Undo','Keep','Last change undone.','Changelog','Current version','Previous releases','NEW','Version','UX Foundations & Contextual Help','One canonical release manifest keeps every version display and the changelog synchronized.','Favorites and recent modules now use one migrated workspace state.','Small ? buttons open only the matching help step and navigate to the correct workspace and tab.','Large cross-module actions show affected areas before applying and offer reliable undo.','All new dynamic UX text is complete in all 14 interface languages.','No core area changed.'],
 de:['Diesen Bereich erklären','Kontextbezogene Hilfe','Verstanden','Schließen','Module suchen…','Kein passendes Modul gefunden.','Änderungen prüfen','Diese Aktion kann mehrere verbundene Bereiche verändern. Prüfe sie, bevor du fortfährst.','Betroffene Bereiche','Abbrechen','Änderungen anwenden','Änderung angewendet','Geändert','Rückgängig','Behalten','Die letzte Änderung wurde rückgängig gemacht.','Changelog','Aktuelle Version','Frühere Versionen','NEU','Version','UX-Grundlagen & kontextbezogene Hilfe','Ein zentrales Release-Manifest hält alle Versionsanzeigen und das Changelog synchron.','Favoriten und zuletzt verwendete Module nutzen nun einen gemeinsamen, migrierten Workspace-Zustand.','Kleine ?-Schaltflächen öffnen nur den passenden Hilfeschritt und führen zum richtigen Workspace und Reiter.','Große modulübergreifende Aktionen zeigen vorab die betroffenen Bereiche und bieten ein zuverlässiges Rückgängig.','Alle neuen dynamischen UX-Texte sind in sämtlichen 14 Oberflächensprachen vollständig.','Kein zentraler Bereich wurde verändert.'],
 fr:['Expliquer cette zone','Aide contextuelle','Compris','Fermer','Rechercher des modules…','Aucun module correspondant.','Vérifier les modifications','Cette action peut modifier plusieurs zones connectées. Vérifiez-les avant de continuer.','Zones concernées','Annuler','Appliquer les modifications','Modification appliquée','Modifié','Annuler la modification','Conserver','La dernière modification a été annulée.','Journal des modifications','Version actuelle','Versions précédentes','NOUVEAU','Version','Fondations UX et aide contextuelle','Un manifeste de version central maintient toutes les versions affichées et le journal synchronisés.','Les favoris et modules récents utilisent désormais un état d’espace de travail unique et migré.','Les petits boutons ? ouvrent uniquement l’étape d’aide correspondante et conduisent au bon espace et onglet.','Les grandes actions entre modules affichent les zones concernées avant application et offrent une annulation fiable.','Tous les nouveaux textes UX dynamiques sont complets dans les 14 langues de l’interface.','Aucune zone principale n’a été modifiée.'],
 es:['Explicar esta área','Ayuda contextual','Entendido','Cerrar','Buscar módulos…','No se encontró ningún módulo.','Revisar cambios','Esta acción puede modificar varias áreas conectadas. Revísalas antes de continuar.','Áreas afectadas','Cancelar','Aplicar cambios','Cambio aplicado','Modificado','Deshacer','Conservar','Se deshizo el último cambio.','Historial de cambios','Versión actual','Versiones anteriores','NUEVO','Versión','Fundamentos de UX y ayuda contextual','Un manifiesto central mantiene sincronizadas todas las versiones mostradas y el historial.','Los favoritos y módulos recientes usan ahora un único estado de espacio de trabajo migrado.','Los pequeños botones ? abren solo el paso de ayuda correspondiente y llevan al espacio y pestaña correctos.','Las acciones grandes entre módulos muestran antes las áreas afectadas y ofrecen un deshacer fiable.','Todos los nuevos textos UX dinámicos están completos en los 14 idiomas de la interfaz.','No cambió ninguna área principal.'],
 it:['Spiega quest’area','Aiuto contestuale','Capito','Chiudi','Cerca moduli…','Nessun modulo corrispondente.','Controlla modifiche','Questa azione può modificare più aree collegate. Controllale prima di continuare.','Aree interessate','Annulla','Applica modifiche','Modifica applicata','Modificato','Annulla modifica','Mantieni','L’ultima modifica è stata annullata.','Registro modifiche','Versione attuale','Versioni precedenti','NUOVO','Versione','Fondamenta UX e aiuto contestuale','Un manifesto di rilascio centrale mantiene sincronizzate tutte le versioni visualizzate e il registro.','Preferiti e moduli recenti ora usano un unico stato dell’area di lavoro migrato.','I piccoli pulsanti ? aprono solo il passaggio di aiuto corretto e portano all’area e alla scheda giuste.','Le grandi azioni tra moduli mostrano prima le aree interessate e offrono un annullamento affidabile.','Tutti i nuovi testi UX dinamici sono completi nelle 14 lingue dell’interfaccia.','Nessuna area principale è stata modificata.'],
 pt:['Explicar esta área','Ajuda contextual','Entendido','Fechar','Pesquisar módulos…','Nenhum módulo correspondente.','Rever alterações','Esta ação pode alterar várias áreas ligadas. Reveja-as antes de continuar.','Áreas afetadas','Cancelar','Aplicar alterações','Alteração aplicada','Alterado','Desfazer','Manter','A última alteração foi desfeita.','Registo de alterações','Versão atual','Versões anteriores','NOVO','Versão','Bases de UX e ajuda contextual','Um manifesto central mantém sincronizadas todas as versões apresentadas e o registo de alterações.','Favoritos e módulos recentes usam agora um único estado de área de trabalho migrado.','Os pequenos botões ? abrem apenas o passo de ajuda adequado e levam à área e ao separador corretos.','As grandes ações entre módulos mostram primeiro as áreas afetadas e oferecem um desfazer fiável.','Todos os novos textos UX dinâmicos estão completos nos 14 idiomas da interface.','Nenhuma área principal foi alterada.'],
 'pt-BR':['Explicar esta área','Ajuda contextual','Entendi','Fechar','Pesquisar módulos…','Nenhum módulo correspondente.','Revisar alterações','Esta ação pode alterar várias áreas conectadas. Revise-as antes de continuar.','Áreas afetadas','Cancelar','Aplicar alterações','Alteração aplicada','Alterado','Desfazer','Manter','A última alteração foi desfeita.','Histórico de alterações','Versão atual','Versões anteriores','NOVO','Versão','Fundamentos de UX e ajuda contextual','Um manifesto central mantém sincronizadas todas as versões exibidas e o histórico.','Favoritos e módulos recentes agora usam um único estado de espaço de trabalho migrado.','Os pequenos botões ? abrem apenas a etapa de ajuda adequada e levam ao espaço e à guia corretos.','As grandes ações entre módulos mostram antes as áreas afetadas e oferecem um desfazer confiável.','Todos os novos textos UX dinâmicos estão completos nos 14 idiomas da interface.','Nenhuma área principal foi alterada.'],
 nl:['Dit onderdeel uitleggen','Contextuele hulp','Begrepen','Sluiten','Modules zoeken…','Geen passende module gevonden.','Wijzigingen controleren','Deze actie kan meerdere gekoppelde onderdelen wijzigen. Controleer ze voordat je doorgaat.','Betrokken onderdelen','Annuleren','Wijzigingen toepassen','Wijziging toegepast','Gewijzigd','Ongedaan maken','Behouden','De laatste wijziging is ongedaan gemaakt.','Wijzigingslog','Huidige versie','Eerdere versies','NIEUW','Versie','UX-fundamenten en contextuele hulp','Eén centraal releasemanifest houdt alle versieaanduidingen en het wijzigingslog gelijk.','Favorieten en recente modules gebruiken nu één gemigreerde werkruimtestatus.','Kleine ?-knoppen openen alleen de passende hulpstap en gaan naar de juiste werkruimte en tab.','Grote acties tussen modules tonen vooraf de betrokken onderdelen en bieden betrouwbaar ongedaan maken.','Alle nieuwe dynamische UX-teksten zijn volledig in alle 14 interfacetalen.','Geen kernonderdeel is gewijzigd.'],
 pl:['Wyjaśnij ten obszar','Pomoc kontekstowa','Rozumiem','Zamknij','Szukaj modułów…','Nie znaleziono pasującego modułu.','Sprawdź zmiany','Ta czynność może zmienić kilka połączonych obszarów. Sprawdź je przed kontynuacją.','Obszary objęte zmianą','Anuluj','Zastosuj zmiany','Zastosowano zmianę','Zmieniono','Cofnij','Zachowaj','Ostatnia zmiana została cofnięta.','Dziennik zmian','Bieżąca wersja','Poprzednie wersje','NOWOŚĆ','Wersja','Podstawy UX i pomoc kontekstowa','Centralny manifest wydania synchronizuje wszystkie oznaczenia wersji i dziennik zmian.','Ulubione i ostatnie moduły korzystają teraz z jednego przeniesionego stanu obszaru roboczego.','Małe przyciski ? otwierają tylko odpowiedni krok pomocy i prowadzą do właściwego obszaru i karty.','Duże działania między modułami pokazują wcześniej objęte obszary i zapewniają niezawodne cofanie.','Wszystkie nowe dynamiczne teksty UX są kompletne w 14 językach interfejsu.','Nie zmieniono żadnego głównego obszaru.'],
 tr:['Bu alanı açıkla','Bağlamsal yardım','Anladım','Kapat','Modül ara…','Eşleşen modül bulunamadı.','Değişiklikleri incele','Bu işlem birden fazla bağlı alanı değiştirebilir. Devam etmeden önce alanları inceleyin.','Etkilenen alanlar','İptal','Değişiklikleri uygula','Değişiklik uygulandı','Değiştirildi','Geri al','Koru','Son değişiklik geri alındı.','Değişiklik günlüğü','Geçerli sürüm','Önceki sürümler','YENİ','Sürüm','UX temelleri ve bağlamsal yardım','Merkezi sürüm bildirimi tüm sürüm gösterimlerini ve günlüğü eşit tutar.','Favoriler ve son modüller artık taşınmış tek bir çalışma alanı durumu kullanır.','Küçük ? düğmeleri yalnızca uygun yardım adımını açar ve doğru çalışma alanı ile sekmeye götürür.','Büyük modüller arası işlemler önce etkilenen alanları gösterir ve güvenilir geri alma sunar.','Tüm yeni dinamik UX metinleri 14 arayüz dilinin tamamında eksiksizdir.','Hiçbir ana alan değişmedi.'],
 ru:['Объяснить этот раздел','Контекстная помощь','Понятно','Закрыть','Поиск модулей…','Подходящий модуль не найден.','Проверить изменения','Это действие может изменить несколько связанных разделов. Проверьте их перед продолжением.','Затрагиваемые разделы','Отмена','Применить изменения','Изменение применено','Изменено','Отменить','Сохранить','Последнее изменение отменено.','Журнал изменений','Текущая версия','Предыдущие версии','НОВОЕ','Версия','Основы UX и контекстная помощь','Единый манифест выпуска синхронизирует все номера версий и журнал изменений.','Избранные и недавние модули теперь используют единое перенесённое состояние рабочего пространства.','Маленькие кнопки ? открывают только нужный шаг помощи и переходят к правильному разделу и вкладке.','Крупные действия между модулями заранее показывают затрагиваемые разделы и поддерживают надёжную отмену.','Все новые динамические UX-тексты полностью доступны на 14 языках интерфейса.','Ни один основной раздел не изменён.'],
 ja:['このエリアを説明','コンテキストヘルプ','了解','閉じる','モジュールを検索…','一致するモジュールがありません。','変更を確認','この操作は複数の連携エリアを変更する場合があります。続行前に確認してください。','対象エリア','キャンセル','変更を適用','変更を適用しました','変更済み','元に戻す','保持','最後の変更を元に戻しました。','変更履歴','現在のバージョン','以前のバージョン','新規','バージョン','UX基盤とコンテキストヘルプ','中央のリリースマニフェストが、すべてのバージョン表示と変更履歴を同期します。','お気に入りと最近のモジュールは、移行済みの単一ワークスペース状態を使用します。','小さな?ボタンは対応するヘルプだけを開き、正しいワークスペースとタブへ移動します。','大きなモジュール間操作は適用前に対象を表示し、確実に元へ戻せます。','新しい動的UXテキストは14のインターフェース言語すべてで揃っています。','主要エリアは変更されませんでした。'],
 ko:['이 영역 설명','상황별 도움말','알겠습니다','닫기','모듈 검색…','일치하는 모듈이 없습니다.','변경 사항 검토','이 작업은 연결된 여러 영역을 변경할 수 있습니다. 계속하기 전에 확인하세요.','영향받는 영역','취소','변경 적용','변경 사항 적용됨','변경됨','실행 취소','유지','마지막 변경을 취소했습니다.','변경 기록','현재 버전','이전 버전','새 기능','버전','UX 기반과 상황별 도움말','중앙 릴리스 매니페스트가 모든 버전 표시와 변경 기록을 동기화합니다.','즐겨찾기와 최근 모듈은 이제 마이그레이션된 하나의 작업 영역 상태를 사용합니다.','작은 ? 버튼은 해당 도움말 단계만 열고 올바른 작업 영역과 탭으로 이동합니다.','큰 모듈 간 작업은 적용 전에 영향받는 영역을 보여주고 안정적인 실행 취소를 제공합니다.','모든 새로운 동적 UX 텍스트가 14개 인터페이스 언어로 완성되었습니다.','핵심 영역은 변경되지 않았습니다.'],
 'zh-CN':['说明此区域','情境帮助','知道了','关闭','搜索模块…','未找到匹配的模块。','检查更改','此操作可能会更改多个关联区域。继续前请先检查。','受影响区域','取消','应用更改','已应用更改','已更改','撤销','保留','已撤销上一次更改。','更新日志','当前版本','以前的版本','新功能','版本','UX 基础与情境帮助','中央版本清单让所有版本显示和更新日志保持同步。','收藏和最近模块现在使用一个已迁移的工作区状态。','小型 ? 按钮只打开对应的帮助步骤，并前往正确的工作区和标签页。','大型跨模块操作会在应用前显示受影响区域，并提供可靠的撤销。','所有新的动态 UX 文本均已完整支持 14 种界面语言。','未更改任何核心区域。']
};

const LANGUAGES=Object.freeze(Object.keys(ROWS));
const DATA=Object.freeze(Object.fromEntries(LANGUAGES.map(language=>[
 language,
 Object.freeze(Object.fromEntries(KEYS.map((key,index)=>[key,ROWS[language][index]])))
])));

function languageOf(value){
 const raw=String(value||'en').trim(),lower=raw.toLowerCase();
 const exact=LANGUAGES.find(language=>language.toLowerCase()===lower);
 if(exact)return exact;
 const base=lower.split('-')[0];
 return LANGUAGES.find(language=>language.toLowerCase().split('-')[0]===base)||'en';
}
function text(language,key){return DATA[languageOf(language)]?.[key]||DATA.en[key]||key}
function validate(){
 const missing={};
 LANGUAGES.forEach(language=>{
  const absent=KEYS.filter((key,index)=>typeof ROWS[language][index]!=='string'||!ROWS[language][index].trim());
  if(ROWS[language].length!==KEYS.length)absent.push(`row-length:${ROWS[language].length}/${KEYS.length}`);
  if(absent.length)missing[language]=absent;
 });
 return Object.freeze({valid:Object.keys(missing).length===0,missing:Object.freeze(missing)});
}

return Object.freeze({VERSION:'7.5.10',KEYS,LANGUAGES,DATA,languageOf,text,validate});
});
