
(function(){'use strict';const $=id=>document.getElementById(id);let rows=[],pron='';
function source(){return window.NSW_VOCAL_DIRECTOR_LAST?.sections||[]}
function trans(a,b){if((a.intensity||0)<(b.intensity||0)-20)return'Breath pickup and stronger attack';if((a.intensity||0)>(b.intensity||0)+20)return'Drop to intimate close-mic';if(a.identity!==b.identity)return'Clear performer handoff with one-beat pause';return'Smooth character transition'}
function build(){const s=source();rows=s.map((x,i)=>({name:x.name,performer:/narrator|spoken/i.test(x.identity)?$('vd2Secondary').value:$('vd2Primary').value,range:/chorus|final/i.test(x.name)?'Upper-Mid to High':/intro|outro/i.test(x.name)?'Low to Mid':'Mid',technique:x.character||'Controlled',background:/chorus|final/i.test(x.name)?'Wide Harmony Stack':/pre/i.test(x.name)?'Third Above Harmony':'Minimal',adlibs:/final/i.test(x.name)?'High sustained ad-libs':/chorus/i.test(x.name)?'Short response ad-libs':'None',transition:i?trans(s[i-1],x):'Opening entry'}));render();expose()}
function render(){const roles=[...new Set(rows.map(x=>x.performer).filter(x=>x!=='None'))];$('vd2CastCount').textContent=`${roles.length} cast roles`;$('vd2Cards').innerHTML=[['Primary',$('vd2Primary').value],['Secondary',$('vd2Secondary').value],['Range',$('vd2Range').value],['Separation',$('vd2Separation').value],['Sections',rows.length],['Pronunciation',pron?'Saved':'None']].map(x=>`<article class="vd2-card"><b>${x[0]}</b><small>${x[1]}</small></article>`).join('');$('vd2Matrix').innerHTML=`<table class="vd2-table"><thead><tr><th>Section</th><th>Performer</th><th>Range</th><th>Technique</th><th>Background</th><th>Ad-Libs</th><th>Transition</th></tr></thead><tbody>${rows.map((x,i)=>`<tr data-i="${i}"><td>${x.name}</td><td><input data-k="performer" value="${x.performer}"></td><td><select data-k="range">${['Low','Low to Mid','Mid','Upper-Mid to High','High','Wide'].map(v=>`<option ${v===x.range?'selected':''}>${v}</option>`).join('')}</select></td><td><input data-k="technique" value="${x.technique}"></td><td><input data-k="background" value="${x.background}"></td><td><input data-k="adlibs" value="${x.adlibs}"></td><td><input data-k="transition" value="${x.transition}"></td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('#vd2Matrix [data-k]').forEach(e=>e.onchange=()=>{rows[+e.closest('tr').dataset.i][e.dataset.k]=e.value;expose()})}
function auto(){const g=String($('vdGenre')?.value||'').toLowerCase();if(g.includes('metal')){$('vd2Primary').value='Male Tenor';$('vd2Secondary').value='Harsh Male Vocal';$('vd2Range').value='Wide Cinematic Range'}else if(g.includes('viking')){$('vd2Primary').value='Male Baritone';$('vd2Secondary').value='Deep Male Narrator';$('vd2Range').value='Low'}else if(g.includes('anime')||g.includes('kpop')){$('vd2Primary').value='Female Mezzo-Soprano';$('vd2Secondary').value='Male Clean Vocal';$('vd2Range').value='High'}else if(g.includes('ballad')){$('vd2Primary').value='Female Alto';$('vd2Secondary').value='None';$('vd2Range').value='Mid'}build()}
function adlibs(){rows.forEach(x=>{if(/final/i.test(x.name))x.adlibs='Layered high ad-libs and final sustained note';else if(/chorus/i.test(x.name))x.adlibs='Short phrase-end responses';else if(/bridge/i.test(x.name))x.adlibs='Breathy emotional fragments'});render();expose()}
function transitions(){const s=source();rows.forEach((x,i)=>x.transition=i?trans(s[i-1]||{},s[i]||{}):'Opening entry');render();expose()}
function check(){const high=rows.filter(x=>/High|Wide/.test(x.range)).length,r=[];if(high>Math.max(3,rows.length/2))r.push('Too many high-range sections may reduce contrast.');if($('vd2Primary').value.includes('Bass')&&high)r.push('Bass voice conflicts with repeated high-range sections.');$('vdStatus').textContent=r.join(' ')||'Vocal range distribution looks practical.'}
function text(){return rows.map(x=>`[${x.name}]\n[Performer: ${x.performer}]\n[Vocal Range: ${x.range}]\n[Technique: ${x.technique}]\n[Background Vocals: ${x.background}]\n[Ad-Libs: ${x.adlibs}]\n[Vocal Transition: ${x.transition}]`).join('\n\n')+(pron?`\n\n[Pronunciation Notes: ${pron}]`:'')}
function expose(){window.NSW_VOCAL_DIRECTOR_V2_LAST={cast:{primary:$('vd2Primary').value,secondary:$('vd2Secondary').value,range:$('vd2Range').value,separation:$('vd2Separation').value},matrix:JSON.parse(JSON.stringify(rows)),pronunciation:pron,metatags:text(),updatedAt:Date.now()}}
function init(){if(!$('vd2AutoCast'))return;$('vd2AutoCast').onclick=auto;$('vd2Transitions').onclick=transitions;$('vd2Adlibs').onclick=adlibs;$('vd2RangeCheck').onclick=check;$('vd2Copy').onclick=()=>navigator.clipboard?.writeText(text());$('vd2Apply').onclick=()=>window.NSWConnections?.appendLyrics(text());$('vd2SavePronunciation').onclick=()=>{pron=$('vd2Pronunciation').value;render();expose()};['vd2Primary','vd2Secondary','vd2Range','vd2Separation'].forEach(i=>$(i).onchange=build);setTimeout(build,150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
