
(function(){'use strict';
const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),uniq=a=>[...new Set(a.filter(Boolean))];
const IDs=['Instrumental','Female Lead Vocal','Male Lead Vocal','Female Rap Vocal','Male Rap Vocal','Male/Female Duet','Deep Male Narrator','Female Narrator','Spoken Word','Child Choir','SATB Choir','Male Choir','Female Choir','Gang Vocals'];
const CH=['Soft','Warm','Bright','Dark','Airy','Intimate','Emotional','Heroic','Epic','Powerful','Belting','Broken Voice','Crying Voice','Whispered','Aggressive','Screamed','Growled','Operatic','Ethereal','Robotic','Calm','Confident','Playful','Mature','Innocent','Kuudere','Tsundere','Yandere'];
const EM=['Neutral','Hopeful','Sad','Angry','Determined','Calm','Intimate','Heroic','Epic','Desperate','Joyful','Mysterious','Dark','Melancholic','Playful','Confident','Dreamlike','Triumphant'];
const HA=['Lead Only','Double-Tracked Lead','Third Above Harmony','Third Below Harmony','Octave Double','Wide Layered Harmony','Choir Layer','Call and Response','Male/Female Duet','Gang Response','Question and Answer','Echo Choir','SATB Choir Layer'];
const PR=['Dry Close-Mic','Intimate Close-Mic','Forward Studio Vocal','Warm Plate Reverb','Large Hall Vocal','Cathedral Vocal','Arena Vocal','Stadium Vocal','Telephone Vocal','Vintage Radio Vocal','Megaphone Vocal','Huge Reverb','Delay Throws','Doubled Vocals','Wide Stereo Choir','Distant Ethereal Vocal'];
const TR=['No Change','Soft Fade','Breath Pause','Whisper Transition','Call and Response','Choir Entry','Vocal Riser','Intensity Jump','Broken Voice Shift','Belting Entry','Hard Cut','Echo Tail'];
const P={
'Anime Opening':[['Intro','Female Lead Vocal','Whispered','Mysterious','Lead Only','Intimate Close-Mic',25],['Verse 1','Female Lead Vocal','Warm','Determined','Lead Only','Forward Studio Vocal',48],['Pre-Chorus','Female Lead Vocal','Emotional','Hopeful','Third Above Harmony','Warm Plate Reverb',68],['Chorus','Female Lead Vocal','Belting','Heroic','Wide Layered Harmony','Doubled Vocals',90],['Verse 2','Female Lead Vocal','Bright','Determined','Double-Tracked Lead','Forward Studio Vocal',58],['Bridge','Female Lead Vocal','Broken Voice','Desperate','Lead Only','Large Hall Vocal',70],['Final Chorus','Female Lead Vocal','Powerful','Triumphant','SATB Choir Layer','Wide Stereo Choir',100],['Outro','Female Lead Vocal','Soft','Hopeful','Lead Only','Distant Ethereal Vocal',28]],
'Anime Ending':[['Intro','Female Lead Vocal','Airy','Dreamlike','Lead Only','Intimate Close-Mic',20],['Verse 1','Female Lead Vocal','Warm','Melancholic','Lead Only','Dry Close-Mic',38],['Pre-Chorus','Female Lead Vocal','Emotional','Hopeful','Third Above Harmony','Warm Plate Reverb',52],['Chorus','Female Lead Vocal','Bright','Hopeful','Wide Layered Harmony','Doubled Vocals',72],['Bridge','Female Lead Vocal','Broken Voice','Desperate','Lead Only','Large Hall Vocal',60],['Final Chorus','Female Lead Vocal','Powerful','Hopeful','Choir Layer','Wide Stereo Choir',82],['Outro','Female Lead Vocal','Whispered','Dreamlike','Lead Only','Distant Ethereal Vocal',18]],
'Viking Choir':[['Intro','Deep Male Narrator','Dark','Mysterious','Male Choir','Large Hall Vocal',22],['Verse 1','Male Lead Vocal','Powerful','Determined','Lead Only','Dry Close-Mic',48],['Chant','Male Choir','Epic','Heroic','Gang Response','Cathedral Vocal',70],['Chorus','Male Lead Vocal','Powerful','Heroic','Male Choir','Wide Stereo Choir',88],['Verse 2','Male Lead Vocal','Dark','Determined','Call and Response','Arena Vocal',60],['War Build','Gang Vocals','Aggressive','Angry','Gang Response','Stadium Vocal',82],['Final Chorus','Male Lead Vocal','Epic','Triumphant','SATB Choir Layer','Cathedral Vocal',100],['Outro','Deep Male Narrator','Calm','Mysterious','Male Choir','Large Hall Vocal',30]],
'Metalcore':[['Intro','Male Lead Vocal','Dark','Angry','Lead Only','Dry Close-Mic',35],['Verse 1','Male Lead Vocal','Aggressive','Determined','Double-Tracked Lead','Forward Studio Vocal',65],['Pre-Chorus','Male Lead Vocal','Emotional','Desperate','Third Above Harmony','Warm Plate Reverb',72],['Chorus','Male Lead Vocal','Belting','Heroic','Wide Layered Harmony','Doubled Vocals',92],['Verse 2','Male Lead Vocal','Screamed','Angry','Gang Response','Forward Studio Vocal',78],['Breakdown','Male Lead Vocal','Growled','Angry','Gang Response','Dry Close-Mic',100],['Bridge','Male Lead Vocal','Broken Voice','Desperate','Lead Only','Large Hall Vocal',62],['Final Chorus','Male Lead Vocal','Powerful','Triumphant','SATB Choir Layer','Wide Stereo Choir',96]],
'Power Metal':[['Intro','Male Lead Vocal','Operatic','Mysterious','Lead Only','Large Hall Vocal',30],['Verse 1','Male Lead Vocal','Powerful','Determined','Double-Tracked Lead','Forward Studio Vocal',60],['Pre-Chorus','Male Lead Vocal','Emotional','Heroic','Third Above Harmony','Warm Plate Reverb',74],['Chorus','Male Lead Vocal','Belting','Triumphant','Wide Layered Harmony','Arena Vocal',94],['Bridge','Male Lead Vocal','Operatic','Epic','Choir Layer','Cathedral Vocal',80],['Final Chorus','Male Lead Vocal','Powerful','Triumphant','SATB Choir Layer','Wide Stereo Choir',100],['Outro','Male Lead Vocal','Calm','Hopeful','Lead Only','Large Hall Vocal',32]],
'Electro Swing':[['Vintage Intro','Female Lead Vocal','Playful','Mysterious','Lead Only','Vintage Radio Vocal',28],['Verse 1','Female Lead Vocal','Bright','Playful','Call and Response','Vintage Radio Vocal',56],['Chorus','Female Lead Vocal','Powerful','Joyful','Wide Layered Harmony','Doubled Vocals',82],['Brass Break','Instrumental','Neutral','Neutral','Lead Only','Vintage Radio Vocal',30],['Verse 2','Female Lead Vocal','Confident','Playful','Call and Response','Vintage Radio Vocal',62],['Dance Break','Female Lead Vocal','Robotic','Joyful','Gang Response','Megaphone Vocal',76],['Final Chorus','Female Lead Vocal','Belting','Triumphant','SATB Choir Layer','Wide Stereo Choir',92],['Outro','Female Lead Vocal','Soft','Playful','Lead Only','Vintage Radio Vocal',25]],
'K-Pop Performance':[['Intro','Female Lead Vocal','Bright','Confident','Lead Only','Forward Studio Vocal',35],['Verse 1','Female Lead Vocal','Playful','Confident','Double-Tracked Lead','Dry Close-Mic',56],['Rap Verse','Female Rap Vocal','Aggressive','Confident','Gang Response','Forward Studio Vocal',72],['Pre-Chorus','Female Lead Vocal','Emotional','Hopeful','Third Above Harmony','Warm Plate Reverb',68],['Chorus','Male/Female Duet','Powerful','Joyful','Wide Layered Harmony','Doubled Vocals',92],['Verse 2','Male Lead Vocal','Confident','Confident','Double-Tracked Lead','Forward Studio Vocal',62],['Bridge','Female Lead Vocal','Airy','Dreamlike','Lead Only','Large Hall Vocal',58],['Final Chorus','Male/Female Duet','Belting','Triumphant','SATB Choir Layer','Wide Stereo Choir',100]],
'J-Pop Idol':[['Intro','Female Lead Vocal','Innocent','Joyful','Lead Only','Forward Studio Vocal',30],['Verse 1','Female Lead Vocal','Bright','Playful','Double-Tracked Lead','Dry Close-Mic',52],['Pre-Chorus','Female Lead Vocal','Emotional','Hopeful','Third Above Harmony','Warm Plate Reverb',68],['Chorus','Female Lead Vocal','Powerful','Joyful','Wide Layered Harmony','Doubled Vocals',90],['Verse 2','Female Lead Vocal','Playful','Confident','Call and Response','Forward Studio Vocal',60],['Bridge','Female Lead Vocal','Airy','Dreamlike','Lead Only','Large Hall Vocal',55],['Final Chorus','Female Lead Vocal','Belting','Triumphant','Choir Layer','Wide Stereo Choir',98],['Outro','Female Lead Vocal','Soft','Hopeful','Lead Only','Distant Ethereal Vocal',28]],
'Epic Trailer':[['Omen Intro','Deep Male Narrator','Dark','Mysterious','Male Choir','Cathedral Vocal',25],['Movement I','Female Lead Vocal','Ethereal','Hopeful','Lead Only','Large Hall Vocal',45],['Build','SATB Choir','Epic','Heroic','SATB Choir Layer','Cathedral Vocal',72],['Climax','SATB Choir','Powerful','Triumphant','Wide Layered Harmony','Wide Stereo Choir',100],['Quiet Passage','Female Lead Vocal','Whispered','Sad','Lead Only','Distant Ethereal Vocal',30],['Finale','Male/Female Duet','Operatic','Epic','SATB Choir Layer','Cathedral Vocal',96],['Outro','Deep Male Narrator','Calm','Mysterious','Male Choir','Large Hall Vocal',25]],
'Dark Fantasy':[['Intro','Female Narrator','Whispered','Mysterious','Echo Choir','Distant Ethereal Vocal',18],['Verse 1','Female Lead Vocal','Dark','Melancholic','Lead Only','Intimate Close-Mic',45],['Pre-Chorus','Female Lead Vocal','Broken Voice','Desperate','Third Below Harmony','Large Hall Vocal',65],['Chorus','Male/Female Duet','Powerful','Epic','Choir Layer','Cathedral Vocal',88],['Verse 2','Deep Male Narrator','Dark','Angry','Male Choir','Large Hall Vocal',58],['Bridge','Female Lead Vocal','Crying Voice','Sad','Lead Only','Huge Reverb',62],['Final Chorus','Male/Female Duet','Operatic','Triumphant','SATB Choir Layer','Wide Stereo Choir',100],['Outro','Female Narrator','Whispered','Mysterious','Echo Choir','Distant Ethereal Vocal',18]],
'Rap Storytelling':[['Intro','Deep Male Narrator','Calm','Mysterious','Lead Only','Dry Close-Mic',24],['Verse 1','Male Rap Vocal','Confident','Determined','Lead Only','Forward Studio Vocal',58],['Hook','Male Lead Vocal','Warm','Hopeful','Double-Tracked Lead','Warm Plate Reverb',70],['Verse 2','Male Rap Vocal','Aggressive','Angry','Gang Response','Forward Studio Vocal',68],['Hook 2','Male Lead Vocal','Powerful','Determined','Wide Layered Harmony','Doubled Vocals',78],['Bridge','Spoken Word','Broken Voice','Desperate','Lead Only','Telephone Vocal',45],['Final Hook','Male Lead Vocal','Powerful','Triumphant','Gang Response','Wide Stereo Choir',88],['Outro','Deep Male Narrator','Calm','Melancholic','Lead Only','Dry Close-Mic',22]],
'Emotional Ballad':[['Piano Intro','Female Lead Vocal','Airy','Melancholic','Lead Only','Intimate Close-Mic',18],['Verse 1','Female Lead Vocal','Warm','Sad','Lead Only','Dry Close-Mic',38],['Pre-Chorus','Female Lead Vocal','Emotional','Hopeful','Third Above Harmony','Warm Plate Reverb',55],['Chorus','Female Lead Vocal','Powerful','Hopeful','Double-Tracked Lead','Large Hall Vocal',72],['Verse 2','Female Lead Vocal','Intimate','Melancholic','Lead Only','Intimate Close-Mic',42],['Bridge','Female Lead Vocal','Broken Voice','Desperate','Lead Only','Huge Reverb',64],['Final Chorus','Female Lead Vocal','Belting','Triumphant','Wide Layered Harmony','Wide Stereo Choir',84],['Outro','Female Lead Vocal','Whispered','Calm','Lead Only','Distant Ethereal Vocal',16]]};
let S=[],sel=null,drag=null,next=1,preset='Anime Opening';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function mk(x,i){return{id:next++,name:x[0],identity:x[1],character:x[2],emotion:x[3],harmony:x[4],production:x[5],intensity:x[6],transition:i===P[preset].length-1?'Soft Fade':/pre|build/i.test(x[0])?'Intensity Jump':'No Change',breathiness:/whisper|airy|soft|intimate/i.test(x[2])?65:20,vibrato:/operatic|emotional|belting|powerful/i.test(x[2])?60:25,sustain:/chorus|final|climax/i.test(x[0])?75:35,attack:/rap|spoken|aggressive|scream|growl/i.test(x[1]+' '+x[2])?75:45,release:/outro|bridge|quiet/i.test(x[0])?70:40,clarity:/growl|scream|broken/i.test(x[2])?55:85,width:/choir|layer|duet/i.test(x[4]+' '+x[1])?85:35,notes:''}}
function build(n){preset=n;S=P[n].map(mk);sel=S[0]?.id||null;render();renderPresets()}
function namesLyrics(){const t=$('lyricsEditor')?.value||'';if(window.NSWMetaTagStackEngine)return window.NSWMetaTagStackEngine.parseLyrics(t).sections.map(section=>section.stack.section);return[...t.matchAll(/^\s*\[([^\]]+)\]\s*$/gm)].map(m=>m[1].split(':')[0]).filter(x=>/intro|verse|chorus|bridge|drop|build|outro|hook|solo|break|final|movement|instrumental|chant|phase|coda|pre-chorus/i.test(x))}
function namesBlueprint(){if(window.NSW_SONG_BLUEPRINT_LAST?.sections)return window.NSW_SONG_BLUEPRINT_LAST.sections.map(x=>x.name);if($('bpTableBody')?.rows?.length)return Array.from($('bpTableBody').rows).map(r=>r.cells[1]?.textContent.trim()).filter(Boolean);return[]}
function generic(n,i,total){let e=30+i/Math.max(1,total-1)*55,arc=$('vdArc').value;if(arc==='waves')e=50+Math.sin(i/Math.max(1,total-1)*Math.PI*4)*22;if(arc==='early')e=35+Math.sin(Math.min(1,i/Math.max(1,total-1)*1.5)*Math.PI)*55;if(arc==='late')e=22+Math.pow(i/Math.max(1,total-1),1.8)*76;if(arc==='contrast')e=i%2?75:38;if(arc==='constant')e=82;if(/chorus|hook|drop|final|climax/i.test(n))e+=14;if(/intro|outro|break/i.test(n))e-=18;return mk([n,/instrumental|solo|break|drop/i.test(n)?'Instrumental':'Female Lead Vocal',/intro|outro/i.test(n)?'Soft':/chorus|final/i.test(n)?'Powerful':'Warm',/final|chorus/i.test(n)?'Heroic':'Determined',/chorus|final/i.test(n)?'Wide Layered Harmony':'Lead Only',/chorus|final/i.test(n)?'Doubled Vocals':'Forward Studio Vocal',clamp(Math.round(e),5,100)],i)}
function generate(){let n=[];if($('vdSource').value==='lyrics')n=namesLyrics();if($('vdSource').value==='blueprint')n=namesBlueprint();if($('vdSource').value==='preset'||!n.length){build($('vdPreset').value);return}if($('vdSource').value==='blank')n=['Intro','Verse 1','Pre-Chorus','Chorus','Verse 2','Bridge','Final Chorus','Outro'];S=n.map((x,i)=>generic(x,i,n.length));sel=S[0]?.id;smart(false);render()}
function currentGenre(){return $('vdGenre').value!=='auto'?$('vdGenre').value:($('subgenre')?.value||$('genreFamily')?.value||$('mainGenre')?.value||'')}
function smart(show=true){let g=String(currentGenre()).toLowerCase(),n=/metal/.test(g)?'Metalcore':/viking|nordic|folk/.test(g)?'Viking Choir':/k-pop|kpop/.test(g)?'K-Pop Performance':/rap|hip-hop|trap|drill/.test(g)?'Rap Storytelling':/jazz|swing/.test(g)?'Electro Swing':/cinematic|trailer|orchestral/.test(g)?'Epic Trailer':/ballad|acoustic/.test(g)?'Emotional Ballad':/dark fantasy|souls|gothic/.test(g)?'Dark Fantasy':'Anime Opening';let r=P[n];if(!S.length){build(n);return}S.forEach((s,i)=>{let x=r[Math.min(i,r.length-1)];s.identity=x[1];s.character=x[2];s.emotion=x[3];s.harmony=x[4];s.production=x[5];s.intensity=clamp(Math.round((s.intensity+x[6])/2),5,100)});preset=n;$('vdPreset').value=n;if(show)$('vdStatus').textContent=`Smart Director applied ${n}.`;render()}
function opts(a,v){return a.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}
function timeline(){let z=+$('vdZoom').value/100;$('vdTimeline').innerHTML=S.map(s=>`<article draggable="true" class="vd-block ${s.id===sel?'active':''}" data-id="${s.id}" style="width:${Math.max(105,115*z)}px"><b>${esc(s.name)}</b><small>${esc(s.identity)}<br>${esc(s.character)} · ${esc(s.emotion)}</small><div class="vd-block-tags"><span>${esc(s.harmony)}</span><span>${esc(s.production)}</span></div><div class="vd-block-tools"><button data-move="-1">←</button><button data-move="1">→</button><button data-del="1">×</button></div><div class="vd-intensity"><i style="width:${s.intensity}%"></i></div></article>`).join('');document.querySelectorAll('.vd-block').forEach(e=>{e.onclick=x=>{if(x.target.closest('button'))return;sel=+e.dataset.id;timeline();inspector()};e.ondragstart=()=>{drag=+e.dataset.id;e.classList.add('dragging')};e.ondragend=()=>{drag=null;e.classList.remove('dragging')};e.ondragover=x=>{x.preventDefault();e.classList.add('drag-over')};e.ondragleave=()=>e.classList.remove('drag-over');e.ondrop=x=>{x.preventDefault();e.classList.remove('drag-over');let t=+e.dataset.id;if(drag&&drag!==t){let a=S.findIndex(v=>v.id===drag),b=S.findIndex(v=>v.id===t),[q]=S.splice(a,1);S.splice(b,0,q);render()}}});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=x=>{x.stopPropagation();let i=S.findIndex(v=>v.id===+b.closest('[data-id]').dataset.id),j=i+(+b.dataset.move);if(j>=0&&j<S.length){[S[i],S[j]]=[S[j],S[i]];render()}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=x=>{x.stopPropagation();let id=+b.closest('[data-id]').dataset.id;S=S.filter(v=>v.id!==id);if(sel===id)sel=S[0]?.id||null;render()})}
function heat(){let peak=[...S].sort((a,b)=>b.intensity-a.intensity)[0];$('vdPeakLabel').textContent=`Peak: ${peak?.name||'—'} · ${peak?.intensity||0}%`;$('vdHeatmap').innerHTML=S.map(s=>`<div class="vd-heat" style="background:linear-gradient(180deg,hsl(${330-s.intensity*.7} 72% ${18+s.intensity*.22}%),hsl(280 45% 12%))"><b>${esc(s.name)}</b><small>${s.intensity}% · ${esc(s.character)}</small><div>${/choir|gang/i.test(s.identity+' '+s.harmony)?'👥 ':''}${s.harmony!=='Lead Only'?'🎶 ':''}${!/dry|forward/i.test(s.production)?'🎛️ ':''}${s.intensity>85?'🔥':''}</div></div>`).join('')}
function slider(n,id,v){return`<label class="vd-slider"><span>${n}</span><b id="${id}V">${v}%</b><input id="${id}" type="range" min="0" max="100" value="${v}"></label>`}
function inspector(){let s=S.find(x=>x.id===sel),h=$('vdInspector');if(!s){h.innerHTML='<div class="vd-empty"><span>🎤</span><h3>Select a section</h3></div>';return}h.innerHTML=`<h3>🎤 Section Vocal DNA</h3><div class="vd-grid"><label class="full">Section Name<input id="veName" value="${esc(s.name)}"></label><label>Identity<select id="veId">${opts(IDs,s.identity)}</select></label><label>Character<select id="veCh">${opts(CH,s.character)}</select></label><label>Emotion<select id="veEm">${opts(EM,s.emotion)}</select></label><label>Harmony<select id="veHa">${opts(HA,s.harmony)}</select></label><label>Production<select id="vePr">${opts(PR,s.production)}</select></label><label>Transition<select id="veTr">${opts(TR,s.transition)}</select></label>${slider('Intensity','veIn',s.intensity)}${slider('Breathiness','veBr',s.breathiness)}${slider('Vibrato','veVi',s.vibrato)}${slider('Sustain','veSu',s.sustain)}${slider('Attack','veAt',s.attack)}${slider('Release','veRe',s.release)}${slider('Clarity','veCl',s.clarity)}${slider('Width','veWi',s.width)}<label class="full">Notes<textarea id="veNo">${esc(s.notes)}</textarea></label></div><div class="vd-inspector-actions"><button id="veDup">Duplicate</button><button id="veDel">Delete</button><button class="primary" id="veSave">Save Section</button></div>`;['In','Br','Vi','Su','At','Re','Cl','Wi'].forEach(k=>{$('ve'+k).oninput=()=>document.getElementById('ve'+k+'V').textContent=$('ve'+k).value+'%'});$('veSave').onclick=()=>{Object.assign(s,{name:$('veName').value||s.name,identity:$('veId').value,character:$('veCh').value,emotion:$('veEm').value,harmony:$('veHa').value,production:$('vePr').value,transition:$('veTr').value,intensity:+$('veIn').value,breathiness:+$('veBr').value,vibrato:+$('veVi').value,sustain:+$('veSu').value,attack:+$('veAt').value,release:+$('veRe').value,clarity:+$('veCl').value,width:+$('veWi').value,notes:$('veNo').value});render()};$('veDel').onclick=()=>{S=S.filter(x=>x.id!==s.id);sel=S[0]?.id||null;render()};$('veDup').onclick=()=>{let i=S.findIndex(x=>x.id===s.id),c={...s,id:next++,name:s.name+' Copy'};S.splice(i+1,0,c);sel=c.id;render()}}
function analysis(){let ids=uniq(S.map(x=>x.identity)),chs=uniq(S.map(x=>x.character)),choir=S.filter(x=>/choir|gang/i.test(x.identity+' '+x.harmony)).length,harm=S.filter(x=>x.harmony!=='Lead Only').length,peaks=S.filter(x=>x.intensity>=85).length,avg=S.length?S.reduce((a,b)=>a+b.intensity,0)/S.length:0,w=[];if(S.length<4)w.push('The vocal timeline is very short.');if(ids.length>5)w.push('Many vocal identities may reduce voice separation.');if(peaks>Math.max(3,S.length*.45))w.push('Too many high-intensity sections reduce contrast.');if(S.length&&Math.max(...S.map(x=>x.intensity))-Math.min(...S.map(x=>x.intensity))<25)w.push('The vocal intensity curve has little contrast.');S.forEach(s=>{if(s.identity==='Instrumental'&&s.harmony!=='Lead Only')w.push(`${s.name}: Instrumental conflicts with ${s.harmony}.`);if(/whisper/i.test(s.character)&&s.intensity>85)w.push(`${s.name}: Whispered character with very high intensity.`)});let r=[];if(!choir)r.push('A choir or group response could strengthen the final peak.');if(!harm)r.push('Add harmony to the chorus or final chorus.');if(!S.some(x=>/whisper|soft|airy/i.test(x.character)))r.push('Add a softer section for stronger contrast.');if(!S.some(x=>/broken|crying/i.test(x.character)))r.push('A fragile bridge can deepen the emotional arc.');if(!r.length)r.push('The vocal arc contains useful contrast.');let contrast=S.length?Math.max(...S.map(x=>x.intensity))-Math.min(...S.map(x=>x.intensity)):0,score=Math.round((clamp(45+Math.min(25,ids.length*6)+Math.min(20,chs.length*3))+clamp(100-w.length*11)+clamp(45+contrast*.7)+clamp(100-Math.max(0,choir-4)*6))/4);$('vdScore').textContent=score;$('vdScoreBar').style.width=score+'%';$('vdMetrics').innerHTML=[['Sections',S.length],['Avg. Intensity',Math.round(avg)+'%'],['Identities',ids.length],['Harmony',harm],['Choir / Group',choir],['Peaks',peaks]].map(x=>`<div class="vd-metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('vdWarnings').innerHTML=(w.length?uniq(w):['No major conflicts detected.']).map(x=>`<div class="vd-message ${w.length?'warn':'good'}">${esc(x)}</div>`).join('');$('vdRecommendations').innerHTML=r.map(x=>`<div class="vd-message info">${esc(x)}</div>`).join('');$('vdBadge').textContent=`${S.length} sections · ${ids.length} roles · local`;return score}
function vocalDirectives(s){let p=[];if(s.intensity>=85)p.push('High Intensity');else if(s.intensity<=30)p.push('Restrained');if(s.breathiness>=60)p.push('Breathy');if(s.vibrato>=60)p.push('Expressive Vibrato');if(s.sustain>=65)p.push('Long Sustained Notes');if(s.attack>=70)p.push('Strong Vocal Attack');if(s.clarity>=80)p.push('Clear Voice Separation');if(s.width>=75)p.push('Wide Vocal Image');return[`Emotion: ${s.emotion}`,`${s.identity}, ${s.character}`,`Harmony: ${s.harmony}`,`Performance: ${p.join(', ')||'Controlled'}`,`Space: ${s.production}`,`Transition: ${s.transition}`]}
function tag(s,existing=[]){const directives=[...existing,...vocalDirectives(s)];return window.NSWMetaTagStackEngine?window.NSWMetaTagStackEngine.createStack(s.name,directives,{sort:true}).line:`[${[s.name,...directives].join(' | ')}]`}
function dna(){return S.map(s=>tag(s)).join('\n\n')}function global(){return uniq([...S.filter(x=>x.identity!=='Instrumental').map(x=>x.identity),...S.map(x=>x.character).slice(0,5),...S.map(x=>x.harmony).filter(x=>x!=='Lead Only').slice(0,4),...S.map(x=>x.production).slice(0,4),'Clear Voice Separation','Section-Specific Vocal Direction']).join(', ')}
function table(){$('vdTableBody').innerHTML=S.map(s=>`<tr data-row="${s.id}"><td>${esc(s.name)}</td><td>${esc(s.identity)}</td><td>${esc(s.character)}</td><td>${esc(s.emotion)}</td><td>${s.intensity}%</td><td>${esc(s.harmony)}</td><td>${esc(s.production)}</td><td>${esc(s.transition)}</td></tr>`).join('');document.querySelectorAll('[data-row]').forEach(r=>r.onclick=()=>{sel=+r.dataset.row;timeline();inspector()})}
function render(){timeline();heat();inspector();table();analysis();$('vdDNA').value=dna();$('vdSummaryBadge').textContent=`${S.length} sections`;window.NSW_VOCAL_DIRECTOR_LAST={preset,genre:currentGenre(),sections:JSON.parse(JSON.stringify(S)),dna:dna(),globalStyle:global(),updatedAt:Date.now()}}
function renderPresets(){let n=Object.keys(P);$('vdPreset').innerHTML=n.map(x=>`<option ${x===preset?'selected':''}>${x}</option>`).join('');$('vdPresetCount').textContent=`${n.length} presets`;$('vdPresetGrid').innerHTML=n.map(x=>`<button class="vd-preset-card ${x===preset?'active':''}" data-p="${x}"><b>${x}</b><small>${P[x].length} sections · complete vocal arc</small></button>`).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{build(b.dataset.p);$('vdStatus').textContent=`${b.dataset.p} applied.`})}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch(e){let a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}}function down(n,t,type='text/plain'){let b=new Blob([t],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function plan(){return['VOCAL DIRECTOR PLAN',`Preset: ${preset}`,`Genre: ${currentGenre()}`,'',...S.map(s=>`${s.name} | ${s.identity} | ${s.character} | ${s.emotion} | ${s.intensity}% | ${s.harmony} | ${s.production}`),'','SUNO METATAGS','',dna()].join('\n')}
function applyLyrics(){
 let e=$('lyricsEditor');
 if(!e)return;
 const engine=window.NSWMetaTagStackEngine;
 const hasSections=engine?.parseLyrics(e.value).sections.length>0;
 e.value=engine?engine.mergeStackDocument(e.value,dna(),{create:!hasSections,repeatLast:true}).text:e.value.trim()?`${e.value.trim()}\n\n${dna()}`:dna();
 e.dispatchEvent(new Event('input',{bubbles:true}));
 if(typeof showToast==='function')showToast('Vocal Pipe-Stacks applied.');
}
function applyStyle(){let e=$('customStyle');if(!e)return;e.value=uniq([...String(e.value||'').split(',').map(x=>x.trim()),...global().split(',').map(x=>x.trim())]).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}
function saveProject(){let pm=JSON.parse(localStorage.getItem('nsw-project-manager-v4')||'null');if(!pm?.projects?.length){$('vdStatus').textContent='No project available.';return}let p=pm.projects.find(x=>x.id===pm.activeProjectId)||pm.projects[0],t=p.tracks?.[0];if(!t){$('vdStatus').textContent='Active project has no track.';return}t.vocalDirector=window.NSW_VOCAL_DIRECTOR_LAST;t.updated=Date.now();p.updated=Date.now();localStorage.setItem('nsw-project-manager-v4',JSON.stringify(pm));$('vdStatus').textContent=`Saved to ${p.name} · ${t.title}.`}
function init(){if(!$('vdGenerate'))return;renderPresets();build(preset);$('vdGenerate').onclick=generate;$('vdSmartDirector').onclick=()=>smart(true);$('vdAddSection').onclick=()=>{let s=generic('New Section',S.length,S.length+1);S.push(s);sel=s.id;render()};$('vdReset').onclick=()=>build($('vdPreset').value);$('vdZoom').oninput=timeline;$('vdArc').onchange=()=>{S.forEach((s,i)=>s.intensity=generic(s.name,i,S.length).intensity);render()};$('vdPreset').onchange=e=>{preset=e.target.value;if($('vdSource').value==='preset')build(preset);renderPresets()};$('vdCopyDNA').onclick=()=>copy(dna());$('vdCopyPlan').onclick=()=>copy(plan());$('vdExportJson').onclick=()=>down('vocal-director-plan.json',JSON.stringify(window.NSW_VOCAL_DIRECTOR_LAST,null,2),'application/json');$('vdExportTxt').onclick=()=>down('vocal-director-plan.txt',plan());$('vdApplyLyrics').onclick=applyLyrics;$('vdApplyStyle').onclick=applyStyle;$('vdSaveProject').onclick=saveProject}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
