(function(root,factory){
'use strict';
const api=factory();
if(typeof module==='object'&&module.exports)module.exports=api;
if(root)root.NSWWorkspaceI18nCatalog=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

const VERSION='7.5.7';
const LANGUAGES=Object.freeze(['en','de','fr','es','it','pt','pt-BR','nl','pl','tr','ru','ja','ko','zh-CN']);

const VIEW_WORKSPACE=Object.freeze({
 homeView:'create',randomView:'create',composerView:'create',vocalDirectorView:'song',styleView:'style',lyricsView:'lyrics',promptChatView:'style',assistantView:'create',musicDirectorView:'create',studioIntelligenceView:'create',aiProducerView:'create',songDirectorView:'create',dnaAnalyzerView:'analysis',lyricsIntelligenceView:'lyrics',conflictResolverView:'style',variationEngineView:'style',styleSimplifierView:'style',styleHealthView:'style',optimizerView:'style',successPredictorView:'song',evolutionView:'style',learningView:'analysis',genreIntelligenceView:'knowledge',worldMusicView:'knowledge',genreEvolutionView:'knowledge',metaTagEncyclopediaView:'knowledge',metatagsView:'knowledge',styleLibraryView:'knowledge',blueprintView:'song',arrangementDesignerView:'song',instrumentsView:'knowledge',instrumentEncyclopediaView:'knowledge',instrumentEvolutionView:'knowledge',instrumentGraphView:'knowledge',vocalsView:'song',storyView:'create',productionView:'song',theoryView:'song',theoryDirectorView:'song',projectManagerView:'project',presetsView:'project',guidedView:'create',simpleView:'create'
});

const WORKSPACES=Object.freeze({
 en:{create:['✨ CREATE','Start ideas and coordinate the complete song'],style:['🎨 STYLE','Build, simplify, vary and validate the STYLE prompt'],song:['🎵 SONG','Arrange, perform and complete the production'],lyrics:['📝 LYRICS','Write, structure and improve lyrics'],knowledge:['📚 KNOWLEDGE','Explore genres, instruments, MetaTags and musical systems'],analysis:['🔍 ANALYSIS','Understand, compare and learn from results'],project:['📁 PROJECTS','Manage projects, presets and versions']},
 de:{create:['✨ ERSTELLEN','Ideen starten und den kompletten Song koordinieren'],style:['🎨 STYLE','STYLE erstellen, vereinfachen, variieren und prüfen'],song:['🎵 SONG','Arrangement, Stimmen und Produktion fertigstellen'],lyrics:['📝 LYRICS','Songtexte schreiben, strukturieren und verbessern'],knowledge:['📚 WISSEN','Genres, Instrumente, MetaTags und Musiksysteme erkunden'],analysis:['🔍 ANALYSE','Ergebnisse verstehen, vergleichen und daraus lernen'],project:['📁 PROJEKTE','Projekte, Presets und Versionen verwalten']},
 fr:{create:['✨ CRÉER','Démarrer des idées et coordonner la chanson complète'],style:['🎨 STYLE','Créer, simplifier, varier et vérifier le STYLE'],song:['🎵 CHANSON','Organiser, interpréter et finaliser la production'],lyrics:['📝 PAROLES','Écrire, structurer et améliorer les paroles'],knowledge:['📚 CONNAISSANCES','Explorer les genres, instruments, MetaTags et systèmes musicaux'],analysis:['🔍 ANALYSE','Comprendre, comparer et apprendre des résultats'],project:['📁 PROJETS','Gérer les projets, préréglages et versions']},
 es:{create:['✨ CREAR','Iniciar ideas y coordinar la canción completa'],style:['🎨 STYLE','Crear, simplificar, variar y comprobar el STYLE'],song:['🎵 CANCIÓN','Arreglar, interpretar y completar la producción'],lyrics:['📝 LETRAS','Escribir, estructurar y mejorar letras'],knowledge:['📚 CONOCIMIENTO','Explorar géneros, instrumentos, MetaTags y sistemas musicales'],analysis:['🔍 ANÁLISIS','Comprender, comparar y aprender de los resultados'],project:['📁 PROYECTOS','Gestionar proyectos, preajustes y versiones']},
 it:{create:['✨ CREA','Avvia idee e coordina il brano completo'],style:['🎨 STYLE','Crea, semplifica, varia e verifica lo STYLE'],song:['🎵 BRANO','Arrangia, interpreta e completa la produzione'],lyrics:['📝 TESTI','Scrivi, struttura e migliora i testi'],knowledge:['📚 CONOSCENZA','Esplora generi, strumenti, MetaTag e sistemi musicali'],analysis:['🔍 ANALISI','Comprendi, confronta e impara dai risultati'],project:['📁 PROGETTI','Gestisci progetti, preset e versioni']},
 pt:{create:['✨ CRIAR','Iniciar ideias e coordenar a música completa'],style:['🎨 STYLE','Criar, simplificar, variar e verificar o STYLE'],song:['🎵 MÚSICA','Organizar, interpretar e concluir a produção'],lyrics:['📝 LETRAS','Escrever, estruturar e melhorar letras'],knowledge:['📚 CONHECIMENTO','Explorar géneros, instrumentos, MetaTags e sistemas musicais'],analysis:['🔍 ANÁLISE','Compreender, comparar e aprender com os resultados'],project:['📁 PROJETOS','Gerir projetos, predefinições e versões']},
 'pt-BR':{create:['✨ CRIAR','Iniciar ideias e coordenar a música completa'],style:['🎨 STYLE','Criar, simplificar, variar e verificar o STYLE'],song:['🎵 MÚSICA','Organizar, interpretar e concluir a produção'],lyrics:['📝 LETRAS','Escrever, estruturar e melhorar letras'],knowledge:['📚 CONHECIMENTO','Explorar gêneros, instrumentos, MetaTags e sistemas musicais'],analysis:['🔍 ANÁLISE','Compreender, comparar e aprender com os resultados'],project:['📁 PROJETOS','Gerenciar projetos, predefinições e versões']},
 nl:{create:['✨ MAKEN','Ideeën starten en het volledige nummer coördineren'],style:['🎨 STYLE','STYLE bouwen, vereenvoudigen, variëren en controleren'],song:['🎵 NUMMER','Arrangeren, uitvoeren en de productie afronden'],lyrics:['📝 TEKSTEN','Songteksten schrijven, structureren en verbeteren'],knowledge:['📚 KENNIS','Genres, instrumenten, MetaTags en muzieksystemen verkennen'],analysis:['🔍 ANALYSE','Resultaten begrijpen, vergelijken en ervan leren'],project:['📁 PROJECTEN','Projecten, presets en versies beheren']},
 pl:{create:['✨ TWORZENIE','Rozpocznij pomysł i koordynuj cały utwór'],style:['🎨 STYLE','Twórz, upraszczaj, zmieniaj i sprawdzaj STYLE'],song:['🎵 UTWÓR','Aranżuj, wykonuj i kończ produkcję'],lyrics:['📝 TEKST','Pisz, porządkuj i ulepszaj tekst'],knowledge:['📚 WIEDZA','Poznawaj gatunki, instrumenty, MetaTagi i systemy muzyczne'],analysis:['🔍 ANALIZA','Rozumiej, porównuj i ucz się z wyników'],project:['📁 PROJEKTY','Zarządzaj projektami, presetami i wersjami']},
 tr:{create:['✨ OLUŞTUR','Fikirleri başlat ve şarkının tamamını koordine et'],style:['🎨 STYLE','STYLE oluştur, sadeleştir, çeşitlendir ve denetle'],song:['🎵 ŞARKI','Aranje et, seslendir ve prodüksiyonu tamamla'],lyrics:['📝 SÖZLER','Sözleri yaz, yapılandır ve geliştir'],knowledge:['📚 BİLGİ','Türleri, enstrümanları, MetaTag’leri ve müzik sistemlerini keşfet'],analysis:['🔍 ANALİZ','Sonuçları anla, karşılaştır ve öğren'],project:['📁 PROJELER','Projeleri, ön ayarları ve sürümleri yönet']},
 ru:{create:['✨ СОЗДАНИЕ','Начните идею и координируйте всю песню'],style:['🎨 STYLE','Создавайте, упрощайте, изменяйте и проверяйте STYLE'],song:['🎵 ПЕСНЯ','Создавайте аранжировку и завершайте продакшн'],lyrics:['📝 ТЕКСТЫ','Пишите, структурируйте и улучшайте тексты'],knowledge:['📚 ЗНАНИЯ','Изучайте жанры, инструменты, MetaTag и музыкальные системы'],analysis:['🔍 АНАЛИЗ','Понимайте, сравнивайте и учитесь на результатах'],project:['📁 ПРОЕКТЫ','Управляйте проектами, пресетами и версиями']},
 ja:{create:['✨ 作成','アイデアを始め、曲全体を調整します'],style:['🎨 STYLE','STYLEを作成・簡略化・変化・検証します'],song:['🎵 楽曲','アレンジ、ボーカル、制作を完成させます'],lyrics:['📝 歌詞','歌詞を書き、構成し、改善します'],knowledge:['📚 知識','ジャンル、楽器、MetaTag、音楽システムを探索します'],analysis:['🔍 分析','結果を理解・比較し、学習します'],project:['📁 プロジェクト','プロジェクト、プリセット、バージョンを管理します']},
 ko:{create:['✨ 만들기','아이디어를 시작하고 전체 곡을 조정합니다'],style:['🎨 STYLE','STYLE을 만들고 단순화·변형·검증합니다'],song:['🎵 곡','편곡, 보컬과 제작을 완성합니다'],lyrics:['📝 가사','가사를 쓰고 구성하고 개선합니다'],knowledge:['📚 지식','장르, 악기, MetaTag와 음악 시스템을 탐색합니다'],analysis:['🔍 분석','결과를 이해하고 비교하며 학습합니다'],project:['📁 프로젝트','프로젝트, 프리셋과 버전을 관리합니다']},
 'zh-CN':{create:['✨ 创作','开始构思并协调完整歌曲'],style:['🎨 STYLE','创建、精简、变化并检查 STYLE'],song:['🎵 歌曲','完成编曲、人声与制作'],lyrics:['📝 歌词','编写、组织并改进歌词'],knowledge:['📚 知识','探索流派、乐器、MetaTag 与音乐系统'],analysis:['🔍 分析','理解、比较并从结果中学习'],project:['📁 项目','管理项目、预设与版本']}
});

const VIEW_DESCRIPTIONS=Object.freeze({
 en:Object.freeze({
  homeView:'Quick access and recent tools',randomView:'Play with intelligent combinations',composerView:'Develop a song idea into directions',vocalDirectorView:'Plan vocal roles for every song section',styleView:'Fine-tune the complete musical style',lyricsView:'Write, structure and prepare lyrics',promptChatView:'Change STYLE with natural instructions',assistantView:'Plan, connect and synchronize all modules',musicDirectorView:'Coordinate modules with transparent decisions',studioIntelligenceView:'Mentor, coach, genre mixer and sound-design guidance',aiProducerView:'Musical recommendations, alternatives and producer reasoning',songDirectorView:'Build a complete song across the Studio',dnaAnalyzerView:'Reverse-engineer an existing STYLE',lyricsIntelligenceView:'Check rhyme, flow, hooks, emotion and singability',conflictResolverView:'Find contradictions and resolve them by priority or section',variationEngineView:'Create controlled STYLE variations',styleSimplifierView:'Reduce repetition while preserving musical identity',styleHealthView:'Check density, conflicts and repair suggestions',optimizerView:'Clean and improve STYLE prompts',successPredictorView:'Estimate clarity, compatibility and generation risk',evolutionView:'Develop a STYLE in controlled directions',learningView:'Rate results and learn local preferences',genreIntelligenceView:'Explore genre DNA, fusion and Suno guidance',worldMusicView:'Explore regions, modes, rhythms and authentic palettes',genreEvolutionView:'Explore roots, eras, branches and controlled fusion',metaTagEncyclopediaView:'Learn meaning, reliability, examples and conflicts',metatagsView:'Build Pipe-Stacks, Song Maps and Prompt DNA',styleLibraryView:'Find and apply curated styles',blueprintView:'Plan structure, energy and musical roles',arrangementDesignerView:'Plan layers, density and transitions by section',instrumentsView:'Explore instruments and recommendations',instrumentEncyclopediaView:'Learn sound, roles, pairings and Suno reliability',instrumentEvolutionView:'Develop roles, articulations, layers and mutations',instrumentGraphView:'Visualize support, competition and masking',vocalsView:'Choose voices, characters and duet controls',storyView:'Define world, scene, emotion and energy',productionView:'Shape mix, sound design and mastering',theoryView:'Plan rhythm, harmony and dynamics',theoryDirectorView:'Choose key, scale, chords, groove and tension',projectManagerView:'Manage albums, tracks, assets and versions',presetsView:'Save, organize and restore styles',guidedView:'Create a song through a guided sequence',simpleView:'Build a focused prompt with essential controls'
 }),
 de:Object.freeze({
  homeView:'Schnellzugriff und zuletzt verwendete Werkzeuge',randomView:'Intelligente Kombinationen spielerisch ausprobieren',composerView:'Aus einer Songidee klare musikalische Anweisungen entwickeln',vocalDirectorView:'Stimmen und Rollen für jeden Songabschnitt planen',styleView:'Den gesamten Musikstil gezielt abstimmen',lyricsView:'Lyrics schreiben, strukturieren und vorbereiten',promptChatView:'Den STYLE mit normalen Anweisungen verändern',assistantView:'Module planen, verbinden und synchronisieren',musicDirectorView:'Module mit nachvollziehbaren Entscheidungen koordinieren',studioIntelligenceView:'Mentor, Song-Coach, Genre-Mixer und Sounddesign-Beratung',aiProducerView:'Musikalische Empfehlungen, Alternativen und Producer-Begründungen',songDirectorView:'Einen vollständigen Song im gesamten Studio aufbauen',dnaAnalyzerView:'Einen vorhandenen STYLE in seine Bestandteile zerlegen',lyricsIntelligenceView:'Reime, Flow, Hooks, Emotion und Singbarkeit prüfen',conflictResolverView:'Widersprüche finden und nach Priorität oder Abschnitt lösen',variationEngineView:'Kontrollierte STYLE-Varianten erzeugen',styleSimplifierView:'Wiederholungen reduzieren und die musikalische Identität bewahren',styleHealthView:'Dichte, Konflikte und Reparaturvorschläge prüfen',optimizerView:'STYLE-Prompts aufräumen und verbessern',successPredictorView:'Klarheit, Kompatibilität und Generierungsrisiko einschätzen',evolutionView:'Einen STYLE kontrolliert weiterentwickeln',learningView:'Ergebnisse bewerten und lokale Vorlieben lernen',genreIntelligenceView:'Genre-DNA, Fusionen und Suno-Hinweise erkunden',worldMusicView:'Regionen, Modi, Rhythmen und authentische Klangpaletten erkunden',genreEvolutionView:'Wurzeln, Epochen, Abzweigungen und Fusionen erkunden',metaTagEncyclopediaView:'Bedeutung, Zuverlässigkeit, Beispiele und Konflikte kennenlernen',metatagsView:'Pipe-Stacks, Song Maps und Prompt-DNA erstellen',styleLibraryView:'Kuratierte Styles finden und anwenden',blueprintView:'Struktur, Energie und musikalische Rollen planen',arrangementDesignerView:'Layer, Dichte und Übergänge je Abschnitt planen',instrumentsView:'Instrumente und Empfehlungen erkunden',instrumentEncyclopediaView:'Klang, Rollen, Kombinationen und Suno-Zuverlässigkeit kennenlernen',instrumentEvolutionView:'Rollen, Spielweisen, Layer und moderne Varianten entwickeln',instrumentGraphView:'Unterstützung, Konkurrenz und Maskierung sichtbar machen',vocalsView:'Stimmen, Charaktere und Duettsteuerung auswählen',storyView:'Welt, Szene, Emotion und Energie festlegen',productionView:'Mix, Sounddesign und Mastering gestalten',theoryView:'Rhythmus, Harmonie und Dynamik planen',theoryDirectorView:'Tonart, Skala, Akkorde, Groove und Spannung wählen',projectManagerView:'Alben, Tracks, Dateien und Versionen verwalten',presetsView:'Styles speichern, ordnen und wiederherstellen',guidedView:'Einen Song Schritt für Schritt aufbauen',simpleView:'Mit den wichtigsten Reglern einen klaren Prompt erstellen'
 })
});

const UI=Object.freeze({
 en:{ready:'Ready',analyze:'Analyze',importStyle:'Import Current STYLE',copy:'Copy',apply:'Apply',save:'Save',clear:'Clear',exportJson:'Export JSON',copyReport:'Copy Report',sendProducer:'Send to AI Producer',runHealth:'Run Health Check',saveProject:'Save to Project',settings:'Settings',results:'Results',recommended:'Recommended',issues:'Issues',strengths:'Strengths',nextStep:'Next step',history:'History',clearHistory:'Clear History',load:'Load',overview:'Overview',creativeData:'Creative Data',release:'Release',versions:'Versions',assets:'Assets',library:'MetaTag Library',songMaps:'Song Maps',promptDna:'Prompt DNA',combinations:'Tag Combinations',safeClear:'Safe & clear',creativeMix:'Creative mix',extreme:'Extreme',lyrics:'LYRICS',metatags:'METATAGS',exclude:'EXCLUDE'},
 de:{ready:'Bereit',analyze:'Analysieren',importStyle:'Aktuellen STYLE importieren',copy:'Kopieren',apply:'Übernehmen',save:'Speichern',clear:'Leeren',exportJson:'JSON exportieren',copyReport:'Bericht kopieren',sendProducer:'An AI Producer senden',runHealth:'Health Check starten',saveProject:'Im Projekt speichern',settings:'Einstellungen',results:'Ergebnisse',recommended:'Empfohlen',issues:'Probleme',strengths:'Stärken',nextStep:'Nächster Schritt',history:'Verlauf',clearHistory:'Verlauf löschen',load:'Laden',overview:'Übersicht',creativeData:'Kreative Daten',release:'Veröffentlichung',versions:'Versionen',assets:'Dateien',library:'MetaTag-Bibliothek',songMaps:'Song Maps',promptDna:'Prompt-DNA',combinations:'Tag-Kombinationen',safeClear:'Sicher & klar',creativeMix:'Kreativer Mix',extreme:'Extrem',lyrics:'LYRICS',metatags:'METATAGS',exclude:'EXCLUDE'},
 fr:{ready:'Prêt',analyze:'Analyser',importStyle:'Importer le STYLE actuel',copy:'Copier',apply:'Appliquer',save:'Enregistrer',clear:'Effacer',exportJson:'Exporter JSON',copyReport:'Copier le rapport',sendProducer:'Envoyer à AI Producer',runHealth:'Lancer le Health Check',saveProject:'Enregistrer dans le projet',settings:'Paramètres',results:'Résultats',recommended:'Recommandé',issues:'Problèmes',strengths:'Points forts',nextStep:'Étape suivante',history:'Historique',clearHistory:'Effacer l’historique',load:'Charger',overview:'Vue d’ensemble',creativeData:'Données créatives',release:'Publication',versions:'Versions',assets:'Ressources',library:'Bibliothèque MetaTag',songMaps:'Cartes de chanson',promptDna:'ADN du prompt',combinations:'Combinaisons de tags',safeClear:'Sûr et clair',creativeMix:'Mix créatif',extreme:'Extrême',lyrics:'PAROLES',metatags:'METATAGS',exclude:'EXCLURE'},
 es:{ready:'Listo',analyze:'Analizar',importStyle:'Importar STYLE actual',copy:'Copiar',apply:'Aplicar',save:'Guardar',clear:'Borrar',exportJson:'Exportar JSON',copyReport:'Copiar informe',sendProducer:'Enviar a AI Producer',runHealth:'Ejecutar Health Check',saveProject:'Guardar en proyecto',settings:'Ajustes',results:'Resultados',recommended:'Recomendado',issues:'Problemas',strengths:'Fortalezas',nextStep:'Siguiente paso',history:'Historial',clearHistory:'Borrar historial',load:'Cargar',overview:'Resumen',creativeData:'Datos creativos',release:'Publicación',versions:'Versiones',assets:'Recursos',library:'Biblioteca MetaTag',songMaps:'Mapas de canción',promptDna:'ADN del prompt',combinations:'Combinaciones de tags',safeClear:'Seguro y claro',creativeMix:'Mezcla creativa',extreme:'Extremo',lyrics:'LETRAS',metatags:'METATAGS',exclude:'EXCLUIR'},
 it:{ready:'Pronto',analyze:'Analizza',importStyle:'Importa STYLE attuale',copy:'Copia',apply:'Applica',save:'Salva',clear:'Cancella',exportJson:'Esporta JSON',copyReport:'Copia rapporto',sendProducer:'Invia ad AI Producer',runHealth:'Avvia Health Check',saveProject:'Salva nel progetto',settings:'Impostazioni',results:'Risultati',recommended:'Consigliato',issues:'Problemi',strengths:'Punti di forza',nextStep:'Passaggio successivo',history:'Cronologia',clearHistory:'Cancella cronologia',load:'Carica',overview:'Panoramica',creativeData:'Dati creativi',release:'Pubblicazione',versions:'Versioni',assets:'Risorse',library:'Libreria MetaTag',songMaps:'Mappe del brano',promptDna:'DNA del prompt',combinations:'Combinazioni di tag',safeClear:'Sicuro e chiaro',creativeMix:'Mix creativo',extreme:'Estremo',lyrics:'TESTI',metatags:'METATAG',exclude:'ESCLUDI'},
 pt:{ready:'Pronto',analyze:'Analisar',importStyle:'Importar STYLE atual',copy:'Copiar',apply:'Aplicar',save:'Guardar',clear:'Limpar',exportJson:'Exportar JSON',copyReport:'Copiar relatório',sendProducer:'Enviar ao AI Producer',runHealth:'Executar Health Check',saveProject:'Guardar no projeto',settings:'Definições',results:'Resultados',recommended:'Recomendado',issues:'Problemas',strengths:'Pontos fortes',nextStep:'Próximo passo',history:'Histórico',clearHistory:'Limpar histórico',load:'Carregar',overview:'Visão geral',creativeData:'Dados criativos',release:'Lançamento',versions:'Versões',assets:'Recursos',library:'Biblioteca MetaTag',songMaps:'Mapas da música',promptDna:'DNA do prompt',combinations:'Combinações de tags',safeClear:'Seguro e claro',creativeMix:'Mistura criativa',extreme:'Extremo',lyrics:'LETRAS',metatags:'METATAGS',exclude:'EXCLUIR'},
 'pt-BR':{ready:'Pronto',analyze:'Analisar',importStyle:'Importar STYLE atual',copy:'Copiar',apply:'Aplicar',save:'Salvar',clear:'Limpar',exportJson:'Exportar JSON',copyReport:'Copiar relatório',sendProducer:'Enviar ao AI Producer',runHealth:'Executar Health Check',saveProject:'Salvar no projeto',settings:'Configurações',results:'Resultados',recommended:'Recomendado',issues:'Problemas',strengths:'Pontos fortes',nextStep:'Próximo passo',history:'Histórico',clearHistory:'Limpar histórico',load:'Carregar',overview:'Visão geral',creativeData:'Dados criativos',release:'Lançamento',versions:'Versões',assets:'Recursos',library:'Biblioteca MetaTag',songMaps:'Mapas da música',promptDna:'DNA do prompt',combinations:'Combinações de tags',safeClear:'Seguro e claro',creativeMix:'Mistura criativa',extreme:'Extremo',lyrics:'LETRAS',metatags:'METATAGS',exclude:'EXCLUIR'},
 nl:{ready:'Gereed',analyze:'Analyseren',importStyle:'Huidige STYLE importeren',copy:'Kopiëren',apply:'Toepassen',save:'Opslaan',clear:'Wissen',exportJson:'JSON exporteren',copyReport:'Rapport kopiëren',sendProducer:'Naar AI Producer sturen',runHealth:'Health Check uitvoeren',saveProject:'In project opslaan',settings:'Instellingen',results:'Resultaten',recommended:'Aanbevolen',issues:'Problemen',strengths:'Sterke punten',nextStep:'Volgende stap',history:'Geschiedenis',clearHistory:'Geschiedenis wissen',load:'Laden',overview:'Overzicht',creativeData:'Creatieve gegevens',release:'Uitgave',versions:'Versies',assets:'Bestanden',library:'MetaTag-bibliotheek',songMaps:'Songkaarten',promptDna:'Prompt-DNA',combinations:'Tagcombinaties',safeClear:'Veilig en duidelijk',creativeMix:'Creatieve mix',extreme:'Extreem',lyrics:'TEKSTEN',metatags:'METATAGS',exclude:'UITSLUITEN'},
 pl:{ready:'Gotowe',analyze:'Analizuj',importStyle:'Importuj bieżący STYLE',copy:'Kopiuj',apply:'Zastosuj',save:'Zapisz',clear:'Wyczyść',exportJson:'Eksportuj JSON',copyReport:'Kopiuj raport',sendProducer:'Wyślij do AI Producer',runHealth:'Uruchom Health Check',saveProject:'Zapisz w projekcie',settings:'Ustawienia',results:'Wyniki',recommended:'Zalecane',issues:'Problemy',strengths:'Mocne strony',nextStep:'Następny krok',history:'Historia',clearHistory:'Wyczyść historię',load:'Wczytaj',overview:'Przegląd',creativeData:'Dane kreatywne',release:'Publikacja',versions:'Wersje',assets:'Zasoby',library:'Biblioteka MetaTagów',songMaps:'Mapy utworu',promptDna:'DNA promptu',combinations:'Kombinacje tagów',safeClear:'Bezpiecznie i jasno',creativeMix:'Kreatywny miks',extreme:'Ekstremalnie',lyrics:'TEKST',metatags:'METATAGI',exclude:'WYKLUCZ'},
 tr:{ready:'Hazır',analyze:'Analiz et',importStyle:'Geçerli STYLE’ı içe aktar',copy:'Kopyala',apply:'Uygula',save:'Kaydet',clear:'Temizle',exportJson:'JSON dışa aktar',copyReport:'Raporu kopyala',sendProducer:'AI Producer’a gönder',runHealth:'Health Check çalıştır',saveProject:'Projeye kaydet',settings:'Ayarlar',results:'Sonuçlar',recommended:'Önerilen',issues:'Sorunlar',strengths:'Güçlü yönler',nextStep:'Sonraki adım',history:'Geçmiş',clearHistory:'Geçmişi temizle',load:'Yükle',overview:'Genel bakış',creativeData:'Yaratıcı veriler',release:'Yayın',versions:'Sürümler',assets:'Varlıklar',library:'MetaTag kitaplığı',songMaps:'Şarkı haritaları',promptDna:'Prompt DNA’sı',combinations:'Etiket kombinasyonları',safeClear:'Güvenli ve net',creativeMix:'Yaratıcı karışım',extreme:'Aşırı',lyrics:'SÖZLER',metatags:'METATAGLER',exclude:'HARİÇ TUT'},
 ru:{ready:'Готово',analyze:'Анализировать',importStyle:'Импортировать текущий STYLE',copy:'Копировать',apply:'Применить',save:'Сохранить',clear:'Очистить',exportJson:'Экспорт JSON',copyReport:'Копировать отчёт',sendProducer:'Отправить в AI Producer',runHealth:'Запустить Health Check',saveProject:'Сохранить в проекте',settings:'Настройки',results:'Результаты',recommended:'Рекомендуется',issues:'Проблемы',strengths:'Сильные стороны',nextStep:'Следующий шаг',history:'История',clearHistory:'Очистить историю',load:'Загрузить',overview:'Обзор',creativeData:'Творческие данные',release:'Релиз',versions:'Версии',assets:'Материалы',library:'Библиотека MetaTag',songMaps:'Карты песни',promptDna:'ДНК промпта',combinations:'Комбинации тегов',safeClear:'Безопасно и ясно',creativeMix:'Творческий микс',extreme:'Экстремально',lyrics:'ТЕКСТЫ',metatags:'METATAG',exclude:'ИСКЛЮЧИТЬ'},
 ja:{ready:'準備完了',analyze:'分析',importStyle:'現在のSTYLEを読み込む',copy:'コピー',apply:'適用',save:'保存',clear:'クリア',exportJson:'JSONを書き出す',copyReport:'レポートをコピー',sendProducer:'AI Producerへ送る',runHealth:'Health Checkを実行',saveProject:'プロジェクトに保存',settings:'設定',results:'結果',recommended:'推奨',issues:'問題',strengths:'長所',nextStep:'次のステップ',history:'履歴',clearHistory:'履歴を削除',load:'読み込む',overview:'概要',creativeData:'制作データ',release:'リリース',versions:'バージョン',assets:'素材',library:'MetaTagライブラリ',songMaps:'ソングマップ',promptDna:'プロンプトDNA',combinations:'タグの組み合わせ',safeClear:'安全で明確',creativeMix:'創造的なミックス',extreme:'極端',lyrics:'歌詞',metatags:'メタタグ',exclude:'除外'},
 ko:{ready:'준비됨',analyze:'분석',importStyle:'현재 STYLE 가져오기',copy:'복사',apply:'적용',save:'저장',clear:'지우기',exportJson:'JSON 내보내기',copyReport:'보고서 복사',sendProducer:'AI Producer로 보내기',runHealth:'Health Check 실행',saveProject:'프로젝트에 저장',settings:'설정',results:'결과',recommended:'추천',issues:'문제',strengths:'강점',nextStep:'다음 단계',history:'기록',clearHistory:'기록 삭제',load:'불러오기',overview:'개요',creativeData:'창작 데이터',release:'출시',versions:'버전',assets:'자료',library:'MetaTag 라이브러리',songMaps:'송 맵',promptDna:'프롬프트 DNA',combinations:'태그 조합',safeClear:'안전하고 명확하게',creativeMix:'창의적 믹스',extreme:'극단적',lyrics:'가사',metatags:'메타태그',exclude:'제외'},
 'zh-CN':{ready:'就绪',analyze:'分析',importStyle:'导入当前 STYLE',copy:'复制',apply:'应用',save:'保存',clear:'清除',exportJson:'导出 JSON',copyReport:'复制报告',sendProducer:'发送到 AI Producer',runHealth:'运行 Health Check',saveProject:'保存到项目',settings:'设置',results:'结果',recommended:'推荐',issues:'问题',strengths:'优点',nextStep:'下一步',history:'历史记录',clearHistory:'清除历史',load:'加载',overview:'概览',creativeData:'创作数据',release:'发布',versions:'版本',assets:'资源',library:'MetaTag 资料库',songMaps:'歌曲地图',promptDna:'提示词 DNA',combinations:'标签组合',safeClear:'安全且清晰',creativeMix:'创意混合',extreme:'极端',lyrics:'歌词',metatags:'元标签',exclude:'排除'}
});

const HOME=Object.freeze({
 en:{home:'Home',homeDesc:'Quick access and recent tools',quickStart:'QUICK START',wantCreate:'What do you want to create?',chooseEntry:'Choose a direct entry point. Smart Randomizer is the fastest and most playful way to begin.',pinned:'Pinned modules',shortcuts:'Your personal shortcuts',pinHint:'Pin modules with the ☆ icon in the sidebar.',pinnedMeta:'Pinned',recent:'Recent',continue:'Continue where you left off',recentHint:'Your recently used modules will appear here.',clear:'Clear',principles:'Design principles',principlesDesc:'Every feature must create real value',saveTime:'Save time',improveResults:'Improve Suno results',creativity:'Encourage creativity',minAgo:'{count} min ago',hourAgo:'{count} h ago',dayAgo:'{count} d ago',pin:'Pin module',unpin:'Unpin module'},
 de:{home:'Home',homeDesc:'Schnellzugriff und zuletzt verwendete Werkzeuge',quickStart:'SCHNELLSTART',wantCreate:'Was möchtest du erstellen?',chooseEntry:'Wähle einen direkten Einstieg. Der Smart Randomizer ist der schnellste und spielerischste Start.',pinned:'Angeheftete Module',shortcuts:'Deine persönlichen Abkürzungen',pinHint:'Hefte Module mit dem ☆-Symbol in der Seitenleiste an.',pinnedMeta:'Angeheftet',recent:'Zuletzt verwendet',continue:'Dort weitermachen, wo du aufgehört hast',recentHint:'Deine zuletzt verwendeten Module erscheinen hier.',clear:'Leeren',principles:'Gestaltungsprinzipien',principlesDesc:'Jede Funktion muss echten Nutzen schaffen',saveTime:'Zeit sparen',improveResults:'Suno-Ergebnisse verbessern',creativity:'Kreativität fördern',minAgo:'vor {count} Min.',hourAgo:'vor {count} Std.',dayAgo:'vor {count} T.',pin:'Modul anheften',unpin:'Modul lösen'},
 fr:{home:'Accueil',homeDesc:'Accès rapide et outils récents',quickStart:'DÉMARRAGE RAPIDE',wantCreate:'Que souhaitez-vous créer ?',chooseEntry:'Choisissez un accès direct. Smart Randomizer est le moyen le plus rapide et ludique de commencer.',pinned:'Modules épinglés',shortcuts:'Vos raccourcis personnels',pinHint:'Épinglez des modules avec ☆ dans la barre latérale.',pinnedMeta:'Épinglé',recent:'Récents',continue:'Reprendre là où vous vous êtes arrêté',recentHint:'Vos modules récents apparaîtront ici.',clear:'Effacer',principles:'Principes de conception',principlesDesc:'Chaque fonction doit apporter une vraie valeur',saveTime:'Gagner du temps',improveResults:'Améliorer les résultats Suno',creativity:'Favoriser la créativité',minAgo:'il y a {count} min',hourAgo:'il y a {count} h',dayAgo:'il y a {count} j',pin:'Épingler le module',unpin:'Détacher le module'},
 es:{home:'Inicio',homeDesc:'Accesos rápidos y herramientas recientes',quickStart:'INICIO RÁPIDO',wantCreate:'¿Qué quieres crear?',chooseEntry:'Elige un acceso directo. Smart Randomizer es la forma más rápida y divertida de empezar.',pinned:'Módulos fijados',shortcuts:'Tus accesos personales',pinHint:'Fija módulos con el icono ☆ de la barra lateral.',pinnedMeta:'Fijado',recent:'Recientes',continue:'Continúa donde lo dejaste',recentHint:'Aquí aparecerán tus módulos recientes.',clear:'Borrar',principles:'Principios de diseño',principlesDesc:'Cada función debe aportar un valor real',saveTime:'Ahorrar tiempo',improveResults:'Mejorar resultados de Suno',creativity:'Fomentar la creatividad',minAgo:'hace {count} min',hourAgo:'hace {count} h',dayAgo:'hace {count} d',pin:'Fijar módulo',unpin:'Soltar módulo'},
 it:{home:'Home',homeDesc:'Accesso rapido e strumenti recenti',quickStart:'AVVIO RAPIDO',wantCreate:'Cosa vuoi creare?',chooseEntry:'Scegli un accesso diretto. Smart Randomizer è il modo più rapido e divertente per iniziare.',pinned:'Moduli fissati',shortcuts:'Le tue scorciatoie personali',pinHint:'Fissa i moduli con l’icona ☆ nella barra laterale.',pinnedMeta:'Fissato',recent:'Recenti',continue:'Continua da dove eri rimasto',recentHint:'Qui appariranno i moduli usati di recente.',clear:'Cancella',principles:'Principi di progettazione',principlesDesc:'Ogni funzione deve creare valore reale',saveTime:'Risparmia tempo',improveResults:'Migliora i risultati Suno',creativity:'Favorisci la creatività',minAgo:'{count} min fa',hourAgo:'{count} h fa',dayAgo:'{count} g fa',pin:'Fissa modulo',unpin:'Rimuovi modulo'},
 pt:{home:'Início',homeDesc:'Acesso rápido e ferramentas recentes',quickStart:'INÍCIO RÁPIDO',wantCreate:'O que pretende criar?',chooseEntry:'Escolha uma entrada direta. Smart Randomizer é a forma mais rápida e divertida de começar.',pinned:'Módulos fixados',shortcuts:'Os seus atalhos pessoais',pinHint:'Fixe módulos com o ícone ☆ na barra lateral.',pinnedMeta:'Fixado',recent:'Recentes',continue:'Continue onde ficou',recentHint:'Os módulos usados recentemente aparecerão aqui.',clear:'Limpar',principles:'Princípios de design',principlesDesc:'Cada função deve criar valor real',saveTime:'Poupar tempo',improveResults:'Melhorar resultados do Suno',creativity:'Estimular a criatividade',minAgo:'há {count} min',hourAgo:'há {count} h',dayAgo:'há {count} d',pin:'Fixar módulo',unpin:'Desafixar módulo'},
 'pt-BR':{home:'Início',homeDesc:'Acesso rápido e ferramentas recentes',quickStart:'INÍCIO RÁPIDO',wantCreate:'O que você quer criar?',chooseEntry:'Escolha uma entrada direta. Smart Randomizer é a forma mais rápida e divertida de começar.',pinned:'Módulos fixados',shortcuts:'Seus atalhos pessoais',pinHint:'Fixe módulos com o ícone ☆ na barra lateral.',pinnedMeta:'Fixado',recent:'Recentes',continue:'Continue de onde parou',recentHint:'Os módulos usados recentemente aparecerão aqui.',clear:'Limpar',principles:'Princípios de design',principlesDesc:'Cada função deve criar valor real',saveTime:'Economizar tempo',improveResults:'Melhorar resultados do Suno',creativity:'Estimular a criatividade',minAgo:'há {count} min',hourAgo:'há {count} h',dayAgo:'há {count} d',pin:'Fixar módulo',unpin:'Desafixar módulo'},
 nl:{home:'Home',homeDesc:'Snelle toegang en recente hulpmiddelen',quickStart:'SNEL STARTEN',wantCreate:'Wat wil je maken?',chooseEntry:'Kies een directe ingang. Smart Randomizer is de snelste en speelsste manier om te beginnen.',pinned:'Vastgezette modules',shortcuts:'Je persoonlijke snelkoppelingen',pinHint:'Zet modules vast met het ☆-pictogram in de zijbalk.',pinnedMeta:'Vastgezet',recent:'Recent',continue:'Ga verder waar je gebleven bent',recentHint:'Recent gebruikte modules verschijnen hier.',clear:'Wissen',principles:'Ontwerpprincipes',principlesDesc:'Elke functie moet echte waarde bieden',saveTime:'Tijd besparen',improveResults:'Suno-resultaten verbeteren',creativity:'Creativiteit stimuleren',minAgo:'{count} min geleden',hourAgo:'{count} u geleden',dayAgo:'{count} d geleden',pin:'Module vastzetten',unpin:'Module losmaken'},
 pl:{home:'Start',homeDesc:'Szybki dostęp i ostatnie narzędzia',quickStart:'SZYBKI START',wantCreate:'Co chcesz utworzyć?',chooseEntry:'Wybierz bezpośrednie wejście. Smart Randomizer to najszybszy i najbardziej swobodny początek.',pinned:'Przypięte moduły',shortcuts:'Twoje osobiste skróty',pinHint:'Przypinaj moduły ikoną ☆ na pasku bocznym.',pinnedMeta:'Przypięte',recent:'Ostatnie',continue:'Kontynuuj od ostatniego miejsca',recentHint:'Ostatnio używane moduły pojawią się tutaj.',clear:'Wyczyść',principles:'Zasady projektowe',principlesDesc:'Każda funkcja musi dawać realną wartość',saveTime:'Oszczędzaj czas',improveResults:'Poprawiaj wyniki Suno',creativity:'Wspieraj kreatywność',minAgo:'{count} min temu',hourAgo:'{count} godz. temu',dayAgo:'{count} dni temu',pin:'Przypnij moduł',unpin:'Odepnij moduł'},
 tr:{home:'Ana Sayfa',homeDesc:'Hızlı erişim ve son araçlar',quickStart:'HIZLI BAŞLANGIÇ',wantCreate:'Ne oluşturmak istiyorsunuz?',chooseEntry:'Doğrudan bir giriş seçin. Smart Randomizer başlamanın en hızlı ve eğlenceli yoludur.',pinned:'Sabitlenen modüller',shortcuts:'Kişisel kısayollarınız',pinHint:'Yan çubuktaki ☆ simgesiyle modülleri sabitleyin.',pinnedMeta:'Sabitlendi',recent:'Son kullanılanlar',continue:'Kaldığınız yerden devam edin',recentHint:'Son kullanılan modüller burada görünür.',clear:'Temizle',principles:'Tasarım ilkeleri',principlesDesc:'Her özellik gerçek değer sağlamalıdır',saveTime:'Zaman kazandırır',improveResults:'Suno sonuçlarını geliştirir',creativity:'Yaratıcılığı destekler',minAgo:'{count} dk önce',hourAgo:'{count} sa önce',dayAgo:'{count} gün önce',pin:'Modülü sabitle',unpin:'Sabitlemeyi kaldır'},
 ru:{home:'Главная',homeDesc:'Быстрый доступ и недавние инструменты',quickStart:'БЫСТРЫЙ СТАРТ',wantCreate:'Что вы хотите создать?',chooseEntry:'Выберите прямой вход. Smart Randomizer — самый быстрый и игровой способ начать.',pinned:'Закреплённые модули',shortcuts:'Ваши личные ярлыки',pinHint:'Закрепляйте модули значком ☆ на боковой панели.',pinnedMeta:'Закреплено',recent:'Недавние',continue:'Продолжить с последнего места',recentHint:'Недавно использованные модули появятся здесь.',clear:'Очистить',principles:'Принципы дизайна',principlesDesc:'Каждая функция должна приносить реальную пользу',saveTime:'Экономить время',improveResults:'Улучшать результаты Suno',creativity:'Поддерживать творчество',minAgo:'{count} мин назад',hourAgo:'{count} ч назад',dayAgo:'{count} дн. назад',pin:'Закрепить модуль',unpin:'Открепить модуль'},
 ja:{home:'ホーム',homeDesc:'クイックアクセスと最近のツール',quickStart:'クイックスタート',wantCreate:'何を作りますか？',chooseEntry:'入口を選んでください。Smart Randomizerは最も速く気軽に始められます。',pinned:'固定したモジュール',shortcuts:'個人用ショートカット',pinHint:'サイドバーの☆でモジュールを固定できます。',pinnedMeta:'固定済み',recent:'最近',continue:'前回の続きから始める',recentHint:'最近使ったモジュールがここに表示されます。',clear:'クリア',principles:'設計原則',principlesDesc:'すべての機能が実用的な価値を生みます',saveTime:'時間を節約',improveResults:'Sunoの結果を改善',creativity:'創造性を促進',minAgo:'{count}分前',hourAgo:'{count}時間前',dayAgo:'{count}日前',pin:'モジュールを固定',unpin:'固定を解除'},
 ko:{home:'홈',homeDesc:'빠른 실행과 최근 도구',quickStart:'빠른 시작',wantCreate:'무엇을 만들까요?',chooseEntry:'바로 시작할 도구를 선택하세요. Smart Randomizer가 가장 빠르고 재미있는 출발점입니다.',pinned:'고정한 모듈',shortcuts:'개인 바로가기',pinHint:'사이드바의 ☆ 아이콘으로 모듈을 고정하세요.',pinnedMeta:'고정됨',recent:'최근',continue:'이어서 작업하기',recentHint:'최근 사용한 모듈이 여기에 표시됩니다.',clear:'지우기',principles:'설계 원칙',principlesDesc:'모든 기능은 실질적인 가치를 제공해야 합니다',saveTime:'시간 절약',improveResults:'Suno 결과 개선',creativity:'창의성 촉진',minAgo:'{count}분 전',hourAgo:'{count}시간 전',dayAgo:'{count}일 전',pin:'모듈 고정',unpin:'고정 해제'},
 'zh-CN':{home:'主页',homeDesc:'快速访问和最近工具',quickStart:'快速开始',wantCreate:'你想创作什么？',chooseEntry:'选择一个直接入口。Smart Randomizer 是最快、最轻松的开始方式。',pinned:'已固定模块',shortcuts:'你的个人快捷方式',pinHint:'使用侧边栏中的 ☆ 图标固定模块。',pinnedMeta:'已固定',recent:'最近使用',continue:'从上次位置继续',recentHint:'最近使用的模块会显示在这里。',clear:'清除',principles:'设计原则',principlesDesc:'每项功能都必须带来真实价值',saveTime:'节省时间',improveResults:'改进 Suno 结果',creativity:'鼓励创造力',minAgo:'{count} 分钟前',hourAgo:'{count} 小时前',dayAgo:'{count} 天前',pin:'固定模块',unpin:'取消固定'}
});

function languageOf(value){
 const raw=String(value||'en');
 if(LANGUAGES.includes(raw))return raw;
 const lower=raw.toLowerCase();
 const exact=LANGUAGES.find(code=>code.toLowerCase()===lower);
 if(exact)return exact;
 const base=lower.split('-')[0];
 return LANGUAGES.find(code=>code.toLowerCase().split('-')[0]===base)||'en';
}
function workspaceText(language,id,field){
 const code=languageOf(language),row=WORKSPACES[code]?.[id]||WORKSPACES.en[id];
 return row?.[field==='label'?0:1]||'';
}
function viewDescription(language,id){
 const code=languageOf(language),direct=VIEW_DESCRIPTIONS[code]?.[id];
 if(direct)return direct;
 return workspaceText(code,VIEW_WORKSPACE[id]||'analysis','description');
}
function uiText(language,key){const code=languageOf(language);return UI[code]?.[key]||UI.en[key]||key}
function homeText(language,key,variables={}){
 const code=languageOf(language),source=HOME[code]?.[key]||HOME.en[key]||key;
 return String(source).replace(/\{([^}]+)\}/g,(match,name)=>variables[name]!=null?String(variables[name]):match);
}

return Object.freeze({VERSION,LANGUAGES,VIEW_WORKSPACE,WORKSPACES,VIEW_DESCRIPTIONS,UI,HOME,languageOf,workspaceText,viewDescription,uiText,homeText});
});
