
(function(){
'use strict';
const $=id=>document.getElementById(id),D=window.NSW_WORLD_MUSIC_DATA;let selected='medieval',output='';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function world(){return D.worlds.find(x=>x.id===selected)||D.worlds[0]}
function filters(){const q=$('wmSearch').value.toLowerCase(),era=$('wmEra').value;return D.worlds.filter(w=>{const text=JSON.stringify(w).toLowerCase();let ok=!q||text.includes(q);if(era==='medieval')ok=ok&&/medieval|renaissance/.test(w.id);if(era==='modern')ok=ok&&/electronic|fusion|modern|cinematic/i.test(JSON.stringify(w.genres));return ok})}
function renderGrid(){const list=filters();$('wmCount').textContent=`${list.length} results`;$('wmWorldGrid').innerHTML=list.map(w=>`<button class="wm-world-card ${w.id===selected?'active':''}" data-id="${w.id}"><span>${w.icon}</span><b>${esc(w.name)}</b><small>${esc(w.era)}<br>${esc(w.genres.slice(0,3).join(' · '))}</small></button>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()})}
function detail(){const w=world(),inst=D.instruments.filter(i=>i.world===w.name);$('wmDetail').innerHTML=`<div class="wm-detail-hero"><span>${w.icon}</span><h2>${esc(w.name)}</h2><p>${esc(w.era)}<br>${esc(w.production)}</p></div>${sec('Genres',w.genres)}${sec('Scales & Modes',w.scales)}${sec('Rhythms',w.rhythms)}${sec('Vocal Traditions',w.vocals)}${sec('Atmospheres',w.atmospheres)}${sec('Recommended Instruments',inst.slice(0,12).map(x=>x.name))}<div class="wm-detail-section"><h3>Tempo Range</h3><div class="wm-chips"><span class="wm-chip">${w.bpm} BPM</span></div></div>`}
function sec(n,a){return`<div class="wm-detail-section"><h3>${n}</h3><div class="wm-chips">${a.map(x=>`<span class="wm-chip">${esc(x)}</span>`).join('')}</div></div>`}
function build(){const w=world(),goal=$('wmGoal').value,blend=D.worlds.find(x=>x.id===$('wmBlend').value),inst=D.instruments.filter(i=>i.world===w.name).slice(0,6);let parts=[w.genres[0],goal==='authentic'?'Authentic Traditional Performance':goal==='cinematic'?'Cinematic World Music Expansion':goal==='modern'?'Modern Electronic World Fusion':'Experimental Cross-Cultural Texture',`${w.bpm} BPM Range`,w.scales.slice(0,2).join(' and '),w.rhythms.slice(0,2).join(', '),w.vocals.slice(0,2).join(', '),inst.map(x=>x.name).join(', '),w.atmospheres.slice(0,2).join(', '),w.production];if(blend)parts.splice(1,0,`${blend.genres[0]} Supporting Influence`,D.instruments.filter(i=>i.world===blend.name).slice(0,3).map(x=>x.name).join(', '));output=parts.filter(Boolean).join(', ');$('wmOutput').value=output;const score=blend?compat(w,blend):94;$('wmCompatibility').innerHTML=[['Primary Identity',w.genres[0]],['Blend Compatibility',blend?score+'/100':'Single world'],['Instrument Coverage',inst.length+' core instruments']].map(x=>`<div class="wm-compat-card"><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('');$('wmStatus').textContent=`${w.name} palette built${blend?' with '+blend.name:''}.`;window.NSW_WORLD_MUSIC_LAST={world:w,blend,goal,style:output,score,updatedAt:Date.now()}}
function compat(a,b){let s=58;if(a.scales.some(x=>b.scales.includes(x)))s+=15;if(a.rhythms.some(x=>b.rhythms.includes(x)))s+=8;if(/cinematic|fusion|electronic/i.test(JSON.stringify(a.genres)+JSON.stringify(b.genres)))s+=10;return Math.min(96,s)}
function apply(){const e=$('customStyle');if(!e||!output)return;e.value=window.NSWConnections?.mergeStyle([e.value,output])||[e.value,output].filter(Boolean).join(', ');e.dispatchEvent(new Event('input',{bubbles:true}));if(typeof generateOutput==='function')generateOutput()}
function render(){renderGrid();detail();build()}
function init(){if(!$('wmBuild')||!D)return;$('wmBlend').innerHTML='<option value="">No secondary world</option>'+D.worlds.map(w=>`<option value="${w.id}">${w.name}</option>`).join('');$('wmBuild').onclick=build;$('wmSearch').oninput=renderGrid;$('wmEra').onchange=renderGrid;$('wmGoal').onchange=build;$('wmBlend').onchange=build;$('wmRandom').onclick=()=>{selected=D.worlds[Math.floor(Math.random()*D.worlds.length)].id;render()};$('wmCopy').onclick=()=>navigator.clipboard?.writeText(output);$('wmApply').onclick=apply;$('wmSendDirector').onclick=()=>{window.NSWConnections?.navigate('songDirectorView');const e=$('sdBrief');if(e){e.value=(e.value.trim()?e.value.trim()+'\n\n':'')+`World Music Direction: ${output}`;e.dispatchEvent(new Event('input',{bubbles:true}))}};$('wmSendTheory').onclick=()=>{window.NSWConnections?.navigate('theoryDirectorView');const e=$('mtdBrief');if(e)e.value=`${world().name}: ${world().scales.join(', ')}; ${world().rhythms.join(', ')}`};$('wmSaveProject').onclick=()=>{let p;try{p=JSON.parse(localStorage.getItem('nsw-project-manager-v4')||'null')}catch(e){}const pr=p?.projects?.find(x=>x.id===p.activeProjectId)||p?.projects?.[0],t=pr?.tracks?.[0];if(t){t.worldMusicAtlas=window.NSW_WORLD_MUSIC_LAST;localStorage.setItem('nsw-project-manager-v4',JSON.stringify(p));$('wmStatus').textContent='World palette saved to active project.'}};render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
